const REDEMITTEL = [
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`eine Anfrage stellen`,kz:`提出詢問`,en:`to submit an inquiry`,ex:`Wir möchten eine Anfrage an verschiedene Lieferanten stellen.`,ez:`我們想向不同供應商提出詢問。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Angebote einholen`,kz:`索取報價`,en:`to request / collect quotes`,ex:`Bei größeren Aufträgen ist es üblich, zuerst Angebote einzuholen.`,ez:`對於較大的訂單，通常需要先向供應商索取報價。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`ein unverbindliches Angebot einholen`,kz:`索取不具約束力的報價`,en:`to request a non-binding quote`,ex:`Wir hätten gern ein unverbindliches Angebot für folgende Stückzahl.`,ez:`我們希望獲得以下數量的不具約束力報價。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`auf jmdn. aufmerksam gemacht werden`,kz:`被介紹認識某人/某公司`,en:`to be referred to / made aware of`,ex:`Von Partnerfirmen sind wir auf Ihr Unternehmen aufmerksam gemacht worden.`,ez:`我們是透過合作廠商得知您公司的。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Konditionen mitteilen`,kz:`告知條件（價格、付款方式等）`,en:`to communicate terms and conditions`,ex:`Bitte teilen Sie uns Ihre aktuellen Konditionen mit.`,ez:`請告知我們您目前的條件。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`zeitnahe Lieferung`,kz:`及時交貨`,en:`prompt / timely delivery`,ex:`Eine zeitnahe Lieferung ist für uns besonders entscheidend.`,ez:`及時交貨對我們尤為重要。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Informationen zukommen lassen`,kz:`提供資訊給對方`,en:`to send / forward information to`,ex:`Könnten Sie uns weitere Informationen zukommen lassen?`,ez:`您能將更多資訊提供給我們嗎？`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`sich erkundigen nach`,kz:`詢問、打聽（關於…）`,en:`to inquire about`,ex:`Ich möchte mich nach den Preisen und Lieferbedingungen erkundigen.`,ez:`我想詢問一下價格和交貨條件。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`um Rückmeldung bitten`,kz:`請求回覆`,en:`to request a reply`,ex:`Wir bitten um eine baldige Rückmeldung zu unserem Anliegen.`,ez:`我們請求盡快對我們的詢問予以回覆。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`freundliches Entgegenkommen`,kz:`友好的回應、通融`,en:`goodwill / willingness to accommodate`,ex:`Wir freuen uns auf Ihr freundliches Entgegenkommen.`,ez:`我們期待您的友好回應。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Interesse wecken`,kz:`引起興趣`,en:`to arouse / attract interest`,ex:`Ihre Kollektion hat auf der Messe mein Interesse geweckt.`,ez:`您的系列在展覽上引起了我的興趣。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`auf Interesse stoßen`,kz:`獲得興趣、受到關注`,en:`to meet with interest`,ex:`Ihr neues Produkt ist auf unserem Messestand auf großes Interesse gestoßen.`,ez:`您的新產品在我們的展覽攤位上獲得了廣泛關注。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Auskunft geben über`,kz:`提供（關於…的）資訊`,en:`to provide information about`,ex:`Geben Sie uns bitte auch Auskunft über mögliche Farbmuster.`,ez:`請也提供可選顏色樣式的相關資訊。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Gewährleistung angeben`,kz:`說明保固條件`,en:`to state warranty conditions`,ex:`Geben Sie uns bitte außerdem Ihre Gewährleistung und Zahlungsbedingungen an.`,ez:`請也告知我們您的保固條件和付款方式。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`Probeexemplare zusenden`,kz:`寄送樣品`,en:`to send sample copies / trial items`,ex:`Eine Zusendung von Probeexemplaren wäre für uns sehr hilfreich.`,ez:`如能寄送樣品，對我們會很有幫助。`},
{s:`R1: Anfrage stellen（詢價與詢問）`,k:`auf Empfehlung`,kz:`根據推薦`,en:`on the recommendation of`,ex:`Auf Empfehlung unserer Hauptverwaltung wenden wir uns an Sie.`,ez:`根據我們總部的推薦，我們聯繫了您。`},
{s:`R2: Angebot machen（報價與提案）`,k:`ein Angebot unterbreiten`,kz:`正式提呈報價`,en:`to submit / present an offer`,ex:`Wir möchten Ihnen folgendes Angebot unterbreiten.`,ez:`我們希望向您提呈以下報價。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Preise verstehen sich inklusive MwSt.`,kz:`價格含增值稅`,en:`prices include VAT`,ex:`Die genannten Preise verstehen sich inklusive gesetzlicher Mehrwertsteuer.`,ez:`所列價格均含法定增值稅。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Preise verstehen sich zzgl. MwSt.`,kz:`價格需另加增值稅`,en:`prices plus VAT`,ex:`Die Preise verstehen sich zuzüglich der gesetzlichen Mehrwertsteuer von 19%.`,ez:`價格需另加19%法定增值稅。`},
{s:`R2: Angebot machen（報價與提案）`,k:`auf die AGB verweisen`,kz:`參見一般商業條款`,en:`to refer to general terms and conditions`,ex:`Für weitere Details verweisen wir auf unsere Allgemeinen Geschäftsbedingungen.`,ez:`更多詳情請參見我們的一般商業條款。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Lieferung garantieren`,kz:`保證交貨`,en:`to guarantee delivery`,ex:`Die Lieferung garantieren wir innerhalb von fünf Werktagen.`,ez:`我們保證在五個工作天內完成交貨。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Neukundenrabatt gewähren`,kz:`給予新客優惠`,en:`to grant a new customer discount`,ex:`Als Neukunde kommen wir Ihnen gerne mit einem Neukundenrabatt entgegen.`,ez:`作為新客戶，我們很樂意給予您新客優惠。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Mengenrabatt gewähren`,kz:`給予數量折扣`,en:`to grant a volume discount`,ex:`Auf alle Bestellungen ab 10 Stück gewähren wir einen Mengenrabatt von 10%.`,ez:`所有10件以上的訂單，我們給予10%的數量折扣。`},
{s:`R2: Angebot machen（報價與提案）`,k:`2% Skonto gewähren`,kz:`給予2%早付折扣`,en:`to grant a 2% cash discount`,ex:`Bei Zahlung innerhalb von zehn Tagen gewähren wir 2% Skonto.`,ez:`在發票日後十天內付款，可享2%早付折扣。`},
{s:`R2: Angebot machen（報價與提案）`,k:`für Rückfragen zur Verfügung stehen`,kz:`如有問題可隨時聯繫`,en:`to be available for questions`,ex:`Für weitere Rückfragen stehen wir Ihnen jederzeit zur Verfügung.`,ez:`如有任何問題，我們隨時為您服務。`},
{s:`R2: Angebot machen（報價與提案）`,k:`pünktliche Ausführung versichern`,kz:`保證準時完成`,en:`to assure punctual execution`,ex:`Wir versichern Ihnen eine pünktliche und sorgfältige Ausführung.`,ez:`我們向您保證準時且細心地執行。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Garantie gewähren`,kz:`提供保固`,en:`to grant / provide a warranty`,ex:`Auf alle Komponenten gewähren wir 5 Jahre Garantie.`,ez:`所有零件我們提供5年保固。`},
{s:`R2: Angebot machen（報價與提案）`,k:`Garantie verlängern`,kz:`延長保固`,en:`to extend the warranty`,ex:`Wir bieten an, die Garantie um ein weiteres Jahr zu verlängern.`,ez:`我們提議將保固延長一年。`},
{s:`R2: Angebot machen（報價與提案）`,k:`ein Angebot annehmen`,kz:`接受提議／報價`,en:`to accept an offer`,ex:`Wir haben Ihr Angebot geprüft und möchten es gerne annehmen.`,ez:`我們已審閱您的報價，很樂意接受。`},
{s:`R2: Angebot machen（報價與提案）`,k:`der folgenden Tabelle entnehmen`,kz:`從下表中查看／得知`,en:`to refer to / find in the following table`,ex:`Die Preise entnehmen Sie bitte der folgenden Tabelle.`,ez:`請從下表中查看各項價格。`},
{s:`R2: Angebot machen（報價與提案）`,k:`in der Anlage zusenden`,kz:`隨附寄出`,en:`to send enclosed / as an attachment`,ex:`Gerne schicken wir Ihnen in der Anlage unser aktuelles Angebot zu.`,ez:`我們很樂意隨附寄上我們最新的報價單。`},
{s:`R2: Angebot machen（報價與提案）`,k:`ein Abonnement abschließen`,kz:`簽訂訂閱合約`,en:`to take out a subscription`,ex:`Danach können Sie mit einer dreimonatigen Kündigungsfrist ein Abonnement abschließen.`,ez:`之後您可以以三個月的通知期簽訂訂閱合約。`},
{s:`R2: Angebot machen（報價與提案）`,k:`sich in Verbindung setzen mit`,kz:`與…取得聯繫`,en:`to get in touch with / contact`,ex:`Unser Mitarbeiter wird sich zur Terminvereinbarung direkt mit Ihnen in Verbindung setzen.`,ez:`我們的員工將直接與您聯繫約定時間。`},
{s:`R2: Angebot machen（報價與提案）`,k:`zu den Kunden zählen`,kz:`成為（我們的）客戶`,en:`to count among one's customers`,ex:`Wir hoffen, auch Sie bald zu unseren zufriedenen Kunden zählen zu dürfen.`,ez:`我們希望很快也能讓您加入我們滿意客戶的行列。`},

{s:`R2: Angebot machen（報價與提案）`,k:`ein Angebot annehmen`,kz:`接受提議／報價`,en:`to accept an offer`,ex:`Wir haben Ihr Angebot geprüft und möchten es gerne annehmen.`,ez:`我們已審閱您的報價，很樂意接受。`},
{s:`R2: Angebot machen（報價與提案）`,k:`der folgenden Tabelle entnehmen`,kz:`從下表中查看／得知`,en:`to refer to / find in the following table`,ex:`Die Preise entnehmen Sie bitte der folgenden Tabelle.`,ez:`請從下表中查看各項價格。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`eine Bestellung aufgeben`,kz:`下訂單`,en:`to place an order`,ex:`Wir möchten eine Bestellung für folgende Artikel aufgeben.`,ez:`我們想為以下商品下訂單。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`gemäß Ihrem Angebot bestellen`,kz:`依照您的報價訂購`,en:`to order as per your offer`,ex:`Gemäß Ihrem Angebot vom 01.12. bestellen wir folgende Mengen.`,ez:`依照您12月1日的報價，我們訂購如下數量。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`Lieferzeit einhalten`,kz:`遵守交貨期限`,en:`to meet the delivery deadline`,ex:`Wir bitten Sie, die vereinbarte Lieferzeit unbedingt einzuhalten.`,ez:`我們請您務必遵守約定的交貨期限。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`um Auftragsbestätigung bitten`,kz:`請求訂單確認`,en:`to request order confirmation`,ex:`Bitte schicken Sie uns eine kurze Auftragsbestätigung.`,ez:`請寄給我們一份簡短的訂單確認。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`Versand erfolgen bis`,kz:`出貨在…之前完成`,en:`shipment to be completed by`,ex:`Der Versand muss bis zum 15.12. erfolgen.`,ez:`出貨必須在12月15日前完成。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`fristgerechte Abwicklung`,kz:`按時完成的處理`,en:`on-time processing`,ex:`Bei fristgerechter Abwicklung können Sie mit weiteren Aufträgen rechnen.`,ez:`如能按時處理，您可以期待更多訂單。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`mit weiteren Aufträgen rechnen`,kz:`可預期更多訂單`,en:`to expect further orders`,ex:`Bei guter Zusammenarbeit können Sie in Zukunft mit weiteren Aufträgen rechnen.`,ez:`如果合作順利，未來您可以預期更多訂單。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`einwandfreie Lieferung`,kz:`完好無缺的交貨`,en:`flawless delivery`,ex:`Bei einwandfreier Lieferung freuen wir uns auf weitere Zusammenarbeit.`,ez:`如果交貨完好，我們期待進一步合作。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`Zahlungsbedingungen gelten`,kz:`付款條件適用`,en:`payment terms apply`,ex:`Es gelten folgende Zahlungsbedingungen: 30 Tage netto.`,ez:`適用以下付款條件：30天淨額付款。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`einen Folgeauftrag erteilen`,kz:`下後續訂單`,en:`to place a follow-up order`,ex:`Bei guten Konditionen würden wir Ihnen gerne auch einen Folgeauftrag erteilen.`,ez:`如果條件合適，我們也很樂意給您下後續訂單。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`etw. zur Auswahl stellen`,kz:`提供選擇`,en:`to offer as an option / put forward for selection`,ex:`Vielen Dank für die Veranstaltungsorte, die Sie uns zur Auswahl gestellt haben.`,ez:`非常感謝您為我們提供的場地選項。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`der Preis beträgt`,kz:`費用為…`,en:`the price amounts to`,ex:`Für einen kompletten Tag beträgt der Preis 800 Euro zuzüglich Mehrwertsteuer.`,ez:`租用整天的費用為800歐元另加增值稅。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`der Gesamtpreis erhöht sich auf`,kz:`總價提高至…`,en:`the total price increases to`,ex:`Der Gesamtpreis erhöht sich damit auf 1150 Euro zuzüglich Mehrwertsteuer.`,ez:`總價因此提高至1150歐元另加增值稅。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`Anzahlung leisten`,kz:`支付訂金`,en:`to make a down payment`,ex:`Bei Auftragsvergabe bitten wir um eine Anzahlung von 20%.`,ez:`在承接訂單時，請支付20%的訂金。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`Rechnung fällig sein`,kz:`帳單到期`,en:`invoice / payment is due`,ex:`Die Restzahlung wird 30 Tage nach Rechnungsdatum fällig.`,ez:`餘款在發票日後30天到期。`},
{s:`R3: Bestellung aufgeben（下訂單）`,k:`etw. in Rechnung stellen`,kz:`開帳收費`,en:`to charge / invoice for something`,ex:`Für den Auf- und Abbau der Technik stellen wir keine zusätzlichen Kosten in Rechnung.`,ez:`技術設備的架設和拆除我們不另行收費。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Lieferung eintreffen`,kz:`貨物到達`,en:`delivery arrives`,ex:`Die Lieferung ist gestern bei uns eingetroffen.`,ez:`貨物昨天已到達我們這裡。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Lieferung verzögert sich`,kz:`交貨延誤`,en:`delivery is delayed`,ex:`Leider hat sich die Lieferung um zwei Wochen verzögert.`,ez:`很遺憾，交貨延誤了兩週。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Versandverzögerung`,kz:`出貨延遲`,en:`shipping delay`,ex:`Aufgrund einer Versandverzögerung konnten wir die Ware nicht rechtzeitig liefern.`,ez:`由於出貨延遲，我們未能及時交貨。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Ware durchzählen / prüfen`,kz:`清點/檢查貨物`,en:`to count / inspect goods`,ex:`Bitte zählen Sie die gelieferte Ware genau durch und prüfen Sie auf Mängel.`,ez:`請仔細清點交付的貨物並檢查是否有瑕疵。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Ware annehmen`,kz:`驗收貨物`,en:`to accept goods`,ex:`Die Ware wurde ordnungsgemäß angenommen und eingelagert.`,ez:`貨物已按規定驗收並入庫。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Empfang quittieren lassen`,kz:`讓對方簽收`,en:`to have the recipient sign for receipt`,ex:`Bitte lassen Sie sich den Empfang der Pakete quittieren.`,ez:`請讓對方簽收包裹。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`auf Mängel prüfen`,kz:`檢查瑕疵`,en:`to check for defects`,ex:`Alle Waren wurden auf Mängel geprüft und für gut befunden.`,ez:`所有貨物均已檢查過瑕疵，結果良好。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Liefertermin vereinbaren`,kz:`約定交貨日期`,en:`to arrange a delivery date`,ex:`Könnten wir einen verbindlichen Liefertermin vereinbaren?`,ez:`我們可以約定一個確定的交貨日期嗎？`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Nachbestellung aufgeben`,kz:`補訂貨物`,en:`to place a reorder`,ex:`Da uns der Bestand ausgegangen ist, müssen wir eine Nachbestellung aufgeben.`,ez:`由於庫存用完了，我們需要補訂。`},
{s:`R4: Lieferung und Empfang（收貨與物流）`,k:`Arbeiten ausführen`,kz:`執行工程/工作`,en:`to carry out / execute work`,ex:`Wir möchten ein Angebot für die auszuführenden Arbeiten einholen.`,ez:`我們想為待執行的工程索取報價。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`eine Reklamation einreichen`,kz:`提出投訴`,en:`to file a complaint / claim`,ex:`Wir möchten hiermit eine schriftliche Reklamation einreichen.`,ez:`我們謹此提出書面投訴。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Mängel feststellen`,kz:`發現瑕疵`,en:`to identify defects`,ex:`Bei der Wareneingangsprüfung haben wir folgende Mängel festgestellt.`,ez:`在驗貨時，我們發現了以下瑕疵。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Defekt melden`,kz:`回報故障`,en:`to report a defect`,ex:`Bitte melden Sie Defekte sofort an die Haustechnik.`,ez:`請立即將故障回報給技術部門。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Fehler beheben`,kz:`排除錯誤`,en:`to fix / resolve an error`,ex:`Wir haben den Fehler sofort identifiziert und werden ihn umgehend beheben.`,ez:`我們已立即找到錯誤並將儘快排除。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Fehler zugeben`,kz:`承認錯誤`,en:`to admit a mistake`,ex:`Wir müssen zugeben, dass auf unserer Seite ein Fehler gemacht wurde.`,ez:`我們必須承認，我方犯了一個錯誤。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`sich über etw. beschweren`,kz:`就某事投訴、抱怨`,en:`to complain about something`,ex:`Mehrere Kunden haben sich über die verzögerte Lieferung beschwert.`,ez:`多位客戶投訴了交貨延誤的問題。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Beschwerde entgegennehmen`,kz:`受理投訴`,en:`to receive / accept a complaint`,ex:`Ich nehme Ihre Beschwerde ernst und werde mich sofort darum kümmern.`,ez:`我會認真對待您的投訴，並立即處理。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Problem schildern`,kz:`描述問題`,en:`to describe / explain a problem`,ex:`Bitte schildern Sie uns das Problem so genau wie möglich.`,ez:`請盡可能詳細地向我們描述問題。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Forderung stellen`,kz:`提出要求`,en:`to make a demand`,ex:`Der Kunde stellt folgende Forderung: vollständiger Ersatz der Ware.`,ez:`客戶提出以下要求：全額更換貨物。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`mangelhafte Ware zurückschicken`,kz:`退回有瑕疵的貨物`,en:`to send back defective goods`,ex:`Wir bitten Sie, die mangelhaften Artikel umgehend zurückzunehmen.`,ez:`我們請您立即收回有瑕疵的商品。`},
{s:`R5: Reklamation und Beschwerde（投訴與抱怨）`,k:`Ersatz liefern`,kz:`提供替換品`,en:`to deliver a replacement`,ex:`Können Sie uns Ersatz für die defekten Geräte liefern?`,ez:`您能為有故障的設備提供替換品嗎？`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`sich für etw. entschuldigen`,kz:`為某事道歉`,en:`to apologize for something`,ex:`Wir entschuldigen uns nochmals für die entstandenen Unannehmlichkeiten.`,ez:`我們再次為造成的不便道歉。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Versehen entschuldigen`,kz:`為疏失道歉`,en:`to apologize for an oversight`,ex:`Bitte entschuldigen Sie unser Versehen. Wir haben die Angelegenheit sofort überprüft.`,ez:`請原諒我們的疏失。我們已立即查核此事。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Als Entgegenkommen anbieten`,kz:`作為補償提供`,en:`as goodwill, to offer`,ex:`Als Entgegenkommen bieten wir Ihnen einen Rabatt von 10% auf die nächste Bestellung an.`,ez:`作為補償，我們為您下次訂單提供10%的折扣。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Preisnachlass gewähren`,kz:`給予折扣`,en:`to grant a price reduction`,ex:`Für die entstandenen Unannehmlichkeiten gewähren wir einen Preisnachlass von 50 Euro.`,ez:`針對造成的不便，我們給予50歐元的折扣。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Betrag zurückerstatten`,kz:`退還金額`,en:`to refund an amount`,ex:`Wir werden den entsprechenden Betrag auf Ihr Konto zurückerstatten.`,ez:`我們將把相應金額退還至您的帳戶。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Gutschrift anbieten`,kz:`提供折抵額度`,en:`to offer a credit note`,ex:`Als Entschädigung bieten wir Ihnen eine Gutschrift von 200 Euro an.`,ez:`作為補償，我們為您提供200歐元的折抵額度。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Fehler nicht mehr auftreten`,kz:`錯誤不再發生`,en:`error will not occur again`,ex:`Wir versichern Ihnen, dass derartige Fehler in Zukunft nicht mehr auftreten werden.`,ez:`我們向您保證，此類錯誤將不再發生。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Wiedergutmachung anbieten`,kz:`提供補救措施`,en:`to offer compensation / redress`,ex:`Um Sie nicht als Kunden zu verlieren, möchten wir eine Wiedergutmachung anbieten.`,ez:`為了不失去您作為客戶，我們希望提供補救措施。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Konto ausgeglichen sein`,kz:`帳戶已結清`,en:`account has been settled`,ex:`Ihre Zahlung ist eingegangen und Ihr Konto ist demnach ausgeglichen.`,ez:`您的付款已收到，帳戶因此已結清。`},
{s:`R6: Entschuldigung und Entschädigung（道歉與補償）`,k:`Kosten übernehmen`,kz:`承擔費用`,en:`to cover / bear the costs`,ex:`In diesem Fall übernehmen wir selbstverständlich die entstandenen Kosten.`,ez:`在這種情況下，我們當然承擔所產生的費用。`},

{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`ein Telefongespräch führen`,kz:`進行電話通話`,en:`to conduct a phone call`,ex:`In der Prüfung sollen Sie ein berufliches Telefongespräch führen.`,ez:`在考試中，您需要進行一次職業電話通話。`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`verbinden mit`,kz:`轉接給`,en:`to connect to / put through to`,ex:`Können Sie mich bitte mit Frau Müller verbinden?`,ez:`請問您能幫我轉接給 Müller 女士嗎？`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`durchstellen`,kz:`轉接電話`,en:`to put a call through`,ex:`Ich stelle Sie gleich zu meiner Kollegin durch.`,ez:`我馬上幫您轉接給我的同事。`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`eine Nachricht hinterlassen`,kz:`留下留言`,en:`to leave a message`,ex:`Soll ich eine Nachricht für Herrn Petersen hinterlassen?`,ez:`我是否要為 Petersen 先生留下留言？`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`etwas ausrichten`,kz:`轉達訊息`,en:`to pass on a message`,ex:`Können Sie Frau Schröder ausrichten, dass ich morgen anrufe?`,ez:`您能轉告 Schröder 女士，我明天會打電話嗎？`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`wir verbleiben so`,kz:`我們就這樣確認`,en:`we'll leave it at that / agreed`,ex:`Gut, dann können wir festhalten: Lieferung am Dienstag. Wir verbleiben also so.`,ez:`好，那我們確認：週二交貨。我們就這樣定了。`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`sich vergewissern`,kz:`確認、核實`,en:`to make sure / verify`,ex:`Ich bin mir nicht ganz sicher. Können Sie das bitte noch einmal wiederholen?`,ez:`我不太確定。您能再說一遍嗎？`},
{s:`R7: Telefon und Kommunikation（電話溝通）`,k:`Rückruf bitten`,kz:`請求回電`,en:`to ask for a callback`,ex:`Könnte Herr Weber mich bitte zurückrufen? Hier ist meine Nummer.`,ez:`Weber 先生能回電給我嗎？這是我的電話號碼。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`sich um eine Stelle bewerben`,kz:`應徵一個職位`,en:`to apply for a position`,ex:`Ich bewerbe mich hiermit um die ausgeschriebene Stelle als Teamassistent.`,ez:`我謹此應徵貴公司招募的團隊助理職位。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`auf ein Stellenangebot aufmerksam werden`,kz:`注意到徵才廣告`,en:`to come across a job advertisement`,ex:`Auf Ihrer Homepage bin ich auf das Stellenangebot aufmerksam geworden.`,ez:`我在您的官網上注意到了這份職缺。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`die genannten Voraussetzungen erfüllen`,kz:`符合所列的資格條件`,en:`to meet the stated requirements`,ex:`Ich bin überzeugt, die genannten Voraussetzungen zu erfüllen.`,ez:`我相信自己符合所列的各項資格條件。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`praktische Erfahrungen sammeln`,kz:`累積實務經驗`,en:`to gain practical experience`,ex:`In meiner bisherigen Tätigkeit konnte ich wertvolle praktische Erfahrungen sammeln.`,ez:`在我目前的工作中，我積累了寶貴的實務經驗。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`beigefügte Unterlagen`,kz:`隨附的文件`,en:`enclosed documents`,ex:`Wie Sie aus den beigefügten Unterlagen ersehen können, habe ich bereits Erfahrung in...`,ez:`如您從隨附文件中所見，我已有…方面的經驗`},
{s:`R8: Bewerbung（求職與應徵）`,k:`zu einem Vorstellungsgespräch einladen`,kz:`邀請參加面試`,en:`to invite to a job interview`,ex:`Ueber eine Einladung zu einem Vorstellungsgespräch freue ich mich sehr.`,ez:`我非常期待能受邀參加面試。`},
{s:`R8: Bewerbung（求職與應徵）`,k:`Kompetenzen einbringen`,kz:`貢獻自身能力`,en:`to contribute one's competencies`,ex:`Ich bin hoch motiviert, meine Kompetenzen in Ihre Firma einzubringen.`,ez:`我非常有動力將自己的能力貢獻給貴公司。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`sich beim Arbeitgeber krankmelden`,kz:`向雇主請病假`,en:`to call in sick to one's employer`,ex:`Wenn Sie erkranken, müssen Sie sich sofort beim Arbeitgeber krankmelden.`,ez:`如果您生病，必須立即向雇主請病假。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`sich krankschreiben lassen`,kz:`取得病假單（醫生開立）`,en:`to get a sick leave certificate`,ex:`Ich musste mich für eine Woche krankschreiben lassen.`,ez:`我不得不請一週的病假。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`Arbeitsunfähigkeitsbescheinigung vorlegen`,kz:`提交病假證明`,en:`to submit a sick leave certificate`,ex:`Ab dem dritten Krankheitstag müssen Sie eine AU-Bescheinigung vorlegen.`,ez:`從第三天起，您必須提交病假證明。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`Unfall melden`,kz:`回報事故`,en:`to report an accident`,ex:`Einen Arbeitsunfall müssen Sie umgehend dem Vorgesetzten melden.`,ez:`工作意外必須立即向上司回報。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`Urlaubsantrag stellen`,kz:`提交休假申請`,en:`to submit a leave request`,ex:`Den Jahresurlaub müssen Sie rechtzeitig per Urlaubsantrag beantragen.`,ez:`您必須及時提交休假申請來申請年假。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`Anspruch auf Urlaub haben`,kz:`有休假權利`,en:`to be entitled to leave`,ex:`Bei einer Fünf-Tage-Woche haben Arbeitnehmer Anspruch auf mindestens 20 Urlaubstage.`,ez:`五天工作制的員工有權享有至少20天的年假。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`fristgerecht kündigen`,kz:`按時提出辭職`,en:`to resign within the notice period`,ex:`Ich kündige hiermit mein Arbeitsverhältnis fristgerecht zum Monatsende.`,ez:`我謹此按時提交辭職，生效日期為月底。`},
{s:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`,k:`Arbeitszeugnis ausstellen`,kz:`開立工作證明`,en:`to issue a reference / certificate`,ex:`Bitte stellen Sie mir ein qualifiziertes Arbeitszeugnis aus.`,ez:`請為我開立一份詳細的工作證明。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`eine Präsentation halten`,kz:`進行報告`,en:`to give a presentation`,ex:`Ich soll nächste Woche vor dem Team eine Präsentation halten.`,ez:`我下週需要在團隊面前進行一次報告。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Termin vereinbaren`,kz:`約定時間`,en:`to arrange / schedule a meeting`,ex:`Können wir einen Termin für ein Vorstellungsgespräch vereinbaren?`,ez:`我們可以約定一個面試時間嗎？`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Protokoll schreiben`,kz:`撰寫會議記錄`,en:`to write the minutes`,ex:`Nach dem Meeting muss jemand das Protokoll schreiben und versenden.`,ez:`會議結束後，需要有人撰寫並傳送會議記錄。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Entscheidung treffen`,kz:`做決定`,en:`to make a decision`,ex:`Wir müssen bis Ende der Woche eine Entscheidung zum Angebot treffen.`,ez:`我們必須在週末前對這份報價做出決定。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Beschluss fassen`,kz:`做出決議`,en:`to pass a resolution`,ex:`Im Meeting haben wir den Beschluss gefasst, den Lieferanten zu wechseln.`,ez:`在會議中，我們做出了更換供應商的決議。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Lösungsweg diskutieren`,kz:`討論解決方案`,en:`to discuss solutions`,ex:`Wir sollten gemeinsam Lösungswege diskutieren, bevor wir handeln.`,ez:`在採取行動之前，我們應該共同討論解決方案。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Prüfung ablegen`,kz:`參加考試`,en:`to take an exam`,ex:`Um die Stelle zu bekommen, muss ich noch eine Prüfung ablegen.`,ez:`為了獲得這個職位，我還需要參加一次考試。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Überstunden abbauen`,kz:`消化加班時數`,en:`to reduce overtime hours`,ex:`Er hat beantragt, seine angesammelten Überstunden abbauen zu dürfen.`,ez:`他申請消化所累積的加班時數。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`etwas ins Programm aufnehmen`,kz:`納入計畫／課程`,en:`to include in the programme`,ex:`Wir möchten das Training auf Trampolinen in unser Programm aufnehmen.`,ez:`我們希望將彈床訓練納入我們的課程。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`Daten aufnehmen`,kz:`記錄資料`,en:`to record / capture data`,ex:`Die Kundendaten werden beim ersten Kontakt aufgenommen und gespeichert.`,ez:`客戶資料在第一次接觸時被記錄並儲存。`},
{s:`R10: Präsentation und Meetings（報告與會議）`,k:`freie Kapazitäten haben`,kz:`有空閒產能/人力`,en:`to have free capacity`,ex:`Wenn Sie freie Kapazitäten haben sollten, senden Sie uns bitte umgehend ein Angebot zu.`,ez:`如果您有空閒的工作能量，請立即寄給我們報價。`},

{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`Qualität sichern`,kz:`確保品質`,en:`to ensure quality`,ex:`Unser Unternehmen hat Maßnahmen eingeführt, um die Qualität zu sichern.`,ez:`我們公司已引入措施來確保品質。`},
{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`Arbeitsabläufe optimieren`,kz:`優化工作流程`,en:`to optimize work processes`,ex:`Durch das neue System können wir unsere Arbeitsabläufe weiter optimieren.`,ez:`透過新系統，我們可以進一步優化工作流程。`},
{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`Maßnahmen einhalten`,kz:`遵守措施規定`,en:`to comply with measures`,ex:`Alle Mitarbeitenden sind verpflichtet, die Hygienemaßnahmen einzuhalten.`,ez:`所有員工都有義務遵守衛生措施。`},
{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`konstruktiv mit Fehlern umgehen`,kz:`建設性地處理錯誤`,en:`to deal with errors constructively`,ex:`Es ist wichtig, konstruktiv mit Fehlern umzugehen und daraus zu lernen.`,ez:`重要的是，要建設性地處理錯誤並從中學習。`},
{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`betriebliche Gesundheitsförderung`,kz:`職場健康促進措施`,en:`workplace health promotion`,ex:`Unser Betriebsrat hat Vorschläge zur betrieblichen Gesundheitsförderung gesammelt.`,ez:`我們的員工代表會收集了職場健康促進措施的建議。`},
{s:`R11: Qualität und Gesundheit（品質管理與職場健康）`,k:`Schulung anbieten`,kz:`提供培訓`,en:`to offer training`,ex:`Für alle Mitarbeitenden werden regelmäßig Sicherheitsschulungen angeboten.`,ez:`定期為所有員工提供安全培訓。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Fehler zugeben`,kz:`承認錯誤`,en:`to admit a mistake`,ex:`Ich gebe zu, dass ich in dieser Sache einen Fehler gemacht habe.`,ez:`我承認我在這件事上犯了一個錯誤。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Verständnis zeigen`,kz:`表示理解`,en:`to show understanding`,ex:`Ich verstehe gut, dass Sie in dieser Situation frustriert sind.`,ez:`我完全理解您在這種情況下感到沮喪。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Kompromisse finden`,kz:`找到妥協方案`,en:`to find a compromise`,ex:`In Konflikten ist es wichtig, bereit zu sein, Kompromisse zu finden.`,ez:`在衝突中，願意尋找妥協方案非常重要。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Probleme ansprechen`,kz:`提出問題`,en:`to address problems`,ex:`Es ist besser, Probleme direkt anzusprechen, als sie zu ignorieren.`,ez:`直接提出問題比忽視問題要好得多。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Ich-Botschaften formulieren`,kz:`使用「我訊息」表達`,en:`to use I-messages`,ex:`Statt Vorwürfe zu machen, sollte man Ich-Botschaften formulieren.`,ez:`與其指責他人，不如使用「我訊息」來表達。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Kritik annehmen`,kz:`接受批評`,en:`to accept criticism`,ex:`Es ist keine Schwäche, Kritik anzunehmen und davon zu lernen.`,ez:`接受批評並從中學習並不是弱點。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`dem Kunden entgegenkommen`,kz:`向客戶讓步、通融`,en:`to accommodate the customer`,ex:`In diesem Fall sollten wir dem Kunden etwas entgegenkommen.`,ez:`在這種情況下，我們應該對客戶有所通融。`},
{s:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`,k:`Verantwortung übernehmen`,kz:`承擔責任`,en:`to take responsibility`,ex:`Es ist wichtig, dass jeder Verantwortung für seine Fehler übernimmt.`,ez:`重要的是，每個人都要為自己的錯誤承擔責任。`},

];

const RD_SECTIONS = [
  {title:`R1: Anfrage stellen（詢價與詢問）`,       color:`#2E7D32`},
  {title:`R2: Angebot machen（報價與提案）`,         color:`#1565C0`},
  {title:`R3: Bestellung aufgeben（下訂單）`,        color:`#6A1B9A`},
  {title:`R4: Lieferung und Empfang（收貨與物流）`,  color:`#00695C`},
  {title:`R5: Reklamation und Beschwerde（投訴與抱怨）`, color:`#BF360C`},
  {title:`R6: Entschuldigung und Entschädigung（道歉與補償）`, color:`#37474F`},
  {title:`R7: Telefon und Kommunikation（電話溝通）`, color:`#4527A0`},
  {title:`R8: Bewerbung（求職與應徵）`,               color:`#1B5E20`},
  {title:`R9: Krankmeldung und Arbeitsrecht（請病假與勞動法規）`, color:`#880E4F`},
  {title:`R10: Präsentation und Meetings（報告與會議）`, color:`#E65100`},
  {title:`R11: Qualität und Gesundheit（品質管理與職場健康）`, color:`#0D47A1`},
  {title:`R12: Konflikte und Zusammenarbeit（衝突處理與協作）`, color:`#4E342E`},
];
