// Data_Cornelsen_Wortschatz.js
// Cornelsen Prüfungstraining DTB B2 (2022) — "Übungen zum Wortschatz" (S. 111–122)
// Format: { mt, teil, a, w, p, en, zh, k, kz, ex, ez } — identisch zu MT8/MT10

const CORNELSEN_WORTSCHATZ_DATA = [

  // ── DAS UNTERNEHMEN (S.112) ──────────────────────────────────
  { mt:"WS1", teil:"L1",
    a:"das", w:"Personal", p:"",
    en:"staff / personnel", zh:"員工、人事",
    k:"das Personal einstellen / verwalten",
    kz:"雇用員工；管理人事",
    ex:"das Personal — gleichbedeutend mit 'die Beschäftigten'.",
    ez:"das Personal 與 die Beschäftigten 意思相同。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Direktion", p:"-en",
    en:"management / board of directors", zh:"管理層、董事部",
    k:"die Direktion eines Unternehmens",
    kz:"公司的管理層",
    ex:"die Direktion — gleichbedeutend mit 'die Geschäftsführung'.",
    ez:"die Direktion 與 die Geschäftsführung 意思相同。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Entlassung", p:"-en",
    en:"dismissal / layoff", zh:"解僱、裁員",
    k:"eine Entlassung aussprechen",
    kz:"宣布解僱",
    ex:"die Entlassung — Gegenstück zu 'die Kündigung' im Sinne einer vom Unternehmen ausgehenden Trennung.",
    ez:"die Entlassung 是雇主主動終止僱用關係（相對於員工自己辭職的 Kündigung）。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Niederlassung", p:"-en",
    en:"branch / subsidiary", zh:"分公司、分支機構",
    k:"eine Niederlassung eröffnen",
    kz:"開設一間分公司",
    ex:"die Niederlassung — bedeutungsgleich mit 'die Filiale' im Kontext von Unternehmensstandorten.",
    ez:"die Niederlassung 在企業據點語境中與 die Filiale 意思相近。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Ausgabe", p:"-n",
    en:"expense / expenditure", zh:"支出",
    k:"die Ausgaben senken",
    kz:"降低支出",
    ex:"die Ausgaben — Gegenüberstellung von Einnahmen und Ausgaben ergibt die Bilanz.",
    ez:"收入與支出的對照即構成資產負債表（Bilanz）。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Einnahme", p:"-n",
    en:"income / revenue", zh:"收入",
    k:"Einnahmen erzielen",
    kz:"獲得收入",
    ex:"die Einnahmen — Gegenteil von 'die Ausgaben'.",
    ez:"die Einnahmen 是 die Ausgaben 的反義詞。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Verpflichtung", p:"-en",
    en:"obligation / liability", zh:"義務、債務",
    k:"offene Verpflichtungen, z. B. offene Rechnungen",
    kz:"未清償的債務，例如未付帳款",
    ex:"die Verpflichtungen — Definition zu 'die Schulden': Verpflichtungen, z. B. offene Rechnungen.",
    ez:"Schulden 的定義即是「Verpflichtungen，例如未付帳款」。" },

  { mt:"WS1", teil:"L1",
    a:"der", w:"Verlust", p:"-e",
    en:"loss", zh:"損失、虧損",
    k:"einen Verlust machen",
    kz:"出現虧損",
    ex:"der Verlust — Gegenteil von 'der Gewinn'.",
    ez:"der Verlust 是 der Gewinn 的反義詞。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Schulden", p:"(Pl.)",
    en:"debts", zh:"債務",
    k:"Schulden abbauen / aufbauen",
    kz:"減少債務／增加債務",
    ex:"die Schulden — 'ist es uns auch gelungen, unsere Schulden abzubauen.'",
    ez:"我們也成功減少了債務。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Bilanz", p:"-en",
    en:"balance sheet", zh:"資產負債表",
    k:"der Bilanz entnehmen",
    kz:"從資產負債表中得知",
    ex:"die Bilanz — 'Wie Sie der Bilanz entnehmen können, ist es uns auch gelungen, unsere Schulden abzubauen.'",
    ez:"如您可從資產負債表中得知，我們也成功減少了債務。" },

  // ── DAS UNTERNEHMEN — Übung 11 (S.113) ───────────────────────
  { mt:"WS1", teil:"L1",
    a:"", w:"erheblich", p:"",
    en:"considerably / significantly", zh:"顯著地、相當地",
    k:"sich erheblich erweitern",
    kz:"顯著地擴展",
    ex:"Auch das Angebot hat sich erheblich erweitert.",
    ez:"產品供應範圍也顯著地擴大了。" },

  { mt:"WS1", teil:"L1",
    a:"", w:"erweitern", p:"",
    en:"to expand", zh:"擴展、擴大",
    k:"das Angebot erweitern",
    kz:"擴大供應範圍",
    ex:"Auch das Angebot hat sich erheblich erweitert.",
    ez:"供應範圍也顯著地擴大了。" },

  { mt:"WS1", teil:"L1",
    a:"", w:"sich gut behaupten", p:"",
    en:"to hold one's own well / to maintain a strong position", zh:"站穩腳步、保持優勢",
    k:"sich auf dem Markt gut behaupten",
    kz:"在市場上站穩腳步",
    ex:"Aufgrund der gleichbleibend hohen Qualität der Waren kann sich der Betrieb trotz großer Konkurrenz auf dem Markt für Backwaren gut behaupten.",
    ez:"由於產品品質一直維持很高水準，該公司即使面對激烈競爭，仍能在烘焙食品市場上站穩腳步。" },

  { mt:"WS1", teil:"L1",
    a:"", w:"entstehen", p:"",
    en:"to arise / to be created", zh:"產生、出現",
    k:"neue Arbeitsplätze entstehen",
    kz:"產生新的職位",
    ex:"K&L auf Erfolgskurs: Im nächsten Jahr sollen 50 neue Arbeitsplätze entstehen.",
    ez:"明年將產生50個新職位。" },

  { mt:"WS1", teil:"L1",
    a:"", w:"vertreiben", p:"",
    en:"to distribute / to sell / to market", zh:"銷售、經銷",
    k:"Produkte vertreiben",
    kz:"銷售產品",
    ex:"Sie vertreibt Armaturenbretter und Navigationssysteme für Fahrzeuge.",
    ez:"該公司銷售車用儀表板和導航系統。" },

  { mt:"WS1", teil:"L1",
    a:"", w:"beschäftigen", p:"",
    en:"to employ", zh:"雇用",
    k:"Mitarbeitende beschäftigen",
    kz:"雇用員工",
    ex:"In Bayreuth beschäftigt K&Y zurzeit 35 Mitarbeitende.",
    ez:"K&Y 目前在拜羅伊特雇用35名員工。" },

  { mt:"WS1", teil:"L1",
    a:"die", w:"Einigung", p:"-en",
    en:"agreement / settlement", zh:"協議、達成共識",
    k:"eine Einigung finden",
    kz:"達成共識",
    ex:"Man hofft, dass man eine Einigung finden könne, um Streiks zu vermeiden.",
    ez:"希望能達成共識以避免罷工。" },

  // ── ARBEITSSUCHE UND BEWERBUNG (S.114–115) ───────────────────
  { mt:"WS1", teil:"L2",
    a:"", w:"sogenannt", p:"",
    en:"so-called", zh:"所謂的",
    k:"die sogenannte Initiativbewerbung",
    kz:"所謂的主動應徵信",
    ex:"In dieser sogenannten Initiativbewerbung sollte man genau angeben, welche Tätigkeiten man gerne ausüben möchte.",
    ez:"在這份所謂的主動應徵信中，應明確說明自己希望從事的工作內容。" },

  { mt:"WS1", teil:"L2",
    a:"", w:"abhalten", p:"",
    en:"to hold (a meeting) / to prevent someone from (doing something)", zh:"舉行（會議）；阻止（某人）",
    k:"ein Meeting abhalten; jemanden davon abhalten",
    kz:"舉行會議；阻止某人做某事",
    ex:"ein Meeting abhalten（舉行會議）vs. jmd. davon abhalten（阻止某人）— 同一動詞的兩種不同用法。",
    ez:"abhalten 在不同搭配下意思不同：舉行會議，或阻止某人做某事。" },

  { mt:"WS1", teil:"L2",
    a:"das", w:"Betriebssystem", p:"-e",
    en:"operating system", zh:"作業系統",
    k:"Kenntnisse über Betriebssysteme",
    kz:"作業系統相關知識",
    ex:"Ich verfüge über Kenntnisse verschiedener Datenbanken und Betriebssysteme.",
    ez:"我具備多種資料庫和作業系統的相關知識。" },

  { mt:"WS1", teil:"L2",
    a:"", w:"beigefügt", p:"",
    en:"enclosed / attached", zh:"附上的、隨附的",
    k:"dem beigefügten Lebenslauf entnehmen",
    kz:"從隨附的履歷中得知",
    ex:"Weitere Details können Sie dem beigefügten Lebenslauf entnehmen.",
    ez:"更多細節請參閱隨附的履歷。" },

  { mt:"WS1", teil:"L2",
    a:"", w:"gewissenhaft", p:"",
    en:"conscientious / diligent", zh:"認真負責的、盡心盡力的",
    k:"Aufgaben gewissenhaft erledigen",
    kz:"認真完成任務",
    ex:"Irina erledigt alle Aufgaben gewissenhaft. Man kann sich auf sie verlassen.",
    ez:"Irina 認真負責地完成所有任務，大家都能信賴她。" },

  { mt:"WS1", teil:"L2",
    a:"", w:"sich verlassen (auf)", p:"",
    en:"to rely on / to count on", zh:"依靠、信賴",
    k:"sich auf jemanden verlassen können",
    kz:"能夠信賴某人",
    ex:"Man kann sich auf sie verlassen. Sie ist zuverlässig.",
    ez:"大家能夠信賴她，她很可靠。" },

  // ── GESCHÄFTSKORRESPONDENZ (S.116–119) ───────────────────────
  { mt:"WS1", teil:"L3",
    a:"der", w:"Einsatz", p:"",
    en:"use / deployment / application", zh:"使用、應用",
    k:"geeignet für den Einsatz auf Geschäftsreisen",
    kz:"適合用於商務旅行",
    ex:"KHS tragbarer Projektor weiß, ideal für den Einsatz auf Ihren Geschäftsreisen.",
    ez:"KHS 白色攜帶式投影機，非常適合用於您的商務旅行。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"hervorragend", p:"",
    en:"excellent / outstanding", zh:"卓越的、出色的",
    k:"hervorragende Präsentationen liefern",
    kz:"提供卓越的展示效果",
    ex:"Der Projektor liefert hervorragende Präsentationen.",
    ez:"該投影機能呈現卓越的展示效果。" },

  { mt:"WS1", teil:"L3",
    a:"die", w:"Geschäftsbedingungen", p:"(Pl.)",
    en:"terms and conditions", zh:"交易條款",
    k:"die Allgemeinen Geschäftsbedingungen (AGB)",
    kz:"一般交易條款",
    ex:"Es gelten unsere beiliegenden Allgemeinen Geschäftsbedingungen (AGB).",
    ez:"隨附的一般交易條款（AGB）適用於本交易。" },

  { mt:"WS1", teil:"L3",
    a:"die", w:"Feststellung", p:"-en",
    en:"determination / confirmation / finding", zh:"確認、查明",
    k:"um Feststellung bitten, wann Sie liefern können",
    kz:"請求確認交貨時間",
    ex:"Da wir die Waren dringend benötigen, bitten wir um Feststellung, wann Sie liefern können.",
    ez:"由於我們急需這些貨物，請告知確切交貨時間。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"ohne Abzug", p:"",
    en:"without deduction", zh:"不扣除（折扣）",
    k:"der Rechnungsbetrag ist ohne Abzug fällig",
    kz:"應付帳款不扣除折扣",
    ex:"Der Rechnungsbetrag ist ohne Abzug innerhalb von 30 Tagen fällig.",
    ez:"帳款須在30天內全額支付，不得扣除折扣。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"eintreffen", p:"",
    en:"to arrive", zh:"到達、抵達",
    k:"die Ware wird spätestens am Freitag eintreffen",
    kz:"貨品最晚將於週五送達",
    ex:"Die Lieferung wird spätestens am Freitag, den 14. Januar, bei Ihnen eintreffen.",
    ez:"貨品最晚將於1月14日（週五）送達。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"versehentlich", p:"",
    en:"by mistake / accidentally", zh:"不小心地、誤送地",
    k:"versehentlich zugeschickte Produkte",
    kz:"誤送的商品",
    ex:"Der Spediteur kann bei Lieferung die versehentlich zugeschickten Produkte zurücknehmen.",
    ez:"貨運公司可在送貨時取回誤送的商品。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"zurücktreten (von)", p:"",
    en:"to withdraw (from a purchase/contract)", zh:"撤銷（交易、合約）",
    k:"vom Kauf zurücktreten",
    kz:"撤銷購買",
    ex:"Sollten die Projektoren innerhalb der nächsten Woche nicht eintreffen, sehen wir uns gezwungen, vom Kauf zurückzutreten.",
    ez:"若投影機在下週內未送達，我們將被迫撤銷此次購買。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"angegeben", p:"",
    en:"specified / stated", zh:"已標明的、已列出的",
    k:"die unten angegebenen Posten",
    kz:"下方列出的項目",
    ex:"Für die unten angegebenen Posten konnten wir bis zum heutigen Tag keinen Zahlungseingang feststellen.",
    ez:"截至今日，我們尚未收到下方列出項目的款項。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"gewähren", p:"",
    en:"to grant", zh:"給予、提供（折扣等）",
    k:"2% Skonto gewähren",
    kz:"提供2%的現金折扣",
    ex:"Wir können Ihnen 2% Skonto gewähren.",
    ez:"我們可以提供您2%的現金折扣。" },

  { mt:"WS1", teil:"L3",
    a:"", w:"fällig", p:"",
    en:"due (payment)", zh:"到期應付的",
    k:"der Betrag ist fällig",
    kz:"該款項已到期",
    ex:"Ich kann Ihnen versichern, dass ich den offenen Betrag fällig bis zum 21.10 überweisen werde.",
    ez:"我向您保證，將在10月21日到期前匯出未付款項。" },

  // ── ARBEITSBEDINGUNGEN UND ARBEITSRECHT (S.122) ──────────────
  { mt:"WS1", teil:"L4",
    a:"die", w:"Abfindung", p:"-en",
    en:"severance pay", zh:"遣散費、補償金",
    k:"eine Abfindung beanspruchen",
    kz:"申請領取遣散費",
    ex:"Für den Zeitraum, in dem sie bei der Firma gearbeitet hat, wird sie eine Abfindung beanspruchen.",
    ez:"以她在公司工作的這段期間計算，她將申請領取遣散費。" },

  // ── ARBEITSSICHERHEIT / GESUNDHEIT AM ARBEITSPLATZ (S.123) ───
  { mt:"WS1", teil:"L4",
    a:"", w:"erforderlich", p:"",
    en:"required / necessary", zh:"必須的、必要的",
    k:"eine Schutzbrille ist erforderlich",
    kz:"必須佩戴護目鏡",
    ex:"Zum Schutz vor herabfallenden Teilen ist eine Schutzbrille oder eine Gesichtsmaske erforderlich.",
    ez:"為防止掉落物造成傷害，必須佩戴護目鏡或面罩。" },

  { mt:"WS1", teil:"L4",
    a:"der", w:"Vorrang", p:"",
    en:"priority / right of way", zh:"優先權",
    k:"Transportfahrzeuge haben Vorrang",
    kz:"運輸車輛享有優先權",
    ex:"In den Montagehallen den Sicherheitsabstand zu Maschinen einhalten — Transportfahrzeuge, z. B. Stapler, haben Vorrang.",
    ez:"在組裝廠房內須與機械保持安全距離——運輸車輛（如堆高機）享有優先通行權。" },

  { mt:"WS1", teil:"L4",
    a:"das", w:"Informationsblatt", p:"-blätter",
    en:"information sheet", zh:"資訊單、公告單",
    k:"die ausgehängten Informationsblätter lesen",
    kz:"閱讀張貼的資訊單",
    ex:"Informationsblätter geben Hinweise zum richtigen Vorgehen bei Unfällen.",
    ez:"資訊單上提供了事故發生時的正確處理方式。" },

  { mt:"WS1", teil:"L4",
    a:"das", w:"Verbandsmaterial", p:"",
    en:"first-aid material / bandaging supplies", zh:"急救包紮用品",
    k:"Verbandsmaterial aus dem Erste-Hilfe-Koffer nehmen",
    kz:"從急救箱取出包紮用品",
    ex:"Bei Arbeitsunfällen kann man vom Sicherheitsbeauftragten Verbandsmaterial bekommen.",
    ez:"工作意外發生時，可向安全負責人領取包紮用品。" },

  { mt:"WS1", teil:"L4",
    a:"", w:"gestattet", p:"",
    en:"permitted / allowed", zh:"被允許的",
    k:"Rauchen ist nur im Raucherzimmer gestattet",
    kz:"僅允許在吸菸室吸菸",
    ex:"Rauchen ist nur in einem speziellen Raucherzimmer gestattet.",
    ez:"吸菸僅被允許在特定的吸菸室內進行。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列（與 MT8/MT10 相同方式）
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...CORNELSEN_WORTSCHATZ_DATA);
}
