// data_ModellTest10.js
// Modelltest 10 — Cornelsen Prüfungstraining DTB B2, "Modelltest 2" im Buch (S. 129–145)
// Quelle: Prüfungstraining DTB B2 (2022), Cornelsen Verlag
// Format: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST10_DATA = [

  // ── LESEN TEIL 1 ──────────────────────────────────────────────
  { mt:"MT10", teil:"L1",
    a:"die", w:"Entlassung", p:"-en",
    en:"dismissal / layoff", zh:"解僱、裁員",
    k:"sich gegen Entlassungen wehren; betriebsbedingte Entlassung",
    kz:"抵抗解僱；因公司經營需要的解僱",
    ex:"Katharina fragt sich, wie man sich gegen Entlassungen wehren kann.",
    ez:"Katharina 想知道該如何對抗解僱。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"ökologisch nachhaltig", p:"",
    en:"ecologically sustainable", zh:"生態上可持續的",
    k:"ökologisch nachhaltig wirtschaften",
    kz:"以生態可持續的方式經營",
    ex:"Auch die Chemiebranche hat sich das Ziel gesetzt, ökologisch nachhaltig zu wirtschaften.",
    ez:"化學產業也設定了以生態可持續方式經營的目標。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"belastet", p:"",
    en:"burdened / strained", zh:"受到負擔的、壓力大的",
    k:"stark belastet sein; psychisch belastet",
    kz:"承受巨大壓力；心理上有負擔",
    ex:"Er wollte sogar die Stelle wechseln, so stark belastete ihn das angespannte Arbeitsklima.",
    ez:"緊張的工作氛圍讓他壓力很大，甚至想換工作。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"angespannt", p:"",
    en:"tense / strained", zh:"緊張的",
    k:"angespanntes Arbeitsklima; angespannte Situation",
    kz:"緊張的工作氛圍；緊張的局勢",
    ex:"So stark belastete ihn das angespannte Arbeitsklima in seiner Firma.",
    ez:"公司裡緊張的工作氛圍讓他承受很大壓力。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"sich davor hüten", p:"",
    en:"to be wary of / to guard against", zh:"提防、小心避免",
    k:"sich davor hüten, etwas zu tun",
    kz:"小心避免做某事",
    ex:"Sie behandelt auch die Frage, wie man sich davor hüten kann, zu schnell falsche Entscheidungen zu treffen.",
    ez:"她也探討了如何避免過快做出錯誤決定。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"in Anspruch nehmen", p:"",
    en:"to make use of / to take advantage of", zh:"使用、享有（權利或服務）",
    k:"Elternzeit in Anspruch nehmen; ein Angebot in Anspruch nehmen",
    kz:"享有育嬰假；使用某項服務",
    ex:"Auch wenn inzwischen immer mehr Eltern die Möglichkeiten der Elternzeit in Anspruch nehmen, gibt es noch viele offene Fragen.",
    ez:"儘管越來越多父母享有育嬰假的權利，仍有許多懸而未決的問題。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"klimaneutral", p:"",
    en:"climate-neutral", zh:"氣候中和的、碳中和的",
    k:"klimaneutral agieren; klimaneutral wirtschaften",
    kz:"以碳中和方式行動；碳中和經營",
    ex:"Immer mehr Betriebe haben sich zum Ziel gesetzt, klimaneutral zu agieren.",
    ez:"越來越多企業設定了以碳中和方式運營的目標。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"abgebaut", p:"",
    en:"cut / reduced (jobs)", zh:"被削減、被裁減（職位）",
    k:"Arbeitsplätze abbauen; Personal abbauen",
    kz:"削減職位；裁減人員",
    ex:"Durch zahlreiche Umstrukturierungen werden immer wieder Arbeitsplätze abgebaut.",
    ez:"由於多次的組織重整，職位不斷被削減。" },

  { mt:"MT10", teil:"L1",
    a:"", w:"vorzugehen", p:"",
    en:"to take action / proceed (against)", zh:"採取行動、進行處理",
    k:"gegen Kündigungen vorzugehen; rechtlich vorgehen",
    kz:"對抗解僱採取行動；採取法律行動",
    ex:"Welche Möglichkeiten hat man als Arbeitnehmer, gegen Kündigungen vorzugehen?",
    ez:"員工有哪些方式可以對抗解僱？" },

  // ── LESEN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT10", teil:"L2",
    a:"", w:"betriebsbedingt", p:"",
    en:"for operational reasons", zh:"基於營運需要的（解僱、加班等）",
    k:"betriebsbedingte Mehrarbeit; betriebsbedingte Kündigung",
    kz:"基於營運需要的加班；基於營運需要的解僱",
    ex:"Betriebsbedingt ist es möglich, dass Sie bis zu zehn Stunden pro Tag arbeiten.",
    ez:"基於營運需要，您每天最多可工作到十小時。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"in Ausnahmefällen", p:"",
    en:"in exceptional cases", zh:"在特殊情況下",
    k:"nur in Ausnahmefällen erlaubt",
    kz:"僅在特殊情況下被允許",
    ex:"Diese Mehrarbeit ist aber nur in Ausnahmefällen erlaubt und muss innerhalb von sechs Monaten ausgeglichen werden.",
    ez:"這項額外工作僅在特殊情況下被允許，且必須在六個月內以調休方式平衡。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"aussetzen", p:"",
    en:"to suspend", zh:"暫停、中止",
    k:"die Gleitzeit aussetzen; eine Regelung aussetzen",
    kz:"暫停彈性工時；暫停某項規定",
    ex:"Aus betrieblichen Gründen kann der Arbeitgeber die Gleitzeit für eine gewisse Zeit aussetzen.",
    ez:"基於營運理由，雇主可以暫停彈性工時一段時間。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"geleistete (Arbeitsstunden)", p:"",
    en:"hours worked / rendered", zh:"已完成的（工作時數）",
    k:"geleistete Arbeitsstunden; geleistete Überstunden",
    kz:"已完成的工作時數；已完成的加班時數",
    ex:"Unser elektronisches Zeiterfassungssystem registriert täglich die Zahl der von Ihnen geleisteten Arbeitsstunden.",
    ez:"我們的電子計時系統每天記錄您已完成的工作時數。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"rasche (Lösung)", p:"",
    en:"quick (solution)", zh:"迅速的（解決方案）",
    k:"eine rasche Lösung besprechen; rasch handeln",
    kz:"討論一個迅速的解決方案；迅速行動",
    ex:"Wenn ein Abbau nicht möglich ist, wird mit der Geschäftsführung eine rasche Lösung besprochen.",
    ez:"如果無法削減時數，將與管理層討論迅速的解決方案。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"vertraulich behandeln", p:"",
    en:"to treat confidentially", zh:"保密處理",
    k:"Firmenereignisse vertraulich behandeln; Daten vertraulich behandeln",
    kz:"保密處理公司事件；保密處理資料",
    ex:"Die Mitarbeitenden sind bei ihrer Arbeit verpflichtet, alle Firmenereignisse vertraulich zu behandeln.",
    ez:"員工在工作中有義務對所有公司事件保密處理。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"zu Werbezwecken", p:"",
    en:"for advertising purposes", zh:"用於廣告目的",
    k:"Fotos zu Werbezwecken machen",
    kz:"為廣告目的拍照",
    ex:"Sollte der Betrieb für Werbezwecke Fotos machen wollen, auf denen Sie zu sehen sind, geht das nur mit Ihrer Zustimmung.",
    ez:"如果公司想為廣告目的拍攝有您出現的照片，必須先取得您的同意。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"umzugehen (mit)", p:"",
    en:"to handle / to deal with", zh:"處理、應對（某事物）",
    k:"mit Passwörtern umzugehen; mit Daten umzugehen",
    kz:"如何處理密碼；如何處理資料",
    ex:"Im Seminar erfahren Sie, wie mit Passwörtern umzugehen ist.",
    ez:"在研討會中，您將學到如何妥善處理密碼。" },

  // ── LESEN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT10", teil:"L3",
    a:"", w:"ungeeignet", p:"",
    en:"unsuitable / unfit", zh:"不適合的",
    k:"sich als ungeeignet erweisen; für etwas ungeeignet sein",
    kz:"證明不適合；不適合做某事",
    ex:"Ich bekomme immer wieder Kritik von meinem Chef, ich wäre ungeeignet.",
    ez:"我老闆一直批評我，說我不適合（這份工作）。" },

  { mt:"MT10", teil:"L3",
    a:"", w:"langsam genug haben", p:"",
    en:"to slowly have enough (of something)", zh:"漸漸感到受夠了",
    k:"ich habe langsam genug",
    kz:"我漸漸覺得受夠了",
    ex:"Ich habe langsam genug. Soll ich kündigen?",
    ez:"我漸漸覺得受夠了，我應該辭職嗎？" },

  { mt:"MT10", teil:"L3",
    a:"", w:"grundsätzlich", p:"",
    en:"basically / fundamentally", zh:"基本上、原則上",
    k:"grundsätzlich muss schriftlich gekündigt werden",
    kz:"原則上必須以書面方式解僱",
    ex:"Grundsätzlich muss nach dem Arbeitsrecht schriftlich gekündigt werden.",
    ez:"根據勞動法，原則上解僱必須以書面方式進行。" },

  { mt:"MT10", teil:"L3",
    a:"", w:"hitzig", p:"",
    en:"heated / fiery", zh:"激烈的、火爆的",
    k:"eine hitzige Diskussion",
    kz:"一場激烈的討論",
    ex:"Wenn der Chef oder die Chefin in einer hitzigen Diskussion sagt, man könne gehen, ist das nicht schön.",
    ez:"如果老闆在激烈的爭論中說可以走了，這並不是好的處理方式。" },

  { mt:"MT10", teil:"L3",
    a:"", w:"sich entspannen", p:"",
    en:"to calm down / to ease", zh:"平靜下來、緩和",
    k:"die Situation hat sich entspannt; sich entspannen",
    kz:"情況已經緩和；冷靜下來",
    ex:"Man sollte abwarten, bis sich die Situation entspannt hat.",
    ez:"應該等到情況緩和下來。" },

  { mt:"MT10", teil:"L3",
    a:"die", w:"Drohung", p:"-en",
    en:"threat", zh:"威脅",
    k:"eine Abmahnung mit der Drohung; jemandem mit etwas drohen",
    kz:"附帶威脅的警告信；以某事威脅某人",
    ex:"Mein Chef hat das nicht akzeptiert und so bekam ich eine Abmahnung mit der Drohung, dass bei Wiederholungen eine Kündigung möglich ist.",
    ez:"我的上司不接受，因此我收到一份警告信，並附帶若再犯就可能解僱的威脅。" },

  { mt:"MT10", teil:"L3",
    a:"die", w:"Krise", p:"-n",
    en:"crisis", zh:"危機",
    k:"in der Krise sein; eine Krise bewältigen",
    kz:"處於危機中；克服危機",
    ex:"Ich arbeite bei einem Automobilzulieferbetrieb. Wir waren in der Krise.",
    ez:"我在一家汽車零件供應商工作，我們曾經處於危機之中。" },

  { mt:"MT10", teil:"L3",
    a:"die", w:"Werksschließung", p:"-en",
    en:"plant/factory closure", zh:"工廠關閉",
    k:"eine Werksschließung abwenden",
    kz:"避免工廠關閉",
    ex:"Wir konnten eine Werksschließung abwenden, indem die Gewerkschaft in der letzten Tarifrunde auf Lohnerhöhungen verzichtete.",
    ez:"我們透過工會在上次薪資談判中放棄加薪，成功避免了工廠關閉。" },

  { mt:"MT10", teil:"L3",
    a:"", w:"verzichten (auf)", p:"",
    en:"to forgo / to give up", zh:"放棄",
    k:"auf Lohnerhöhungen verzichten",
    kz:"放棄加薪",
    ex:"Die Gewerkschaft hat in der letzten Tarifrunde auf Lohnerhöhungen verzichtet.",
    ez:"工會在上次薪資談判中放棄了加薪。" },

  { mt:"MT10", teil:"L3",
    a:"die", w:"Abfindung", p:"-en",
    en:"severance pay / compensation", zh:"遣散費、補償金",
    k:"Anspruch auf eine Abfindung haben",
    kz:"有權獲得遣散費",
    ex:"Eventuell gibt es auch einen Anspruch auf eine Abfindung. Hier ist eine Rechtsberatung wichtig.",
    ez:"也可能有權獲得遣散費，這部分法律諮詢很重要。" },

  // ── LESEN TEIL 4 ──────────────────────────────────────────────
  { mt:"MT10", teil:"L4",
    a:"der", w:"Beschluss", p:"Beschlüsse",
    en:"decision / resolution", zh:"決議、決定",
    k:"nach Beschluss der letzten Sitzung",
    kz:"依據上次會議的決議",
    ex:"Da KS, der nach Beschluss der letzten Sitzung heute Protokoll führen sollte, wegen Krankheit verhindert ist, übernimmt SM die Protokollführung.",
    ez:"由於依上次會議決議該由 KS 今天負責記錄，但他因病無法出席，故由 SM 接手記錄工作。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"zudem", p:"",
    en:"moreover / in addition", zh:"此外、而且",
    k:"zudem weist sie darauf hin, dass...",
    kz:"此外她指出……",
    ex:"SM weist aber zudem darauf hin, dass es Probleme bei den Auslieferungen der bestellten Möbel gebe.",
    ez:"不過 SM 也指出，訂購的家具在配送上出現了問題。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"eingehen", p:"",
    en:"to arrive / to come in", zh:"（款項、訊息等）到達、收到",
    k:"Kundenzahlungen eingehen; eine Bestellung geht ein",
    kz:"客戶款項到帳；訂單收到",
    ex:"Auch die Kundenzahlungen werden dann später bei uns eingehen.",
    ez:"客戶的款項也將因此較晚收到。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"sich auswirken (auf)", p:"",
    en:"to have an effect (on)", zh:"對……產生影響",
    k:"sich positiv auf den Umsatz auswirken",
    kz:"對營業額產生正面影響",
    ex:"Man müsse davon ausgehen, dass sich die positiven Verkaufszahlen erst im 2. oder 3. Quartal auf unseren Umsatz auswirken.",
    ez:"必須假設正面的銷售數字要到第二或第三季才會對營業額產生影響。" },

  { mt:"MT10", teil:"L4",
    a:"der", w:"Stoffbezug", p:"-bezüge",
    en:"fabric cover / upholstery", zh:"布料套、布製外罩",
    k:"mangelhafte Stoffbezüge",
    kz:"有缺陷的布製外罩",
    ex:"MS berichtet, dass es seit Kurzem Reklamationen wegen mangelhafter Stoffbezüge gebe.",
    ez:"MS 報告說，最近開始有關於布製外罩缺陷的客訴。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"außerordentlich", p:"",
    en:"extraordinarily / exceptionally", zh:"異常地、特別地",
    k:"außerordentlich empfindlich sein",
    kz:"特別敏感",
    ex:"Kunden und Kundinnen beschweren sich darüber, dass sie entgegen den Aussagen im Katalog außerordentlich empfindlich seien.",
    ez:"客戶投訴說，這些產品與目錄上的說法不同，異常容易受損。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"sich wundern", p:"",
    en:"to be surprised", zh:"感到驚訝、感到不解",
    k:"sich über etwas wundern",
    kz:"對某事感到不解",
    ex:"KG wundert sich über die Reklamationen, da sie mit den Stofflieferanten bisher immer gute Erfahrungen gemacht habe.",
    ez:"KG 對這些客訴感到不解，因為她與布料供應商一直以來合作經驗良好。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"gesondert", p:"",
    en:"separate / separately", zh:"個別的、另外安排的",
    k:"sich an einem gesonderten Termin treffen",
    kz:"另外安排時間會面",
    ex:"Es wird gemeinsam entschieden, dass sich die Abteilungen Verkauf, Qualitätskontrolle und Einkauf an einem gesonderten Termin treffen.",
    ez:"大家共同決定，銷售、品管和採購部門將另外安排時間會面。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"berechtigt", p:"",
    en:"justified / legitimate", zh:"有理由的、正當的",
    k:"berechtigte Reklamationen; berechtigt sein",
    kz:"合理的客訴；有正當理由",
    ex:"Sie treffen sich, um zu sehen, ob die Reklamationen berechtigt sind.",
    ez:"他們將會面確認這些客訴是否合理。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"gut angenommen werden", p:"",
    en:"to be well received", zh:"受到好評、被良好接受",
    k:"unser Engagement wird gut angenommen",
    kz:"我們的努力受到好評",
    ex:"Dass unsere Verkaufszahlen so positiv waren, liege, merkt MS an, neben unserer gut angenommenen Online-Präsenz auch an dem großen Engagement unserer Mitarbeitenden im Geschäft vor Ort.",
    ez:"MS 指出，銷售數字之所以這麼好，除了我們深受好評的網路曝光，也歸功於員工在實體店面的高度投入。" },

  { mt:"MT10", teil:"L4",
    a:"das", w:"Engagement", p:"",
    en:"commitment / dedication", zh:"投入、敬業精神",
    k:"großes Engagement zeigen",
    kz:"展現高度投入",
    ex:"Das großes Engagement unserer Mitarbeitenden im Geschäft vor Ort hat zu den guten Verkaufszahlen beigetragen.",
    ez:"員工在實體店面的高度投入對良好的銷售數字有所貢獻。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"kein Widerspruch sein", p:"",
    en:"to not be a contradiction", zh:"並不矛盾",
    k:"das sei kein Widerspruch",
    kz:"這並不矛盾",
    ex:"MS bemerkt hierzu, dass das kein Widerspruch sei, da der Online-Verkauf immer mehr an Bedeutung gewinnen würde.",
    ez:"MS 對此表示，這並不矛盾，因為網路銷售的重要性正在不斷提升。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"zusammenstellen", p:"",
    en:"to put together / to assemble", zh:"組合、配置（產品）",
    k:"individuell durch die Kunden zusammenstellen",
    kz:"由客戶個別組合配置",
    ex:"Es handle sich um hochwertige Möbel, deren Ausstattung individuell durch die Kunden zusammengestellt würde.",
    ez:"這些是高品質家具，其配置可由顧客自行個別組合。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"angeben", p:"",
    en:"to specify / to state", zh:"標示、註明",
    k:"konkrete Preise online angeben",
    kz:"在網路上標示具體價格",
    ex:"Auch konkrete Preise ließen sich online nicht angeben, da der Endpreis von verschiedenen Komponenten abhänge.",
    ez:"由於最終價格取決於多種組件，因此也無法在網路上標示出具體價格。" },

  { mt:"MT10", teil:"L4",
    a:"die", w:"zunehmende Arbeitsbelastung", p:"",
    en:"increasing workload", zh:"日益增加的工作負荷",
    k:"die zunehmende Arbeitsbelastung der Mitarbeitenden ernst nehmen",
    kz:"重視員工日益增加的工作負荷",
    ex:"HK ergänzt hier, dass man die zunehmende Arbeitsbelastung der Mitarbeitenden ernst nehmen müsse.",
    ez:"HK 補充說，必須認真重視員工日益增加的工作負荷。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"vereinzelte (Ausfälle)", p:"",
    en:"isolated / occasional (absences)", zh:"偶發的（缺勤）",
    k:"vereinzelte Ausfälle durch stressbedingte Krankheit",
    kz:"因壓力導致的疾病造成偶發缺勤",
    ex:"Überstunden seien keine Seltenheit, es habe schon vereinzelte Ausfälle durch stressbedingte Krankheit gegeben.",
    ez:"加班並不少見，已經出現了一些因壓力相關疾病導致的偶發缺勤。" },

  { mt:"MT10", teil:"L4",
    a:"die", w:"Personalerweiterung", p:"-en",
    en:"staff expansion", zh:"人員擴編",
    k:"einen Vorschlag zur Personalerweiterung entwickeln",
    kz:"提出人員擴編的建議",
    ex:"BD bittet HK, einen Vorschlag zur Personalerweiterung zu entwickeln.",
    ez:"BD 請 HK 提出一份人員擴編的建議。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"sich einig sein", p:"",
    en:"to agree (with one another)", zh:"達成一致、意見一致",
    k:"die Versammlung ist sich einig, dass...",
    kz:"與會者一致認為……",
    ex:"Die Versammlung ist sich einig, dass hier etwas geschehen muss.",
    ez:"與會者一致認為這方面需要採取行動。" },

  { mt:"MT10", teil:"L4",
    a:"", w:"anregen", p:"",
    en:"to suggest / to propose", zh:"提議、建議",
    k:"PG regt an, dass...",
    kz:"PG 提議……",
    ex:"PG regt an, dass selbiges in diesem Jahr nicht auf unserem Firmengelände stattfinden sollte.",
    ez:"PG 提議今年該活動不應在公司場地舉行。" },

  { mt:"MT10", teil:"L4",
    a:"die", w:"Abwechslung", p:"",
    en:"variety / change of routine", zh:"變化、不同的體驗",
    k:"sich eine Abwechslung wünschen",
    kz:"希望有些不同的體驗",
    ex:"Da sich viele Mitarbeitenden hier gerne eine Abwechslung wünschen, schlägt er vor, das Sommerfest mit unserem Betriebsausflug zu verbinden.",
    ez:"由於許多員工希望有些不同的體驗，他建議將夏季慶典與員工旅遊結合。" },

  // ── LESEN UND SCHREIBEN ───────────────────────────────────────
  { mt:"MT10", teil:"L2",
    a:"", w:"entsprechend (+ Dativ)", p:"",
    en:"in accordance with / according to", zh:"依照、符合……",
    k:"entsprechend Ihrer Zahlungsbedingungen",
    kz:"依照您的付款條件",
    ex:"Die Rechnung haben wir sofort am 5. März überwiesen und uns dann entsprechend Ihrer Zahlungsbedingungen fristgemäß 2% Skonto abgezogen.",
    ez:"我們在3月5日立即匯款，並依照您的付款條件如期扣除了2%的現金折扣。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"fristgemäß", p:"",
    en:"within the deadline / on time", zh:"按期限、如期",
    k:"fristgemäß abziehen; fristgemäß liefern",
    kz:"如期扣除；如期交貨",
    ex:"Wir haben uns fristgemäß 2% Skonto abgezogen, sodass wir €906,50 überwiesen haben.",
    ez:"我們已如期扣除2%的現金折扣，因此匯款了906.50歐元。" },

  { mt:"MT10", teil:"L2",
    a:"", w:"auffordern", p:"",
    en:"to request / to call upon", zh:"要求、催請",
    k:"jemanden auffordern, etwas zu tun",
    kz:"要求某人做某事",
    ex:"Ich möchte Sie noch einmal auffordern, unser Konto auszugleichen.",
    ez:"我想再次要求您結清我們的帳戶款項。" },

  // ── HÖREN TEIL 1 ──────────────────────────────────────────────
  { mt:"MT10", teil:"H1",
    a:"die", w:"Urlaubssperre", p:"-n",
    en:"holiday/vacation freeze", zh:"休假禁令（不可請假的期間）",
    k:"eine Urlaubssperre haben; an Weihnachten eine Urlaubssperre",
    kz:"有休假禁令；聖誕節期間禁止休假",
    ex:"Dieses Jahr gibt es an Weihnachten eine Urlaubssperre.",
    ez:"今年聖誕節期間有休假禁令。" },

  { mt:"MT10", teil:"H1",
    a:"der", w:"Umgang", p:"",
    en:"handling / dealing (with something)", zh:"應對方式、處理方式",
    k:"den Umgang mit unzufriedenen Gästen planen",
    kz:"規劃應對不滿顧客的方式",
    ex:"Das Team plant den Umgang mit unzufriedenen Gästen.",
    ez:"團隊正在規劃應對不滿顧客的方式。" },

  { mt:"MT10", teil:"H1",
    a:"", w:"entgegenkommen", p:"",
    en:"to accommodate / to meet halfway", zh:"配合、體貼地對待",
    k:"Gästen mit Infomaterial entgegenkommen",
    kz:"以資訊資料體貼地對待客人",
    ex:"Man sollte den Gästen mit kostenlosem Infomaterial über die Sehenswürdigkeiten der Stadt entgegenkommen.",
    ez:"應該以免費的城市景點資訊資料來體貼地對待客人。" },

  // ── HÖREN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT10", teil:"H2",
    a:"", w:"sich verstecken (hinter)", p:"",
    en:"to hide (behind)", zh:"隱藏（在……之後）",
    k:"sich hinter der Mehrheitsmeinung verstecken",
    kz:"隱藏在多數意見之後",
    ex:"Bei der Teamarbeit kann man sich schnell hinter der Mehrheitsmeinung verstecken.",
    ez:"在團隊合作中，容易很快就躲在多數人的意見之後。" },

  { mt:"MT10", teil:"H2",
    a:"", w:"schüchtern", p:"",
    en:"shy / timid", zh:"害羞的、內向的",
    k:"mit schüchternen Menschen gibt es Konflikte",
    kz:"與內向的人之間容易有衝突",
    ex:"Mit schüchternen Menschen gibt es im Team oft Konflikte.",
    ez:"團隊中與內向的人之間經常會有衝突。" },

  // ── HÖREN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT10", teil:"H3",
    a:"", w:"anfallen", p:"",
    en:"to arise / to accumulate (waste, costs)", zh:"產生、累積（廢棄物、費用）",
    k:"wo die Abfälle anfallen",
    kz:"廢棄物在哪裡產生",
    ex:"Um Abfälle zu vermeiden, überlegt das Restaurant, wo die Abfälle anfallen.",
    ez:"為了避免浪費，餐廳正在思考廢棄物是在哪裡產生的。" },

  { mt:"MT10", teil:"H3",
    a:"der", w:"Mitnahmebehälter", p:"-",
    en:"take-away container", zh:"外帶容器",
    k:"die Gäste bitten, eigene Mitnahmebehälter zu benutzen",
    kz:"請顧客使用自己的外帶容器",
    ex:"Das Restaurant überlegt, die Gäste zu bitten, eigene Mitnahmebehälter zu benutzen.",
    ez:"餐廳正考慮請顧客自備外帶容器。" },

  { mt:"MT10", teil:"H3",
    a:"", w:"abgeschafft werden", p:"",
    en:"to be abolished", zh:"被取消、被廢除",
    k:"das Sonntagsfrühstück soll abgeschafft werden",
    kz:"週日早餐將被取消",
    ex:"In Zukunft soll das Sonntagsfrühstück abgeschafft werden.",
    ez:"未來週日早餐供應將被取消。" },

  { mt:"MT10", teil:"H3",
    a:"der", w:"Anlass", p:"Anlässe",
    en:"occasion / cause / reason", zh:"原因、起因",
    k:"das Lagerverwaltungssystem gibt wenig Anlass zur Kritik",
    kz:"庫存管理系統很少有值得批評的地方",
    ex:"Das Lagerverwaltungssystem gibt wenig Anlass zur Kritik.",
    ez:"庫存管理系統很少有需要批評的地方。" },

  { mt:"MT10", teil:"H3",
    a:"", w:"sich an etwas beteiligen", p:"",
    en:"to participate in / to take part in", zh:"參與某事",
    k:"sich an einer Methode zur Lebensmittelrettung beteiligen",
    kz:"參與一項拯救食物浪費的方法",
    ex:"Damit weniger Lebensmittel verschwendet werden, wird man sich an einer Methode zur Lebensmittelrettung beteiligen.",
    ez:"為了減少食物浪費，餐廳將參與一項拯救食物的方法。" },

  // ── HÖREN TEIL 4 ──────────────────────────────────────────────
  { mt:"MT10", teil:"H4",
    a:"die", w:"Anzahlung", p:"-en",
    en:"down payment / deposit", zh:"訂金、預付款",
    k:"um eine Anzahlung bitten",
    kz:"要求支付訂金",
    ex:"Die Firma K+W GmbH bittet um eine Anzahlung.",
    ez:"K+W 有限公司要求支付訂金。" },

  { mt:"MT10", teil:"H4",
    a:"die", w:"Teillieferung", p:"-en",
    en:"partial delivery", zh:"部分交貨",
    k:"eine Teillieferung ankündigen",
    kz:"宣布部分交貨",
    ex:"Die Firma K+W GmbH kündigt eine Teillieferung an.",
    ez:"K+W 有限公司宣布將進行部分交貨。" },

  // ── 聽力逐字稿補充 ──────────────────────────────────────────
  { mt:"MT10", teil:"H1",
    a:"die", w:"Überschneidung", p:"-en",
    en:"overlap", zh:"重疊、衝突（時間上）",
    k:"Überschneidungen geben; Termine überschneiden sich",
    kz:"出現重疊；行程互相衝突",
    ex:"Wenn es Überschneidungen gibt, vor allem im Sommer, also wenn viele zur gleichen Zeit Urlaub machen wollen, besprechen Sie das alles auf einem Termin.",
    ez:"如果出現休假時間重疊的情況，尤其是在很多人想同時休假的夏天，請在一次會議中一起討論。" },

  { mt:"MT10", teil:"H1",
    a:"", w:"enttäuscht", p:"",
    en:"disappointed", zh:"感到失望的",
    k:"enttäuscht sein, weil...",
    kz:"因為……而感到失望",
    ex:"Am Anfang der Woche waren die Gäste mal enttäuscht, weil wir ausgebucht waren.",
    ez:"這週初客人有些失望，因為我們已經客滿了。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST10_DATA);
}
