// data_ModellTest4.js
// MT4 = telc Prüfungstraining DTB B2 — Übungstest 1 (書本頁碼 112-121)
// 來源: telc-prufungstraining-deutsch-test-fu-r-den-beruf-b2 PDF, 黃色螢光筆標記
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST4_DATA = [

  // ── LESEN TEIL 1 (S.110-111，原先漏掉的前兩頁) ───────────────────
  { mt:"MT4", teil:"L1",
    a:"", w:"befördert (werden)", p:"",
    en:"to be promoted", zh:"被升職、被晉升",
    k:"befördert werden; frustriert, weil sie nicht befördert wird",
    kz:"被升職；因未獲升職而感到沮喪",
    ex:"Aleksandra ist frustriert, weil sie nicht befördert wird.",
    ez:"Aleksandra 因為沒有獲得升職而感到沮喪。" },

  { mt:"MT4", teil:"L1",
    a:"", w:"neuerdings", p:"",
    en:"lately / recently", zh:"最近、近來",
    k:"neuerdings oft gestresst sein; neuerdings anders sein",
    kz:"最近常常感到壓力大；最近變得不一樣",
    ex:"Hamid kommt neuerdings oft gestresst, nervös und müde von der Arbeit.",
    ez:"Hamid 最近常常帶著壓力、緊張和疲憊的狀態下班回家。" },

  { mt:"MT4", teil:"L1",
    a:"das", w:"Alarmzeichen", p:"-",
    en:"warning sign", zh:"警訊、預警訊號",
    k:"erste Alarmzeichen; ein Alarmzeichen erkennen",
    kz:"最初的警訊；辨識出警訊",
    ex:"Erste Alarmzeichen sind Erschöpfung, Schlaflosigkeit.",
    ez:"最初的警訊是疲憊和失眠。" },

  { mt:"MT4", teil:"L1",
    a:"die", w:"Erschöpfung", p:"",
    en:"exhaustion", zh:"疲憊、力竭",
    k:"Erschöpfung als Symptom; an Erschöpfung leiden",
    kz:"疲憊作為症狀；遭受疲憊之苦",
    ex:"Erste Alarmzeichen sind Erschöpfung, Schlaflosigkeit.",
    ez:"最初的警訊是疲憊和失眠。" },

  { mt:"MT4", teil:"L1",
    a:"die", w:"Unruhe und Reizbarkeit", p:"",
    en:"restlessness and irritability", zh:"焦躁不安與易怒",
    k:"Unruhe und Reizbarkeit zeigen; unter Reizbarkeit leiden",
    kz:"表現出焦躁不安與易怒；受易怒所苦",
    ex:"Schlaflosigkeit, Unruhe und Reizbarkeit.",
    ez:"失眠、焦躁不安與易怒。" },

  { mt:"MT4", teil:"L1",
    a:"das", w:"Gleichgewicht", p:"",
    en:"balance", zh:"平衡",
    k:"Gleichgewicht zwischen Arbeit und Privatleben; das Gleichgewicht finden",
    kz:"工作與私生活之間的平衡；找到平衡點",
    ex:"Gleichgewicht zwischen Arbeit und Privatleben.",
    ez:"工作與私生活之間的平衡。" },

  { mt:"MT4", teil:"L1",
    a:"", w:"nachgehen (seiner Arbeit)", p:"",
    en:"to pursue / go about (one's work)", zh:"從事、進行（自己的工作）",
    k:"seiner Arbeit nachgehen; einer Tätigkeit nachgehen",
    kz:"從事自己的工作；進行某項活動",
    ex:"Hat ausreichend Kraft, um seiner Arbeit nachzugehen.",
    ez:"有足夠的精力去從事自己的工作。" },

  { mt:"MT4", teil:"L1",
    a:"die", w:"Ebene", p:"-n",
    en:"level (relationship level)", zh:"層面、關係層級",
    k:"eine persönliche Ebene aufbauen; auf einer anderen Ebene",
    kz:"建立私人層面的關係；在另一個層面上",
    ex:"Eine persönliche Ebene zu Kollegen und Vorgesetzten aufzubauen.",
    ez:"與同事和上司建立私人層面的關係。" },

  { mt:"MT4", teil:"L1",
    a:"die", w:"Stressbewältigung", p:"",
    en:"stress management", zh:"壓力應對、壓力管理",
    k:"Stressbewältigung – aber wie?; Strategien zur Stressbewältigung",
    kz:"壓力管理——但該怎麼做？；壓力管理策略",
    ex:"Stressbewältigung – aber wie?",
    ez:"壓力管理——但該怎麼做呢？" },

  { mt:"MT4", teil:"L1",
    a:"", w:"anstrengend", p:"",
    en:"exhausting / strenuous", zh:"費力的、累人的",
    k:"ein anstrengender Arbeitstag; etwas ist anstrengend",
    kz:"累人的工作日；某事是費力的",
    ex:"Der Arbeitstag war anstrengend und zur Erholung gönnt man sich abends ein alkoholisches Getränk.",
    ez:"這天工作很累人，晚上就想喝一杯酒放鬆一下。" },

  // ── LESEN TEIL 2 — Einarbeitung (S.112) ─────────────────────────
  { mt:"MT4", teil:"L2",
    a:"", w:"unabhängig (von)", p:"",
    en:"independent of / regardless of", zh:"不論、無關（與……無關）",
    k:"unabhängig von Ihrer Funktion; unabhängig davon, ob...",
    kz:"無論您的職位為何；無論是否……",
    ex:"Bekommen Sie bei uns unabhängig von Ihrer Funktion eine Patin oder einen Paten zur Seite gestellt.",
    ez:"無論您的職位是什麼，我們都會為您安排一位輔導夥伴。" },

  { mt:"MT4", teil:"L2",
    a:"die", w:"Eingliederung", p:"",
    en:"integration / induction", zh:"融入、導入（新環境）",
    k:"die erfolgreiche Eingliederung ins Unternehmen; bei der Eingliederung helfen",
    kz:"成功融入公司；協助融入新環境",
    ex:"Sie/Er hilft Ihnen bei der erfolgreichen Eingliederung ins Unternehmen.",
    ez:"他/她會協助您順利融入公司。" },

  // ── LESEN TEIL 2 — Kfz-Hebebühne (S.113) ────────────────────────
  { mt:"MT4", teil:"L2",
    a:"", w:"unter allen Umständen einhalten", p:"",
    en:"to comply with under all circumstances", zh:"在任何情況下都必須遵守",
    k:"unter allen Umständen eingehalten werden; Vorschriften einhalten",
    kz:"在任何情況下都必須遵守；遵守規定",
    ex:"Hier gelten besondere Sicherheitsvorschriften, die unter allen Umständen eingehalten werden müssen.",
    ez:"這裡適用特殊的安全規定，必須在任何情況下都遵守。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"bedienen (eine Maschine)", p:"",
    en:"to operate (a machine)", zh:"操作（機器）",
    k:"die Hebebühne bedienen; eine Maschine bedienen",
    kz:"操作升降機；操作機器",
    ex:"Die Hebebühne darf nicht jeder bedienen.",
    ez:"並非任何人都可以操作這台升降機。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"überschreiten", p:"",
    en:"to exceed", zh:"超過、超出",
    k:"die Tragfähigkeit darf nicht überschritten werden; eine Grenze überschreiten",
    kz:"承重量不得超過；超出界限",
    ex:"Die maximale Tragfähigkeit der Hebebühne darf nicht überschritten werden.",
    ez:"升降機的最大承重量不得超過。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"angebracht (sein)", p:"",
    en:"to be affixed / attached", zh:"標示在、裝設於",
    k:"gut sichtbar angebracht sein; ein Schild anbringen",
    kz:"清楚可見地標示出來；裝設標誌",
    ex:"Die entsprechenden Werte sind gut sichtbar an der Hebebühne angebracht.",
    ez:"相應的數值清楚標示在升降機上。" },

  { mt:"MT4", teil:"L2",
    a:"das", w:"Steuerelement", p:"-e",
    en:"control element / control panel", zh:"操控裝置、控制元件",
    k:"das Steuerelement hängt rechts; ein Steuerelement bedienen",
    kz:"操控裝置位於右側；操作控制元件",
    ex:"Das Steuerelement hängt stets rechts von der Hebebühne.",
    ez:"操控裝置總是位於升降機的右側。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"im Stehen bedient werden", p:"",
    en:"to be operated while standing", zh:"站立操作",
    k:"im Stehen bedient werden; im Stehen arbeiten",
    kz:"以站立方式操作；站著工作",
    ex:"Das Steuerelement kann im Stehen bedient werden.",
    ez:"這個操控裝置可以站著操作。" },

  { mt:"MT4", teil:"L2",
    a:"der", w:"Aufenthalt", p:"-e",
    en:"presence / staying (in a place)", zh:"停留、滯留",
    k:"ein unnötiger Aufenthalt im Bewegungsbereich; sich im Aufenthalt befinden",
    kz:"不必要地停留在活動範圍內；處於停留狀態",
    ex:"Ein unnötiger Aufenthalt im Bewegungsbereich der Hebebühne ist verboten.",
    ez:"在升降機的活動範圍內不必要地停留是被禁止的。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"sich aufhalten", p:"",
    en:"to stay / remain (in a place)", zh:"停留、待在",
    k:"sich auf der Hebebühne aufhalten; sich an einem Ort aufhalten",
    kz:"停留在升降機上；待在某個地方",
    ex:"Personen dürfen sich zu keiner Zeit auf der Hebebühne aufhalten.",
    ez:"任何時候都不允許有人停留在升降機上。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"belasten", p:"",
    en:"to load / put weight on", zh:"施加負重於",
    k:"die Tragarme unterschiedlich belasten; eine Last gleichmäßig verteilen",
    kz:"使兩臂的承重不均；平均分配負重",
    ex:"Beim Bedienen der Hebebühne soll man die Tragarme nicht unterschiedlich belasten.",
    ez:"操作升降機時不應讓兩支托臂的承重不均。" },

  // ── LESEN TEIL 4 — Protokoll Firma Wicker (S.117) ───────────────
  { mt:"MT4", teil:"L4",
    a:"", w:"verlegen (eine Feier)", p:"",
    en:"to relocate / move (an event)", zh:"轉移地點、改地點舉行（活動）",
    k:"die Feier wird verlegt; etwas an einen anderen Ort verlegen",
    kz:"慶祝活動改地點舉行；把某事物轉移到別處",
    ex:"Die Betriebsfeier wird in ein Restaurant verlegt.",
    ez:"員工聚餐將改地點移到一家餐廳舉行。" },

  { mt:"MT4", teil:"L4",
    a:"", w:"angefallen (Überstunden)", p:"",
    en:"accrued / accumulated (overtime)", zh:"累積的、產生的（加班時數）",
    k:"die bis jetzt angefallenen Überstunden; Kosten fallen an",
    kz:"目前累積的加班時數；產生費用",
    ex:"Die bis jetzt angefallenen Überstunden müssen spätestens im Sommer ausgeglichen werden.",
    ez:"目前累積的加班時數最晚必須在夏天前抵償完。" },

  { mt:"MT4", teil:"L4",
    a:"die", w:"Kippe", p:"-n",
    en:"cigarette butt", zh:"菸蒂",
    k:"die Kippen in die Aschenbecher werfen; eine Kippe ausdrücken",
    kz:"把菸蒂丟進菸灰缸；捻熄菸蒂",
    ex:"Die Raucherinnen und Raucher sollen die Kippen in die Aschenbecher werfen.",
    ez:"吸菸者應該把菸蒂丟進菸灰缸裡。" },

  { mt:"MT4", teil:"L4",
    a:"der", w:"Aschenbecher", p:"-",
    en:"ashtray", zh:"菸灰缸",
    k:"Zigarettenreste im Aschenbecher entsorgen; einen Aschenbecher aufstellen",
    kz:"在菸灰缸內處理菸蒂；放置菸灰缸",
    ex:"Die Zigarettenreste sollten in den Aschenbechern entsorgt werden.",
    ez:"菸蒂應該丟在菸灰缸裡處理。" },

  // ── LESEN UND SCHREIBEN — Frisörbedarf (S.118-119) ──────────────
  { mt:"MT4", teil:"L2",
    a:"", w:"vergangen (Woche)", p:"",
    en:"past / last (week)", zh:"上（週）、過去的",
    k:"vergangene Woche; im vergangenen Jahr",
    kz:"上週；去年",
    ex:"Leider ist bei unserer Bestellung vergangene Woche wieder etwas schiefgegangen.",
    ez:"很遺憾，我們上週的訂單又出了點問題。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"schiefgehen", p:"",
    en:"to go wrong", zh:"出錯、不順利",
    k:"etwas ist schiefgegangen; bei der Bestellung ist etwas schiefgegangen",
    kz:"出了差錯；訂單出了問題",
    ex:"Bei unserer Bestellung ist wieder etwas schiefgegangen.",
    ez:"我們的訂單又出了點差錯。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"bzw. unvollständig", p:"",
    en:"or rather, incomplete", zh:"或者說、不完整",
    k:"falsch bzw. unvollständig sein; bzw. heißt beziehungsweise",
    kz:"錯誤或者說不完整；bzw. 表示「或者說」",
    ex:"Sie war falsch bzw. unvollständig.",
    ez:"它（送貨）是錯的、或者說是不完整的。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"eintreffen", p:"",
    en:"to arrive", zh:"到達、送達",
    k:"die Ware trifft ein; sollte sie nicht morgen bei uns eintreffen",
    kz:"貨物送達；若明天前未能送達",
    ex:"Sollte die bestellte Ware nicht morgen bei uns eintreffen, werden wir uns einen anderen Großhändler suchen.",
    ez:"如果訂購的貨品明天前無法送達，我們將另尋批發商。" },

  { mt:"MT4", teil:"L2",
    a:"der", w:"Eingang dieses Schreibens", p:"",
    en:"receipt of this letter", zh:"這份信函的收件",
    k:"den Eingang dieses Schreibens bestätigen; den Eingang bestätigen",
    kz:"確認收到此信函；確認收件",
    ex:"Bitte bestätigen Sie den Eingang dieses Schreibens und den Liefertermin schriftlich.",
    ez:"請以書面確認收到此信函以及交貨日期。" },

  { mt:"MT4", teil:"L2",
    a:"", w:"gewohnte Qualität", p:"",
    en:"customary / usual quality", zh:"一貫的、習慣的品質",
    k:"der gewohnten Qualität entsprechen; die gewohnte Qualität erwarten",
    kz:"符合一貫的品質；期待一貫的品質水準",
    ex:"Einige der bestellten Produkte entsprechen nicht der gewohnten Qualität.",
    ez:"部分訂購的產品不符合一貫的品質水準。" },

  // ── HÖREN TEIL 1 (S.14-15, 逐字稿PDF) ────────────────────────────
  { mt:"MT4", teil:"H1",
    a:"die", w:"Stempelkarte", p:"-n",
    en:"time card / clock-in card", zh:"打卡卡",
    k:"die Stempelkarte haben; mit der Stempelkarte stempeln",
    kz:"持有打卡卡；用打卡卡打卡",
    ex:"Ihre Stempelkarte haben Sie ja schon, oder?",
    ez:"您已經有打卡卡了，對吧？" },

  { mt:"MT4", teil:"H1",
    a:"", w:"betreten", p:"",
    en:"to enter", zh:"進入",
    k:"das Lager betreten; einen Raum betreten",
    kz:"進入倉庫；進入一個房間",
    ex:"Sie tragen müssen, wenn Sie das Lager betreten.",
    ez:"當您進入倉庫時必須穿戴的（防護服）。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"schräg", p:"",
    en:"diagonally / across", zh:"斜對面",
    k:"schräg gegenüber; schräg liegen",
    kz:"斜對面；斜放",
    ex:"Eine Kantine haben wir hier nicht. Aber schräg gegenüber vom Gebäude ist ein Supermarkt.",
    ez:"我們這裡沒有員工餐廳，但大樓斜對面有一家超市。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"Einzelheiten regeln", p:"",
    en:"to settle the details", zh:"處理細節",
    k:"die Einzelheiten zu regeln; über Einzelheiten sprechen",
    kz:"處理細節事項；討論細節",
    ex:"Es wird langsam Zeit, die Einzelheiten zu regeln.",
    ez:"現在該開始處理細節事項了。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"einzeln", p:"",
    en:"individual / each", zh:"個別的、單獨的",
    k:"die einzelnen Kunden; einzeln betrachtet",
    kz:"個別的客戶；分別來看",
    ex:"Aber wie kommt ihr dann von Hamburg an die Ostsee zu den einzelnen Kunden?",
    ez:"那你們要怎麼從漢堡到波羅的海拜訪個別的客戶呢？" },

  { mt:"MT4", teil:"H1",
    a:"der", w:"Leihwagen", p:"-",
    en:"rental car", zh:"租賃汽車",
    k:"einen Leihwagen nehmen; einen Leihwagen mieten",
    kz:"租一輛車；租用租賃汽車",
    ex:"Wir müssten einen Leihwagen nehmen.",
    ez:"我們得租一輛車。" },

  { mt:"MT4", teil:"H1",
    a:"die", w:"Verpflegung", p:"",
    en:"catering / provisions", zh:"餐飲供應",
    k:"die Verpflegung unterwegs; für die Verpflegung sorgen",
    kz:"途中的餐飲供應；負責餐飲供應",
    ex:"Wie war das noch mal mit der Verpflegung unterwegs?",
    ez:"途中的餐飲供應規定是怎麼樣的？" },

  { mt:"MT4", teil:"H1",
    a:"", w:"Quittungen aufheben", p:"",
    en:"to keep receipts", zh:"保留收據",
    k:"Quittungen aufheben und einreichen; eine Quittung aufheben",
    kz:"保留收據並提交；保留一張收據",
    ex:"Müssen wir alle Quittungen aufheben und einreichen?",
    ez:"我們必須保留所有收據並提交嗎？" },

  { mt:"MT4", teil:"H1",
    a:"der", w:"Prospekt", p:"-e",
    en:"brochure", zh:"宣傳手冊",
    k:"Prospekte und Preislisten mitnehmen; einen Prospekt verteilen",
    kz:"攜帶宣傳手冊和價目表；發送宣傳手冊",
    ex:"Wir sollten aber außerdem Prospekte und Preislisten für das gesamte Sortiment mitnehmen.",
    ez:"我們還應該攜帶整個產品系列的宣傳手冊和價目表。" },

  { mt:"MT4", teil:"H1",
    a:"das", w:"gesamte Sortiment", p:"",
    en:"entire product range", zh:"整個產品系列",
    k:"Preislisten für das gesamte Sortiment; das Sortiment erweitern",
    kz:"整個產品系列的價目表；擴充產品系列",
    ex:"Prospekte und Preislisten für das gesamte Sortiment mitnehmen.",
    ez:"攜帶整個產品系列的宣傳手冊和價目表。" },

  { mt:"MT4", teil:"H1",
    a:"der", w:"Apparat (am Apparat)", p:"-e",
    en:"on the line / phone (speaking)", zh:"電話中（接聽者）",
    k:"Anna Siemers am Apparat; wer ist am Apparat?",
    kz:"Anna Siemers 接聽；是哪位在線上？",
    ex:"Regiobus Potsdam, Anna Siemers am Apparat.",
    ez:"Potsdam 區域巴士公司，我是 Anna Siemers。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"klimatisiert", p:"",
    en:"air-conditioned", zh:"有空調的",
    k:"klimatisiert sein; ein klimatisierter Bus",
    kz:"配有空調；有空調的巴士",
    ex:"Natürlich muss der Bus modern und klimatisiert sein.",
    ez:"巴士當然必須是現代化且配有空調的。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"inbegriffen", p:"",
    en:"included", zh:"包含在內的",
    k:"das Benzin ist nicht inbegriffen; im Preis inbegriffen",
    kz:"汽油不包含在內；包含在價格內",
    ex:"Das Benzin ist natürlich nicht inbegriffen.",
    ez:"汽油當然不包含在內。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"ausgestattet", p:"",
    en:"equipped", zh:"配備的",
    k:"modern ausgestattet sein; gut ausgestattet sein",
    kz:"配備現代化設施；配備良好",
    ex:"Dieser Bus ist erst sechs Monate alt und modern ausgestattet.",
    ez:"這輛巴士才六個月新，配備也很現代化。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"auf kurzen Strecken einsetzen", p:"",
    en:"to deploy on short routes", zh:"用於短程路線",
    k:"den Bus auf kurzen Strecken einsetzen; etwas einsetzen",
    kz:"把巴士用於短程路線；調派使用某物",
    ex:"Wenn Sie ihn auf einer kurzen Strecke einsetzen, könnte Ihr Fahrer bei Bedarf mehrmals fahren.",
    ez:"如果您把它用於短程路線，您的司機需要時可以多跑幾趟。" },

  { mt:"MT4", teil:"H1",
    a:"", w:"fürchten", p:"",
    en:"to fear", zh:"擔心、害怕",
    k:"ich fürchte, ich habe keine andere Wahl; etwas fürchten",
    kz:"我恐怕沒有別的選擇；害怕某事",
    ex:"Ich fürchte, ich habe keine andere Wahl.",
    ez:"我恐怕沒有別的選擇了。" },

  // ── HÖREN TEIL 2 (S.15, 逐字稿PDF) ───────────────────────────────
  { mt:"MT4", teil:"H2",
    a:"die", w:"Angelegenheit", p:"-en",
    en:"matter / affair", zh:"事務、私事",
    k:"über persönliche Angelegenheiten Bescheid wissen; eine Angelegenheit regeln",
    kz:"知道私人事務的詳情；處理一項事務",
    ex:"Ich möchte ehrlich gesagt auch gar nicht so genau über Ihre persönlichen Angelegenheiten Bescheid wissen.",
    ez:"老實說，我也不想太清楚知道您的私人事務細節。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"belästigen", p:"",
    en:"to bother / harass", zh:"打擾、騷擾",
    k:"jemanden belästigen; ich will Sie nicht belästigen",
    kz:"打擾某人；我不想打擾您",
    ex:"Ich will Sie ja nicht belästigen!",
    ez:"我並不想打擾您！" },

  { mt:"MT4", teil:"H2",
    a:"der", w:"Kopierer (läuft)", p:"-",
    en:"copier (is running)", zh:"影印機（運轉中）",
    k:"der Kopierer läuft; ständig läuft ein Telefon",
    kz:"影印機在運轉；電話不斷響",
    ex:"Es stört mich, wenn ständig ein Telefon klingelt, der Kopierer läuft.",
    ez:"電話不斷響、影印機一直運轉，這讓我感到困擾。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"anstrengend", p:"",
    en:"strenuous / tiring", zh:"費力的、累人的",
    k:"das stelle ich mir auch anstrengend vor; eine anstrengende Arbeit",
    kz:"我也覺得那聽起來很累人；費力的工作",
    ex:"Ich stelle mir das auch ziemlich anstrengend vor.",
    ez:"我覺得那聽起來也相當累人。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"dauernd", p:"",
    en:"constantly", zh:"不斷地",
    k:"dauernd Leute; dauernd anrufen",
    kz:"不斷有人；不斷打電話",
    ex:"Hier telefonieren doch dauernd Leute.",
    ez:"這裡不斷有人在講電話。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"ankommen (es kommt an)", p:"",
    en:"to matter", zh:"重要、有影響",
    k:"da kommt es doch nicht an; auf etwas ankommen",
    kz:"這不重要、沒有影響；取決於某事",
    ex:"Da kommt es doch auf einen mehr oder weniger nicht an, oder?",
    ez:"多一個人或少一個人講電話應該沒什麼差別吧？" },

  { mt:"MT4", teil:"H2",
    a:"", w:"sich einmischen", p:"",
    en:"to interfere", zh:"插嘴、干涉",
    k:"sich einmischen; ich will mich nicht einmischen",
    kz:"插嘴、干涉；我不想插嘴",
    ex:"Entschuldigung, wenn ich mich einmische.",
    ez:"抱歉我插嘴了。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"überwiegen", p:"",
    en:"to outweigh / prevail", zh:"佔優勢、超過",
    k:"die Vorteile überwiegen; etwas überwiegt",
    kz:"優點超過缺點；某事佔優勢",
    ex:"Die Vorteile überwiegen. Wir arbeiten im Team einfach produktiver.",
    ez:"優點還是比較多。我們團隊合作確實更有效率。" },

  { mt:"MT4", teil:"H2",
    a:"", w:"abgelenkt (werden)", p:"",
    en:"to be distracted", zh:"被分心",
    k:"leicht abgelenkt werden; sich abgelenkt fühlen",
    kz:"容易被分心；感到分心",
    ex:"Der einzige Nachteil ist, dass man leicht abgelenkt wird.",
    ez:"唯一的缺點是容易分心。" },

  // ── HÖREN TEIL 3 (S.15-16, 逐字稿PDF) ─────────────────────────────
  { mt:"MT4", teil:"H3",
    a:"", w:"beauftragen", p:"",
    en:"to commission / instruct", zh:"委託、指派",
    k:"jemanden beauftragen, etwas zu tun; eine Agentur beauftragen",
    kz:"指派某人做某事；委託代理商",
    ex:"Unsere Geschäftsführerin hat uns vor einem halben Jahr beauftragt, das Marketingkonzept zu entwickeln.",
    ez:"我們的女總經理半年前指派我們開發行銷方案。" },

  { mt:"MT4", teil:"H3",
    a:"der", w:"Hochdruck", p:"",
    en:"high pressure (work intensity)", zh:"高壓、緊鑼密鼓",
    k:"mit Hochdruck daran arbeiten; unter Hochdruck stehen",
    kz:"緊鑼密鼓地進行；處於高壓狀態",
    ex:"Wir in der Marketingabteilung arbeiten seitdem mit Hochdruck daran.",
    ez:"我們行銷部從那時起就緊鑼密鼓地進行這項工作。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"gleichermaßen", p:"",
    en:"equally / likewise", zh:"同樣地、一致地",
    k:"bei allen gleichermaßen beliebt; gleichermaßen wichtig sein",
    kz:"在所有人中同樣受歡迎；同樣重要",
    ex:"Diese Produkte sind seit Jahren bei Kindern und älteren Personen gleichermaßen beliebt.",
    ez:"這些產品多年來在兒童和年長者中同樣受到喜愛。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"einen Erfolg fortsetzen", p:"",
    en:"to continue a success", zh:"延續一項成功",
    k:"den Erfolg fortsetzen; etwas fortsetzen",
    kz:"延續成功；繼續某事",
    ex:"Mit unserer neuen Produktlinie möchten wir den Erfolg fortsetzen.",
    ez:"我們希望用新的產品線延續這項成功。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"ansprechen (Zielgruppe)", p:"",
    en:"to target / appeal to (an audience)", zh:"吸引、針對（目標族群）",
    k:"junge Leute gezielt ansprechen; eine Zielgruppe ansprechen",
    kz:"有針對性地吸引年輕人；針對目標族群",
    ex:"Die Cremes sollen gezielt junge Leute ansprechen.",
    ez:"這些乳霜應該有針對性地吸引年輕人。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"auf Bedürfnisse eingehen", p:"",
    en:"to address / cater to needs", zh:"回應、滿足（需求）",
    k:"auf ihre Bedürfnisse eingehen; auf etwas eingehen",
    kz:"回應他們的需求；對某事做出回應",
    ex:"Und auf ihre Bedürfnisse eingehen.",
    ez:"並回應他們的需求。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"optisch umsetzen", p:"",
    en:"to visually implement / translate into design", zh:"以視覺方式呈現",
    k:"das haben wir auch optisch umgesetzt; etwas umsetzen",
    kz:"我們也用視覺方式呈現了這點；實現某事",
    ex:"Das haben wir auch optisch umgesetzt.",
    ez:"我們也用視覺方式呈現了這一點。" },

  { mt:"MT4", teil:"H3",
    a:"die", w:"Botschaft", p:"-en",
    en:"message", zh:"訊息、宣言",
    k:"diese Botschaft auch im Markendesign umgesetzt; eine Botschaft vermitteln",
    kz:"在品牌設計中呈現這個訊息；傳遞訊息",
    ex:"Wir haben diese Botschaft auch im Markendesign umgesetzt.",
    ez:"我們也在品牌設計中呈現了這個訊息。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"reichen (das Logo)", p:"",
    en:"to be enough / suffice", zh:"足夠",
    k:"reicht dafür nicht unser Logo; das reicht nicht",
    kz:"我們的標誌就不夠了嗎；這不夠",
    ex:"Reicht dafür denn nicht unser Firmenlogo?",
    ez:"那我們的公司標誌就不夠了嗎？" },

  { mt:"MT4", teil:"H3",
    a:"der", w:"Bestandteil", p:"-e",
    en:"component / part", zh:"組成部分",
    k:"ein Bestandteil des Ganzen; fester Bestandteil sein",
    kz:"整體的一部分；是固定的組成部分",
    ex:"Das gehört natürlich auch dazu, ist aber nur ein kleiner Bestandteil des Ganzen.",
    ez:"那當然也是其中一部分，但只是整體中很小的一部分。" },

  { mt:"MT4", teil:"H3",
    a:"das", w:"Lebensgefühl", p:"-e",
    en:"sense of life / lifestyle feeling", zh:"生活態度、生活感",
    k:"die Vermittlung eines Lebensgefühls; ein bestimmtes Lebensgefühl vermitteln",
    kz:"傳達一種生活態度；傳達特定的生活感",
    ex:"Neben dem Wiedererkennungswert geht es auch um die Vermittlung eines Lebensgefühls.",
    ez:"除了辨識度之外，也關係到傳達一種生活態度。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"unverwechselbar", p:"",
    en:"unmistakable / distinctive", zh:"無法混淆的、獨特的",
    k:"unverwechselbar sein; ein unverwechselbares Design",
    kz:"獨特而無法混淆；獨特的設計",
    ex:"Wir müssen unverwechselbar sein und uns klar von der Konkurrenz abheben.",
    ez:"我們必須做到獨特，並清楚地與競爭對手有所區隔。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"sich von der Konkurrenz abheben", p:"",
    en:"to stand out from the competition", zh:"與競爭對手有所區隔",
    k:"sich von der Konkurrenz abheben; sich abheben",
    kz:"與競爭對手有所區隔；顯得突出",
    ex:"Uns klar von der Konkurrenz abheben.",
    ez:"清楚地與競爭對手有所區隔。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"gestalten (Verpackungen)", p:"",
    en:"to design (packaging)", zh:"設計（包裝）",
    k:"die Verpackungen gestalten; etwas neu gestalten",
    kz:"設計包裝；重新設計某物",
    ex:"In diesen Farben sind auch die Verpackungen gestaltet.",
    ez:"包裝也是用這些顏色設計的。" },

  { mt:"MT4", teil:"H3",
    a:"der", w:"Kanal", p:"Kanäle",
    en:"channel", zh:"管道、頻道",
    k:"auf diesen Kanälen sprechen; über Social-Media-Kanäle",
    kz:"透過這些管道溝通；透過社群媒體管道",
    ex:"Auf diesen Kanälen sprechen wir unsere potenziellen Kundinnen und Kunden an.",
    ez:"我們透過這些管道接觸潛在客戶。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"sich im jungen Segment etablieren", p:"",
    en:"to establish oneself in the young segment", zh:"在年輕客群中立足",
    k:"erfolgreich im jungen Segment etablieren; sich etablieren",
    kz:"成功在年輕客群中立足；確立地位",
    ex:"Damit stellen wir sicher, dass wir eine weitere Marke aus unserem Haus erfolgreich im jungen Segment etablieren.",
    ez:"這樣我們就能確保我們公司的另一個品牌能成功在年輕客群中立足。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"erwerben", p:"",
    en:"to acquire / purchase", zh:"購買、取得",
    k:"unsere Kosmetik zu testen und zu erwerben; ein Produkt erwerben",
    kz:"試用並購買我們的化妝品；購買產品",
    ex:"Die Leute trotzdem die Möglichkeit haben, unsere Kosmetika zu testen und zu erwerben.",
    ez:"人們仍然有機會試用並購買我們的化妝品。" },

  { mt:"MT4", teil:"H3",
    a:"der", w:"Werbespot", p:"-s",
    en:"commercial / advertisement", zh:"廣告片",
    k:"drei verschiedene Werbespots produzieren; einen Werbespot zeigen",
    kz:"製作三種不同的廣告片；播放廣告片",
    ex:"Wir haben drei verschiedene Werbespots produziert.",
    ez:"我們製作了三種不同的廣告片。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"eher junges (Publikum)", p:"",
    en:"rather young (audience)", zh:"偏年輕的（觀眾）",
    k:"ein eher junges Publikum ansprechen; eher jung sein",
    kz:"吸引偏年輕的觀眾；偏向年輕",
    ex:"Da wir ein eher junges Publikum ansprechen, werden wir die Verbraucher in unseren Werbespots duzen.",
    ez:"因為我們吸引的是偏年輕的觀眾，我們的廣告片會以「du」稱呼消費者。" },

  { mt:"MT4", teil:"H3",
    a:"der/die", w:"Verbraucher/in", p:"-",
    en:"consumer", zh:"消費者",
    k:"die Verbraucher duzen; den Verbraucher ansprechen",
    kz:"以「du」稱呼消費者；對消費者進行宣傳",
    ex:"Werden wir die Verbraucher in unseren Werbespots duzen.",
    ez:"我們會在廣告片中以「du」稱呼消費者。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"versprechen", p:"",
    en:"to promise", zh:"承諾、保證",
    k:"genau das, was unsere Produkte auch versprechen; jemandem etwas versprechen",
    kz:"正是我們產品所承諾的；向某人承諾某事",
    ex:"Also genau das, was unsere Produkte auch versprechen.",
    ez:"也就是我們的產品所承諾的那種感覺。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"verzichten (auf)", p:"",
    en:"to forgo / do without", zh:"放棄、不使用",
    k:"auf Radiowerbung verzichten; auf etwas verzichten",
    kz:"放棄廣播廣告；放棄某事物",
    ex:"Auf Radiowerbung werden wir vorerst verzichten.",
    ez:"我們暫時不會使用廣播廣告。" },

  { mt:"MT4", teil:"H3",
    a:"", w:"verabredet (sein mit)", p:"",
    en:"to have an appointment (with)", zh:"與……有約",
    k:"mit jemandem verabredet sein; einen Termin verabreden",
    kz:"與某人有約；約定一個時間",
    ex:"Ich war heute um 14.00 Uhr mit Herrn Kaiser bei mir im Büro verabredet.",
    ez:"我今天14點和 Kaiser 先生在我辦公室有約。" },

  // ── HÖREN TEIL 4 / HÖREN UND SCHREIBEN (S.17, 逐字稿PDF) ─────────
  { mt:"MT4", teil:"H4",
    a:"", w:"Angaben zur Dosierung", p:"",
    en:"dosage information", zh:"劑量說明",
    k:"die genauen Angaben zur Dosierung; Angaben fehlen",
    kz:"準確的劑量說明；缺少資訊",
    ex:"Außerdem fehlen auch die genauen Angaben zur Dosierung.",
    ez:"此外也缺少準確的劑量說明。" },

  { mt:"MT4", teil:"H4",
    a:"", w:"ausgefallen (Heizung)", p:"",
    en:"to have failed / broken down (heating)", zh:"故障、失效（暖氣）",
    k:"die Heizung ist ausgefallen; komplett ausgefallen sein",
    kz:"暖氣故障了；完全失效",
    ex:"Bei uns in der dritten Etage ist die Heizung komplett ausgefallen.",
    ez:"我們三樓的暖氣完全故障了。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST4_DATA);
}
