// data_ModellTest3.js
// Modelltest 3 — Kommentierter Modelltest (telc DTB B2)
// Format: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST3_DATA = [

  // ── LESEN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT3", teil:"L2",
    a:"", w:"erforderlich", p:"",
    en:"required / necessary", zh:"必要的、需要的",
    k:"eine Anmeldung ist erforderlich; als erforderlich gelten",
    kz:"需要報名；被視為必要",
    ex:"Da die Kursinhalte hier aufeinander aufbauen, gibt es feste Gruppen, und es ist eine Anmeldung erforderlich.",
    ez:"由於課程內容互相銜接，課程分為固定小組，且報名是必要的。" },

  { mt:"MT3", teil:"L2",
    a:"der/die", w:"Angehörige", p:"-n",
    en:"member / employee (of a company)", zh:"公司成員、員工",
    k:"Angehörige unserer Firma; Firmenangehörige",
    kz:"本公司員工；公司成員",
    ex:"Aus versicherungstechnischen Gründen sind diese Angebote Angehörigen unserer Firma vorbehalten.",
    ez:"基於保險方面的原因，這些活動僅限本公司員工參加。" },

  // ── LESEN TEIL 4 ──────────────────────────────────────────────
  { mt:"MT3", teil:"L4",
    a:"", w:"anstelle (+ Genitiv)", p:"",
    en:"instead of", zh:"代替、取而代之",
    k:"anstelle eines Lebkuchenpakets; anstelle der Feier Geld spenden",
    kz:"代替薑餅禮盒；以捐款代替慶典",
    ex:"MQ gibt bekannt, dass unsere externen Mitarbeiter*innen dieses Jahr anstelle eines Lebkuchenpakets elektronische Grußkarten bekommen werden.",
    ez:"MQ 宣布，今年外部員工將收到電子賀卡，而非薑餅禮盒。" },

  { mt:"MT3", teil:"L4",
    a:"", w:"absprechen", p:"",
    en:"to agree on / to arrange / to coordinate", zh:"約定、協調、商定",
    k:"Termine absprechen; etwas mit jemandem absprechen",
    kz:"約定時間；與某人協商某事",
    ex:"NE macht für die Sitzung mit der jeweiligen Leitung im Anschluss Zeiten aus und spricht Termine ab.",
    ez:"NE 在每次會議結束後與各部門主管約定時間並安排後續行程。" },

  { mt:"MT3", teil:"L4",
    a:"", w:"im Anschluss (an + Akk.)", p:"",
    en:"afterwards / subsequently / following", zh:"隨後、緊接著、之後",
    k:"im Anschluss an die Sitzung; im Anschluss daran",
    kz:"在會議結束後；緊接著",
    ex:"Sie macht für die Sitzung mit der jeweiligen Leitung im Anschluss Zeiten aus.",
    ez:"她在每次會議後立即與各部門主管安排後續時間。" },

  { mt:"MT3", teil:"L4",
    a:"", w:"erläutern", p:"",
    en:"to explain / to elaborate", zh:"說明、闡述（比 erklären 更正式）",
    k:"einen Plan erläutern; Hintergründe erläutern",
    kz:"說明計畫；闡述背景",
    ex:"Der Geschäftsführer erläutert den Dienstplan zwischen Weihnachten und Neujahr.",
    ez:"總經理說明了聖誕節到元旦之間的排班計畫。" },

  { mt:"MT3", teil:"L4",
    a:"", w:"spenden", p:"",
    en:"to donate", zh:"捐贈、贊助",
    k:"Geld spenden; für einen guten Zweck spenden",
    kz:"捐款；為公益捐款",
    ex:"Der Geschäftsführer will anstelle der Feier Geld spenden.",
    ez:"總經理希望以捐款取代慶典活動。" },

  // ── HÖREN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT3", teil:"H2",
    a:"die", w:"Ablenkung", p:"-en",
    en:"distraction", zh:"分心、干擾",
    k:"Ablenkung im Büro; für Ablenkung sorgen; abgelenkt sein",
    kz:"辦公室裡的干擾；造成分心；處於分心狀態",
    ex:"Ablenkung gibt es im Home-Office und auch im Büro.",
    ez:"不管是居家辦公還是在辦公室，都會有分心的狀況。" },

  { mt:"MT3", teil:"H2",
    a:"", w:"ersparen", p:"",
    en:"to save / to spare", zh:"節省、免去",
    k:"den Arbeitsweg ersparen; jemandem etwas ersparen",
    kz:"節省通勤時間；為某人免去某事",
    ex:"Im Home-Office zu arbeiten erspart den Arbeitsweg.",
    ez:"居家辦公可以省去通勤的時間。" },

  { mt:"MT3", teil:"H2",
    a:"", w:"misstrauen (+ Dativ)", p:"",
    en:"to mistrust / to distrust", zh:"不信任（注意：接第三格）",
    k:"jemandem misstrauen; Mitarbeitern misstrauen",
    kz:"不信任某人；不信任員工",
    ex:"Mitarbeitern im Home-Office wird manchmal misstraut.",
    ez:"居家辦公的員工有時候會受到不信任。" },

  // ── HÖREN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT3", teil:"H3",
    a:"die", w:"Bodenfläche", p:"-n",
    en:"floor area / floor surface", zh:"地板面積、地板平面",
    k:"Bodenflächen reinigen; Bodenflächen desinfizieren",
    kz:"清潔地板；消毒地板",
    ex:"Die größte Änderung betrifft die Reinigung der Bodenflächen in den Produktionshallen.",
    ez:"最大的改變涉及生產大廳地板的清潔方式。" },

  { mt:"MT3", teil:"H3",
    a:"der", w:"Aufenthaltsraum", p:"Aufenthaltsräume",
    en:"break room / common room", zh:"休息室、員工休息區",
    k:"in den Aufenthaltsräumen reinigen; den Aufenthaltsraum nutzen",
    kz:"清潔休息室；使用休息室",
    ex:"In den Aufenthaltsräumen, den Teeküchen und auf den Korridoren müsst ihr alles reinigen und desinfizieren.",
    ez:"在休息室、茶水間和走廊，你們必須清潔和消毒所有物品。" },

  { mt:"MT3", teil:"H3",
    a:"der", w:"Korridor", p:"-e",
    en:"corridor / hallway", zh:"走廊（口語也說 der Flur）",
    k:"auf den Korridoren; durch den Korridor gehen",
    kz:"在走廊上；穿過走廊",
    ex:"Auf den Korridoren müsst ihr alles reinigen, womit die Mitarbeiter*innen in Berührung kommen.",
    ez:"走廊上所有員工會接觸到的東西，你們都必須清潔。" },

  { mt:"MT3", teil:"H3",
    a:"", w:"ausstatten (mit + Dativ)", p:"",
    en:"to equip / to furnish with", zh:"配備、提供設備",
    k:"mit Geräten ausstatten; ausgestattet werden",
    kz:"配備器具；被配備設備",
    ex:"Dafür werden sie ausgestattet und bekommen gebrauchsfertige Multi-Cleans in Spenderboxen.",
    ez:"為此他們將獲得配備，並收到放在分配盒裡可直接使用的清潔紙巾。" },

  { mt:"MT3", teil:"H3",
    a:"", w:"für Ersatz sorgen", p:"",
    en:"to ensure replenishment / to arrange for replacements", zh:"負責補充、確保備用品足夠",
    k:"für Ersatz sorgen; Ersatz bereitstellen",
    kz:"負責補充；提供備品",
    ex:"Ihr müsst abends für Ersatz sorgen, wenn ihr seht, dass nur noch sehr wenige Tücher drin sind.",
    ez:"如果你們發現盒裡的紙巾所剩無幾，晚上必須補充。" },

  { mt:"MT3", teil:"H3",
    a:"", w:"zuständig (für + Akk.)", p:"",
    en:"responsible for / in charge of", zh:"負責的、主管的（強調職責分工）",
    k:"zuständig sein für; die zuständige Person; zuständige Behörde",
    kz:"負責某事；負責人；主管機關",
    ex:"Die Schreibtische lassen wir in Zukunft in Ruhe. Dafür sind nur noch die Bürokräfte selbst zuständig.",
    ez:"今後我們不再負責桌子的清潔，那部分只由辦公室員工自行負責。" },

  { mt:"MT3", teil:"H3",
    a:"die", w:"Zuverlässigkeit", p:"",
    en:"reliability / dependability", zh:"可靠性",
    k:"Zuverlässigkeit zeigen; auf die Zuverlässigkeit vertrauen",
    kz:"展現可靠性；信賴可靠性",
    ex:"（聽力中強調工作人員的可靠性。）",
    ez:"（出現於聽力語境，強調人員或設備的可靠性。）" },

  { mt:"MT3", teil:"H3",
    a:"die", w:"Verantwortung", p:"-en",
    en:"responsibility", zh:"責任、職責",
    k:"Verantwortung übernehmen; Verantwortung tragen; die Verantwortung für etw. haben",
    kz:"承擔責任；負有責任；對某事負責",
    ex:"（聽力中強調各工作人員的職責分工。）",
    ez:"（出現於聽力語境，強調職責分工，何人負責何事。）" },

  { mt:"MT3", teil:"H3",
    a:"", w:"berührungslos", p:"",
    en:"contactless / touchless", zh:"非接觸式的（berühren = 觸摸 → berührungslos = 無觸碰）",
    k:"berührungslose Spender; berührungslos bedienen",
    kz:"非接觸式分配器；無接觸操作",
    ex:"Die Firma Wandspacher hat die Desinfektionsmittel-Spender ausgetauscht. Die sind jetzt berührungslos.",
    ez:"Wandspacher 公司已更換消毒液分配器，現在改為非接觸式。" },

  { mt:"MT3", teil:"H3",
    a:"die", w:"Anwendung", p:"-en",
    en:"application / use / operation", zh:"使用、操作、應用",
    k:"einfach in der Anwendung; zur Anwendung kommen",
    kz:"使用簡單；派上用場",
    ex:"Die Geräte sind nicht schwierig in der Anwendung. Im Prinzip funktionieren sie wie Staubsauger.",
    ez:"這些設備使用起來並不困難，基本原理就像吸塵器一樣。" },

  { mt:"MT3", teil:"H3",
    a:"", w:"in Berührung kommen (mit + Dativ)", p:"",
    en:"to come into contact with", zh:"接觸到、碰觸到",
    k:"mit Oberflächen in Berührung kommen; mit Chemikalien in Berührung kommen",
    kz:"接觸到表面；接觸到化學品",
    ex:"Ihr müsst alles reinigen, womit die Mitarbeiter*innen in Berührung kommen.",
    ez:"你們必須清潔員工會碰觸到的所有物品。" },

  { mt:"MT3", teil:"H3",
    a:"", w:"in Ruhe lassen", p:"",
    en:"to leave alone / to leave as is", zh:"不去碰、讓它保持原樣",
    k:"jemanden in Ruhe lassen; etwas in Ruhe lassen",
    kz:"不打擾某人；不去動某物",
    ex:"Die Schreibtische lassen wir in Zukunft in Ruhe.",
    ez:"今後我們不再去動桌子。" },

  // ── SPRACHBAUSTEINE TEIL 2 ────────────────────────────────────
  { mt:"MT3", teil:"SB2",
    a:"die", w:"Bemühung", p:"-en",
    en:"effort / endeavour", zh:"努力、盡力",
    k:"große Bemühungen; trotz aller Bemühungen; sich bemühen um + Akk.",
    kz:"巨大的努力；儘管付出努力；努力爭取某事",
    ex:"Wir bieten mit unserer Gewerbe-Kühl-Gefrierkombination ein zu Ihren großen Bemühungen passendes Produkt.",
    ez:"我們提供的商用冷藏冷凍組合，是一款符合您大力爭取目標的產品。" },

  { mt:"MT3", teil:"SB2",
    a:"", w:"äußern", p:"",
    en:"to express / to voice", zh:"表達、說出（geäußert = 所表達的）",
    k:"einen Wunsch äußern; Kritik äußern; seinen Wunsch geäußert haben",
    kz:"表達願望；提出批評；曾表達過願望",
    ex:"Wir bieten ein zu Ihrem geäußerten Wunsch passendes Produkt an.",
    ez:"我們提供一款符合您所表達意願的產品。" },

  { mt:"MT3", teil:"SB2",
    a:"", w:"ausstehend", p:"",
    en:"outstanding / pending", zh:"待付的、懸而未決的",
    k:"ausstehende Schulden; ausstehende Zahlungen",
    kz:"待付款項；待付款",
    ex:"Innerhalb der von Ihnen ausstehenden Schulden konnten wir in der Preiskalkulation bleiben.",
    ez:"在您尚未清償的款項範圍內，我們的報價仍能符合您的預算。" },

  { mt:"MT3", teil:"SB2",
    a:"die", w:"Preisvorgabe", p:"-n",
    en:"price specification / budget ceiling", zh:"預算上限、定價規格（Vorgabe = 規定的目標值）",
    k:"innerhalb der Preisvorgabe bleiben; eine Preisvorgabe einhalten",
    kz:"維持在預算上限內；遵守定價規格",
    ex:"Innerhalb der von Ihnen genannten Preisvorgabe konnten wir in der Preiskalkulation bleiben.",
    ez:"我們的報價計算能夠維持在您所提出的預算上限之內。" },

  { mt:"MT3", teil:"SB2",
    a:"die", w:"Auftragserteilung", p:"-en",
    en:"placing of an order", zh:"下訂單、委託訂單（erteilen = 發出 → Auftragserteilung = 發出委託）",
    k:"nach erfolgter Auftragserteilung; die Auftragserteilung bestätigen",
    kz:"在下訂單之後；確認訂單",
    ex:"Wir können Ihnen die Kombination spätestens drei Wochen nach der von Ihnen erfolgten Auftragserteilung liefern.",
    ez:"我們最晚可在您下訂後三週內交貨。" },

  { mt:"MT3", teil:"SB2",
    a:"die", w:"Schadensmeldung", p:"-en",
    en:"damage report / claims notification", zh:"損害申報、事故通報",
    k:"eine Schadensmeldung einreichen; ausgefüllte Schadensmeldung",
    kz:"提交損害申報；填妥的事故通報",
    ex:"（Sprachbausteine 選項，為干擾選項，不符合語境。）",
    ez:"（出現於 Sprachbausteine 選項中，注意與 Auftragserteilung 的語義差異。）" },

  { mt:"MT3", teil:"SB2",
    a:"die", w:"Stornierung", p:"-en",
    en:"cancellation", zh:"取消（stornieren = 取消訂單或預訂）",
    k:"eine sofortige Stornierung; eine Stornierung vornehmen; stornieren",
    kz:"立即取消；進行取消；取消訂單",
    ex:"（Sprachbausteine 選項，為干擾選項，不符合語境。）",
    ez:"（出現於 Sprachbausteine 選項中，注意與 termingerechte Lieferung 的語義差異。）" },

  { mt:"MT3", teil:"SB2",
    a:"", w:"termingerecht", p:"",
    en:"on time / on schedule", zh:"按時的、準時的（Termin = 期限 + gerecht = 符合）",
    k:"termingerechte Lieferung; termingerecht liefern",
    kz:"準時交貨；按時送達",
    ex:"Wir garantieren Ihnen eine termingerechte Lieferung nach Ihren Wünschen.",
    ez:"我們保證依照您的要求準時交貨。" },
];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST3_DATA);
}
