// data_ModellTest2.js
// Modelltest 2 — Cornelsen Prüfungstraining DTB B2 (2022), S. 1–81
// Format: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST2_DATA = [

  // ── LESEN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT2", teil:"L2",
    a:"die", w:"Sicherheitsbestimmung", p:"-en",
    en:"safety regulation / safety rule", zh:"安全規定、安全守則",
    k:"Sicherheitsbestimmungen befolgen; Sicherheitsbestimmungen einhalten",
    kz:"遵守安全規定；遵守安全守則",
    ex:"Bei der Bedienung der Maschinen sind die jeweiligen Sicherheitsbestimmungen zu befolgen, angepasst an die neuen Richtlinien laut Arbeitsschutzgesetz.",
    ez:"操作機器時，必須遵守各自的安全規定，並依據勞動安全法的最新指導方針進行調整。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"anpassen (an + Akk.)", p:"",
    en:"to adapt / to adjust to", zh:"調整、使適應（angepasst an = 依照……調整）",
    k:"an neue Richtlinien anpassen; an die Situation anpassen",
    kz:"依據新規定調整；因應情況調整",
    ex:"Die Sicherheitsbestimmungen wurden an die neuen Richtlinien laut Arbeitsschutzgesetz angepasst.",
    ez:"安全規定已依據勞動安全法的最新指導方針進行了調整。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"aktualisieren", p:"",
    en:"to update / to revise", zh:"更新、修訂",
    k:"Regeln aktualisieren; Informationen aktualisieren; aktualisiert werden",
    kz:"更新規定；更新資訊；被更新",
    ex:"Die Regelungen am Arbeitsplatz wurden aktualisiert.",
    ez:"工作場所的規定已更新。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"entsorgen", p:"",
    en:"to dispose of / to get rid of", zh:"處置、丟棄（廢棄物）",
    k:"Abfall entsorgen; Schutzkleidung entsorgen; ordnungsgemäß entsorgen",
    kz:"丟棄垃圾；處置防護服；依規定處置",
    ex:"Auf dem Firmengelände darf kein Abfall entsorgt werden.",
    ez:"公司場地內不得隨意丟棄廢棄物。" },

  { mt:"MT2", teil:"L2",
    a:"die", w:"Unterhaltung", p:"",
    en:"entertainment / amusement", zh:"娛樂、消遣",
    k:"für Unterhaltung sorgen; Unterhaltung bieten; der Unterhaltungsteil",
    kz:"提供娛樂；帶來娛樂；娛樂部分",
    ex:"Der Infotag dient der Außenpräsentation und Unterhaltung.",
    ez:"資訊日是為了對外展示和娛樂活動而舉辦的。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"bekanntgeben", p:"",
    en:"to announce / to make known", zh:"宣布、公告",
    k:"einen Vorschlag bekanntgeben; Ergebnisse bekanntgeben; Termine bekanntgeben",
    kz:"公告提案；公布結果；公告時間",
    ex:"Die Geschäftsleitung wird ihren Terminvorschlag bekanntgeben.",
    ez:"管理層將公告其時間提案。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"einen Vorschlag unterbreiten", p:"",
    en:"to submit / present a proposal", zh:"提出提案、提交建議（較正式）",
    k:"einen Vorschlag unterbreiten; einen Terminvorschlag unterbreiten",
    kz:"提出建議；提交時間方案",
    ex:"Den Terminvorschlag unterbreitet die Geschäftsleitung.",
    ez:"時間方案由管理層提出。" },

  // ── LESEN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT2", teil:"L3",
    a:"", w:"weisungsbefugt", p:"",
    en:"authorized to give instructions / having authority over", zh:"有指揮權的、有授權下令的",
    k:"weisungsbefugt sein; der Vorgesetzte ist weisungsbefugt",
    kz:"擁有指揮權；上司有權下令",
    ex:"Tatsächlich ist es so, dass der Chef weisungsbefugt ist, das heißt, er kann die Handynutzung während der Arbeit untersagen.",
    ez:"事實上，老闆是有指揮權的，也就是說，他可以禁止在工作期間使用手機。" },

  { mt:"MT2", teil:"L3",
    a:"die", w:"Abmahnung", p:"-en",
    en:"formal warning from employer", zh:"正式書面警告（來自雇主，解僱前的必要程序）",
    k:"eine Abmahnung erhalten / aussprechen; vor einer Kündigung kommt eine Abmahnung",
    kz:"收到正式警告；發出正式警告；解僱前先有正式警告",
    ex:"In diesem Fall muss es vor einer einseitigen Beendigung des Arbeitsverhältnisses eine Abmahnung geben.",
    ez:"在這種情況下，單方面終止勞動關係前必須先發出正式警告。" },

  // ── LESEN TEIL 4 ──────────────────────────────────────────────
  { mt:"MT2", teil:"L4",
    a:"der", w:"Vordruck", p:"-e",
    en:"printed form / template", zh:"印刷表格、範本",
    k:"einen Vordruck ausfüllen; es gibt einen Vordruck der Broschüre",
    kz:"填寫表格；有一份簡介範本",
    ex:"Es gibt inzwischen einen Vordruck unserer Firmenbroschüre, in dem der Werdegang anschaulich dargestellt wird.",
    ez:"公司簡介現已有一份印刷範本，清楚地展示了公司的發展歷程。" },

  { mt:"MT2", teil:"L4",
    a:"", w:"anschaulich", p:"",
    en:"vividly / clearly / illustratively", zh:"生動地、清晰地、直觀地",
    k:"anschaulich darstellen / erklären / präsentieren",
    kz:"生動地呈現；清楚地說明；直觀地展示",
    ex:"Der Werdegang unseres Unternehmens wird in der Broschüre anschaulich dargestellt.",
    ez:"公司的發展歷程在簡介中被清晰地呈現出來。" },

  { mt:"MT2", teil:"L4",
    a:"", w:"genehmigen", p:"",
    en:"to approve / to authorize", zh:"批准、核准",
    k:"einen Antrag genehmigen; zum Druck genehmigen; genehmigt werden",
    kz:"批准申請；核准印刷；獲得批准",
    ex:"Die Firmenbroschüre wird zum Druck genehmigt.",
    ez:"公司簡介獲准付印。" },

  { mt:"MT2", teil:"L4",
    a:"", w:"annehmen", p:"",
    en:"to accept / to be received (well)", zh:"接受、採納；（被動）受到接受",
    k:"einen Vorschlag annehmen; von Kunden angenommen werden",
    kz:"採納建議；受到客戶接受",
    ex:"Unser Online-Shop wird von den Kunden noch zu wenig angenommen.",
    ez:"我們的網路商店目前還沒有得到客戶足夠的接受。" },

  { mt:"MT2", teil:"L4",
    a:"", w:"zugunsten (+ Genitiv)", p:"",
    en:"in favour of / to the benefit of", zh:"有利於、以……為利益",
    k:"zugunsten der Werbung im Internet; zugunsten einer Partei entscheiden",
    kz:"有利於網路廣告；有利於某方做決定",
    ex:"Die klassischen Werbemaßnahmen sollen zugunsten der Werbung im Internet reduziert werden.",
    ez:"傳統廣告措施應縮減，以有利於網路廣告。" },

  // ── LESEN UND SCHREIBEN ───────────────────────────────────────
  { mt:"MT2", teil:"L2",
    a:"", w:"vorhanden", p:"",
    en:"existing / available / present", zh:"現有的、存在的",
    k:"vorhanden sein; vorhandene Ressourcen; nicht vorhanden sein",
    kz:"存在；現有資源；不存在",
    ex:"Thomas Hoger reklamiert einen nicht vorhandenen Service.",
    ez:"Thomas Hoger 投訴了一項根本不存在的服務。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"auftreten", p:"",
    en:"to occur / to arise / to appear", zh:"出現、發生（問題、缺陷）",
    k:"Mängel treten auf; ein Problem tritt auf; zum ersten Mal auftreten",
    kz:"缺陷出現；問題出現；第一次出現",
    ex:"Die genannten Mängel sind nicht zum ersten Mal aufgetreten.",
    ez:"所提到的缺陷並非第一次出現。" },

  { mt:"MT2", teil:"L2",
    a:"", w:"rasch", p:"",
    en:"quickly / promptly / rapidly", zh:"迅速地、立即（= schnell，但更正式）",
    k:"rasch beseitigen; rasch reagieren; rasch handeln",
    kz:"迅速排除；迅速反應；迅速行動",
    ex:"Die genannten Mängel sollen rasch beseitigt werden.",
    ez:"所提到的缺陷應迅速排除。" },

  // ── HÖREN TEIL 1 ──────────────────────────────────────────────
  { mt:"MT2", teil:"H1",
    a:"der", w:"Diätplan", p:"-pläne",
    en:"diet plan / dietary plan", zh:"飲食計畫",
    k:"einen Diätplan haben / einhalten / befolgen",
    kz:"有飲食計畫；遵守飲食計畫；依照飲食計畫",
    ex:"Herr Groß hat einen genauen Diätplan. Achten Sie bitte darauf, dass er sich gesund ernährt.",
    ez:"Groß 先生有一份詳細的飲食計畫，請注意讓他保持健康飲食。" },

  { mt:"MT2", teil:"H1",
    a:"", w:"schmackhaft", p:"",
    en:"tasty / palatable / appetizing", zh:"美味的、可口的",
    k:"Speisen schmackhaft zubereiten; schmackhaft machen",
    kz:"烹調出美味的料理；使食物可口",
    ex:"Sie kann auch vegetarische Speisen schmackhaft zubereiten.",
    ez:"她也能將素食料理烹調得美味可口。" },

  { mt:"MT2", teil:"H1",
    a:"", w:"verzichten (auf + Akk.)", p:"",
    en:"to do without / to forgo / to give up", zh:"放棄、不享用、戒除",
    k:"auf Fleisch verzichten; auf Hülsenfrüchte verzichten; auf Flüge verzichten",
    kz:"放棄肉食；不吃豆類；不搭飛機",
    ex:"Er darf auf Hülsenfrüchte wie Bohnen, Erbsen und Linsen nicht zurückgreifen – er muss darauf verzichten.",
    ez:"他不能食用菜豆、豌豆和扁豆等豆類，必須放棄這些食物。" },

  { mt:"MT2", teil:"H1",
    a:"", w:"unbedingt", p:"",
    en:"absolutely / without fail / under all circumstances", zh:"絕對地、務必、不管如何",
    k:"unbedingt einhalten; unbedingt beachten; unbedingt notwendig",
    kz:"務必遵守；務必注意；絕對必要",
    ex:"Er muss die Vorgaben im Diätplan unbedingt einhalten.",
    ez:"他務必遵守飲食計畫中的規定。" },

  // ── HÖREN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT2", teil:"H2",
    a:"", w:"unverzichtbar", p:"",
    en:"indispensable / essential", zh:"不可或缺的、必不可少的",
    k:"unverzichtbar sein; als unverzichtbar gelten; unverzichtbarer Bestandteil",
    kz:"不可或缺；被視為不可缺少；不可或缺的組成部分",
    ex:"Geschäftsreisen sind weiter unverzichtbar.",
    ez:"出差仍然是不可或缺的。" },

  { mt:"MT2", teil:"H2",
    a:"die", w:"ökologische Folge", p:"-n",
    en:"ecological consequence / environmental impact", zh:"生態影響、環境後果",
    k:"ökologische Folgen berücksichtigen; ökologische Folgen von Dienstreisen",
    kz:"考量生態影響；出差的環境後果",
    ex:"Bei Dienstreisen sind die ökologischen Folgen zu berücksichtigen.",
    ez:"出差時應將生態影響納入考量。" },

  { mt:"MT2", teil:"H2",
    a:"", w:"umweltbewusst", p:"",
    en:"environmentally conscious / eco-aware", zh:"有環保意識的",
    k:"umweltbewusst handeln; umweltbewusst sein; umweltbewusstes Verhalten",
    kz:"以環保意識行動；有環保意識；有環保意識的行為",
    ex:"Wer umweltbewusst ist, sollte sich gegen Geschäftsreisen wehren.",
    ez:"有環保意識的人應該抵制出差。" },

  { mt:"MT2", teil:"H2",
    a:"der", w:"Geschäftsabschluss", p:"-schlüsse",
    en:"closing a deal / business conclusion", zh:"完成交易、談成生意",
    k:"zu einem Geschäftsabschluss kommen; einen Geschäftsabschluss erzielen",
    kz:"達成交易；完成一筆生意",
    ex:"Der persönliche Kontakt zu den Kunden ist vor allem wichtig, wenn es zu einem Geschäftsabschluss kommen soll.",
    ez:"當需要達成交易時，與客戶的個人接觸尤為重要。" },

  { mt:"MT2", teil:"H2",
    a:"der", w:"Brandschutz", p:"",
    en:"fire protection / fire safety", zh:"防火措施、消防安全",
    k:"Brandschutz gewährleisten; Brandschutzmaßnahmen; zum Brandschutz beraten",
    kz:"確保防火安全；防火措施；就消防安全提供建議",
    ex:"Um die Kunden beim Brandschutz zu beraten, muss er an Ort und Stelle sein.",
    ez:"為了就消防安全向客戶提供建議，他必須親自到場。" },

  { mt:"MT2", teil:"H2",
    a:"die", w:"Sicherungsmaßnahme", p:"-n",
    en:"safety measure / protective measure", zh:"安全措施、防護措施",
    k:"Sicherungsmaßnahmen ergreifen; Tipps zu Sicherungsmaßnahmen geben",
    kz:"採取安全措施；提供安全措施建議",
    ex:"Er kann dann auch noch Tipps zu verbesserten Sicherungsmaßnahmen geben.",
    ez:"他之後還可以提供改善安全措施的建議。" },

  { mt:"MT2", teil:"H2",
    a:"", w:"großzügig", p:"",
    en:"generously / lavishly", zh:"慷慨地、大方地",
    k:"großzügig abgelten; großzügig entlohnen; großzügig sein",
    kz:"慷慨補償；慷慨給薪；大方",
    ex:"Da die Dienstreisen bei uns vom Arbeitgeber großzügig mit Überstunden abgegolten werden, ist das kein Problem.",
    ez:"由於出差在我們公司由雇主以加班費慷慨補償，這不成問題。" },

  { mt:"MT2", teil:"H2",
    a:"", w:"abgelten", p:"",
    en:"to compensate / to settle / to offset", zh:"補償、以……抵償",
    k:"mit Überstunden abgelten; Mehrarbeit abgelten",
    kz:"以加班時數補償；補償超時工作",
    ex:"Die Dienstreisen werden vom Arbeitgeber großzügig mit Überstunden abgegolten.",
    ez:"出差由雇主以加班費慷慨補償。" },

  { mt:"MT2", teil:"H2",
    a:"die", w:"Bauabnahme", p:"-n",
    en:"building inspection / final acceptance of construction", zh:"建築驗收、工程完工驗收",
    k:"die Bauabnahme machen / durchführen",
    kz:"進行建築驗收；執行完工驗收",
    ex:"Ich soll die Bauabnahme machen – unsere Firma hat eine Filiale in Barcelona bauen lassen.",
    ez:"我要去進行建築驗收，我們公司在巴塞隆納蓋了一個分公司。" },

  // ── HÖREN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT2", teil:"H3",
    a:"die", w:"Versammlung", p:"-en",
    en:"assembly / meeting / gathering", zh:"大會、集會、聚集",
    k:"eine Versammlung einberufen; an einer Versammlung teilnehmen",
    kz:"召開大會；參加集會",
    ex:"Frau Lowitz hat ihn gebeten, diese Versammlung einzuberufen.",
    ez:"Lowitz 女士請求他召開這次大會。" },

  { mt:"MT2", teil:"H3",
    a:"die", w:"Bürofläche", p:"-n",
    en:"office floor space / office area", zh:"辦公室面積、辦公空間",
    k:"Büroflächen leer stehen; Büroflächen nutzen; die gesamte Bürofläche",
    kz:"辦公空間閒置；利用辦公空間；整體辦公室面積",
    ex:"Es führt dazu, dass viele unserer Büroflächen leer stehen und nicht benutzt werden.",
    ez:"這導致我們許多辦公室面積閒置未被使用。" },

  { mt:"MT2", teil:"H3",
    a:"das", w:"Einzelbüro", p:"-s",
    en:"private / individual office", zh:"獨立辦公室、單人辦公室",
    k:"Einzelbüros umbauen; aus Einzelbüros einen offenen Raum machen",
    kz:"改建獨立辦公室；將獨立辦公室改為開放空間",
    ex:"Wir haben sieben Einzelbüros, von denen vier seit einiger Zeit nicht benutzt werden.",
    ez:"我們有七間獨立辦公室，其中四間已有一段時間未被使用。" },

  { mt:"MT2", teil:"H3",
    a:"", w:"umgestalten", p:"",
    en:"to restructure / to redesign / to reorganize", zh:"重新規劃、改造、重新布置",
    k:"die Bürolandschaft umgestalten; einen Raum umgestalten",
    kz:"重新規劃辦公室環境；改造空間",
    ex:"Wir müssen eine Lösung finden, wie wir die bestehende Bürolandschaft so umgestalten, dass die gesamte Bürofläche sinnvoll genutzt werden kann.",
    ez:"我們必須找到解決方案，重新規劃現有辦公室環境，使整體辦公空間能夠有效利用。" },

  { mt:"MT2", teil:"H3",
    a:"die", w:"Arbeitsumgebung", p:"-en",
    en:"work environment / working environment", zh:"工作環境",
    k:"eine passende Arbeitsumgebung suchen; die Arbeitsumgebung gestalten",
    kz:"尋找合適的工作環境；規劃工作環境",
    ex:"Man sucht sich jetzt seine Arbeitsumgebung, die zu der konkreten Aufgabe passt.",
    ez:"現在人們會自己尋找適合當前任務的工作環境。" },

  { mt:"MT2", teil:"H3",
    a:"der", w:"Einzelschreibtisch", p:"-tische",
    en:"individual desk / personal desk", zh:"個人辦公桌",
    k:"Einzelschreibtische abschaffen; keine festen Einzelschreibtische mehr",
    kz:"廢除個人辦公桌；不再有固定個人辦公桌",
    ex:"Zu dieser neuen Bürolandschaft würden dann ein Meetingbereich und mehrere Einzelschreibtische gehören.",
    ez:"這種新辦公室環境將包括一個會議區和多個個人辦公桌。" },

  // ── SPRACHBAUSTEINE TEIL 1 ────────────────────────────────────
  { mt:"MT2", teil:"SB1",
    a:"", w:"anlässlich (+ Genitiv)", p:"",
    en:"on the occasion of", zh:"藉……之際、在……的場合（指特定事件或場合）",
    k:"anlässlich eines Ereignisses; anlässlich meines Schreibens",
    kz:"藉某事件之際；在我寫信之際",
    ex:"Anlässlich bezieht sich auf ein Ereignis, eine Aktion: Anlässlich meines Schreibens …",
    ez:"Anlässlich 指涉一個事件或行動：藉此函件之際……（注意：與 aufgrund 不同，強調場合而非原因）" },

  // ── LESEN TEIL 1（補錄，物理上置尾以保護現有 checkpoint ID）──
  { mt:"MT2", teil:"L1",
    a:"die", w:"Forderung", p:"-en",
    en:"demand / claim", zh:"要求、訴求",
    k:"die Forderung der Gewerkschaft; eine Forderung stellen",
    kz:"工會的訴求；提出要求",
    ex:"So lautet die Forderung der Gewerkschaft in den letzten Tarifverhandlungen.",
    ez:"這就是工會在上一輪薪資談判中的訴求。" },

  { mt:"MT2", teil:"L1",
    a:"die", w:"Tarifverhandlung", p:"-en",
    en:"collective bargaining / wage negotiation", zh:"薪資談判、集體協商",
    k:"Tarifverhandlungen führen; in den Tarifverhandlungen",
    kz:"進行薪資談判；在薪資談判中",
    ex:"Gerade in der letzten Zeit hat die Gewerkschaft auf Lohnerhöhungen verzichtet, die Zeit für ein Entgegenkommen sei heute reif.",
    ez:"工會在近期的談判中放棄了加薪要求，現在是雙方各退一步的時機。" },

  { mt:"MT2", teil:"L1",
    a:"", w:"verzichten (auf)", p:"",
    en:"to waive / forgo / give up", zh:"放棄、捨棄",
    k:"auf Lohnerhöhungen verzichten; freiwillig verzichten",
    kz:"放棄加薪要求；自願放棄",
    ex:"Gerade in der letzten Zeit hat die Gewerkschaft auf Lohnerhöhungen verzichtet.",
    ez:"工會在近期一直放棄了加薪要求。" },

  { mt:"MT2", teil:"L1",
    a:"", w:"erwartungsgemäß", p:"",
    en:"as expected / predictably", zh:"不出所料、果然",
    k:"erwartungsgemäß waren die Arbeitgeber nicht begeistert; erwartungsgemäß verlief",
    kz:"果然，雇主方並不熱情；預期的進行",
    ex:"Erwartungsgemäß waren die Arbeitgeber von dieser Idee nicht begeistert.",
    ez:"果然，雇主方對這個想法並不感到熱情。" },

  { mt:"MT2", teil:"L1",
    a:"die", w:"Planungssicherheit", p:"",
    en:"planning certainty / reliable planning basis", zh:"規劃確定性、可預期性",
    k:"Planungssicherheit haben; für Planungssicherheit sorgen",
    kz:"擁有規劃確定性；確保可預期性",
    ex:"Unternehmen auf dem Land hatten wenig Planungssicherheit, da nur langsam Internet zur Verfügung stand.",
    ez:"農村的企業規劃確定性很低，因為網路連線速度緩慢。" },

  { mt:"MT2", teil:"L1",
    a:"der", w:"Glasfaserausbau", p:"",
    en:"fiber optic network expansion", zh:"光纖網路建設、光纖鋪設",
    k:"der Glasfaserausbau vorantreiben; Milliarden Euro für den Glasfaserausbau",
    kz:"推進光纖建設；數十億歐元用於光纖鋪設",
    ex:"Durch viele Milliarden Euro für den Glasfaserausbau ist schnelles Internet bald kein Privileg der Städte mehr.",
    ez:"透過數十億歐元的光纖建設投資，快速網路即將不再是城市的專利。" },

  { mt:"MT2", teil:"L1",
    a:"die", w:"Zunahme", p:"-n",
    en:"increase / growth", zh:"增加、成長",
    k:"die Zunahme von Homeoffice; eine starke Zunahme verzeichnen",
    kz:"居家辦公的增加；記錄到明顯增長",
    ex:"Nicht nur durch die Zunahme von Homeoffice, sondern auch durch flexible Gestaltung des Arbeitstags wird sich die Zukunft der Arbeitswelt ändern.",
    ez:"不僅因為居家辦公的增加，還有工作日的彈性安排，都將改變未來的工作世界。" },

  { mt:"MT2", teil:"L1",
    a:"die", w:"Gestaltung", p:"-en",
    en:"design / structuring / organization", zh:"安排、規劃、設計",
    k:"die flexible Gestaltung des Arbeitstags; die Gestaltung der Zukunft",
    kz:"工作日的彈性安排；未來的規劃",
    ex:"Nicht nur durch die Zunahme von Homeoffice, sondern auch durch flexible Gestaltung des Arbeitstags wird sich die Zukunft der Arbeitswelt ändern.",
    ez:"不僅因為居家辦公的增加，還有工作日的彈性安排，都將改變未來的工作世界。" },

  { mt:"MT2", teil:"L1",
    a:"der", w:"Betrüger/in", p:"-",
    en:"fraudster / scammer", zh:"詐騙者、騙子",
    k:"vor Betrügern schützen; Betrüger im Netz",
    kz:"防範詐騙者；網路上的騙子",
    ex:"Es gibt weitere Tipps, wie man Betrügern im Netz das Leben schwer machen kann.",
    ez:"還有更多提示，說明如何讓網路上的騙子更難得手。" },

  // ── HÖREN TEIL 4（補錄，逐字稿 Nr. 36–39）────────────────────
  { mt:"MT2", teil:"H4",
    a:"", w:"ausfallen", p:"",
    en:"to be absent / unable to work (due to injury/illness)", zh:"缺席、無法上班",
    k:"wie lange ich ausfallen muss; krankheitsbedingt ausfallen",
    kz:"我需要缺席多久；因病缺席",
    ex:"Ich gehe morgen zum Arzt, dann weiß ich, wie lange ich ausfallen muss.",
    ez:"我明天去看醫生，到時候就知道我需要缺席多久了。" },

  { mt:"MT2", teil:"H4",
    a:"", w:"einrichten", p:"",
    en:"to set up / install / configure", zh:"安裝、設置",
    k:"neue Software einrichten; ein System einrichten",
    kz:"安裝新軟體；設置一個系統",
    ex:"Neue Software wird eingerichtet und die Sicherheit unserer Firewall wird auf den neuesten Stand gebracht.",
    ez:"新軟體將被安裝，我們的防火牆安全性也將更新到最新版本。" },

  { mt:"MT2", teil:"H4",
    a:"die", w:"Internetverbindung", p:"-en",
    en:"internet connection", zh:"網路連線",
    k:"Probleme bei der Internetverbindung; keine stabile Internetverbindung",
    kz:"網路連線問題；沒有穩定的網路連線",
    ex:"Wer also in dieser Zeit arbeitet, muss mit Problemen bei der Internetverbindung rechnen.",
    ez:"因此在這段時間工作的人，必須預期會遇到網路連線問題。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST2_DATA);
}
