// data_ModellTest9.js
// MT9 = telc Prüfungstraining DTB B2 — Übungstest 2 (書本頁碼 130-145)
// 來源: telc-prufungstraining-deutsch-test-fu-r-den-beruf-b2 PDF, 黃色螢光筆標記
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST9_DATA = [

  // ── LESEN TEIL 2 — Kennenlerntage der neuen Azubis (S.132) ─────
  { mt:"MT9", teil:"L2",
    a:"", w:"vertreten (Marken)", p:"",
    en:"to represent / carry (a brand)", zh:"代理、經銷（品牌）",
    k:"Marken vertreten; eine Firma vertreten",
    kz:"代理品牌；代表一家公司",
    ex:"Die Marken, die wir exklusiv vertreten.",
    ez:"我們獨家代理的品牌。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"jeweilig", p:"",
    en:"respective", zh:"各自的、相應的",
    k:"während eurer jeweiligen Ausbildung; der jeweilige Bereich",
    kz:"在各自的培訓期間；相應的部門",
    ex:"Ihr werdet während eurer jeweiligen Ausbildung eingesetzt.",
    ez:"你們會在各自的培訓期間被分配到不同部門。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"einsetzen (Personal)", p:"",
    en:"to deploy / assign (staff)", zh:"派遣、分配（人力）",
    k:"in Abteilungen eingesetzt werden; Personal einsetzen",
    kz:"被分配到各部門；調派人力",
    ex:"Morgen startet ihr in den Abteilungen, in denen ihr eingesetzt werdet.",
    ez:"明天你們會開始在被分配到的部門工作。" },

  // ── LESEN TEIL 2 — Arbeitszeit (S.133) ──────────────────────────
  { mt:"MT9", teil:"L2",
    a:"die", w:"Anzahl", p:"",
    en:"number / quantity", zh:"數量",
    k:"die Anzahl erhöht sich; eine bestimmte Anzahl",
    kz:"數量增加；特定數量",
    ex:"Die Anzahl erhöht sich mit längerer Dienstzugehörigkeit.",
    ez:"數量會隨著服務年資增長而提高。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"angehalten sein (zu)", p:"",
    en:"to be required / obliged to", zh:"被要求、有義務（做某事）",
    k:"angehalten sein, etwas zu tun; dazu angehalten werden",
    kz:"被要求做某事；被要求遵守",
    ex:"Sie sind angehalten, einmal pro Jahr mindestens 10 Arbeitstage zu nehmen.",
    ez:"你們有義務每年至少請10個連續工作日的假。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"aufeinanderfolgend", p:"",
    en:"consecutive", zh:"連續的",
    k:"aufeinanderfolgende Arbeitstage; an aufeinanderfolgenden Tagen",
    kz:"連續的工作日；在連續幾天",
    ex:"Mindestens 10 aufeinanderfolgende Arbeitstage zu nehmen.",
    ez:"至少要請10個連續的工作日。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"genehmigen", p:"",
    en:"to approve", zh:"批准、核准",
    k:"den Urlaub genehmigen; er genehmigt ihn im Laufe des Folgemonats",
    kz:"核准假期；他在次月內核准",
    ex:"Er genehmigt ihn im Laufe des Folgemonats.",
    ez:"他會在次月內核准（休假申請）。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"gemäß (+ Dat.)", p:"",
    en:"according to / in accordance with", zh:"依照、根據",
    k:"gemäß dem gültigen Tarifvertrag; gemäß den Vorschriften",
    kz:"依照現行的勞動協議；依照規定",
    ex:"Gemäß dem gültigen Tarifvertrag steht jedem Mitarbeiter ein Urlaubsgeld zu.",
    ez:"依照現行的勞動協議，每位員工都有權獲得休假津貼。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"zustehen (jdm. steht etwas zu)", p:"",
    en:"to be entitled to", zh:"有權獲得",
    k:"jedem Mitarbeiter steht ein Urlaubsgeld zu; ein Recht steht jemandem zu",
    kz:"每位員工都有權獲得休假津貼；某人享有某項權利",
    ex:"Jedem Mitarbeiter steht ein jährliches Urlaubsgeld zu.",
    ez:"每位員工都有權獲得年度休假津貼。" },

  { mt:"MT9", teil:"L2",
    a:"die", w:"Unternehmensrichtlinie", p:"-n",
    en:"company policy / guideline", zh:"公司方針、企業規範",
    k:"im Rahmen unserer Unternehmensrichtlinien; gegen die Richtlinien verstoßen",
    kz:"在我們公司方針的框架內；違反規範",
    ex:"Im Rahmen unserer Unternehmensrichtlinien begrüßen wir die Weiterbildung.",
    ez:"依照我們的公司方針，我們鼓勵員工進修。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"vielfältig", p:"",
    en:"diverse / varied", zh:"多樣的、多元的",
    k:"vielfältige interne Angebote; ein vielfältiges Angebot",
    kz:"多元的內部課程；多樣化的選項",
    ex:"Um mehr über unsere vielfältigen internen Angebote zu erfahren.",
    ez:"想了解更多我們多元的內部進修課程。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"gewähren", p:"",
    en:"to grant", zh:"給予、准予",
    k:"fünf freie Tage gewähren; jemandem etwas gewähren",
    kz:"准予五天的假；給予某人某項待遇",
    ex:"Gewährt Ihnen das Unternehmen pro Jahr fünf freie Tage.",
    ez:"公司每年會給予您五天的假。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"vergüten", p:"",
    en:"to compensate / pay for", zh:"支付報酬、給予補償",
    k:"die Zeit wird nicht vergütet; eine Leistung vergüten",
    kz:"這段時間不予支薪；給服務支付報酬",
    ex:"Diese Zeit wird nicht vergütet oder durch Freizeit ausgeglichen.",
    ez:"這段時間不予支薪，也不會以補休方式抵償。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"ausgleichen (durch Freizeit)", p:"",
    en:"to offset / compensate (with time off)", zh:"以（休假）方式抵償",
    k:"durch Freizeit ausgeglichen werden; einen Verlust ausgleichen",
    kz:"以補休方式抵償；彌補損失",
    ex:"Diese Zeit wird nicht vergütet oder durch Freizeit ausgeglichen.",
    ez:"這段時間不予支薪，也不會以補休方式抵償。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"genehmigungspflichtig", p:"",
    en:"subject to approval", zh:"需經核准的",
    k:"genehmigungspflichtig sein; ein genehmigungspflichtiger Antrag",
    kz:"需要事先核准；需經核准的申請",
    ex:"Die Teilnahme an einer Fortbildung während der Arbeitszeit ist genehmigungspflichtig.",
    ez:"在工作時間內參加進修課程需要事先獲得核准。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"fachbezogen", p:"",
    en:"job-related / subject-specific", zh:"與專業相關的",
    k:"eine fachbezogene Fortbildung; fachbezogene Kenntnisse",
    kz:"與專業相關的進修課程；專業相關知識",
    ex:"Der Besuch einer fachbezogenen Fort- oder Weiterbildung kann angeordnet werden.",
    ez:"公司可以指派員工參加與專業相關的進修課程。" },

  // ── LESEN TEIL 3 — Rund um den Beruf (S.134-135) ────────────────
  { mt:"MT9", teil:"L3",
    a:"die", w:"bezahlte Auszeit", p:"",
    en:"paid time off", zh:"有薪假",
    k:"eine bezahlte Auszeit bei der Arbeit; Auszeit nehmen",
    kz:"工作上的有薪假；請假休息",
    ex:"Ist dafür eine bezahlte Auszeit bei der Arbeit möglich?",
    ez:"為此可以申請有薪假嗎？" },

  { mt:"MT9", teil:"L3",
    a:"", w:"abgeben (einen Antrag)", p:"",
    en:"to submit / hand in (an application)", zh:"提交、遞交（申請）",
    k:"einen Antrag abgeben; Unterlagen abgeben",
    kz:"提交申請；遞交文件",
    ex:"Habt ihr euren Antrag auf Elternzeit vor oder nach der Geburt abgegeben?",
    ez:"你們的育嬰假申請是在孩子出生前還是出生後提交的？" },

  { mt:"MT9", teil:"L3",
    a:"", w:"einbinden", p:"",
    en:"to involve / include", zh:"納入、讓……參與",
    k:"den Betriebsrat in die Entscheidung einbinden; jemanden einbinden",
    kz:"讓工會參與決策；讓某人參與其中",
    ex:"Der Arbeitgeber muss den Betriebsrat in die Entscheidung einbinden.",
    ez:"雇主必須讓工會參與這項決策。" },

  { mt:"MT9", teil:"L3",
    a:"die", w:"Versetzung", p:"-en",
    en:"transfer / relocation (job)", zh:"職務調動、調職",
    k:"vor dieser Versetzung; eine Versetzung beantragen",
    kz:"在這次調職之前；申請調職",
    ex:"Versetzung bedeutet z. B., dass sich der Arbeitsort wesentlich ändert.",
    ez:"調職指的是工作地點發生重大改變等情況。" },

  { mt:"MT9", teil:"L3",
    a:"", w:"wesentlich", p:"",
    en:"significantly / substantially", zh:"重大地、實質上地",
    k:"sich wesentlich ändern; ein wesentlicher Unterschied",
    kz:"發生重大改變；實質上的差異",
    ex:"Dass sich der Arbeitsort wesentlich ändert.",
    ez:"工作地點發生了重大改變。" },

  { mt:"MT9", teil:"L3",
    a:"der/die", w:"Angehörige", p:"-n",
    en:"family member / relative", zh:"親屬、家屬",
    k:"die Pflege von Angehörigen; pflegende Angehörige",
    kz:"照護親屬；照顧家屬的人",
    ex:"Obwohl die Pflege von Angehörigen bekanntlich eine enorme Leistung ist.",
    ez:"雖然眾所周知，照護親屬是一項極為辛苦的付出。" },

  { mt:"MT9", teil:"L3",
    a:"", w:"enorm", p:"",
    en:"enormous / huge", zh:"極大的、巨大的",
    k:"eine enorme Leistung; enorme Kosten",
    kz:"極大的付出；極高的成本",
    ex:"Die Pflege von Angehörigen ist eine enorme Leistung.",
    ez:"照護親屬是一項極大的付出。" },

  { mt:"MT9", teil:"L3",
    a:"die", w:"Freistellung", p:"-en",
    en:"leave of absence / release from work duty", zh:"留職停薪、暫時免除工作義務",
    k:"eine Freistellung beantragen; Freistellung für bis zu sechs Monate",
    kz:"申請留職停薪；最長六個月的留職停薪",
    ex:"Du kannst von deinem Arbeitgeber eine Freistellung für bis zu sechs Monate beantragen.",
    ez:"你可以向雇主申請最長六個月的留職停薪。" },

  // ── LESEN TEIL 4 — Protokoll Gallauf-Logistik (S.136-137) ───────
  { mt:"MT9", teil:"L4",
    a:"", w:"verlesen", p:"",
    en:"to read out (aloud)", zh:"朗讀、宣讀",
    k:"das Protokoll verlesen; einen Text verlesen",
    kz:"宣讀會議紀錄；朗讀文章",
    ex:"Sie verliest das Protokoll der letzten Besprechung.",
    ez:"她宣讀了上次會議的紀錄。" },

  { mt:"MT9", teil:"L4",
    a:"die", w:"Wortmeldung", p:"-en",
    en:"request to speak / comment", zh:"發言請求、提出意見",
    k:"nach Wortmeldungen fragen; es gibt keine Wortmeldung",
    kz:"詢問是否有人要發言；沒有人提出意見",
    ex:"Sie fragt nach Wortmeldungen dazu.",
    ez:"她詢問是否有人對此有意見。" },

  { mt:"MT9", teil:"L4",
    a:"die", w:"Genehmigung", p:"-en",
    en:"approval", zh:"核准、批准",
    k:"um Genehmigung bitten; eine Genehmigung erteilen",
    kz:"請求核准；給予核准",
    ex:"Sie bittet um Genehmigung. Das Protokoll wird einstimmig angenommen.",
    ez:"她請求核准，會議紀錄獲得一致通過。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"auftreten (Probleme)", p:"",
    en:"to occur / arise (problems)", zh:"出現、發生（問題）",
    k:"Probleme treten auf; immer häufiger auftreten",
    kz:"出現問題；越來越頻繁地發生",
    ex:"MB berichtet von den Problemen, die immer häufiger aufgetreten sind.",
    ez:"MB 報告了越來越頻繁發生的問題。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"verbunden (damit verbunden)", p:"",
    en:"associated with / accompanying", zh:"伴隨而來的、與此相關的",
    k:"damit verbundene Probleme; mit etwas verbunden sein",
    kz:"與此相關的問題；與某事相關聯",
    ex:"Es ist zu Stromausfällen und damit verbundenen Temperaturschwankungen gekommen.",
    ez:"出現了停電以及伴隨而來的溫度波動問題。" },

  { mt:"MT9", teil:"L4",
    a:"die", w:"Absprache", p:"-n",
    en:"agreement / arrangement made beforehand", zh:"事先商議、約定",
    k:"nach Absprache mit der Geschäftsleitung; eine Absprache treffen",
    kz:"與管理層商議後；達成協議",
    ex:"Den er nach Absprache mit der Geschäftsleitung vor vier Wochen bestellt hat.",
    ez:"那是他四週前與管理層商議後訂購的（冰箱）。" },

  { mt:"MT9", teil:"L4",
    a:"der", w:"verbrauchsarme Kompressor", p:"",
    en:"low-consumption compressor", zh:"低耗能壓縮機",
    k:"ein verbrauchsarmer Kompressor; verbrauchsarm sein",
    kz:"低耗能壓縮機；耗能低",
    ex:"Einen verbrauchsarmen Kompressor sowie eine Türdichtung mit Hartschaum-Isolierung.",
    ez:"配備低耗能壓縮機以及硬泡棉隔熱的門封。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"zusätzlich", p:"",
    en:"additionally / in addition", zh:"額外地、附加地",
    k:"zusätzlich zu den täglich angebotenen Speisen; zusätzliche Kosten",
    kz:"在每日供應的菜色之外額外提供；額外費用",
    ex:"Sollen zusätzlich zu den täglich angebotenen Speisen auch vegane aufgenommen werden.",
    ez:"應在每日供應的菜色之外，額外加入素食選項。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"aufnehmen (ins Angebot)", p:"",
    en:"to add / include (into the offering)", zh:"納入、加入（供應項目）",
    k:"vegane Gerichte aufnehmen; etwas ins Programm aufnehmen",
    kz:"加入素食餐點；把某項目納入計畫",
    ex:"Sollen in das Angebot der Kantine auch vegane Gerichte aufgenommen werden.",
    ez:"員工餐廳的供應項目中也應該加入素食餐點。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"länger als gewohnt", p:"",
    en:"longer than usual", zh:"比平常更久",
    k:"länger als gewohnt warten; länger als gewohnt dauern",
    kz:"等得比平常更久；花的時間比平常更久",
    ex:"Sie haben in der vergangenen Woche viel länger als gewohnt an der Essensausgabe gewartet.",
    ez:"上週他們在取餐處等了比平常更久的時間。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"ausfallen (Personal)", p:"",
    en:"to be absent / unavailable (staff)", zh:"請假、缺勤（人員）",
    k:"zwei Mitarbeiter sind ausgefallen; krankheitsbedingt ausfallen",
    kz:"兩名員工請假缺勤；因病缺勤",
    ex:"Anfang der Woche sind zwei Mitarbeiter kurzfristig ausgefallen.",
    ez:"這週初有兩名員工臨時請假缺勤。" },

  { mt:"MT9", teil:"L4",
    a:"der", w:"Wiederholungsfall", p:"",
    en:"recurrence / repeat case", zh:"再次發生的情況",
    k:"im Wiederholungsfall; für den Wiederholungsfall vorsorgen",
    kz:"若再次發生的情況下；為再次發生的情況做準備",
    ex:"So können im Wiederholungsfall Aushilfskräfte umgehend angefordert werden.",
    ez:"這樣若再次發生同樣情況，就能立即請求支援人力。" },

  { mt:"MT9", teil:"L4",
    a:"der", w:"Arbeitskräftemangel", p:"",
    en:"labor shortage", zh:"人力短缺",
    k:"Arbeitskräftemangel bestehen; unter Arbeitskräftemangel leiden",
    kz:"存在人力短缺；遭受人力短缺之苦",
    ex:"In der gesamten Gastronomiebranche aktuell Arbeitskräftemangel besteht.",
    ez:"整個餐飲業目前都存在人力短缺的問題。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"äußerst", p:"",
    en:"extremely", zh:"極為、非常",
    k:"äußerst zufrieden sein; äußerst wichtig",
    kz:"極為滿意；極為重要",
    ex:"Frau Berndt war äußerst zufrieden mit der Bewirtung.",
    ez:"Berndt 女士對餐飲服務感到極為滿意。" },

  { mt:"MT9", teil:"L4",
    a:"die", w:"Bewirtung", p:"",
    en:"catering / hospitality service", zh:"餐飲服務、款待",
    k:"die Bewirtung der Feier; für die Bewirtung zuständig sein",
    kz:"慶祝活動的餐飲服務；負責餐飲招待",
    ex:"Zufrieden mit der Bewirtung der kleinen Feier.",
    ez:"對這場小型慶祝活動的餐飲服務感到滿意。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"anlässlich (+ Gen.)", p:"",
    en:"on the occasion of", zh:"藉……之際",
    k:"anlässlich des Dienstjubiläums; anlässlich eines Ereignisses",
    kz:"藉服務週年紀念之際；藉某事件之際",
    ex:"Anlässlich Frau Helmers dreißigjährigem Dienstjubiläum.",
    ez:"藉著 Helmer 女士三十週年服務紀念之際。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"lobend", p:"",
    en:"praising / commendatory", zh:"讚揚地、稱許地",
    k:"sich lobend äußern; lobende Worte",
    kz:"表達讚揚之意；讚許的話語",
    ex:"Sich sehr lobend über das Kantinenteam ausgesprochen hat.",
    ez:"對員工餐廳團隊表達了非常正面的讚揚。" },

  { mt:"MT9", teil:"L4",
    a:"der", w:"Personalbedarf", p:"",
    en:"staffing requirement / personnel needs", zh:"人力需求",
    k:"der Personalbedarf für die Bewirtungsaufträge; den Personalbedarf abstimmen",
    kz:"餐飲委託的人力需求；協調人力需求",
    ex:"Der Personalbedarf für die kommenden Bewirtungsaufträge soll abgestimmt werden.",
    ez:"接下來餐飲委託的人力需求應在下次會議協調確定。" },

  { mt:"MT9", teil:"L4",
    a:"der", w:"Bewirtungsauftrag", p:"-aufträge",
    en:"catering order / hospitality assignment", zh:"餐飲委託、款待任務",
    k:"kommende Bewirtungsaufträge; einen Bewirtungsauftrag übernehmen",
    kz:"未來的餐飲委託；承接餐飲委託",
    ex:"Der Personalbedarf für die kommenden Bewirtungsaufträge soll abgestimmt werden.",
    ez:"接下來餐飲委託的人力需求應協調確定。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"abstimmen", p:"",
    en:"to coordinate / agree on", zh:"協調、商定",
    k:"bei der Teamsitzung abgestimmt werden; etwas miteinander abstimmen",
    kz:"在團隊會議中協調確定；彼此商定某事",
    ex:"Soll bei der nächsten Teamsitzung abgestimmt werden.",
    ez:"應在下次團隊會議中協調確定。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"bewilligen", p:"",
    en:"to approve / grant (an application)", zh:"批准、核准（申請）",
    k:"Urlaub bewilligen; ein Antrag wird bewilligt",
    kz:"批准休假申請；申請獲得核准",
    ex:"Dass ihm bereits für Mai drei Wochen Urlaub bewilligt wurden.",
    ez:"提醒他五月已經有三週的假期獲得核准了。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"übernehmen (Schichten)", p:"",
    en:"to take over (shifts)", zh:"接手、承接（班次）",
    k:"die Schichten übernehmen; eine Aufgabe übernehmen",
    kz:"接手班次；承接任務",
    ex:"Um die Schichten von AT zu übernehmen.",
    ez:"以便接手 AT 的班次。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"vorlegen", p:"",
    en:"to submit / present (documents)", zh:"提交、呈交（文件）",
    k:"der Personalabteilung vorgelegt werden; einen Antrag vorlegen",
    kz:"提交給人事部門；呈交申請",
    ex:"Der Personalabteilung vorgelegt werden müssen.",
    ez:"必須提交給人事部門。" },

  { mt:"MT9", teil:"L4",
    a:"", w:"bestehen (Bedarf)", p:"",
    en:"to exist (a need/demand)", zh:"存在（需求）",
    k:"noch Bedarf bestehen; ein Problem besteht weiterhin",
    kz:"仍存在需求；問題仍然存在",
    ex:"Noch Bedarf an Aushilfskräften besteht.",
    ez:"仍然存在對臨時人力的需求。" },

  // ── LESEN UND SCHREIBEN — Floralu (S.138) ────────────────────────
  { mt:"MT9", teil:"L2",
    a:"", w:"rote und goldene (Töpfe)", p:"",
    en:"red and golden (pots)", zh:"紅色與金色的（花盆）",
    k:"rote und goldene Töpfe in den gleichen Größen",
    kz:"同樣尺寸的紅色與金色花盆",
    ex:"Könnten wir ihr als Ersatz rote und goldene Töpfe liefern.",
    ez:"我們可以提供紅色和金色的花盆作為替代品。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"großzügig", p:"",
    en:"generous", zh:"大方的、優惠的",
    k:"einen großzügigen Rabatt anbieten; großzügig sein",
    kz:"提供優惠折扣；大方的",
    ex:"Biete ihr auch einen großzügigen Rabatt auf diese Bestellung an.",
    ez:"也提供她這筆訂單一個優惠的折扣。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"versprechen", p:"",
    en:"to promise", zh:"承諾、保證",
    k:"die Lieferung versprechen; jemandem etwas versprechen",
    kz:"承諾交貨；向某人承諾某事",
    ex:"Versprich ihr die Lieferung Anfang nächster Woche.",
    ez:"向她承諾下週初會送達。" },

  { mt:"MT9", teil:"L2",
    a:"der", w:"Blumenübertopf", p:"-töpfe",
    en:"decorative flower pot (planter cover)", zh:"花盆套（裝飾用外盆）",
    k:"Blumenübertöpfe bestellen; regelmäßig Blumenübertöpfe kaufen",
    kz:"訂購裝飾花盆；定期購買花盆套",
    ex:"Bestelle ich seit Jahren regelmäßig Blumenübertöpfe und Dekoartikel.",
    ez:"我多年來定期訂購花盆套和裝飾品。" },

  { mt:"MT9", teil:"L2",
    a:"der", w:"Dekoartikel", p:"-",
    en:"decorative item", zh:"裝飾品",
    k:"Dekoartikel für das Weihnachtsgeschäft; Dekoartikel bestellen",
    kz:"聖誕節銷售用的裝飾品；訂購裝飾品",
    ex:"Blumenübertöpfe und Dekoartikel für das Weihnachtsgeschäft.",
    ez:"用於聖誕節銷售的花盆套和裝飾品。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"umfassen", p:"",
    en:"to comprise / include", zh:"包含、涵蓋",
    k:"die Bestellung umfasste 50 Töpfe; etwas umfassen",
    kz:"訂單包含50個花盆；涵蓋某事物",
    ex:"Die Bestellung umfasste 50 große und 60 kleine Töpfe.",
    ez:"這筆訂單包含50個大花盆和60個小花盆。" },

  { mt:"MT9", teil:"L2",
    a:"das", w:"Weihnachtsgeschäft", p:"",
    en:"Christmas (retail) season / Christmas sales", zh:"聖誕節銷售旺季",
    k:"das Weihnachtsgeschäft hat begonnen; vom Weihnachtsgeschäft profitieren",
    kz:"聖誕銷售旺季已經開始；從聖誕銷售旺季中獲益",
    ex:"Wie Ihnen bekannt ist, hat das Weihnachtsgeschäft begonnen.",
    ez:"如您所知，聖誕銷售旺季已經開始了。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"angewiesen sein (auf eine Lieferung)", p:"",
    en:"to be dependent on / urgently need", zh:"迫切需要、依賴",
    k:"dringend angewiesen sein; auf etwas angewiesen sein",
    kz:"迫切需要；依賴某事物",
    ex:"Bin ich auf eine schnelle Lieferung der restlichen Ware dringend angewiesen.",
    ez:"我迫切需要儘快收到剩餘貨品的交付。" },

  { mt:"MT9", teil:"L2",
    a:"", w:"verlässlich", p:"",
    en:"reliable / dependable", zh:"可靠的",
    k:"ein verlässliches Lieferdatum; eine verlässliche Information",
    kz:"可靠的交貨日期；可靠的資訊",
    ex:"Bitte teilen Sie mir ein verlässliches Lieferdatum noch in dieser Woche mit.",
    ez:"請在本週內告知我一個可靠的交貨日期。" },

  // ── HÖREN TEIL 3 — Sicherheitsbeauftragte (S.141) ───────────────
  { mt:"MT9", teil:"H3",
    a:"", w:"verstellen", p:"",
    en:"to block / obstruct", zh:"擋住、阻塞",
    k:"Fluchtwege dürfen nicht verstellt sein; mit Gegenständen verstellen",
    kz:"逃生通道不得被擋住；用物品擋住",
    ex:"Die Fluchtwege dürfen nicht mit kleineren Gegenständen verstellt sein.",
    ez:"逃生通道不能被較小的物品擋住。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"eingezeichnet (sein)", p:"",
    en:"to be marked / drawn in (on a plan)", zh:"標示在（圖上）",
    k:"auf Plänen eingezeichnet sein; etwas einzeichnen",
    kz:"標示在平面圖上；把某物標示出來",
    ex:"Die Fluchtwege sind auf Plänen eingezeichnet.",
    ez:"逃生通道都標示在平面圖上。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"beinhalten", p:"",
    en:"to contain / include", zh:"包含、含有",
    k:"Adressen beinhalten; ein Erste-Hilfe-Kasten beinhaltet...",
    kz:"包含地址資訊；急救箱裡含有……",
    ex:"Ein Erste-Hilfe-Kasten beinhaltet Adressen von Ärztinnen und Ärzten.",
    ez:"急救箱裡含有醫師的聯絡地址資訊。" },

  // ── HÖREN TEIL 4 (S.142) ──────────────────────────────────────────
  { mt:"MT9", teil:"H4",
    a:"die", w:"Kupplung", p:"-en",
    en:"clutch (car part)", zh:"離合器（汽車零件）",
    k:"die Kupplung ist kaputt; die Kupplung wechseln",
    kz:"離合器壞了；更換離合器",
    ex:"Torsten Hellwig informiert einen Kunden, dass die Kupplung seines Autos kaputt ist.",
    ez:"Torsten Hellwig 通知客戶，他車子的離合器壞了。" },

  { mt:"MT9", teil:"H4",
    a:"die", w:"Mitfahrgelegenheit", p:"-en",
    en:"ride-share / lift", zh:"共乘機會、搭便車",
    k:"eine Mitfahrgelegenheit brauchen; eine Mitfahrgelegenheit anbieten",
    kz:"需要共乘機會；提供共乘機會",
    ex:"Vanessa braucht eine Mitfahrgelegenheit.",
    ez:"Vanessa 需要找人共乘。" },

  { mt:"MT9", teil:"H4",
    a:"der", w:"Abschied", p:"-e",
    en:"farewell / departure", zh:"告別、離職",
    k:"seinen Abschied feiern; Abschied nehmen",
    kz:"慶祝他的離職；道別",
    ex:"Stefan feiert in drei Tagen seinen Abschied.",
    ez:"Stefan 三天後要慶祝他的離職。" },

  { mt:"MT9", teil:"H4",
    a:"", w:"fertigstellen", p:"",
    en:"to finish / complete", zh:"完成、製作完畢",
    k:"die Torte fertigstellen; ein Projekt fertigstellen",
    kz:"把蛋糕做完；完成一項專案",
    ex:"Cornelias Kolleginnen sollen die Torte fertigstellen.",
    ez:"Cornelia 的同事們應該要把蛋糕做完。" },

  { mt:"MT9", teil:"H4",
    a:"der/die", w:"Auszubildende", p:"-n",
    en:"apprentice / trainee", zh:"學徒、實習生",
    k:"mit dem Auszubildenden umgehen; einen Auszubildenden betreuen",
    kz:"與學徒相處；指導實習生",
    ex:"Eugenia weiß nicht, wie sie mit dem Auszubildenden umgehen soll.",
    ez:"Eugenia 不知道該如何與這名學徒相處。" },

  // ── SPRACHBAUSTEINE TEIL 1 (S.144) ──────────────────────────────
  { mt:"MT9", teil:"SB1",
    a:"", w:"begleiten", p:"",
    en:"to accompany / assist alongside", zh:"陪同、隨同協助",
    k:"die IT-System-Elektroniker begleiten; jemanden begleiten",
    kz:"隨同IT系統技術員工作；陪同某人",
    ex:"Ich zwei Wochen lang die IT-System-Elektroniker des Unternehmens begleiten durfte.",
    ez:"我有兩週的時間可以隨同公司的IT系統技術員工作。" },

  { mt:"MT9", teil:"SB1",
    a:"", w:"entnehmen", p:"",
    en:"to gather / infer (from a document)", zh:"從（文件）中得知、看出",
    k:"dem Praktikumszeugnis entnehmen; einem Text etwas entnehmen",
    kz:"從實習證明中得知；從文章中得知某事",
    ex:"Das können Sie dem Praktikumszeugnis entnehmen.",
    ez:"這點您可以從我的實習證明中看出來。" },

  // ── SPRACHBAUSTEINE TEIL 2 (S.145) ──────────────────────────────
  { mt:"MT9", teil:"SB2",
    a:"", w:"verzeichnen", p:"",
    en:"to record / register (a trend)", zh:"記錄到、出現（某種趨勢）",
    k:"eine stark steigende Nachfrage verzeichnen; einen Anstieg verzeichnen",
    kz:"記錄到大幅增加的需求；出現上升趨勢",
    ex:"In diesem Segment verzeichnen wir derzeit eine stark steigende Nachfrage.",
    ez:"在這個領域，我們目前記錄到需求大幅上升的情況。" },

  // ── HÖREN TEIL 1 (S.17-18, 逐字稿PDF) ────────────────────────────
  { mt:"MT9", teil:"H1",
    a:"", w:"betreuen", p:"",
    en:"to supervise / look after", zh:"指導、照顧",
    k:"die Praktikanten betreuen; Kunden betreuen",
    kz:"指導實習生；照顧客戶",
    ex:"Ich bin die Personalchefin des Hotels und betreue die Praktikanten in unserem Haus.",
    ez:"我是飯店的人事主管，負責指導我們飯店的實習生。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"fünfwöchig", p:"",
    en:"five-week (lasting five weeks)", zh:"五週的",
    k:"den Ablauf Ihres fünfwöchigen Praktikums; ein fünfwöchiger Kurs",
    kz:"您五週實習的流程；五週的課程",
    ex:"Jetzt möchte ich Ihnen den Ablauf Ihres fünfwöchigen Praktikums erklären.",
    ez:"現在我想向您說明您五週實習的流程。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"das ist erst Ihre letzte Station", p:"",
    en:"that's only your last station/stop", zh:"那才是您最後的階段",
    k:"das erst Ihre letzte Station ist; eine Station durchlaufen",
    kz:"那才是您最後的階段；經歷一個階段",
    ex:"Allerdings müssen Sie sich noch etwas Geduld haben, weil das erst Ihre letzte Station ist.",
    ez:"不過您還需要再耐心一點，因為那才是您最後的階段。" },

  { mt:"MT9", teil:"H1",
    a:"der", w:"Einblick", p:"-e",
    en:"insight", zh:"了解、洞察",
    k:"Einblicke bekommen; einen Einblick in etwas gewinnen",
    kz:"獲得了解的機會；對某事獲得洞察",
    ex:"In unserer Verwaltung bekommen Sie Einblicke in das Lagerwesen und die Buchhaltung.",
    ez:"在我們的行政部門，您將了解倉儲管理和會計工作。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"ausgerechnet", p:"",
    en:"of all things / precisely", zh:"偏偏、恰好",
    k:"ausgerechnet in der Woche; ausgerechnet jetzt",
    kz:"偏偏在這一週；偏偏在這個時候",
    ex:"Das ausgerechnet in der Woche, in der die Sonderaktion für die Markensportschuhe läuft.",
    ez:"偏偏就在名牌運動鞋促銷活動進行的那一週。" },

  { mt:"MT9", teil:"H1",
    a:"das", w:"Kundenaufkommen", p:"",
    en:"customer volume / footfall", zh:"客流量",
    k:"einen hohen Kundenaufkommen rechnen; das Kundenaufkommen steigt",
    kz:"預期高客流量；客流量上升",
    ex:"Wir rechnen mit einem hohen Kundenaufkommen hier in der Sportabteilung.",
    ez:"我們預期運動用品部門會有大量的客流量。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"laut Einsatzplan", p:"",
    en:"according to the duty roster", zh:"依照值班計畫",
    k:"laut Einsatzplan habe ich...; laut Plan",
    kz:"依照值班計畫我有……；依照計畫",
    ex:"Laut Einsatzplan habe ich nächste Woche Frühschicht und am Samstag frei.",
    ez:"依照值班計畫，我下週上早班，星期六休假。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"jemandem nichts ausmachen", p:"",
    en:"to not mind / not bother someone", zh:"對某人來說沒關係、不在乎",
    k:"das macht mir auch nichts aus; es macht nichts aus",
    kz:"這對我來說也沒關係；沒關係",
    ex:"Es macht mir auch nichts aus, wenn ich dann zwei Wochen hintereinander spät arbeite.",
    ez:"如果我連續兩週上晚班，我也不在乎。" },

  // ── HÖREN TEIL 1 — Klimaanlagen (S.18, 逐字稿PDF) ────────────────
  { mt:"MT9", teil:"H1",
    a:"", w:"aufstellen (Klimaanlagen)", p:"",
    en:"to install / set up (air conditioners)", zh:"安裝、架設（空調）",
    k:"Klimaanlagen aufstellen; ein Gerät aufstellen",
    kz:"安裝空調；架設設備",
    ex:"Sie haben uns letzte Woche die mobilen Klimaanlagen für unsere Büros geliefert und aufgestellt.",
    ez:"您上週為我們的辦公室提供並安裝了移動式空調。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"brummen", p:"",
    en:"to hum / drone (noise)", zh:"發出隆隆聲、嗡嗡聲",
    k:"die Geräte brummen; nach einer Stunde Laufzeit brummen",
    kz:"設備發出隆隆聲；運轉一小時後發出隆隆聲",
    ex:"Allerdings brummen die Geräte nach einer Stunde Laufzeit.",
    ez:"不過這些設備運轉一小時後就會發出隆隆聲。" },

  { mt:"MT9", teil:"H1",
    a:"", w:"geräuscharm", p:"",
    en:"low-noise / quiet", zh:"低噪音的",
    k:"geräuscharm sein; ein geräuscharmes Gerät",
    kz:"低噪音的；低噪音的設備",
    ex:"Sie hatten uns eigentlich zugesagt, dass Ihre Anlagen besonders geräuscharm sind.",
    ez:"您原本向我們保證這些設備特別安靜低噪音。" },

  { mt:"MT9", teil:"H1",
    a:"die", w:"Ablassöffnung", p:"-en",
    en:"drain opening / vent", zh:"排放孔、出風口",
    k:"die Ablassöffnungen frei sein; eine Öffnung verschließen",
    kz:"排放孔是暢通的；封住一個開口",
    ex:"Wurde vielleicht die Position der Geräte verändert? Sind die Ablassöffnungen frei?",
    ez:"是否更動了設備的位置？排放孔是暢通的嗎？" },

  // ── HÖREN TEIL 2 (S.18-19, 逐字稿PDF) ────────────────────────────
  { mt:"MT9", teil:"H2",
    a:"", w:"weitgehend frei einteilen", p:"",
    en:"to organize largely freely", zh:"大致上自由安排",
    k:"seine Zeit weitgehend frei einteilen; weitgehend selbstständig sein",
    kz:"大致上自由安排自己的時間；大致上自主",
    ex:"Man kann sich seine Zeit weitgehend frei einteilen.",
    ez:"你可以大致上自由安排自己的時間。" },

  { mt:"MT9", teil:"H2",
    a:"der", w:"Biorhythmus", p:"-rhythmen",
    en:"biorhythm / body clock", zh:"生理節律",
    k:"zu meinem Biorhythmus passen; den Biorhythmus stören",
    kz:"符合我的生理節律；干擾生理節律",
    ex:"Das passt ganz gut zu meinem Biorhythmus.",
    ez:"這跟我的生理節律很合拍。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"auf Dauer", p:"",
    en:"in the long run", zh:"長久下來、長期而言",
    k:"auf Dauer gefallen würde; auf Dauer nicht möglich sein",
    kz:"長久下來會喜歡；長期而言不可行",
    ex:"Ich bin mir auch nicht sicher, ob es meiner Familie auf Dauer gefallen würde.",
    ez:"我也不確定我的家人長久下來會不會喜歡這樣。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"gelingen", p:"",
    en:"to succeed / manage to do", zh:"成功做到、辦得到",
    k:"mir gelingt es nicht; etwas gelingt jemandem",
    kz:"我辦不到；某事某人辦得到",
    ex:"Mir gelingt es einfach nicht, mich zu Hause gut zu strukturieren.",
    ez:"我就是沒辦法在家裡把時間安排好。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"chaotisch", p:"",
    en:"chaotic", zh:"混亂的",
    k:"den Ablauf chaotisch finden; chaotisch verlaufen",
    kz:"覺得流程混亂；混亂地進行",
    ex:"Ich fand den Ablauf wieder chaotisch.",
    ez:"我覺得這次的流程又很混亂。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"zeitweise", p:"",
    en:"at times / temporarily", zh:"有時、暫時地",
    k:"zeitweise offline sein; zeitweise auftreten",
    kz:"有時會斷線；有時會出現",
    ex:"Einige sind zeitweise offline.",
    ez:"有些人有時會斷線。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"nervig", p:"",
    en:"annoying", zh:"令人厭煩的",
    k:"ziemlich nervig sein; das ist nervig",
    kz:"相當令人厭煩；這很煩人",
    ex:"Das ist ziemlich nervig.",
    ez:"這真的相當煩人。" },

  { mt:"MT9", teil:"H2",
    a:"die", w:"Ausstattung", p:"",
    en:"equipment / setup", zh:"設備配置",
    k:"die perfekte Ausstattung haben; was Internet und Computer betrifft",
    kz:"擁有完美的設備配置；就網路和電腦方面而言",
    ex:"Nicht jeder hat zu Hause die perfekte Ausstattung, was Internet und Computer betrifft.",
    ez:"不是每個人家裡的網路和電腦設備都是完美的。" },

  { mt:"MT9", teil:"H2",
    a:"", w:"regelmäßig durchführen", p:"",
    en:"to conduct / carry out regularly", zh:"定期進行",
    k:"Videokonferenzen regelmäßig durchführen; etwas regelmäßig durchführen",
    kz:"定期進行視訊會議；定期進行某事",
    ex:"Wenn wir Videokonferenzen regelmäßig durchführen, dann werden sie irgendwann selbstverständlich sein.",
    ez:"如果我們定期進行視訊會議，它們終將變得理所當然。" },

  // ── HÖREN TEIL 3 (S.19-20, 逐字稿PDF) ─────────────────────────────
  { mt:"MT9", teil:"H3",
    a:"die", w:"rechtliche Grundlage", p:"-n",
    en:"legal basis", zh:"法律依據",
    k:"die rechtlichen Grundlagen erklären; eine rechtliche Grundlage haben",
    kz:"說明法律依據；有法律依據",
    ex:"Erklärt Ihnen die rechtlichen Grundlagen für Arbeitsschutz.",
    ez:"向您說明職業安全保護的法律依據。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"brennen (es brennt)", p:"",
    en:"to be on fire", zh:"著火、起火",
    k:"wenn es brennt; ein Feuer brennt",
    kz:"當失火時；火在燃燒",
    ex:"Im Notfall sehr wichtig, zum Beispiel, wenn es brennt.",
    ez:"在緊急情況下非常重要，例如失火的時候。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"gut sichtbar", p:"",
    en:"clearly visible", zh:"清楚可見地",
    k:"gut sichtbar in den Fluren; gut sichtbar anbringen",
    kz:"在走道上清楚可見；清楚可見地裝設",
    ex:"In Ihren Firmen müssen gut sichtbar in den Fluren und den Aufenthaltsräumen Pläne der Fluchtwege aushängen.",
    ez:"貴公司的走道和休息室必須清楚可見地張貼逃生路線圖。" },

  { mt:"MT9", teil:"H3",
    a:"der", w:"Aufenthaltsraum", p:"-räume",
    en:"break room / common room", zh:"休息室",
    k:"in den Aufenthaltsräumen aushängen; sich im Aufenthaltsraum befinden",
    kz:"張貼在休息室；位於休息室",
    ex:"In den Fluren und den Aufenthaltsräumen Pläne der Fluchtwege aushängen.",
    ez:"在走道和休息室張貼逃生路線圖。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"aushängen (Pläne)", p:"",
    en:"to be posted / displayed (plans)", zh:"張貼、公佈（圖表）",
    k:"Pläne der Fluchtwege aushängen; etwas aushängen",
    kz:"張貼逃生路線圖；張貼某物",
    ex:"Müssen gut sichtbar Pläne der Fluchtwege aushängen.",
    ez:"必須清楚可見地張貼逃生路線圖。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"darüberstolpern", p:"",
    en:"to trip over it", zh:"被它絆倒",
    k:"darüberstolpern und sich verletzen; über etwas stolpern",
    kz:"被絆倒並受傷；被某物絆倒",
    ex:"Da man darüberstolpern und sich verletzen könnte.",
    ez:"因為可能會被絆倒而受傷。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"Kerzen anzünden", p:"",
    en:"to light candles", zh:"點蠟燭",
    k:"offenes Feuer machen oder Kerzen anzünden; eine Kerze anzünden",
    kz:"使用明火或點蠟燭；點一根蠟燭",
    ex:"Ist es in allen Gebäuden verboten, offenes Feuer zu machen, zum Beispiel Kerzen anzünden.",
    ez:"在所有建築物內都禁止使用明火，例如點蠟燭。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"ausgelöst (Alarm)", p:"",
    en:"triggered (alarm)", zh:"被觸發的（警報）",
    k:"wenn der Alarm ausgelöst wird; einen Alarm auslösen",
    kz:"當警報被觸發時；觸發警報",
    ex:"Das geschieht automatisch, wenn der Alarm ausgelöst wird.",
    ez:"當警報被觸發時，這會自動發生。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"decken (Material)", p:"",
    en:"to cover (a minimum of supplies)", zh:"涵蓋、滿足（物資需求）",
    k:"ein Minimum an Material decken; den Bedarf decken",
    kz:"滿足最低限度的物資需求；滿足需求",
    ex:"Sie müssen stets ein Minimum an Material decken.",
    ez:"您必須隨時確保有最低限度的物資。" },

  { mt:"MT9", teil:"H3",
    a:"das", w:"Verbandszeug", p:"",
    en:"bandage / dressing supplies", zh:"包紮用品",
    k:"Verbandszeug, Pflaster und Scheren; Verbandszeug nachfüllen",
    kz:"包紮用品、絆創貼和剪刀；補充包紮用品",
    ex:"Das sind Verbandszeug, Pflaster und Scheren.",
    ez:"那些是包紮用品、絆創貼和剪刀。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"entnehmen (Material)", p:"",
    en:"to take out / remove (supplies)", zh:"取用、拿取（物資）",
    k:"was entnommen wird; etwas einer Liste entnehmen",
    kz:"被取用了什麼；從清單中取用某物",
    ex:"Wenn Sie die Kästen kontrollieren, dann sehen Sie auf der Liste, was entnommen wurde.",
    ez:"當您檢查箱子時，可以從清單上看到取用了哪些東西。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"gegebenenfalls fehlen", p:"",
    en:"to be missing, if applicable", zh:"必要時可能缺少",
    k:"gegebenenfalls fehlen; gegebenenfalls Maßnahmen ergreifen",
    kz:"必要時可能缺少；必要時採取措施",
    ex:"Und können sie wieder gegebenenfalls fehlen.",
    ez:"它們也可能再次缺少（需要補充）。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"auffüllen", p:"",
    en:"to refill / restock", zh:"補充、填滿",
    k:"das sollten Sie etwa alle drei Monate tun; Material auffüllen",
    kz:"應該大約每三個月做一次；補充物資",
    ex:"Das sollten Sie etwa alle drei Monate tun.",
    ez:"這件事您應該大約每三個月做一次。" },

  { mt:"MT9", teil:"H3",
    a:"", w:"aushängen (Informationen)", p:"",
    en:"to be posted (information)", zh:"張貼（資訊）",
    k:"Informationen mit den wichtigsten Notfalladressen aushängen",
    kz:"張貼最重要的緊急聯絡資訊",
    ex:"Neben den Erste-Hilfe-Kästen hängen auch Informationen mit den wichtigsten Notfalladressen aus.",
    ez:"急救箱旁邊也張貼著最重要的緊急聯絡資訊。" },

  { mt:"MT9", teil:"H3",
    a:"die", w:"Anleitung", p:"-en",
    en:"instructions / guide", zh:"說明、指南",
    k:"eine Anleitung, wie man...; eine Anleitung befolgen",
    kz:"關於如何……的說明；遵循說明",
    ex:"Auf dem Informationsblatt finden Sie auch eine Anleitung, wie man Wiederbelebungsmaßnahmen durchführt.",
    ez:"資訊單上也有如何進行急救復甦措施的說明。" },

  // ── HÖREN TEIL 4 (S.20, 逐字稿PDF) ────────────────────────────────
  { mt:"MT9", teil:"H4",
    a:"die", w:"Kupplung", p:"-en",
    en:"clutch (car part)", zh:"離合器（汽車零件）",
    k:"die Kupplung ist defekt; die Kupplung wechseln",
    kz:"離合器壞了；更換離合器",
    ex:"Sie hatten uns Ihr Auto wegen der defekten Kupplung gebracht.",
    ez:"您因為離合器故障把車送來給我們了。" },

  { mt:"MT9", teil:"H4",
    a:"der", w:"Bremsbelag", p:"-beläge",
    en:"brake pad", zh:"煞車片",
    k:"die Bremsbeläge sind abgenutzt; die Bremsbeläge erneuern",
    kz:"煞車片已經磨損；更換煞車片",
    ex:"Wir haben festgestellt, dass Ihre Bremsbeläge abgenutzt sind und erneuert werden müssen.",
    ez:"我們發現您的煞車片已經磨損，需要更換。" },

  { mt:"MT9", teil:"H4",
    a:"", w:"springen (Wagen springt nicht an)", p:"",
    en:"to start (a car, won't start)", zh:"發動（車子發不動）",
    k:"mein Wagen springt nicht mehr an; der Motor springt an",
    kz:"我的車發不動了；引擎啟動",
    ex:"Seit gestern springt mein Wagen nicht mehr an.",
    ez:"從昨天起我的車就發不動了。" },

  { mt:"MT9", teil:"H4",
    a:"", w:"zugesagt", p:"",
    en:"promised / agreed", zh:"已答應的、已承諾的",
    k:"ich hatte ja zugesagt; etwas zusagen",
    kz:"我已經答應了；答應某事",
    ex:"Ich hatte ja zugesagt, einen Gutschein von der Parfümerie zu besorgen.",
    ez:"我已經答應要去買香水店的禮券。" },

  { mt:"MT9", teil:"H4",
    a:"die", w:"Konditorei", p:"-en",
    en:"pastry shop / confectionery", zh:"糕餅店",
    k:"in die Konditorei kommen; eine Konditorei besuchen",
    kz:"來到糕餅店；造訪糕餅店",
    ex:"Ich muss mich um sie kümmern und kann nicht in die Konditorei kommen.",
    ez:"我必須照顧她，沒辦法去糕餅店。" },

  { mt:"MT9", teil:"H4",
    a:"", w:"schwerfallen (es fällt mir nicht leicht)", p:"",
    en:"to be difficult for someone", zh:"對某人來說很困難",
    k:"das fällt mir nicht leicht; etwas fällt schwer",
    kz:"這對我來說不容易；某事很困難",
    ex:"Ich habe schon versucht, mit ihm darüber zu reden, aber das fällt mir nicht leicht.",
    ez:"我已經試著跟他談這件事，但這對我來說不容易。" },

  { mt:"MT9", teil:"H4",
    a:"die", w:"Backstube", p:"-n",
    en:"bakery kitchen / baking room", zh:"烘焙工作間",
    k:"alles steht bereit in der Backstube; in der Backstube arbeiten",
    kz:"一切都已準備好放在烘焙工作間裡；在烘焙工作間工作",
    ex:"Alles steht bereit in der Backstube.",
    ez:"一切都已經準備好放在烘焙工作間裡了。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST9_DATA);
}
