// data_ModellTest7.js
// MT7 = Klett "Mit Erfolg zum DTB B2" — Modelltest 3, Hörtexte (書本頁碼 117-120)
// 來源: 手機照片轉PNG, 紅色底線標記
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST7_DATA = [

  // ── HÖREN TEIL 1 (S.117) ──────────────────────────────────────
  { mt:"MT7", teil:"H1",
    a:"", w:"bisherig", p:"",
    en:"previous / hitherto", zh:"先前的、目前為止的",
    k:"die bisherige Werkstatt; der bisherige Stand",
    kz:"先前的工廠；目前為止的狀況",
    ex:"Unsere bisherige Werkstatt wird langsam zu klein.",
    ez:"我們目前的工廠漸漸變得太小了。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"eher selten", p:"",
    en:"rather rarely", zh:"算是很少",
    k:"Publikumsverkehr eher selten haben; eher selten vorkommen",
    kz:"很少有客戶往來；很少發生",
    ex:"Publikumsverkehr haben wir auch eher selten.",
    ez:"我們也很少有客戶上門。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"nicht erforderlich sein", p:"",
    en:"to not be necessary", zh:"不是必要的",
    k:"das wird für uns eher nicht erforderlich sein; etwas ist erforderlich",
    kz:"這對我們來說不算必要；某事是必要的",
    ex:"Das wird für uns eher nicht erforderlich sein.",
    ez:"這對我們來說應該不是必要的。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"einen Termin abstimmen", p:"",
    en:"to coordinate / agree on an appointment", zh:"商議約定一個時間",
    k:"einen Termin mit jemandem abstimmen; sich abstimmen",
    kz:"與某人商議時間；互相協調",
    ex:"Ich stimme mit meinem Chef einen Termin für die Besichtigung ab.",
    ez:"我會跟我的老闆商議參觀的時間。" },

  { mt:"MT7", teil:"H1",
    a:"die", w:"Lizenz", p:"-en",
    en:"license", zh:"授權、許可證",
    k:"etwas mit der Lizenz ist schiefgelaufen; eine Lizenz erwerben",
    kz:"授權方面出了問題；取得授權",
    ex:"Da ist etwas mit der Lizenz schiefgelaufen, deshalb haben wir noch keinen Zugriff auf die Programme.",
    ez:"授權方面出了點問題，所以我們還無法使用這些程式。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"anstehen", p:"",
    en:"to be on the agenda / be due", zh:"待辦、即將進行",
    k:"was in deiner Abteilung ansteht; eine Aufgabe steht an",
    kz:"你部門接下來要做的事；一項任務待辦",
    ex:"Ich möchte mit dir besprechen, was in den nächsten Tagen in deiner Abteilung ansteht.",
    ez:"我想跟你討論接下來幾天你部門有什麼待辦事項。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"nacheinander", p:"",
    en:"one after another", zh:"依序、一個接一個",
    k:"nacheinander wäre möglich; etwas nacheinander erledigen",
    kz:"依序進行是可行的；依序完成某事",
    ex:"Nacheinander wäre möglich, sodass nicht alle Rechner gleichzeitig ausfallen.",
    ez:"依序進行是可行的，這樣電腦不會同時全部當機。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"ausfallen (Rechner)", p:"",
    en:"to go down / fail (computer)", zh:"當機、故障",
    k:"alle Rechner ausfallen; ein Gerät fällt aus",
    kz:"所有電腦同時當機；設備故障",
    ex:"Sodass nicht alle Rechner gleichzeitig ausfallen.",
    ez:"這樣電腦就不會同時全部當機。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"wenig Betrieb", p:"",
    en:"little activity / low traffic", zh:"業務量少、人少的時候",
    k:"einen Tag mit relativ wenig Betrieb; viel Betrieb haben",
    kz:"業務量相對少的一天；業務量很多",
    ex:"Es wäre gut, das an einem Tag mit relativ wenig Betrieb zu machen.",
    ez:"最好選在業務量相對少的一天進行這件事。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"ausnahmsweise", p:"",
    en:"as an exception", zh:"破例地、例外地",
    k:"ausnahmsweise schon am Mittwoch; etwas ausnahmsweise tun",
    kz:"例外地已經在星期三；破例做某事",
    ex:"Wir haben ausnahmsweise schon am Mittwoch unsere Abteilungsbesprechung.",
    ez:"我們這次破例已經在星期三開部門會議。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"virtuell", p:"",
    en:"virtual", zh:"虛擬的、線上的",
    k:"virtuell stattfinden; ein virtuelles Meeting",
    kz:"以線上方式進行；虛擬會議",
    ex:"Die sollte ja erst virtuell stattfinden, aber nun komme ich doch direkt zu euch.",
    ez:"原本應該以線上方式進行，但現在我還是直接到你們那裡。" },

  { mt:"MT7", teil:"H1",
    a:"das", w:"Schließfach", p:"-fächer",
    en:"locker", zh:"置物櫃",
    k:"kleine Schließfächer; ein Schließfach benutzen",
    kz:"小型置物櫃；使用置物櫃",
    ex:"Daneben, wie du siehst, kleine Schließfächer.",
    ez:"旁邊，如你所見，有些小置物櫃。" },

  { mt:"MT7", teil:"H1",
    a:"die", w:"Wertsache", p:"-n",
    en:"valuables", zh:"貴重物品",
    k:"ihre Wertsachen einschließen; auf Wertsachen aufpassen",
    kz:"把貴重物品鎖起來；留意貴重物品",
    ex:"Achte unbedingt darauf, dass die Kinder morgens ihre Wertsachen einschließen.",
    ez:"一定要注意讓孩子們早上把貴重物品鎖起來。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"einschließen", p:"",
    en:"to lock up", zh:"鎖起來、上鎖收藏",
    k:"Wertsachen einschließen; sich selbst einschließen",
    kz:"把貴重物品鎖起來；把自己關起來",
    ex:"Die Kinder morgens ihre Wertsachen und auch Handys da einschließen.",
    ez:"孩子們早上要把貴重物品和手機鎖在那裡。" },

  { mt:"MT7", teil:"H1",
    a:"die", w:"Ausnahme und nicht die Regel", p:"",
    en:"the exception and not the rule", zh:"是例外而非常態",
    k:"die Ausnahme und nicht die Regel sein; eine Ausnahme machen",
    kz:"是例外而非常態；破例",
    ex:"Zum Glück ist es die Ausnahme und nicht die Regel.",
    ez:"幸好這是例外情況，不是常態。" },

  // ── HÖREN TEIL 2 (S.118) ──────────────────────────────────────
  { mt:"MT7", teil:"H2",
    a:"", w:"nachvollziehen", p:"",
    en:"to understand / relate to", zh:"理解、體會",
    k:"das kann ich absolut nachvollziehen; etwas nachvollziehen können",
    kz:"我完全能理解這點；能夠理解某事",
    ex:"Sonst kann ich das absolut nachvollziehen.",
    ez:"否則我完全能理解這一點。" },

  { mt:"MT7", teil:"H2",
    a:"", w:"jemandem auf der Nase herumtanzen", p:"",
    en:"to walk all over someone / take advantage of someone", zh:"在某人頭上撒野、不把某人當回事",
    k:"die einem ja später auf der Nase herumtanzen; auf der Nase herumtanzen",
    kz:"之後在你頭上撒野；不把你當回事",
    ex:"Sonst tanzen die einem ja später auf der Nase herum und wollen immer bedient werden.",
    ez:"否則他們之後就會不把你當回事，老是要人服侍。" },

  { mt:"MT7", teil:"H2",
    a:"", w:"sich (freiwillig) eintragen", p:"",
    en:"to sign up (voluntarily)", zh:"（自願）登記、報名參加",
    k:"sich freiwillig für Verkaufsschichten eintragen; sich für etwas eintragen",
    kz:"自願報名銷售班次；報名參加某事",
    ex:"Das wird nicht klappen, wenn du dich immer freiwillig für diese Verkaufsschichten einträgst.",
    ez:"如果你總是自願報名這些銷售班次，那就行不通了。" },

  { mt:"MT7", teil:"H2",
    a:"", w:"auf der Strecke bleiben", p:"",
    en:"to fall by the wayside / be neglected", zh:"被忽略、被犧牲",
    k:"meine Tochter bleibt auf der Strecke; etwas bleibt auf der Strecke",
    kz:"我的女兒被忽略了；某事被犧牲掉了",
    ex:"Aber meine Tochter bleibt schon etwas auf der Strecke.",
    ez:"但我的女兒確實多少被我忽略了。" },

  { mt:"MT7", teil:"H2",
    a:"", w:"demnächst", p:"",
    en:"soon / shortly", zh:"即將、近期內",
    k:"demnächst Gleitzeit eingeführt werden; demnächst stattfinden",
    kz:"即將實施彈性工時；近期內舉行",
    ex:"Hast du schon gehört, dass bei uns demnächst Gleitzeit eingeführt werden soll?",
    ez:"你聽說我們公司近期內要實施彈性工時了嗎？" },

  { mt:"MT7", teil:"H2",
    a:"der", w:"Apparat (am Apparat)", p:"-e",
    en:"on the phone", zh:"在電話中",
    k:"Kunden am Apparat haben; am Apparat sein",
    kz:"電話中接到客戶；在電話線上",
    ex:"Ich hatte schon ein paarmal Kunden am Apparat, die sich aufgeregt haben.",
    ez:"我已經接過好幾次客戶來電抱怨。" },

  { mt:"MT7", teil:"H2",
    a:"", w:"sich aufregen", p:"",
    en:"to get upset / worked up", zh:"激動、生氣",
    k:"sich aufgeregt haben; sich über etwas aufregen",
    kz:"曾經激動生氣過；對某事感到生氣",
    ex:"Kunden am Apparat, die sich aufgeregt haben, weil sie ihren Ansprechpartner nicht erreichen konnten.",
    ez:"客戶在電話中感到生氣，因為聯絡不到他們的對口人員。" },

  // ── HÖREN TEIL 3 (S.118) ───────────────────────────────────────
  { mt:"MT7", teil:"H3",
    a:"", w:"untergebracht (sein)", p:"",
    en:"to be accommodated / housed", zh:"被安置在",
    k:"im zweiten Stock untergebracht sein; jemanden unterbringen",
    kz:"被安置在二樓；安置某人",
    ex:"Das Team ist dann im zweiten Stock neben der Geschäftsführung untergebracht.",
    ez:"這個團隊將被安置在二樓，緊鄰管理層辦公室。" },

  { mt:"MT7", teil:"H3",
    a:"die", w:"Verteilung", p:"-en",
    en:"distribution / allocation", zh:"分配",
    k:"Fragen zur bisherigen Verteilung; eine Verteilung vornehmen",
    kz:"關於目前分配方式的問題；進行分配",
    ex:"Sind denn erst mal Fragen zur bisherigen Verteilung?",
    ez:"目前對於原本的（空間）分配方式有沒有問題？" },

  { mt:"MT7", teil:"H3",
    a:"", w:"entsorgen", p:"",
    en:"to dispose of", zh:"處理掉、丟棄",
    k:"verteilt oder entsorgt werden; etwas entsorgen",
    kz:"被分發或丟棄；丟棄某物",
    ex:"Was noch im Lager ist, wird verteilt oder entsorgt.",
    ez:"倉庫裡剩下的東西將被分發或丟棄。" },

  { mt:"MT7", teil:"H3",
    a:"die", w:"Hauptsache", p:"",
    en:"the main thing", zh:"最重要的是",
    k:"die Hauptsache ist, dass...; Hauptsache gesund",
    kz:"最重要的是……；只要健康就好",
    ex:"Die Hauptsache ist, dass die Lieferung vollständig war.",
    ez:"最重要的是這批貨送來是完整的。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"versprechen (halten, was sie versprechen)", p:"",
    en:"to live up to (what it promises)", zh:"做到、實現（承諾的效果）",
    k:"halten, was sie versprechen; etwas versprechen",
    kz:"做到所承諾的效果；承諾某事",
    ex:"Wenn die Geräte das halten, was sie versprechen, werden wir sicher noch mehr brauchen.",
    ez:"如果這些設備真能做到所承諾的效果，我們肯定還會再買更多。" },

  { mt:"MT7", teil:"H3",
    a:"der", w:"Feinkostladen", p:"-läden",
    en:"delicatessen / gourmet food shop", zh:"精緻食品店",
    k:"vor dem Feinkostladen stehen; einen Feinkostladen suchen",
    kz:"站在精緻食品店前；尋找精緻食品店",
    ex:"Ich stehe gerade vor dem Feinkostladen Nolte am Marktplatz.",
    ez:"我現在正站在市集廣場上的 Nolte 精緻食品店前。" },

  { mt:"MT7", teil:"H3",
    a:"der", w:"Präsentkorb", p:"-körbe",
    en:"gift basket / hamper", zh:"禮物籃",
    k:"den Präsentkorb bestellen; einen Präsentkorb zusammenstellen",
    kz:"訂購禮物籃；準備一個禮物籃",
    ex:"Um den Präsentkorb für unseren Chef zum Geburtstag zu bestellen.",
    ez:"為了訂購老闆生日用的禮物籃。" },

  { mt:"MT7", teil:"H3",
    a:"der", w:"Korb", p:"Körbe",
    en:"basket", zh:"籃子",
    k:"den Korb nicht bestellen können; einen Korb kaufen",
    kz:"無法訂購這個籃子；買一個籃子",
    ex:"Hier können wir den Korb nicht bestellen.",
    ez:"我們無法在這裡訂購這個籃子。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"einfallen (uns fällt nichts ein)", p:"",
    en:"to come to mind", zh:"想到、想出（點子）",
    k:"uns fällt nichts Besseres ein; jemandem fällt etwas ein",
    kz:"我們想不出更好的點子；某人想到了某事",
    ex:"Bevor wir lange über ein anderes Geschenk diskutieren und uns am Ende doch nichts Besseres einfällt.",
    ez:"在我們長時間討論其他禮物、最後卻想不出更好點子之前（先問問看）。" },

  // ── LESEN TEIL 1 (S.81) ──────────────────────────────────────
  { mt:"MT7", teil:"L1",
    a:"", w:"überfordert", p:"",
    en:"overwhelmed", zh:"負荷過重的、應付不來的",
    k:"damit überfordert sein; jemanden überfordern",
    kz:"對此感到應付不來；讓某人負荷過重",
    ex:"Nicht nur sind viele damit überfordert, sondern diese Arbeit hält einen auch davon ab.",
    ez:"許多人不僅應付不來，這項工作還會妨礙他們做更重要的事。" },

  { mt:"MT7", teil:"L1",
    a:"", w:"anhand", p:"",
    en:"on the basis of / using", zh:"依據、根據",
    k:"anhand von Beispielen; anhand der Daten",
    kz:"依據範例；根據數據",
    ex:"Wir zeigen Ihnen anhand von Beispielen, worauf Sie achten müssen.",
    ez:"我們透過範例向您展示需要注意的事項。" },

  { mt:"MT7", teil:"L1",
    a:"", w:"erfolgreich Marketing betreiben", p:"",
    en:"to conduct marketing successfully", zh:"成功經營行銷",
    k:"erfolgreich Marketing betreiben; ein Geschäft betreiben",
    kz:"成功經營行銷；經營一項業務",
    ex:"Große Firmen setzen nicht mehr nur auf das Internet, um erfolgreich Marketing zu betreiben.",
    ez:"大公司不再只靠網路來成功經營行銷。" },

  { mt:"MT7", teil:"L1",
    a:"", w:"gemeint sein", p:"",
    en:"to be meant (by something)", zh:"指的是、意指",
    k:"was genau damit gemeint ist; etwas ist so gemeint",
    kz:"那到底指的是什麼意思；某事是這個意思",
    ex:"In einem Interview berichtet er, was genau damit gemeint ist.",
    ez:"他在訪談中說明那到底指的是什麼意思。" },

  { mt:"MT7", teil:"L1",
    a:"", w:"bzw. (beziehungsweise)", p:"",
    en:"or rather / respectively", zh:"或者說、亦即",
    k:"der bzw. die Angestellte; A bzw. B",
    kz:"該員工（不分性別）；A或B",
    ex:"Wenn der bzw. die Angestellte möchte, muss der Arbeitgeber kürzere Arbeitszeiten ermöglichen.",
    ez:"只要員工提出要求，雇主就必須提供較短的工時。" },

  { mt:"MT7", teil:"L1",
    a:"", w:"in Kraft treten", p:"",
    en:"to come into effect", zh:"生效",
    k:"seit unserer letzten Ausgabe in Kraft getreten sind; ein Gesetz tritt in Kraft",
    kz:"自上一期以來已經生效的；法律生效",
    ex:"Wir fassen alle gesetzlichen Neuregelungen zusammen, die seit unserer letzten Ausgabe in Kraft getreten sind.",
    ez:"我們整理了自上一期以來所有已生效的法規新規定。" },

  // ── LESEN TEIL 2 (S.82-83) ────────────────────────────────────
  { mt:"MT7", teil:"L2",
    a:"", w:"aushängen (Pläne)", p:"",
    en:"to be posted (schedules)", zh:"張貼、公佈（值班表）",
    k:"auf Plänen ausgehängt werden; etwas aushängen",
    kz:"被張貼在表格上；張貼某物",
    ex:"Wer Küchendienst hat, wird auf Plänen in den Küchen ausgehängt.",
    ez:"廚房值班的人員會公告在廚房的值班表上。" },

  { mt:"MT7", teil:"L2",
    a:"die", w:"Einteilung", p:"-en",
    en:"allocation / scheduling", zh:"分配、排班",
    k:"die Einteilung erfolgt automatisch; eine Einteilung vornehmen",
    kz:"分配自動進行；進行分配",
    ex:"Die Einteilung erfolgt automatisch in alphabetischer Reihenfolge.",
    ez:"分配是依照字母順序自動進行的。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"eingereicht", p:"",
    en:"submitted", zh:"已提交的",
    k:"frühzeitig eingereicht werden; einen Antrag einreichen",
    kz:"提早提交；提交申請",
    ex:"Berücksichtigt Urlaubszeiten, soweit sie frühzeitig eingereicht wurden.",
    ez:"只要提早提交，就會考慮到休假時間。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"vorhanden", p:"",
    en:"available / present", zh:"存在的、具備的",
    k:"eine Kochmöglichkeit vorhanden; vorhanden sein",
    kz:"有烹飪設備可用；存在",
    ex:"In beiden Küchen ist eine Kochmöglichkeit vorhanden.",
    ez:"兩個廚房裡都有烹飪設備。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"ausgehändigt", p:"",
    en:"handed over / issued", zh:"已發給的、已交付的",
    k:"eine Karte wurde ausgehändigt; jemandem etwas aushändigen",
    kz:"一張卡片已被發給；把某物交給某人",
    ex:"Wurde Ihnen eine elektronische Karte ausgehändigt.",
    ez:"您已被發放一張電子卡片。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"betreten", p:"",
    en:"to enter", zh:"進入",
    k:"das Firmengebäude betreten; einen Raum betreten",
    kz:"進入公司大樓；進入一個房間",
    ex:"Beim Betreten und Verlassen des Firmengebäudes halten Sie Ihre Karte an das Lesegerät.",
    ez:"進出公司大樓時，請將您的卡片靠近讀卡機。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"verlassen", p:"",
    en:"to leave / exit", zh:"離開",
    k:"das Gebäude verlassen; einen Raum verlassen",
    kz:"離開大樓；離開房間",
    ex:"Beim Betreten und Verlassen des Firmengebäudes halten Sie Ihre Karte an das Lesegerät.",
    ez:"進出公司大樓時，請將您的卡片靠近讀卡機。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"einhalten (Pausenzeiten)", p:"",
    en:"to observe / adhere to (break times)", zh:"遵守、恪守（休息時間）",
    k:"Pausenzeiten sind einzuhalten; eine Regel einhalten",
    kz:"必須遵守休息時間；遵守規定",
    ex:"Die Pausenzeiten sind einzuhalten.",
    ez:"必須遵守休息時間規定。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"versäumen", p:"",
    en:"to miss / fail to do", zh:"錯過、未能做到",
    k:"es versäumen, sich abzumelden; eine Frist versäumen",
    kz:"未能進行登出；錯過期限",
    ex:"Wenn Sie es versäumen, sich zur Pause ab- und wieder anzumelden.",
    ez:"如果您沒有在休息時進行登出和重新登入。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"erforderlich (Anpassungen sind erforderlich)", p:"",
    en:"required / necessary", zh:"必要的、需要的",
    k:"Anpassungen sind erforderlich; etwas ist erforderlich",
    kz:"需要調整；某事是必要的",
    ex:"Sind Anpassungen der erfassten Zeit erforderlich, wenden Sie sich an Herrn Sangkam.",
    ez:"若需要調整記錄的時間，請聯繫 Sangkam 先生。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"nachträglich", p:"",
    en:"retroactively / afterward", zh:"事後地、追加地",
    k:"nachträglich ändern lassen; eine nachträgliche Korrektur",
    kz:"請人事後修改；事後的修正",
    ex:"Kann man die erfassten Zeiten nachträglich ändern lassen.",
    ez:"可以事後請人修改已記錄的時間。" },

  { mt:"MT7", teil:"L2",
    a:"das", w:"Ladegerät", p:"-e",
    en:"charging device", zh:"充電裝置",
    k:"am Ladegerät korrigiert werden; ein Ladegerät benutzen",
    kz:"在充電裝置上更正；使用充電裝置",
    ex:"Werden am Ladegerät korrigiert.",
    ez:"在充電裝置上進行更正。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"verlegen (in einen anderen Raum)", p:"",
    en:"to relocate / move (to another room)", zh:"轉移、改地點",
    k:"in einen anderen Raum verlegt werden; eine Fortbildung verlegen",
    kz:"被轉移到另一個房間；轉移進修課程地點",
    ex:"Eine Fortbildung wurde kurzfristig und ohne Rückfrage in einen anderen Raum verlegt.",
    ez:"一場進修課程被臨時且未經詢問就轉移到另一個房間。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"abgesprochen", p:"",
    en:"agreed / arranged", zh:"已約定的、已商議好的",
    k:"obwohl das so abgesprochen war; etwas absprechen",
    kz:"雖然原本已商議好；商議某事",
    ex:"Dort hatte die Trainerin dann keinen Beamer, obwohl das so abgesprochen war.",
    ez:"講師到了那裡卻沒有投影機，雖然原本是這樣約定好的。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"gebracht (werden)", p:"",
    en:"to be brought / delivered", zh:"被送來",
    k:"der Beamer musste erst gebracht werden; etwas bringen",
    kz:"投影機必須先被送來；帶來某物",
    ex:"Der Beamer musste erst gebracht und angeschlossen werden.",
    ez:"投影機必須先被送來並連接好。" },

  { mt:"MT7", teil:"L2",
    a:"", w:"angeschlossen", p:"",
    en:"connected", zh:"已連接的",
    k:"der Beamer musste angeschlossen werden; etwas anschließen",
    kz:"投影機必須被連接好；連接某物",
    ex:"Der Beamer musste erst gebracht und angeschlossen werden, sodass Zeit verlorenging.",
    ez:"投影機必須先被送來並連接好，因此浪費了時間。" },

  // ── LESEN TEIL 3 (S.84-85) ─────────────────────────────────────
  { mt:"MT7", teil:"L3",
    a:"die", w:"Einschränkung", p:"-en",
    en:"restriction / limitation", zh:"限制",
    k:"Angst vor finanziellen Einschränkungen; Einschränkungen hinnehmen",
    kz:"害怕財務上的限制；承受限制",
    ex:"Ich brauche aber mein volles Gehalt und habe Angst vor finanziellen Einschränkungen.",
    ez:"但我需要全額薪水，並擔心財務上會受到限制。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Erwerbsminderungsrente ins Spiel bringen", p:"",
    en:"to bring up disability pension as an option", zh:"提出失能退休金作為選項",
    k:"eine Erwerbsminderungsrente ins Spiel bringen; etwas ins Spiel bringen",
    kz:"提出失能退休金的選項；提出某項可能性",
    ex:"Mein Arzt brachte dann eine Erwerbsminderungsrente ins Spiel.",
    ez:"我的醫生後來提出了失能退休金這個選項。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"gestürzt (sein)", p:"",
    en:"to have fallen / crashed", zh:"摔倒了",
    k:"mit dem Fahrrad gestürzt; vom Fahrrad stürzen",
    kz:"騎自行車摔倒了；從自行車上摔下來",
    ex:"Ich bin vorhin auf dem Weg von der Arbeit nach Hause mit dem Fahrrad gestürzt.",
    ez:"我剛才下班回家路上騎自行車摔倒了。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Schramme", p:"-n",
    en:"scratch / scrape", zh:"擦傷",
    k:"ein paar Schrammen an den Händen; Schrammen davontragen",
    kz:"手上有些擦傷；留下擦傷",
    ex:"Zum Glück ist außer ein paar Schrammen an den Händen nichts passiert.",
    ez:"幸好除了手上有些擦傷，沒有發生其他事情。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Spätfolge", p:"-n",
    en:"long-term effect / late consequence", zh:"後遺症",
    k:"wegen möglicher Spätfolgen; Spätfolgen haben",
    kz:"因為可能有後遺症；留下後遺症",
    ex:"Auch wegen möglicher Spätfolgen.",
    ez:"也是因為可能有後遺症的關係。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"übertrieben", p:"",
    en:"exaggerated / overdone", zh:"誇張的",
    k:"ist das nicht übertrieben?; etwas übertreiben",
    kz:"這樣不會太誇張嗎？；誇大某事",
    ex:"Ist das nicht übertrieben?",
    ez:"這樣不會太誇張嗎？" },

  { mt:"MT7", teil:"L3",
    a:"", w:"anzünden (eine Zigarette)", p:"",
    en:"to light (a cigarette)", zh:"點（香菸）",
    k:"eine Zigarette anzünden; ein Feuer anzünden",
    kz:"點一根香菸；點火",
    ex:"Um eine Zigarette anzuzünden.",
    ez:"為了點一根香菸。" },

  { mt:"MT7", teil:"L3",
    a:"das", w:"Handgelenk brechen", p:"",
    en:"to break one's wrist", zh:"摔斷手腕",
    k:"sich das Handgelenk brechen; ein gebrochenes Handgelenk",
    kz:"摔斷自己的手腕；斷掉的手腕",
    ex:"Habe mir das Handgelenk gebrochen.",
    ez:"我把自己的手腕摔斷了。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"schockieren", p:"",
    en:"to shock", zh:"使震驚",
    k:"das würde mich echt schockieren; jemanden schockieren",
    kz:"這真的會讓我震驚；使某人震驚",
    ex:"Das würde mich echt schockieren.",
    ez:"這真的會讓我感到震驚。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Reha", p:"",
    en:"rehabilitation", zh:"復健",
    k:"eine Reha brauchen; eine Reha machen",
    kz:"需要復健；進行復健",
    ex:"Ich brauche irgendwann auch eine Reha, das kostet doch alles Geld!",
    ez:"我之後也需要復健，這些都要花錢的！" },

  { mt:"MT7", teil:"L3",
    a:"", w:"tatsächlich", p:"",
    en:"actually / really", zh:"確實、實際上",
    k:"das ist tatsächlich nicht einfach; tatsächlich passieren",
    kz:"這確實不容易；實際上發生",
    ex:"Das ist tatsächlich nicht einfach, denn auch im Büro hat man mal private Minuten.",
    ez:"這確實不容易，因為在辦公室裡也會有私人的片刻。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"erwähnen", p:"",
    en:"to mention", zh:"提及",
    k:"ein Urteil, das ich gerade erwähnt habe; etwas erwähnen",
    kz:"我剛剛提到的一個判決；提及某事",
    ex:"Da findest du ein Urteil zu dem Fall, den ich gerade erwähnt habe.",
    ez:"你可以找到我剛剛提到的那個案例的判決。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"ausgefallen (Person)", p:"",
    en:"to have been absent / out (a person)", zh:"請假、缺勤（人）",
    k:"eine Kollegin ist lange Zeit ausgefallen; ausfallen",
    kz:"一位同事長時間缺勤；缺勤",
    ex:"In meiner Firma ist eine Kollegin lange Zeit ausgefallen.",
    ez:"我公司裡有一位同事長時間缺勤。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"dachten (alle dachten)", p:"",
    en:"thought (everyone thought)", zh:"大家都以為",
    k:"alle dachten, sie hätte...; denken, dass",
    kz:"大家都以為她有……；以為……",
    ex:"Alle dachten, sie hätte Probleme mit der Lunge.",
    ez:"大家都以為她的肺有問題。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"gute Karten haben", p:"",
    en:"to have good cards / be in a strong position", zh:"佔優勢、有利",
    k:"dein Arbeitgeber hat gute Karten; gute Karten haben",
    kz:"你的雇主處於優勢；佔有利地位",
    ex:"Ich fürchte, dein Arbeitgeber hat gute Karten.",
    ez:"我擔心你的雇主在這件事上佔優勢。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Raucherpause", p:"-n",
    en:"smoking break", zh:"吸菸休息時間",
    k:"genauso wenig versichert wie deine Raucherpause; eine Raucherpause machen",
    kz:"跟你的吸菸休息時間一樣不受保障；休一段吸菸時間",
    ex:"Sind genauso wenig versichert wie deine Raucherpause.",
    ez:"和你的吸菸休息時間一樣不受保險保障。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"losfahren", p:"",
    en:"to set off / depart", zh:"出發",
    k:"von der Adresse losfahren; um acht Uhr losfahren",
    kz:"從某地址出發；八點出發",
    ex:"Du musst nicht von der Adresse losfahren, unter der du gemeldet bist.",
    ez:"你不必從登記的地址出發。" },

  { mt:"MT7", teil:"L3",
    a:"", w:"regelmäßig", p:"",
    en:"regularly", zh:"定期地",
    k:"regelmäßig Sport in der Firma; regelmäßig stattfinden",
    kz:"公司定期運動；定期舉行",
    ex:"Wenn zum Beispiel regelmäßig Sport in der Firma stattfindet, ist das versichert.",
    ez:"舉例來說，如果公司定期舉辦運動活動，那是受保險保障的。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Belegschaft", p:"",
    en:"workforce / staff", zh:"全體員工",
    k:"den Zusammenhalt der Belegschaft stärken; die gesamte Belegschaft",
    kz:"增強員工之間的凝聚力；全體員工",
    ex:"Um den Zusammenhalt der Belegschaft zu stärken.",
    ez:"為了增強員工之間的凝聚力。" },

  { mt:"MT7", teil:"L3",
    a:"die", w:"Leistung (Anspruch auf Leistungen)", p:"-en",
    en:"benefit / entitlement", zh:"福利、給付",
    k:"Anspruch auf Leistungen haben; Leistungen beziehen",
    kz:"享有福利給付的權利；領取給付",
    ex:"Dann hast du schon Anspruch auf Leistungen.",
    ez:"那麼你就有權利領取相關給付。" },

  // ── LESEN TEIL 4 (S.86-87) ─────────────────────────────────────
  { mt:"MT7", teil:"L4",
    a:"die", w:"Anmerkung", p:"-en",
    en:"remark / comment", zh:"意見、評論",
    k:"Fragen oder Anmerkungen; eine Anmerkung machen",
    kz:"問題或意見；提出意見",
    ex:"HW bittet um Fragen oder Anmerkungen.",
    ez:"HW 請大家提出問題或意見。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"aufgreifen (einen Bericht)", p:"",
    en:"to take up / address (a report)", zh:"提及、討論（報告）",
    k:"den Bericht aufgreifen; ein Thema aufgreifen",
    kz:"討論這份報告；提及一個話題",
    ex:"FT greift den Bericht der IT-Abteilung auf.",
    ez:"FT 提到了IT部門的報告。" },

  { mt:"MT7", teil:"L4",
    a:"die", w:"Erfassung", p:"",
    en:"recording / registration", zh:"記錄、登錄",
    k:"die Datenbank zur Erfassung der Lagerbestände; etwas erfassen",
    kz:"用於記錄庫存的資料庫；記錄某事",
    ex:"Die Datenbank zur Erfassung der Lagerbestände habe sich seit ihrer Einführung bewährt.",
    ez:"這個用於記錄庫存的資料庫自推出以來證明了其效用。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"bewährt (sich)", p:"",
    en:"proven / has proved itself", zh:"證實有效",
    k:"sich bewährt haben; ein bewährtes System",
    kz:"已證實有效；經過驗證的系統",
    ex:"Die Datenbank habe sich seit ihrer Einführung vor einem Jahr bewährt.",
    ez:"這個資料庫自一年前推出以來已經證明了它的效用。" },

  { mt:"MT7", teil:"L4",
    a:"die", w:"Baumaßnahme", p:"-n",
    en:"construction measure", zh:"施工措施",
    k:"die kurzfristig geplante Baumaßnahme; während der Baumaßnahmen",
    kz:"短期內計畫的施工措施；在施工期間",
    ex:"IK informiert über die kurzfristig geplante Fahrbahnerneuerung.",
    ez:"IK 報告了短期內計畫進行的路面更新工程。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"beschlossen", p:"",
    en:"decided / resolved", zh:"已決議的",
    k:"wie auf der letzten Sitzung beschlossen; etwas beschließen",
    kz:"如同上次會議所決議的；決議某事",
    ex:"Wie auf der letzten Sitzung beschlossen, hat AO Angebote eingeholt.",
    ez:"依照上次會議的決議，AO 已經取得了報價。" },

  { mt:"MT7", teil:"L4",
    a:"das", w:"Vorfeld (im Vorfeld)", p:"",
    en:"in advance", zh:"事前",
    k:"im Vorfeld dieser Sitzung; im Vorfeld vorbereiten",
    kz:"在這次會議之前；事前準備",
    ex:"Und im Vorfeld dieser Sitzung drei Angebote präsentiert.",
    ez:"並在這次會議之前提出了三份報價。" },

  { mt:"MT7", teil:"L4",
    a:"die", w:"Neuerung", p:"-en",
    en:"innovation / new feature", zh:"創新、新功能",
    k:"die zentrale Neuerung bei uns sein; eine Neuerung einführen",
    kz:"成為我們的核心創新項目；引進新功能",
    ex:"Was die zentrale Neuerung bei uns sein wird.",
    ez:"這將會是我們最核心的創新項目。" },

  { mt:"MT7", teil:"L4",
    a:"die", w:"Abwicklung", p:"",
    en:"execution / handling (of business)", zh:"執行、處理",
    k:"die zuverlässige Abwicklung der Arbeiten; eine Abwicklung sicherstellen",
    kz:"工作的可靠執行；確保執行流程",
    ex:"AO hält die zuverlässige Abwicklung der Arbeiten dabei für wichtiger, als nur auf die Kosten zu achten.",
    ez:"AO 認為可靠地執行工作比只看成本更重要。" },

  { mt:"MT7", teil:"L4",
    a:"der", w:"Zuschlag", p:"-schläge",
    en:"contract award / winning bid", zh:"得標",
    k:"den Zuschlag erteilen; den Zuschlag erhalten",
    kz:"給予得標；獲得得標",
    ex:"Wird einstimmig beschlossen, der Firma Sasuki Systems den Zuschlag zu erteilen.",
    ez:"一致決議將標案授予 Sasuki Systems 公司。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"genehmigt (werden)", p:"",
    en:"to be approved", zh:"被核准",
    k:"wird nach Änderung genehmigt; ein Protokoll genehmigen",
    kz:"經修改後被核准；核准會議紀錄",
    ex:"Das Protokoll wird nach Änderung genehmigt.",
    ez:"會議紀錄在修改後獲得核准。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"erweitert (werden)", p:"",
    en:"to be expanded / extended", zh:"被擴充",
    k:"wird um einen TOP erweitert; etwas erweitern",
    kz:"增加一個議程項目；擴充某事物",
    ex:"Wird um einen wichtigen Bereich erweitert.",
    ez:"將擴充一個重要的範圍。" },

  { mt:"MT7", teil:"L4",
    a:"", w:"verteilt (werden)", p:"",
    en:"to be distributed / circulated", zh:"被分發",
    k:"wird in der Sitzung verteilt; etwas verteilen",
    kz:"在會議中被分發；分發某物",
    ex:"Wird in der Sitzung verteilt.",
    ez:"在會議中被分發。" },

  // ── HÖREN TEIL 1 (S.90) ───────────────────────────────────────
  { mt:"MT7", teil:"H1",
    a:"der", w:"Makler", p:"-",
    en:"broker / agent", zh:"仲介",
    k:"über einen Makler verkaufen; einen Makler beauftragen",
    kz:"透過仲介出售；委託仲介",
    ex:"Die Firma Glasklar GmbH will ihre Räume über einen Makler verkaufen.",
    ez:"Glasklar公司想透過仲介出售他們的場地。" },

  { mt:"MT7", teil:"H1",
    a:"", w:"vergrößert (werden)", p:"",
    en:"to be enlarged", zh:"被擴大",
    k:"in Zukunft noch vergrößert werden; etwas vergrößern",
    kz:"未來還能被擴大；擴大某物",
    ex:"Die Räume im Gewerbepark Ost können in Zukunft noch vergrößert werden.",
    ez:"工業園區東區的場地未來還能再擴大。" },

  { mt:"MT7", teil:"H1",
    a:"die", w:"Umkleide", p:"-n",
    en:"changing room", zh:"更衣室",
    k:"eine separate Umkleide; in der Umkleide umziehen",
    kz:"獨立的更衣室；在更衣室換衣服",
    ex:"Die Räume verfügen über eine separate Umkleide.",
    ez:"這些場地有獨立的更衣室。" },

  { mt:"MT7", teil:"H1",
    a:"die", w:"Betreuung", p:"",
    en:"care / supervision", zh:"照護、托育",
    k:"in der Betreuung; die Betreuung der Kinder",
    kz:"在托育機構中；孩子的照護",
    ex:"In der Betreuung gibt es Aushänge mit den Speiseplänen.",
    ez:"在托育機構裡有張貼菜單的公告。" },

  { mt:"MT7", teil:"H1",
    a:"der", w:"Aushang", p:"-hänge",
    en:"notice / posted announcement", zh:"公告",
    k:"Aushänge mit den Speiseplänen; einen Aushang machen",
    kz:"張貼菜單的公告；張貼公告",
    ex:"Es gibt Aushänge mit den Speiseplänen.",
    ez:"有張貼菜單的公告。" },

  // ── HÖREN TEIL 2 (S.91) ───────────────────────────────────────
  { mt:"MT7", teil:"H2",
    a:"die", w:"Verlässlichkeit", p:"",
    en:"reliability", zh:"可靠性",
    k:"für Verlässlichkeit sorgen; Verlässlichkeit bei den Arbeitsabläufen",
    kz:"確保可靠性；工作流程上的可靠性",
    ex:"Feste Arbeitszeiten sorgen für Verlässlichkeit bei den Arbeitsabläufen.",
    ez:"固定的工作時間能確保工作流程的可靠性。" },

  // ── HÖREN TEIL 3 (S.92) ───────────────────────────────────────
  { mt:"MT7", teil:"H3",
    a:"die", w:"Aufteilung", p:"-en",
    en:"division / reorganization", zh:"分配、重新規劃",
    k:"eine neue Aufteilung in der Firma; die Aufteilung der Räume",
    kz:"公司內部的重新規劃；空間的分配",
    ex:"Eine neue Aufteilung in der Firma.",
    ez:"公司內部進行新的重新規劃。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"verkleinern (sich)", p:"",
    en:"to shrink / reduce in size", zh:"縮小、精簡",
    k:"sich verkleinern; ein Team verkleinern",
    kz:"自身縮小；精簡一個團隊",
    ex:"Das Team der Kundenberater wird sich verkleinern.",
    ez:"客戶顧問團隊將會縮編。" },

  { mt:"MT7", teil:"H3",
    a:"die", w:"Leitung (eine neue Leitung)", p:"-en",
    en:"management / leadership", zh:"主管、領導",
    k:"eine neue Leitung bekommen; die Leitung übernehmen",
    kz:"有了新的主管；接任主管職位",
    ex:"Die Mitarbeiter im Verkauf bekommen eine neue Leitung.",
    ez:"銷售部門的員工將有新的主管。" },

  { mt:"MT7", teil:"H3",
    a:"das", w:"Lager", p:"-",
    en:"warehouse / storage", zh:"倉庫",
    k:"das Lager kommt vorläufig in ein anderes Gebäude; ein Lager einrichten",
    kz:"倉庫暫時搬到另一棟建築；建立倉庫",
    ex:"Das Lager kommt vorläufig in ein anderes Gebäude.",
    ez:"倉庫暫時搬到另一棟建築裡。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"vorläufig", p:"",
    en:"temporarily / provisionally", zh:"暫時地",
    k:"vorläufig in ein anderes Gebäude; eine vorläufige Lösung",
    kz:"暫時搬到另一棟建築；暫時的解決方案",
    ex:"Das Lager kommt vorläufig in ein anderes Gebäude.",
    ez:"倉庫暫時搬到另一棟建築裡。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"eingerichtet (werden)", p:"",
    en:"to be set up / furnished", zh:"被設置、被佈置",
    k:"wird im ersten Stock eingerichtet; ein Büro einrichten",
    kz:"被設置在一樓；佈置一間辦公室",
    ex:"Das Lager wird im ersten Stock eingerichtet.",
    ez:"倉庫將被設置在一樓。" },

  { mt:"MT7", teil:"H3",
    a:"", w:"übernehmen (eine Abteilung)", p:"",
    en:"to take over (a department)", zh:"接管（一個部門）",
    k:"eine Abteilung übernehmen; eine Aufgabe übernehmen",
    kz:"接管一個部門；接下一項任務",
    ex:"In Zukunft übernimmt Frau Teslin eine Abteilung.",
    ez:"未來 Teslin 女士將接管一個部門。" },

  // ── HÖREN TEIL 4 (S.93) ───────────────────────────────────────
  { mt:"MT7", teil:"H4",
    a:"die", w:"Betriebsanleitung", p:"-en",
    en:"operating instructions / manual", zh:"操作說明書",
    k:"eine Betriebsanleitung benötigen; eine Betriebsanleitung lesen",
    kz:"需要操作說明書；閱讀操作說明書",
    ex:"Frau Hertel benötigt noch eine Betriebsanleitung.",
    ez:"Hertel 女士還需要一份操作說明書。" },

  { mt:"MT7", teil:"H4",
    a:"", w:"vertreten", p:"",
    en:"to represent / stand in for", zh:"代理、代表",
    k:"jemanden vertreten; schlägt vor, dass Susanne ihn vertritt",
    kz:"代理某人；建議讓 Susanne 代理他",
    ex:"Paul schlägt vor, dass Susanne ihn vertritt.",
    ez:"Paul 建議讓 Susanne 代理他。" },

  // ── SPRACHBAUSTEINE TEIL 1 (S.95) ─────────────────────────────
  { mt:"MT7", teil:"SB1",
    a:"", w:"ungekündigt", p:"",
    en:"not terminated / still current (employment)", zh:"尚未終止的（僱用關係）",
    k:"in einem ungekündigten Arbeitsverhältnis; ein Arbeitsverhältnis kündigen",
    kz:"目前仍在職（尚未被解僱）；終止僱用關係",
    ex:"Wie Sie wissen, bin ich derzeit noch in einem ungekündigten Arbeitsverhältnis.",
    ez:"如您所知，我目前仍在原職位上（尚未離職）。" },

  // ── SPRACHBAUSTEINE TEIL 2 (S.96) ─────────────────────────────
  { mt:"MT7", teil:"SB2",
    a:"", w:"erstellen", p:"",
    en:"to draw up / prepare", zh:"製作、擬定",
    k:"ein Angebot erstellen; ein Dokument erstellen",
    kz:"擬定一份報價；製作一份文件",
    ex:"Gerne erstellen wir ein Angebot für die Lieferung und den Einbau von 25 Fenstern.",
    ez:"我們很樂意為25個窗戶的供貨與安裝擬定一份報價。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST7_DATA);
}
