// data_ModellTest11.js
// Modelltest 11 — Hueber Prüfung Express Deutsch-Test für den Beruf B2, 2026-06-25
// 單字來源：考題 PDF（19 頁 PNG 逐頁判讀黃色螢光筆標記）
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST11_DATA = [

  // ── LESEN TEIL 2 — Text 1: Konfliktberatung (S.14) ──────────────
  { mt:"MT11", teil:"L2",
    a:"", w:"völlig", p:"",
    en:"completely / totally", zh:"完全地、徹底地",
    k:"völlig normal sein; völlig unlösbar; völlig klar",
    kz:"完全正常；完全無法解決；完全清楚",
    ex:"Konflikte am Arbeitsplatz sind völlig normal.",
    ez:"職場上的衝突是完全正常的。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"unlösbar (Konflikt scheint unlösbar)", p:"",
    en:"unsolvable / irresolvable", zh:"無法解決的（衝突似乎無法解決）",
    k:"ein Konflikt scheint unlösbar; ein unlösbares Problem",
    kz:"衝突似乎無法解決；無法解決的問題",
    ex:"Doch manchmal helfen auch Gespräche nicht. Der Konflikt scheint unlösbar.",
    ez:"但有時候談話也無濟於事，衝突似乎無法解決。" },

  { mt:"MT11", teil:"L2",
    a:"die", w:"Bewältigung", p:"",
    en:"coping with / managing", zh:"應對、克服、處理（困難或衝突）",
    k:"bei der Bewältigung unterstützen; die Bewältigung von Konflikten",
    kz:"在處理過程中提供支援；衝突的處理",
    ex:"Die Konfliktberatung soll die Mitarbeiter bei der Bewältigung konkreter Konflikte unterstützen.",
    ez:"衝突諮詢應在處理具體衝突時為員工提供支持。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"verhindern", p:"",
    en:"to prevent", zh:"阻止、防止",
    k:"verhindern, dass...; Schaden verhindern",
    kz:"防止……發生；防止損害",
    ex:"Die Konfliktberatung soll verhindern, dass die Mitarbeiter durch einen Konflikt Schaden nehmen.",
    ez:"衝突諮詢應防止員工因衝突而受到傷害。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Versand", p:"",
    en:"shipping department / dispatch", zh:"出貨部門、發送部",
    k:"aus dem Versand; im Versand arbeiten",
    kz:"來自出貨部門；在出貨部門工作",
    ex:"Als Konfliktberater haben sich Frau Korth aus dem Versand zur Verfügung gestellt.",
    ez:"出貨部門的 Korth 女士自願擔任衝突諮詢員。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"sich wenden (an + Akk.)", p:"",
    en:"to turn to (sb for help)", zh:"向（某人）求助、聯繫",
    k:"sich an jemanden wenden; auf Anfrage tätig werden, wenn sich jemand wendet",
    kz:"向某人求助；當有人求助時才介入處理",
    ex:"Die Konfliktberater werden auf Anfrage tätig, wenn sich jemand an sie wendet.",
    ez:"當有人向衝突諮詢員求助時，他們才會根據請求展開行動。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"eigenständig", p:"",
    en:"independently / on one's own initiative", zh:"自主地、獨立地（主動採取行動）",
    k:"eigenständig handeln; eigenständig Personen ansprechen",
    kz:"自主行動；主動找人談話",
    ex:"Sie können aber auch eigenständig Personen ansprechen, wenn sie glauben, dass eine Konfliktsituation besteht.",
    ez:"但若他們認為存在衝突情況，也可以主動找人談話。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"beraten (das Unternehmen berät Firmen)", p:"",
    en:"to advise / consult", zh:"提供諮詢、建議",
    k:"Firmen beraten; im Bereich Konfliktmanagement beraten",
    kz:"為公司提供諮詢；在衝突管理領域提供建議",
    ex:"Das Unternehmen berät Firmen im Bereich Konfliktmanagement.",
    ez:"該公司在衝突管理領域為其他企業提供諮詢。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Umgang (mit + Dat.)", p:"",
    en:"way of dealing with / handling", zh:"應對方式、處理方式",
    k:"einen Umgang mit Konflikten ermöglichen; der Umgang mit Kollegen",
    kz:"使應對衝突成為可能；與同事的相處方式",
    ex:"Die Firma möchte eine Unternehmenskultur, die einen Umgang mit Konflikten in der Firma ermöglicht.",
    ez:"公司希望建立一種能讓員工妥善應對衝突的企業文化。" },

  { mt:"MT11", teil:"L2",
    a:"die", w:"Verhinderung", p:"",
    en:"prevention", zh:"防止、預防",
    k:"zur Verhinderung von Konflikten beitragen",
    kz:"有助於防止衝突",
    ex:"...die zur Verhinderung von Konflikten in der Firma beiträgt.",
    ez:"……有助於防止公司內部發生衝突的（企業文化）。" },

  // ── LESEN TEIL 2 — Text 2: Arbeitsunfälle (S.15) ────────────────
  { mt:"MT11", teil:"L2",
    a:"", w:"sich ereignen", p:"",
    en:"to occur / happen", zh:"發生（事故、事件）",
    k:"ein Unfall ereignet sich; sich auf dem Weg ereignen",
    kz:"發生事故；在途中發生",
    ex:"Wegeunfälle sind Unfälle, die sich auf dem direkten Weg zur Arbeit ereignen.",
    ez:"通勤事故是指在直接往返工作的路上發生的事故。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"geschehen", p:"",
    en:"to happen / occur", zh:"發生",
    k:"Geschieht ein Arbeitsunfall, so...; etwas geschieht plötzlich",
    kz:"若發生工作事故……；事情突然發生",
    ex:"Geschieht ein Arbeitsunfall, so sind unverzüglich die direkten Vorgesetzten zu informieren.",
    ez:"若發生工作事故，必須立即通知直屬上司。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"erforderlich", p:"",
    en:"required / necessary", zh:"必要的、需要的",
    k:"falls erforderlich; ein Arztbesuch ist erforderlich",
    kz:"若有必要；需要看醫生",
    ex:"Falls erforderlich, kann die Unfallmeldung gleich zusammen mit der Anzeige der Arbeitsunfähigkeit geschehen.",
    ez:"若有必要，事故報告可以與工作能力喪失通知一起進行。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"erfolgen", p:"",
    en:"to take place / occur", zh:"進行、發生（較正式）",
    k:"keine Krankmeldung erfolgt; die Zahlung erfolgt rasch",
    kz:"沒有進行病假通報；付款迅速進行",
    ex:"Ein Arbeitsunfall ist auch dann zu melden, wenn keine Krankmeldung erfolgt.",
    ez:"即使沒有提交病假通報，工作事故仍須報告。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Durchgangsarzt", p:"-ärzte",
    en:"designated trauma physician (occupational accident insurance)", zh:"職災指定醫師（與職災保險簽約的醫師）",
    k:"der nächstgelegene Durchgangsarzt; einen Vertrag mit der Unfallversicherung haben",
    kz:"最近的職災指定醫師；與職災保險訂有合約",
    ex:"Für die erste Behandlung ist der nächstgelegene Durchgangsarzt zuständig.",
    ez:"最近的職災指定醫師負責首次治療。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Unfallchirurg", p:"-en",
    en:"trauma surgeon", zh:"外傷外科醫師",
    k:"ein Orthopäde oder Unfallchirurg sein",
    kz:"是骨科醫師或外傷外科醫師",
    ex:"Der Durchgangsarzt ist normalerweise ein Orthopäde oder Unfallchirurg.",
    ez:"職災指定醫師通常是骨科醫師或外傷外科醫師。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Rettungssanitäter", p:"-",
    en:"paramedic", zh:"救護人員",
    k:"Rettungssanitäter rufen; vom Rettungssanitäter versorgt werden",
    kz:"呼叫救護人員；由救護人員照護",
    ex:"Falls Rettungssanitäter oder ein Notarzt gerufen werden mussten, wenden Sie sich an den Empfang.",
    ez:"若需要呼叫救護人員或急救醫師，請聯繫櫃台。" },

  { mt:"MT11", teil:"L2",
    a:"das", w:"Eintreffen der Rettungskräfte", p:"",
    en:"arrival of the emergency services", zh:"救援人員的到達",
    k:"Maßnahmen für das Eintreffen treffen; die Rettungskräfte treffen ein",
    kz:"為救援人員的到達做好準備；救援人員抵達",
    ex:"Damit notwendige Maßnahmen für das Eintreffen der Rettungskräfte getroffen werden können.",
    ez:"以便能為救援人員的到來做好必要的準備。" },

  // ── LESEN TEIL 3 — Tipps für Angestellte (S.18-19) ──────────────
  { mt:"MT11", teil:"L3",
    a:"", w:"anschreien", p:"",
    en:"to shout at / yell at", zh:"對……大吼、咆哮",
    k:"jemanden anschreien; die Chefin hat mich angeschrien",
    kz:"對某人大吼；老闆對我大吼",
    ex:"Als ich wieder gesund war, hat mich meine Chefin angeschrien.",
    ez:"我康復後，老闆對我大吼。" },

  { mt:"MT11", teil:"L3",
    a:"", w:"verlangen", p:"",
    en:"to demand / require", zh:"要求",
    k:"verlangen, dass jemand arbeitet; etwas von jemandem verlangen",
    kz:"要求某人工作；向某人要求某事",
    ex:"Solange du krankgeschrieben bist, darf dein Arbeitgeber nicht verlangen, dass du arbeitest.",
    ez:"只要你還在病假期間，雇主不得要求你工作。" },

  { mt:"MT11", teil:"L3",
    a:"die", w:"Drohung", p:"-en",
    en:"threat", zh:"威脅",
    k:"leere Drohungen; eine Drohung aussprechen",
    kz:"空洞的威脅；發出威脅",
    ex:"Das sind leere Drohungen. Krankheit ist kein Grund für eine Kündigung.",
    ez:"那些只是空洞的威脅，生病不是解僱的理由。" },

  { mt:"MT11", teil:"L3",
    a:"", w:"ankündigen", p:"",
    en:"to announce in advance", zh:"事先宣布、預告",
    k:"die Krankheit vorher ankündigen; einen Termin ankündigen",
    kz:"事先宣布生病；預告一個時間",
    ex:"Du hast aber den Fehler gemacht, dass du deine Krankheit vorher angekündigt hast.",
    ez:"但你犯的錯是事先就宣布了自己會生病。" },

  { mt:"MT11", teil:"L3",
    a:"", w:"voraussichtlich", p:"",
    en:"expected / anticipated", zh:"預計的、預料中的",
    k:"die voraussichtliche Dauer; voraussichtlich fertig werden",
    kz:"預計的期間；預計完成",
    ex:"Darauf steht auch die voraussichtliche Dauer der Erkrankung.",
    ez:"上面也會註明預計的病程時間。" },

  // ── LESEN TEIL 4 — Protokoll (S.22-23) ──────────────────────────
  { mt:"MT11", teil:"L4",
    a:"", w:"ankündigen (eine Sitzung verlassen)", p:"",
    en:"to announce", zh:"宣布、預告",
    k:"ankündigen, dass...; eine Sitzung vorzeitig verlassen ankündigen",
    kz:"宣布……；宣布要提前離開會議",
    ex:"MA kündigt an, nach einer Stunde die Sitzung verlassen zu müssen.",
    ez:"MA 宣布一小時後必須提前離開會議。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"verhandeln", p:"",
    en:"to negotiate", zh:"談判、協商",
    k:"mit zwei Bäckereien verhandeln; über einen Vertrag verhandeln",
    kz:"與兩家麵包店協商；就合約進行談判",
    ex:"LB verhandelt gerade mit zwei weiteren Bäckereien.",
    ez:"LB 正在與另外兩家麵包店進行協商。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"anfertigen", p:"",
    en:"to manufacture / produce (custom-made)", zh:"製作、訂製",
    k:"speziell anfertigen; Teile anfertigen lassen",
    kz:"特別訂製；委託製作零件",
    ex:"Andere Teile mussten speziell für unser Unternehmen angefertigt werden.",
    ez:"其他零件必須特別為我們公司訂製。" },

  { mt:"MT11", teil:"L4",
    a:"die", w:"Produktpalette", p:"-n",
    en:"product range", zh:"產品系列",
    k:"die Produktpalette erweitern; eine breite Produktpalette",
    kz:"擴展產品系列；廣泛的產品系列",
    ex:"BL präsentiert Ideen zur Erweiterung der Produktpalette.",
    ez:"BL 提出了擴展產品系列的想法。" },

  { mt:"MT11", teil:"L4",
    a:"der", w:"Singlehaushalt", p:"-e",
    en:"single-person household", zh:"單人家庭、獨居戶",
    k:"Brote für Singlehaushalte; für Singlehaushalte geeignet",
    kz:"適合單人家庭的麵包；適合獨居者",
    ex:"Sie schlägt vor, das Angebot um Brote für Singlehaushalte zu erweitern.",
    ez:"她建議將產品擴展為適合單人家庭的麵包。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"wiegen", p:"",
    en:"to weigh", zh:"重量為、稱重",
    k:"350 g wiegen; das Brot wiegt wenig",
    kz:"重350克；麵包重量輕",
    ex:"Die Brote sollen 350 g wiegen und aus hochwertigen Zutaten bestehen.",
    ez:"麵包應重350克，並由優質原料製成。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"hochwertig", p:"",
    en:"high-quality / premium", zh:"高品質的、優質的",
    k:"hochwertige Zutaten; aus hochwertigem Material",
    kz:"優質原料；優質材料製成",
    ex:"Die Brote sollen aus hochwertigen, regionalen Zutaten bestehen.",
    ez:"麵包應由優質的當地原料製成。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"gedacht sein (an + Akk.)", p:"",
    en:"to be intended for / meant for", zh:"考慮、構想（針對某用途設計）",
    k:"gedacht ist an...; für jemanden gedacht sein",
    kz:"構想是針對……；為某人設計",
    ex:"Gedacht ist an Roggenmehl, Dinkelmehl, Rotkornweizen und Leinsamen.",
    ez:"構想是使用裸麥粉、斯佩爾特麵粉、紅粒小麥和亞麻籽。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"beauftragen", p:"",
    en:"to commission / instruct", zh:"委託、指派",
    k:"eine Agentur beauftragen; jemanden mit einer Aufgabe beauftragen",
    kz:"委託一家代理商；指派某人負責某項任務",
    ex:"Es wurde eine Marketingagentur beauftragt, die schon erste Ideen entwickelt hat.",
    ez:"已委託一家行銷代理商，該公司已提出初步想法。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"begreifen (als)", p:"",
    en:"to be understood / perceived as", zh:"被理解為、被視為",
    k:"als modernes Unternehmen begriffen werden",
    kz:"被視為一家現代化企業",
    ex:"Unser Betrieb soll als modernes Unternehmen begriffen werden, das die Umwelt schont.",
    ez:"我們公司應被視為一家重視環保的現代化企業。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"anlässlich (+ Genitiv)", p:"",
    en:"on the occasion of", zh:"藉……之際",
    k:"anlässlich des Firmenjubiläums; anlässlich eines Ereignisses",
    kz:"藉公司週年慶之際；藉某事件之際",
    ex:"Anlässlich des 50-jährigen Firmenjubiläums schlägt GS einen Tag der offenen Tür vor.",
    ez:"藉著公司五十週年慶之際，GS 提議舉辦開放日。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"anfallen", p:"",
    en:"to arise / accrue (e.g. extra work, costs)", zh:"產生、發生（額外的工作量或費用）",
    k:"Mehrstunden fallen an; Kosten fallen an",
    kz:"產生額外的工時；產生費用",
    ex:"In den Wochen vor dem Tag der offenen Tür werden sicherlich Mehrstunden anfallen.",
    ez:"在開放日前的幾週內，肯定會產生額外的工時。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"erforderlich (Zustimmung erforderlich)", p:"",
    en:"required / necessary", zh:"必要的、需要的",
    k:"die Zustimmung ist erforderlich; erforderlich sein für",
    kz:"需要同意；對……是必要的",
    ex:"Sollten diese Überstunden verpflichtend sein, ist die Zustimmung des Betriebsrats erforderlich.",
    ez:"若這些加班是強制性的，則需要工會（員工代表會）的同意。" },

  { mt:"MT11", teil:"L4",
    a:"", w:"konzipieren", p:"",
    en:"to conceive / design (a strategy)", zh:"構思、設計（策略）",
    k:"eine Strategie konzipieren; von der Marketingabteilung konzipiert werden",
    kz:"構思一項策略；由行銷部門設計",
    ex:"Die Marketingstrategie wurde von der Marketingabteilung konzipiert.",
    ez:"行銷策略是由行銷部門設計的。" },

  { mt:"MT11", teil:"L4",
    a:"der/die", w:"Angestellte", p:"-n",
    en:"employee", zh:"員工、職員",
    k:"die Angestellten der Firma; als Angestellter arbeiten",
    kz:"公司的員工；以員工身份工作",
    ex:"Müssen die Angestellten der Firma am Tag der offenen Tür Überstunden machen?",
    ez:"公司員工在開放日當天必須加班嗎？" },

  { mt:"MT11", teil:"L4",
    a:"", w:"allein lebend", p:"",
    en:"living alone", zh:"獨居的",
    k:"für allein lebende Kunden gedacht sein",
    kz:"是為獨居顧客設計的",
    ex:"Die neuen Brote sind für allein lebende Kundinnen und Kunden gedacht.",
    ez:"新的麵包是為獨居的顧客設計的。" },

  // ── LESEN UND SCHREIBEN (S.26-27) ───────────────────────────────
  { mt:"MT11", teil:"L2",
    a:"", w:"veranstalten", p:"",
    en:"to organize / hold (an event)", zh:"舉辦（活動）",
    k:"eine Tagung veranstalten; jährlich mehrere Tagungen veranstalten",
    kz:"舉辦研討會；每年舉辦多場研討會",
    ex:"Wie Sie wissen, veranstalten wir jährlich mehrere Tagungen in Ihrem Konferenzhotel.",
    ez:"如您所知，我們每年都在您的會議飯店舉辦多場研討會。" },

  { mt:"MT11", teil:"L2",
    a:"die", w:"Tagung", p:"-en",
    en:"conference / meeting", zh:"研討會、會議",
    k:"eine Tagung organisieren; an einer Tagung teilnehmen",
    kz:"組織一場研討會；參加研討會",
    ex:"Wir veranstalten jährlich mehrere Tagungen in Ihrem Konferenzhotel.",
    ez:"我們每年在您的會議飯店舉辦多場研討會。" },

  { mt:"MT11", teil:"L2",
    a:"der", w:"Vorfall", p:"-fälle",
    en:"incident", zh:"事件、事故",
    k:"vergleichbare Vorfälle; ein Vorfall wiederholt sich",
    kz:"類似的事件；事件再次發生",
    ex:"Ich gehe davon aus, dass sich vergleichbare Vorfälle nicht wiederholen.",
    ez:"我希望類似的事件不會再次發生。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"gewohnt (gewohnter Service)", p:"",
    en:"usual / customary", zh:"習以為常的、慣常的",
    k:"den gewohnten Service erwarten; wie gewohnt",
    kz:"期待慣常的服務；如往常一樣",
    ex:"Wir dürfen zukünftig den gewohnten Service erwarten.",
    ez:"我們希望未來能恢復一貫的服務水準。" },

  { mt:"MT11", teil:"L2",
    a:"", w:"unzufrieden", p:"",
    en:"dissatisfied", zh:"不滿意的",
    k:"mit etwas unzufrieden sein; schon einmal unzufrieden gewesen sein",
    kz:"對某事不滿意；曾經感到不滿",
    ex:"Frau Spieß war schon einmal mit dem Service und der technischen Ausstattung des Hotels unzufrieden.",
    ez:"Spieß 女士曾對飯店的服務及技術設備感到不滿。" },

  // ── HÖREN TEIL 2 (S.33) ──────────────────────────────────────────
  { mt:"MT11", teil:"H2",
    a:"der/die", w:"Beschäftigte", p:"-n",
    en:"employee", zh:"員工、受僱者",
    k:"manche Beschäftigte; Beschäftigte fühlen sich kontrolliert",
    kz:"部分員工；員工感到被監控",
    ex:"Im Homeoffice fühlen sich manche Beschäftigte stark kontrolliert.",
    ez:"在居家辦公時，有些員工感到自己受到強烈的監控。" },

  // ── HÖREN TEIL 3 (S.35) ──────────────────────────────────────────
  { mt:"MT11", teil:"H3",
    a:"", w:"aufladen", p:"",
    en:"to charge / top up (a card)", zh:"儲值、充值（卡片）",
    k:"eine Karte aufladen; an Automaten aufgeladen werden",
    kz:"為卡片儲值；在自動機台上儲值",
    ex:"Man bezahlt mit einer Karte, die an Automaten mit Geld aufgeladen wird.",
    ez:"使用可以在自動機台上儲值的卡片付款。" },

  { mt:"MT11", teil:"H3",
    a:"die", w:"Umstellung", p:"-en",
    en:"changeover / conversion", zh:"轉換、改制",
    k:"die Umstellung auf ein neues System; eine schnelle Umstellung",
    kz:"轉換到新系統；快速的轉換",
    ex:"Die Umstellung auf das moderne Bezahlsystem ist technisch kompliziert, lohnt sich aber insgesamt.",
    ez:"轉換到現代化支付系統在技術上較複雜，但整體而言是值得的。" },

  { mt:"MT11", teil:"H3",
    a:"die", w:"Ausgabe", p:"-n",
    en:"expense / expenditure", zh:"支出、費用",
    k:"die Ausgaben der Firma verringern; hohe Ausgaben haben",
    kz:"減少公司的支出；有高額支出",
    ex:"Die Umstellung wird langfristig die Ausgaben der Firma verringern.",
    ez:"這項轉換從長遠來看將降低公司的支出。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"verringern", p:"",
    en:"to reduce / decrease", zh:"減少、降低",
    k:"Kosten verringern; das Risiko verringern",
    kz:"降低成本；降低風險",
    ex:"Die Umstellung wird langfristig die Ausgaben der Firma verringern.",
    ez:"這項轉換從長遠來看將降低公司的支出。" },

  // ── HÖREN TEIL 4 (S.37) ────────────────────────────────────────
  { mt:"MT11", teil:"H4",
    a:"", w:"abstellen", p:"",
    en:"to turn off / shut off (water, etc.)", zh:"關閉、停止（水、電等）",
    k:"das Wasser abstellen; einen Automaten abstellen",
    kz:"把水關掉；把機器關掉",
    ex:"Sie meldet, dass das Wasser in der Toilette abgestellt ist.",
    ez:"她報告說廁所裡的水已經被關掉了。" },

  { mt:"MT11", teil:"H4",
    a:"der", w:"Schaden", p:"-schäden",
    en:"damage", zh:"損壞、損害",
    k:"einen Schaden reparieren; der Hausmeister soll den Schaden reparieren",
    kz:"修復損壞；管理員應修復損壞",
    ex:"Sie möchte, dass der Hausmeister den Schaden repariert.",
    ez:"她希望管理員能修復這個損壞的地方。" },

  // ── SPRACHBAUSTEINE TEIL 2 — Angebot (S.47) ─────────────────────
  { mt:"MT11", teil:"SB2",
    a:"", w:"das Angebot umfasst", p:"",
    en:"the offer includes / comprises", zh:"報價包含",
    k:"das Angebot umfasst mehrere Posten; ein Angebot umfasst Lieferung und Aufbau",
    kz:"報價包含多個項目；報價包含運送與安裝",
    ex:"Das Angebot umfasst ca. 2 Wochen, nachdem der Auftrag erteilt wurde.",
    ez:"（此處為語法練習選項：）「報價包含……」表達交貨後約需兩週。" },

  { mt:"MT11", teil:"SB2",
    a:"die", w:"Lieferzeit beträgt", p:"",
    en:"the delivery time amounts to", zh:"交貨時間為",
    k:"die Lieferzeit beträgt zwei Wochen; eine kurze Lieferzeit",
    kz:"交貨時間為兩週；短交貨時間",
    ex:"Die Lieferzeit beträgt ca. 2 Wochen, nachdem der Auftrag erteilt wurde.",
    ez:"交貨時間在訂單下達後約兩週。" },

  { mt:"MT11", teil:"SB2",
    a:"", w:"mit Kosten verbunden ist", p:"",
    en:"is associated with costs", zh:"需付額外費用的",
    k:"mit Kosten verbunden sein; eine Dienstleistung, die mit Kosten verbunden ist",
    kz:"伴隨費用；需要額外付費的服務",
    ex:"Der Kaufpreis ist innerhalb von 30 Tagen nach Rechnungsdatum mit Kosten verbunden, falls verspätet bezahlt wird.",
    ez:"若逾期付款，發票日期後 30 天內的價款將產生額外費用。" },

  { mt:"MT11", teil:"SB2",
    a:"", w:"ohne Abzug fällig ist", p:"",
    en:"is due in full without deduction", zh:"不扣款、全額到期",
    k:"der Kaufpreis ist ohne Abzug fällig; eine Rechnung ohne Abzug bezahlen",
    kz:"價款須全額支付，不得扣款；不扣款支付帳單",
    ex:"Der Kaufpreis ist innerhalb von 30 Tagen nach Rechnungsdatum ohne Abzug fällig.",
    ez:"價款須於發票日期後 30 天內全額付清，不得扣減。" },

  // ── HÖREN TEIL 1 (Sonix 逐字稿標記) ──────────────────────────────
  { mt:"MT11", teil:"H1",
    a:"", w:"abwischen", p:"",
    en:"to wipe (down)", zh:"擦拭",
    k:"die Tische abwischen; eine Oberfläche abwischen",
    kz:"擦桌子；擦拭表面",
    ex:"Man muss jeden Tag die Tische abwischen und die Mülleimer leeren.",
    ez:"每天都要擦桌子並清空垃圾桶。" },

  { mt:"MT11", teil:"H1",
    a:"", w:"angewiesen sein (auf + Akk.)", p:"",
    en:"to be dependent on / reliant on", zh:"依賴、仰賴（某事物）",
    k:"auf die Schulferien angewiesen sein; auf Hilfe angewiesen sein",
    kz:"必須配合學校假期；依賴他人協助",
    ex:"Ich bin auf die Schulferien angewiesen.",
    ez:"我（休假安排）必須配合孩子的學校假期。" },

  { mt:"MT11", teil:"H1",
    a:"der", w:"Kompromiss", p:"-e",
    en:"compromise", zh:"妥協、折衷方案",
    k:"ein Kompromiss finden; das wäre ein Kompromiss",
    kz:"找到折衷方案；這算是個妥協",
    ex:"Das wäre ein Kompromiss. Ja, das könnte ich machen.",
    ez:"這算是個折衷方案，我可以這樣做。" },

  { mt:"MT11", teil:"H1",
    a:"", w:"einrichten", p:"",
    en:"to set up / install (equipment)", zh:"設置、安裝（設備）",
    k:"den Drucker einrichten; PCs anmelden und einrichten",
    kz:"設定印表機；註冊並設定電腦",
    ex:"Wir würden Ihnen den Drucker dann auch gleich einrichten.",
    ez:"我們也會幫您把印表機直接設定好。" },

  // ── HÖREN TEIL 2 (Sonix 逐字稿標記) ──────────────────────────────
  { mt:"MT11", teil:"H2",
    a:"", w:"einführen", p:"",
    en:"to introduce / implement", zh:"引進、實施（制度）",
    k:"Homeoffice einführen; eine neue Regel einführen",
    kz:"引進居家辦公制度；實施新規定",
    ex:"Was haltet ihr denn davon, wenn wir hier im Unternehmen Homeoffice einführen?",
    ez:"你們覺得我們公司引進居家辦公制度怎麼樣？" },

  { mt:"MT11", teil:"H2",
    a:"", w:"dauernd", p:"",
    en:"constantly / all the time", zh:"不斷地、一直",
    k:"dauernd gestört werden; dauernd anrufen",
    kz:"不斷被打擾；不斷打電話來",
    ex:"Ich werde dauernd gestört. Ständig klingelt das Telefon.",
    ez:"我一直被打擾，電話不斷響。" },

  { mt:"MT11", teil:"H2",
    a:"die", w:"Auskunft", p:"-künfte",
    en:"information / inquiry response", zh:"資訊、詢問答覆",
    k:"eine Auskunft geben; von mir eine Auskunft möchten",
    kz:"提供資訊；想向我詢問資訊",
    ex:"Kollegen kommen herein und möchten von mir eine Auskunft.",
    ez:"同事進來想向我詢問一些資訊。" },

  { mt:"MT11", teil:"H2",
    a:"", w:"aufhängen", p:"",
    en:"to hang up (laundry)", zh:"晾曬、掛起（衣物）",
    k:"Wäsche aufhängen; etwas an die Wand aufhängen",
    kz:"晾衣服；把某物掛在牆上",
    ex:"Mein Chef denkt, ich tue irgendetwas anderes, wie Wäsche aufhängen.",
    ez:"我老闆以為我在做別的事，比如晾衣服。" },

  { mt:"MT11", teil:"H2",
    a:"", w:"aufhören", p:"",
    en:"to stop / cease", zh:"停止",
    k:"aufhören zu arbeiten; mit etwas aufhören",
    kz:"停止工作；停止做某事",
    ex:"Kannst du nicht endlich mal aufhören zu arbeiten?",
    ez:"你能不能終於停止工作了？" },

  // ── HÖREN TEIL 3 (Sonix 逐字稿標記) ───────────────────────────────
  { mt:"MT11", teil:"H3",
    a:"", w:"bzw. (beziehungsweise)", p:"",
    en:"or rather / respectively", zh:"或者說、亦即",
    k:"ob bzw. wie man das gestalten kann",
    kz:"是否、或者說如何能達成此事",
    ex:"Wir überlegen sollten, ob bzw. wie man das Bezahlen moderner gestalten kann.",
    ez:"我們該考慮是否、或者說該如何讓付款方式更現代化。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"gestalten", p:"",
    en:"to design / shape", zh:"設計、規劃（方式）",
    k:"etwas moderner gestalten; den Übergang gestalten",
    kz:"把某事設計得更現代；規劃過渡方式",
    ex:"Wie man das Bezahlen in der Kantine moderner gestalten kann.",
    ez:"如何能把員工餐廳的付款方式設計得更現代化。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"einholen (Informationen)", p:"",
    en:"to gather / obtain (information)", zh:"蒐集、取得（資訊）",
    k:"Informationen einholen; ein Angebot einholen",
    kz:"蒐集資訊；取得報價",
    ex:"Ich habe Informationen zu verschiedenen Bezahlmöglichkeiten eingeholt.",
    ez:"我已經蒐集了各種付款方式的相關資訊。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"ergeben (Ergebnisse)", p:"",
    en:"to result in / show (as a finding)", zh:"顯示、得出（結論）",
    k:"die Recherche hat ergeben, dass...; sich ergeben",
    kz:"研究結果顯示……；得出結論",
    ex:"Meine Recherchen haben ergeben, dass es am sinnvollsten ist, umzustellen.",
    ez:"我的研究結果顯示，改換系統是最合理的做法。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"umstellen", p:"",
    en:"to switch over / convert", zh:"改換、轉換（系統）",
    k:"auf kontaktloses Bezahlen umstellen; das System umstellen",
    kz:"改換成非接觸式付款；轉換系統",
    ex:"Es ist am sinnvollsten, komplett auf kontaktloses Bezahlen umzustellen.",
    ez:"最合理的做法是完全改換成非接觸式付款。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"ausgesprochen", p:"",
    en:"extremely / decidedly", zh:"極為、非常（加強語氣）",
    k:"ausgesprochen hygienisch; ausgesprochen wichtig",
    kz:"極為衛生；非常重要",
    ex:"Kontaktloses Bezahlen ist ausgesprochen hygienisch.",
    ez:"非接觸式付款是極為衛生的。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"anfassen", p:"",
    en:"to touch", zh:"觸碰、碰觸",
    k:"nichts mehr anfassen müssen; etwas vorsichtig anfassen",
    kz:"不需要再碰觸任何東西；小心地碰觸某物",
    ex:"Man muss nichts mehr anfassen, weil es kontaktlos funktioniert.",
    ez:"因為是非接觸式，所以不需要再碰觸任何東西。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"zulassen", p:"",
    en:"to allow / permit", zh:"允許、容許",
    k:"nur eine Möglichkeit zulassen; etwas nicht zulassen",
    kz:"只允許一種方式；不允許某事",
    ex:"Man sollte nur eine Bezahlmöglichkeit zulassen.",
    ez:"應該只允許一種付款方式。" },

  { mt:"MT11", teil:"H3",
    a:"der", w:"Betrag", p:"-träge",
    en:"amount (of money)", zh:"金額",
    k:"der Betrag wird gutgeschrieben; einen Betrag überweisen",
    kz:"金額入帳；轉一筆金額",
    ex:"Im Moment muss man Geld in die Automaten stecken, damit der Betrag gutgeschrieben wird.",
    ez:"目前還必須把錢投進機器裡，讓金額入帳到卡片上。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"gutschreiben", p:"",
    en:"to credit (an account/card)", zh:"入帳、記入貸方",
    k:"den Betrag auf der Karte gutschreiben; einem Konto gutschreiben",
    kz:"把金額存入卡片；存入帳戶",
    ex:"Damit der Betrag auf der Kantinenkarte gutgeschrieben wird.",
    ez:"以便讓金額存入員工餐廳卡。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"aufladen", p:"",
    en:"to charge / top up (a card)", zh:"儲值、充值（卡片）",
    k:"eine Karte aufladen; Automaten zum Aufladen",
    kz:"為卡片儲值；用來儲值的機器",
    ex:"Es sind keine Automaten zum Aufladen der Kantinenkarte mehr nötig.",
    ez:"不再需要用來給員工餐廳卡儲值的機器。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"aufwendig", p:"",
    en:"costly / elaborate (in effort)", zh:"耗費（時間或人力）的",
    k:"aufwendiges Zählen; aufwendiger sein",
    kz:"耗費人力的計算工作；更耗費人力",
    ex:"Das aufwendige Zählen des Bargelds entfällt.",
    ez:"耗費人力的現金計算工作將不再需要。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"entfallen", p:"",
    en:"to no longer be needed / to be omitted", zh:"省去、不再需要",
    k:"eine Aufgabe entfällt; der Schritt entfällt",
    kz:"某項工作不再需要；該步驟省去",
    ex:"Das aufwendige Zählen des Bargelds entfällt.",
    ez:"耗費人力的現金計算工作將被省去。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"einsparen", p:"",
    en:"to save (costs)", zh:"省下、節省（成本）",
    k:"Kosten einsparen; die Kosten sind wieder eingespart",
    kz:"節省成本；成本已重新省回來",
    ex:"Die Kosten für das neue System dürften nach einiger Zeit wieder eingespart sein.",
    ez:"新系統的成本過一段時間後應該就能省回來。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"eingeben", p:"",
    en:"to enter / input (data)", zh:"輸入（資料）",
    k:"Daten selbst eingeben; eine Nummer eingeben",
    kz:"自行輸入資料；輸入號碼",
    ex:"Die Beschäftigten geben ihre Daten selbst ein. Das spart uns Arbeit.",
    ez:"員工自行輸入自己的資料，這樣能省下我們的工作量。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"zwingen", p:"",
    en:"to force / compel", zh:"強迫",
    k:"jemanden zu etwas zwingen; man kann niemanden zwingen",
    kz:"強迫某人做某事；不能強迫任何人",
    ex:"Man kann niemanden dazu zwingen, die App herunterzuladen.",
    ez:"不能強迫任何人下載這個應用程式。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"angenommen", p:"",
    en:"assuming / supposing", zh:"假設、假定",
    k:"angenommen, wir entscheiden uns für...; angenommen, dass...",
    kz:"假設我們決定採用……；假定……",
    ex:"Angenommen, wir entscheiden uns für ein neues Bezahlsystem.",
    ez:"假設我們決定採用一套新的付款系統。" },

  { mt:"MT11", teil:"H3",
    a:"der", w:"Übergang", p:"-gänge",
    en:"transition", zh:"過渡、轉換期",
    k:"der Übergang von einem System auf das andere; einen Übergang gestalten",
    kz:"從一套系統轉換到另一套系統；規劃過渡方式",
    ex:"Wie soll der Übergang von einem System auf das andere gestaltet werden?",
    ez:"從一套系統轉換到另一套系統的過渡期該怎麼安排？" },

  { mt:"MT11", teil:"H3",
    a:"", w:"abschaffen", p:"",
    en:"to abolish / do away with", zh:"廢除、取消",
    k:"die Bargeldzahlung abschaffen; eine Regel abschaffen",
    kz:"取消現金支付方式；廢除一項規定",
    ex:"Kelchs hat dann die Bargeldzahlung von einem Tag auf den anderen abgeschafft.",
    ez:"Kelchs 公司後來說一不二地直接取消了現金支付方式。" },

  { mt:"MT11", teil:"H3",
    a:"", w:"spürbar", p:"",
    en:"noticeable / perceptible", zh:"明顯可感受到的",
    k:"die Vorteile werden spürbar; ein spürbarer Unterschied",
    kz:"優點變得明顯可感受到；明顯的差異",
    ex:"Die Vorteile wie die kürzeren Wartezeiten werden für alle deutlich und spürbar.",
    ez:"像縮短等待時間這樣的優點，大家都會明顯感受到。" },

  // ── HÖREN TEIL 4 (Sonix 逐字稿標記) ───────────────────────────────
  { mt:"MT11", teil:"H4",
    a:"", w:"klappen", p:"",
    en:"to work out / go smoothly", zh:"順利進行、行得通",
    k:"das klappt nicht; alles klappt gut",
    kz:"這行不通；一切順利",
    ex:"Aber jetzt klappt das alles nicht.",
    ez:"但現在這一切都不順利、行不通。" },

  { mt:"MT11", teil:"H4",
    a:"", w:"dick", p:"",
    en:"swollen / thick", zh:"腫的、厚的",
    k:"das Knie ist dick; dick und geschwollen",
    kz:"膝蓋腫起來；又腫又脹",
    ex:"Mein rechtes Knie ist dick und tut richtig weh.",
    ez:"我的右膝腫起來，而且真的很痛。" },

  { mt:"MT11", teil:"H4",
    a:"", w:"abstellen", p:"",
    en:"to turn off / shut off (water, etc.)", zh:"關閉、停止（水、電等）",
    k:"das Wasser abstellen; einen Automaten abstellen",
    kz:"把水關掉；把機器關掉",
    ex:"Kannst du ihm sagen, dass er das Wasser abstellen soll?",
    ez:"你能告訴他要把水關掉嗎？" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST11_DATA);
}
