// data_ModellTest6.js
// MT6 = Klett "Mit Erfolg zum DTB B2" — Modelltest 2 (書本頁碼 58-74)
// 來源: 手機照片轉PNG, 紅色/黑色底線標記
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST6_DATA = [

  // ── LESEN TEIL 1 (S.59) ────────────────────────────────────────
  { mt:"MT6", teil:"L1",
    a:"", w:"berichten", p:"",
    en:"to report", zh:"報告、敘述",
    k:"über etwas berichten; ausführlich berichten",
    kz:"報告某事；詳細敘述",
    ex:"Eine Krankenhausärztin, ein Lehrer und ein Sozialarbeiter berichten über den alltäglichen Wahnsinn.",
    ez:"一位醫院醫師、一位老師和一位社工敘述了日常的瘋狂忙碌。" },

  { mt:"MT6", teil:"L1",
    a:"der", w:"Wahnsinn", p:"",
    en:"madness / craziness", zh:"瘋狂、忙亂",
    k:"der alltägliche Wahnsinn; Wahnsinn sein",
    kz:"日常的瘋狂忙亂；是瘋狂的事",
    ex:"Berichten über den alltäglichen Wahnsinn und wie sie damit klarkommen.",
    ez:"敘述日常的瘋狂忙亂以及他們如何應付。" },

  { mt:"MT6", teil:"L1",
    a:"die", w:"Arbeitsbelastung", p:"",
    en:"workload", zh:"工作負荷",
    k:"die Arbeitsbelastung ist hoch; eine hohe Arbeitsbelastung haben",
    kz:"工作負荷很高；有很高的工作負荷",
    ex:"Doch der Job lässt oft wenig Spielraum, die Arbeitsbelastung ist hoch.",
    ez:"但工作往往沒有太多餘裕，工作負荷很高。" },

  { mt:"MT6", teil:"L1",
    a:"", w:"beeindruckt", p:"",
    en:"impressed", zh:"印象深刻的",
    k:"beeindruckt auch Arbeitgeber; jemanden beeindrucken",
    kz:"也讓雇主印象深刻；使某人印象深刻",
    ex:"Das ist nicht nur eine sehr wertvolle Berufserfahrung, sondern beeindruckt auch Arbeitgeber.",
    ez:"這不僅是非常寶貴的工作經驗，也會讓雇主印象深刻。" },

  // ── LESEN TEIL 2 (S.60-61) ────────────────────────────────────
  { mt:"MT6", teil:"L2",
    a:"", w:"jeweilig (jeweils)", p:"",
    en:"respective(ly)", zh:"各自的、相應的",
    k:"die jeweils aktuelle Raumliste; jeweils ein Exemplar",
    kz:"各自最新的場地清單；各一份",
    ex:"Dort hängt auch die jeweils aktuelle Raumliste aus.",
    ez:"那裡也張貼著各自最新的場地使用清單。" },

  { mt:"MT6", teil:"L2",
    a:"", w:"dagegen", p:"",
    en:"on the other hand / however", zh:"相反地、然而",
    k:"Essen dagegen dürfen Sie nur in den Pausenräumen; dagegen sein",
    kz:"然而食物只能在休息室吃；反對",
    ex:"Essen dagegen dürfen Sie nur in den Pausenräumen und in der Kantine.",
    ez:"然而食物只能在休息室和員工餐廳裡吃。" },

  { mt:"MT6", teil:"L2",
    a:"", w:"zugezogen", p:"",
    en:"newly arrived / having moved in", zh:"新搬來的",
    k:"besonders neu zugezogene Mitarbeitende; in eine Stadt zuziehen",
    kz:"特別是新搬來的員工；搬到一座城市",
    ex:"Besonders neu zugezogene Mitarbeitende finden hier schnell Anschluss.",
    ez:"特別是新搬來的員工能很快在這裡融入。" },

  { mt:"MT6", teil:"L2",
    a:"das", w:"Umland", p:"",
    en:"surrounding area", zh:"周邊地區",
    k:"das attraktive Umland kennenlernen; im Umland wohnen",
    kz:"認識有吸引力的周邊地區；住在周邊地區",
    ex:"Wer das attraktive Umland kennenlernen will, kann sich unserer Wandergruppe anschließen.",
    ez:"想認識有吸引力的周邊地區的人，可以加入我們的健行社團。" },

  { mt:"MT6", teil:"L2",
    a:"", w:"geschlossen (einen Vertrag)", p:"",
    en:"concluded / signed (a contract)", zh:"已簽訂的（合約）",
    k:"einen Vertrag geschlossen; einen Vertrag schließen",
    kz:"已簽訂一份合約；簽訂合約",
    ex:"Die Unternehmensleitung hat außerdem einen Vertrag mit dem Fitness-Center geschlossen.",
    ez:"公司管理層此外還與健身中心簽訂了一份合約。" },

  { mt:"MT6", teil:"L2",
    a:"", w:"verlost", p:"",
    en:"raffled off", zh:"被抽獎贈送的",
    k:"Eintrittskarten werden verlost; etwas verlosen",
    kz:"門票被用來抽獎；抽獎贈送某物",
    ex:"Über die regelmäßig Eintrittskarten für Oper, Theater, Lesungen, aber auch für Fußballspiele verlost werden.",
    ez:"定期會抽獎贈送歌劇院、劇院、朗讀會以及足球賽的門票。" },

  { mt:"MT6", teil:"L2",
    a:"das", w:"Veranstaltungsticket", p:"-s",
    en:"event ticket", zh:"活動門票",
    k:"Anspruch auf Veranstaltungstickets; ein Veranstaltungsticket gewinnen",
    kz:"有資格獲得活動門票；贏得活動門票",
    ex:"Haben Anspruch auf Veranstaltungstickets.",
    ez:"有資格獲得活動門票。" },

  // ── LESEN TEIL 3 (S.62-63) ─────────────────────────────────────
  { mt:"MT6", teil:"L3",
    a:"", w:"wachsen (über den Kopf)", p:"",
    en:"to grow beyond one's control / become overwhelming", zh:"變得難以負荷",
    k:"über den Kopf wachsen; etwas wächst einem über den Kopf",
    kz:"變得超出自己能力範圍；某事讓人難以負荷",
    ex:"Familie und Vollzeitjob allmählich über den Kopf wachsen.",
    ez:"家庭與全職工作漸漸變得令人難以負荷。" },

  { mt:"MT6", teil:"L3",
    a:"die", w:"Einhaltung", p:"",
    en:"adherence / compliance", zh:"遵守",
    k:"für die Einhaltung der Ruhezeiten sorgen; die Einhaltung von Regeln",
    kz:"確保遵守休息時間；遵守規則",
    ex:"Dazu gehört auch, die Gesundheit zu schützen und für die Einhaltung der Ruhezeiten zu sorgen.",
    ez:"這也包括保護健康並確保休息時間被遵守。" },

  { mt:"MT6", teil:"L3",
    a:"", w:"abbauen (Überstunden)", p:"",
    en:"to reduce / work off (overtime)", zh:"消除、抵銷（加班時數）",
    k:"Überstunden abzubauen; etwas abbauen",
    kz:"消除加班時數；減少某事",
    ex:"Irgendwann muss dir dein Arbeitgeber die Möglichkeit geben, deine Überstunden abzubauen.",
    ez:"雇主終究必須給你機會去抵銷加班時數。" },

  { mt:"MT6", teil:"L3",
    a:"der/die", w:"Betroffene", p:"-n",
    en:"the affected person", zh:"受影響的人、患者",
    k:"sich der Betroffene immer schlechter konzentrieren kann; ein Betroffener",
    kz:"患者越來越難以集中注意力；受影響的人",
    ex:"Ein Burnout erkennst du daran, dass sich der Betroffene immer schlechter konzentrieren kann.",
    ez:"你可以從患者越來越難以集中注意力來辨識出職業倦怠。" },

  { mt:"MT6", teil:"L3",
    a:"", w:"Fehler bei der Arbeit machen", p:"",
    en:"to make mistakes at work", zh:"在工作上犯錯",
    k:"immer mehr Fehler bei der Arbeit machen; einen Fehler machen",
    kz:"在工作上犯越來越多錯誤；犯一個錯誤",
    ex:"Und immer mehr Fehler bei der Arbeit macht.",
    ez:"並且在工作上犯越來越多的錯誤。" },

  // ── LESEN TEIL 4 (S.64-65) ──────────────────────────────────────
  { mt:"MT6", teil:"L4",
    a:"das", w:"Handzeichen", p:"-",
    en:"show of hands", zh:"舉手表決",
    k:"durch Handzeichen ohne Einwände einstimmig angenommen; ein Handzeichen geben",
    kz:"以舉手表決一致無異議通過；舉手表示",
    ex:"Wird durch Handzeichen ohne Einwände einstimmig angenommen.",
    ez:"以舉手表決方式一致無異議地通過。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"unansehnlich", p:"",
    en:"unsightly / unattractive in appearance", zh:"不雅觀的、難看的",
    k:"unansehnlich geworden; etwas wird unansehnlich",
    kz:"變得不雅觀；某物變得難看",
    ex:"In denen die Bäder durch den häufigen Gebrauch von Desinfektionsmitteln unansehnlich geworden waren.",
    ez:"那些浴室因為頻繁使用消毒劑而變得不雅觀。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"beschädigt (Waschbecken)", p:"",
    en:"damaged (sink)", zh:"損壞的（洗手台）",
    k:"beschädigte Waschbecken; etwas beschädigen",
    kz:"損壞的洗手台；損壞某物",
    ex:"Die teilweise auch beschädigte Waschbecken und Fliesen hatten.",
    ez:"那些有部分也損壞的洗手台和磁磚。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"angetrunken", p:"",
    en:"slightly drunk / tipsy", zh:"帶著醉意的",
    k:"angetrunken auf die Station kommen; angetrunken sein",
    kz:"帶著醉意來到病房；處於微醉狀態",
    ex:"Die manchmal spät abends angetrunken auf die Station kommen.",
    ez:"他們有時會在深夜帶著醉意來到病房。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"übertreiben", p:"",
    en:"to overdo / exaggerate", zh:"過度、誇張",
    k:"manche übertreiben es; etwas übertreiben",
    kz:"有些人做得太過頭；過度做某事",
    ex:"Manche übertreiben es auch mit Blumensträußen.",
    ez:"有些人在花束上也做得太過頭。" },

  { mt:"MT6", teil:"L4",
    a:"der", w:"Blumenstrauß", p:"-sträuße",
    en:"bouquet of flowers", zh:"花束",
    k:"es mit Blumensträußen übertreiben; einen Blumenstrauß mitbringen",
    kz:"在花束上做得太過頭；帶來一束花",
    ex:"Manche übertreiben es auch mit Blumensträußen, sodass es in einigen Krankenzimmern wie in einer Gärtnerei aussehe.",
    ez:"有些人在花束上太過誇張，使得某些病房看起來像花圃一樣。" },

  { mt:"MT6", teil:"L4",
    a:"der", w:"gelungene Umbau", p:"",
    en:"successful renovation", zh:"成功的改建",
    k:"den gelungenen Umbau der Cafeteria; ein Umbau gelingt",
    kz:"成功改建的員工餐廳；改建順利完成",
    ex:"CB lobt den gelungenen Umbau der Caféteria im Erdgeschoss.",
    ez:"CB 讚揚一樓員工餐廳成功的改建。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"dringend darauf hinweisen", p:"",
    en:"to urgently point out", zh:"急切地提醒、強調",
    k:"dringend darauf hinweisen, dass...; auf etwas hinweisen",
    kz:"急切地提醒……；提醒某事",
    ex:"CB weist dringend darauf hin, sich hier nicht über vertrauliche Patienteninformationen zu unterhalten.",
    ez:"CB 急切地提醒大家不要在這裡談論病患的機密資訊。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"vertraulich", p:"",
    en:"confidential", zh:"機密的",
    k:"vertrauliche Patienteninformationen; etwas vertraulich behandeln",
    kz:"病患的機密資訊；機密處理某事",
    ex:"Sich hier nicht über vertrauliche Patienteninformationen zu unterhalten.",
    ez:"不要在這裡談論病患的機密資訊。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"bemängeln", p:"",
    en:"to criticize / find fault with", zh:"批評、指出缺陷",
    k:"familienfeindliche Arbeitszeiten bemängeln; etwas bemängeln",
    kz:"批評不利於家庭的工時；批評某事",
    ex:"MA weist darauf hin, dass... bemängelt familienfeindliche Arbeitszeiten.",
    ez:"MA 指出……批評了不利於家庭的工時安排。" },

  { mt:"MT6", teil:"L4",
    a:"", w:"erfolgen (Malerarbeiten)", p:"",
    en:"to take place / be carried out (painting work)", zh:"進行（油漆工作）",
    k:"erfolgen im April noch Malerarbeiten; etwas erfolgt",
    kz:"四月還會進行油漆工作；某事進行",
    ex:"Erfolgen im April noch Malerarbeiten.",
    ez:"四月還會進行油漆工作。" },

  // ── LESEN UND SCHREIBEN (S.66) ──────────────────────────────────
  { mt:"MT6", teil:"L2",
    a:"das", w:"Spülbecken", p:"-",
    en:"kitchen sink", zh:"水槽",
    k:"ein großes Spülbecken aus Keramik; das Spülbecken reparieren",
    kz:"陶瓷製的大水槽；修理水槽",
    ex:"Dazu gehörte ein großes Spülbecken aus Keramik und mehrere Einbauschränke darüber.",
    ez:"那包含一個陶瓷製的大水槽以及上方好幾個嵌入式汪楃。" },

  { mt:"MT6", teil:"L2",
    a:"der", w:"Einbauschrank", p:"-schränke",
    en:"built-in cabinet", zh:"嵌入式汪楃",
    k:"mehrere Einbauschränke; einen Einbauschrank montieren",
    kz:"好幾個嵌入式汪楃；安裝嵌入式汪楃",
    ex:"Ein großes Spülbecken aus Keramik und mehrere Einbauschränke darüber.",
    ez:"一個陶瓷製的大水槽以及上方好幾個嵌入式汪楃。" },

  { mt:"MT6", teil:"L2",
    a:"", w:"zügig", p:"",
    en:"prompt / swift", zh:"迅速的",
    k:"die zügige Durchführung der Arbeiten; zügig vorangehen",
    kz:"工作迅速地進行；迅速地進展",
    ex:"Mit der zügigen Durchführung der Arbeiten waren wir auch sehr zufrieden.",
    ez:"我們對工作迅速完成的方式也非常滿意。" },

  // ── HÖREN TEIL 2 (S.69) ──────────────────────────────────────────
  { mt:"MT6", teil:"H2",
    a:"", w:"belasten", p:"",
    en:"to burden / put strain on", zh:"造成負擔",
    k:"das Team belasten; jemanden belasten",
    kz:"造成團隊的負擔；造成某人的負擔",
    ex:"Wer nicht auf die eigene Gesundheit achtet, belastet auch das Team.",
    ez:"不照顧好自己健康的人，也會造成團隊的負擔。" },

  // ── HÖREN TEIL 4 (S.71) ──────────────────────────────────────────
  { mt:"MT6", teil:"H4",
    a:"der", w:"Gefallen", p:"",
    en:"favor", zh:"幫忙、人情",
    k:"jemanden um einen Gefallen bitten; einen Gefallen tun",
    kz:"請某人幫個忙；幫個忙",
    ex:"Thomas bittet Ahmed um einen Gefallen.",
    ez:"Thomas 請 Ahmed 幫個忙。" },

  { mt:"MT6", teil:"H4",
    a:"der", w:"Druckertoner", p:"",
    en:"printer toner", zh:"印表機碳粉",
    k:"Druckertoner online bestellen; den Toner wechseln",
    kz:"線上訂購印表機碳粉；更換碳粉",
    ex:"Frau Meyer bestellt Druckertoner online.",
    ez:"Meyer 女士線上訂購印表機碳粉。" },

  { mt:"MT6", teil:"H4",
    a:"", w:"durchführen (Reparaturen)", p:"",
    en:"to carry out (repairs)", zh:"進行（維修）",
    k:"die Reparaturen bis Dienstag durchführen; etwas durchführen",
    kz:"在星期二前完成維修；執行某事",
    ex:"Kann die Reparaturen bis Dienstag durchführen.",
    ez:"能在星期二前完成這些維修工作。" },

  { mt:"MT6", teil:"H4",
    a:"die", w:"Jubiläumsfeier", p:"-n",
    en:"anniversary celebration", zh:"週年慶祝活動",
    k:"an ihrer Stelle zur Jubiläumsfeier gehen; eine Jubiläumsfeier organisieren",
    kz:"代替她去參加週年慶祝活動；籌辦週年慶祝活動",
    ex:"Karin bittet ihre Kollegin, an ihrer Stelle zur Jubiläumsfeier zu gehen.",
    ez:"Karin 請她的同事代替她去參加週年慶祝活動。" },

  // ── SPRACHBAUSTEINE TEIL 1 (S.73) ────────────────────────────────
  { mt:"MT6", teil:"SB1",
    a:"der", w:"Einblick", p:"-e",
    en:"insight", zh:"了解、洞察",
    k:"gute Einblicke in die Abläufe; einen Einblick gewinnen",
    kz:"對流程有良好的了解；獲得洞察",
    ex:"Unser Gespräch hat mir gute Einblicke in die Abläufe und das kollegiale Betriebsklima gegeben.",
    ez:"我們的談話讓我對流程和同事間的工作氛圍有了良好的了解。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST6_DATA);
}
