// data_PreparationTraining_Lesen.js
// 來源: telc Prüfungstraining DTB B2 — 前半部練習題型 "Fit für die Prüfung" (書本頁碼 9-39, Lesen 部分)
// 標籤: telc Preparation Training
// 格式: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const PREPARATIONTRAINING_LESEN_DATA = [

  // ── S.7 — Auf Jobsuche (原先漏掉的起始頁) ────────────────────────
  { mt:"PT", teil:"L1",
    a:"", w:"beschäftigen (ein Unternehmen)", p:"",
    en:"to employ (a company employs)", zh:"僱用、聘用（企業聘用員工）",
    k:"Mitarbeiter beschäftigen; in einem Unternehmen beschäftigt sein",
    kz:"僱用員工；在某企業任職",
    ex:"Ein Unternehmen kündigen, gründen oder beschäftigen.",
    ez:"解散、創立或僱用人員於一家企業。" },

  { mt:"PT", teil:"L1",
    a:"", w:"ausüben (einen Beruf)", p:"",
    en:"to practice / carry out (a profession)", zh:"從事（職業）",
    k:"einen Beruf ausüben; eine Tätigkeit ausüben",
    kz:"從事某職業；從事某項工作",
    ex:"Die Meisterprüfung ausüben, berechtigen oder ablegen.",
    ez:"通過師傅考試後，獲得從事該職業的資格。" },

  { mt:"PT", teil:"L1",
    a:"", w:"berechtigen", p:"",
    en:"to entitle / authorize", zh:"使有資格、授權",
    k:"jemanden berechtigen, etwas zu tun; eine Prüfung berechtigt zu...",
    kz:"授權某人做某事；某項考試授予……資格",
    ex:"Die Meisterprüfung berechtigt dazu, einen Beruf auszuüben.",
    ez:"師傅考試授予從事該職業的資格。" },

  { mt:"PT", teil:"L1",
    a:"", w:"erwerben (eine Qualifikation)", p:"",
    en:"to acquire / obtain (a qualification)", zh:"取得、獲得（資格）",
    k:"eine Qualifikation erwerben; Kenntnisse erwerben",
    kz:"取得一項資格；獲得知識",
    ex:"Eine Qualifikation erwerben, bewerben oder feststellen.",
    ez:"取得一項資格、申請或確認某事。" },

  // ── S.11 — Auf Jobsuche (Lesen Teil 1練習) ───────────────────────
  { mt:"PT", teil:"L1",
    a:"der", w:"Rentenanspruch", p:"-ansprüche",
    en:"pension entitlement", zh:"退休金請求權",
    k:"den Rentenanspruch erhöhen; einen Rentenanspruch haben",
    kz:"提高退休金請求權；擁有退休金請求權",
    ex:"Der Rentenanspruch kann auf verschiedene Weise erhöht werden.",
    ez:"退休金請求權可以透過多種方式提高。" },

  { mt:"PT", teil:"L1",
    a:"", w:"entlohnen", p:"",
    en:"to remunerate / pay (for work)", zh:"支付薪酬、付酬",
    k:"angemessen entlohnt werden; für seine Tätigkeit entlohnt werden",
    kz:"獲得合理的薪酬；因工作而獲得報酬",
    ex:"Arbeitnehmer stellen sich die Frage, ob sie für ihre Tätigkeit angemessen entlohnt werden.",
    ez:"員工會思考自己是否因工作獲得了合理的薪酬。" },

  { mt:"PT", teil:"L1",
    a:"", w:"branchenüblich", p:"",
    en:"customary for the industry", zh:"業界慣例的、同行業通常的",
    k:"die branchenüblichen Gehälter kennen; ein branchenübliches Gehalt",
    kz:"了解業界慣例薪資；符合業界慣例的薪資",
    ex:"Wichtig ist dabei, die branchenüblichen Gehälter zu kennen.",
    ez:"重要的是要了解該行業通常的薪資水準。" },

  // ── S.12 — Auf Jobsuche ──────────────────────────────────────────
  { mt:"PT", teil:"L1",
    a:"der", w:"Unternehmergeist", p:"",
    en:"entrepreneurial spirit", zh:"創業精神",
    k:"mit Kreativität und Unternehmergeist; Unternehmergeist zeigen",
    kz:"懷抱創意與創業精神；展現創業精神",
    ex:"Mit Kreativität, Unternehmergeist und einem Sinn für ausgefallene Serviceideen.",
    ez:"憑著創意、創業精神以及對特殊服務點子的敏銳度。" },

  { mt:"PT", teil:"L1",
    a:"", w:"ausgefallen", p:"",
    en:"unusual / unconventional", zh:"與眾不同的、特殊的",
    k:"ausgefallene Serviceideen; ein ausgefallenes Design",
    kz:"特殊的服務點子；與眾不同的設計",
    ex:"Einem Sinn für ausgefallene Serviceideen ist sie ein Anziehungspunkt in der Stadt.",
    ez:"憑著對特殊服務點子的敏銳度，她成為城裡的一大亮點。" },

  // ── S.13 — Auf Jobsuche ──────────────────────────────────────────
  { mt:"PT", teil:"L1",
    a:"", w:"überwältigend", p:"",
    en:"overwhelming", zh:"驚人的、壓倒性的",
    k:"überwältigendes Interesse; eine überwältigende Mehrheit",
    kz:"驚人的興趣；壓倒性多數",
    ex:"Beweis dafür ist das überwältigende Interesse junger Frauen.",
    ez:"年輕女性驚人的高度興趣就是證明。" },

  { mt:"PT", teil:"L1",
    a:"", w:"diesjährig", p:"",
    en:"this year's", zh:"今年的",
    k:"die diesjährige Ausbildungsmesse; im diesjährigen Programm",
    kz:"今年的職訓博覽會；在今年的計畫中",
    ex:"Am ersten Tag der diesjährigen Ausbildungsmesse.",
    ez:"在今年職訓博覽會的第一天。" },

  { mt:"PT", teil:"L1",
    a:"", w:"unternehmerisch", p:"",
    en:"entrepreneurial", zh:"創業的、企業家精神的",
    k:"unternehmerisches Denken; unternehmerisch handeln",
    kz:"創業思維；以企業家精神行事",
    ex:"Wie junge Menschen mit unternehmerischem Denken vertraut gemacht werden.",
    ez:"年輕人如何被引導熟悉創業思維。" },

  { mt:"PT", teil:"L1",
    a:"", w:"vertraut machen (mit)", p:"",
    en:"to familiarize (with)", zh:"使熟悉、引導認識",
    k:"jemanden mit etwas vertraut machen; mit einem Thema vertraut sein",
    kz:"讓某人熟悉某事；對某主題熟悉",
    ex:"Wie junge Menschen mit unternehmerischem Denken vertraut gemacht werden.",
    ez:"年輕人如何被引導熟悉創業思維。" },

  { mt:"PT", teil:"L1",
    a:"die", w:"Verantwortung übernehmen", p:"",
    en:"to take on responsibility", zh:"承擔責任",
    k:"lernen, Verantwortung zu übernehmen; Verantwortung tragen",
    kz:"學習承擔責任；承擔責任",
    ex:"Und lernen, Verantwortung zu übernehmen.",
    ez:"並學習如何承擔責任。" },

  { mt:"PT", teil:"L1",
    a:"", w:"geeignet", p:"",
    en:"suitable / appropriate", zh:"適合的、合適的",
    k:"geeignete Fortbildungen auswählen; für etwas geeignet sein",
    kz:"挑選合適的進修課程；適合於某事",
    ex:"Wie Sie geeignete Fortbildungen für Ihre Mitarbeitenden auswählen.",
    ez:"如何為您的員工挑選合適的進修課程。" },

  { mt:"PT", teil:"L1",
    a:"das", w:"Startkapital", p:"",
    en:"start-up capital", zh:"創業資金",
    k:"wie viel Startkapital brauche ich; Startkapital aufbringen",
    kz:"我需要多少創業資金；籌措創業資金",
    ex:"Wie viel Startkapital brauche ich? Muss ich einen Businessplan schreiben?",
    ez:"我需要多少創業資金？我需要寫商業計畫書嗎？" },

  // ── S.14 — Vorschriften und Regelungen (Lesen Teil 2練習) ────────
  { mt:"PT", teil:"L2",
    a:"die", w:"Wiederherstellung", p:"",
    en:"restoration / recovery", zh:"恢復、修復",
    k:"der Wiederherstellung und Erhaltung der Arbeitskraft dienen",
    kz:"有助於恢復並維持勞動力",
    ex:"Garantiert die bezahlte Freizeit, die der Wiederherstellung der Arbeitskraft dienen soll.",
    ez:"保障用於恢復勞動力的有薪休假時間。" },

  { mt:"PT", teil:"L2",
    a:"", w:"befreien (von Keimen)", p:"",
    en:"to free / rid of (germs)", zh:"清除、去除（細菌）",
    k:"die Haut von Keimen befreien; etwas von etwas befreien",
    kz:"清除皮膚上的細菌；使某物去除某物",
    ex:"Chemische Substanzen, mit deren Hilfe man die Haut von Keimen befreien kann.",
    ez:"可以用來清除皮膚上細菌的化學物質。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Aufbewahrung", p:"",
    en:"storage / keeping", zh:"保存、存放",
    k:"die Aufbewahrung von Dingen zum Verzehr; zur Aufbewahrung geeignet",
    kz:"食用物品的保存；適合存放",
    ex:"Aufbewahrung von Dingen zum Verzehr, damit sie zeit- und saisonunabhängig zur Verfügung stehen.",
    ez:"保存供食用的物品，使其不受時間和季節限制而隨時可用。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"Verzehr", p:"",
    en:"consumption (of food)", zh:"食用、消費",
    k:"Dinge zum Verzehr; zum sofortigen Verzehr geeignet",
    kz:"供食用的物品；適合立即食用",
    ex:"Aufbewahrung von Dingen zum Verzehr.",
    ez:"供食用物品的保存。" },

  { mt:"PT", teil:"L2",
    a:"", w:"verderben", p:"",
    en:"to spoil / go bad", zh:"變質、腐壞",
    k:"ohne zu verderben; Lebensmittel verderben schnell",
    kz:"不會變質；食物很快腐壞",
    ex:"Damit sie zur Verfügung stehen, ohne zu verderben.",
    ez:"使它們可供使用而不會變質。" },

  // ── S.15 — Vorschriften und Regelungen ──────────────────────────
  { mt:"PT", teil:"L2",
    a:"", w:"sachgerecht", p:"",
    en:"proper / appropriate (handling)", zh:"恰當的、正確的（處理方式）",
    k:"der sachgerechte Umgang mit Lebensmitteln; etwas sachgerecht behandeln",
    kz:"恰當地處理食品；正確處理某物",
    ex:"Der sachgerechte Umgang mit Lebensmitteln ist sicherzustellen.",
    ez:"必須確保正確地處理食品。" },

  { mt:"PT", teil:"L2",
    a:"", w:"ordnungsgemäß", p:"",
    en:"properly / in accordance with regulations", zh:"依規定地、合規地",
    k:"ordnungsgemäß lagern; etwas ordnungsgemäß durchführen",
    kz:"依規定存放；依規定執行某事",
    ex:"Frische Lebensmittel muss man ordnungsgemäß lagern.",
    ez:"新鮮食品必須依規定存放。" },

  { mt:"PT", teil:"L2",
    a:"", w:"einschließlich", p:"",
    en:"including", zh:"包括、含",
    k:"einschließlich der Händehygiene; alles einschließlich Steuer",
    kz:"包括手部衛生；含稅的一切",
    ex:"Auf die persönliche Körperhygiene, einschließlich der Händehygiene, ist zu achten.",
    ez:"必須注意個人衛生，包括手部衛生。" },

  // ── S.16 — Vorschriften und Regelungen ──────────────────────────
  { mt:"PT", teil:"L2",
    a:"", w:"großschreiben (etwas wird großgeschrieben)", p:"",
    en:"to attach great importance to / prioritize highly", zh:"非常重視（某事）",
    k:"die Hygiene wird großgeschrieben; etwas wird bei uns großgeschrieben",
    kz:"非常重視衛生；我們非常重視某事",
    ex:"Die persönliche Hygiene wird bei uns großgeschrieben.",
    ez:"我們非常重視個人衛生。" },

  { mt:"PT", teil:"L2",
    a:"", w:"verpflichtend", p:"",
    en:"mandatory / obligatory", zh:"強制性的、義務的",
    k:"verpflichtend sein; eine verpflichtende Regelung",
    kz:"是強制性的；強制性的規定",
    ex:"Ein sauberes und gepflegtes Äußeres ist für die Mitarbeiter in der Küche verpflichtend.",
    ez:"廚房員工必須保持外觀整潔，這是強制性的規定。" },

  { mt:"PT", teil:"L2",
    a:"", w:"stets", p:"",
    en:"always", zh:"總是、一向",
    k:"stets sauber sein; stets darauf achten",
    kz:"總是保持乾淨；總是留意此事",
    ex:"Gänge und Küchenoberflächen sind stets hygienisch sauber zu halten.",
    ez:"走道和廚房台面必須總是保持衛生清潔。" },

  { mt:"PT", teil:"L2",
    a:"", w:"freihalten", p:"",
    en:"to keep clear / keep free", zh:"保持淨空、保持暢通",
    k:"von Gegenständen freihalten; einen Weg freihalten",
    kz:"保持淨空無雜物；保持通道暢通",
    ex:"Daher sind Kartons von Gegenständen freizuhalten und umgehend zu entsorgen.",
    ez:"因此必須保持紙箱區域淨空無雜物，並立即清理丟棄。" },

  { mt:"PT", teil:"L2",
    a:"", w:"kritisch (Lebensmittel)", p:"",
    en:"critical / sensitive (food items)", zh:"敏感的、需特別注意的（食品）",
    k:"kritische Lebensmittel; ein kritischer Punkt",
    kz:"需特別注意的食品；關鍵點",
    ex:"Kritische Lebensmittel wie rohes Fleisch, Geflügel oder Ei müssen getrennt verarbeitet werden.",
    ez:"像生肉、家禽或蛋這類敏感食品必須分開處理。" },

  { mt:"PT", teil:"L2",
    a:"", w:"aufbewahren", p:"",
    en:"to store / keep", zh:"保存、存放",
    k:"getrennt aufbewahrt werden; etwas sicher aufbewahren",
    kz:"分開保存；安全地保存某物",
    ex:"Kritische Lebensmittel müssen getrennt von anderen Lebensmitteln aufbewahrt werden.",
    ez:"敏感食品必須與其他食品分開保存。" },

  { mt:"PT", teil:"L2",
    a:"", w:"vorgesehen (Gefäße)", p:"",
    en:"designated / intended (containers)", zh:"指定的、預定的（容器）",
    k:"in den vorgesehenen Gefäßen aufbewahrt werden; ein dafür vorgesehener Ort",
    kz:"保存在指定的容器中；為此預定的地點",
    ex:"Reinigungs- und Desinfektionsmittel werden in den dafür vorgesehenen Gefäßen aufbewahrt.",
    ez:"清潔與消毒用品須保存在指定的容器中。" },

  { mt:"PT", teil:"L2",
    a:"", w:"lagern", p:"",
    en:"to store", zh:"存放、儲存",
    k:"im Putzmittelraum gelagert; richtig gelagert werden",
    kz:"存放在清潔用品間；正確地儲存",
    ex:"Und im Putzmittelraum gelagert.",
    ez:"並存放在清潔用品間裡。" },

  { mt:"PT", teil:"L2",
    a:"", w:"gesondert", p:"",
    en:"separately", zh:"分開地、另外地",
    k:"gesondert gelagert werden; etwas gesondert behandeln",
    kz:"分開存放；分別處理某事",
    ex:"Tierische Lebensmittel müssen gesondert gelagert werden.",
    ez:"動物性食品必須分開存放。" },

  // ── S.17 — Vorschriften und Regelungen ──────────────────────────
  { mt:"PT", teil:"L2",
    a:"", w:"betragen", p:"",
    en:"to amount to", zh:"為（數量）、達",
    k:"die Arbeitszeit beträgt 40 Stunden; etwas beträgt eine bestimmte Menge",
    kz:"工作時間為40小時；某數量達到一定值",
    ex:"Die wöchentliche Arbeitszeit beträgt 40 Stunden.",
    ez:"每週工作時間為40小時。" },

  { mt:"PT", teil:"L2",
    a:"", w:"gelten ausschließlich", p:"",
    en:"to apply exclusively", zh:"僅適用於",
    k:"die Arbeitszeit gilt ausschließlich der Pause; etwas gilt nur für...",
    kz:"工作時間僅適用於休息時間；某規定僅適用於……",
    ex:"Die Arbeitszeit gilt ausschließlich der Essens- und Ruhepausen.",
    ez:"這段工作時間僅指用餐和休息的時間。" },

  { mt:"PT", teil:"L2",
    a:"", w:"lediglich", p:"",
    en:"only / merely", zh:"僅、只",
    k:"lediglich denjenigen zur Verfügung stehen; lediglich ein Beispiel",
    kz:"僅提供給那些人使用；僅僅是個例子",
    ex:"Der Ruheraum steht lediglich denjenigen zur Verfügung, die in Spät- und Nachtschicht arbeiten.",
    ez:"休息室僅提供給上晚班或夜班的員工使用。" },

  { mt:"PT", teil:"L2",
    a:"", w:"jeweilig", p:"",
    en:"respective", zh:"各自的",
    k:"mit dem jeweiligen Mehrarbeitszuschlag; der jeweilige Betrag",
    kz:"以各自相應的加班津貼；各自的金額",
    ex:"Wird die angesammelte Arbeitszeit mit dem jeweiligen Mehrarbeitszuschlag ausgezahlt.",
    ez:"累積的工時將以相應的加班津貼支付。" },

  { mt:"PT", teil:"L2",
    a:"", w:"aushängen", p:"",
    en:"to be posted / displayed (notice)", zh:"張貼、公佈",
    k:"der Dienstplan hängt aus; etwas aushängen",
    kz:"班表已張貼公佈；張貼某物",
    ex:"Der Dienstplan hängt jeweils ab Donnerstag für die kommende Woche aus.",
    ez:"下週的班表每週四開始張貼公佈。" },

  { mt:"PT", teil:"L2",
    a:"", w:"enthalten (sein)", p:"",
    en:"to be included", zh:"被包含在內",
    k:"in der Arbeitszeit enthalten sein; etwas enthält etwas",
    kz:"包含在工作時間內；某物包含某事物",
    ex:"Die Pausen sind in der Arbeitszeit enthalten.",
    ez:"休息時間包含在工作時間內。" },

  { mt:"PT", teil:"L2",
    a:"", w:"genehmigt (werden)", p:"",
    en:"to be approved", zh:"被核准",
    k:"von Frau Golobek genehmigt werden; einen Antrag genehmigen",
    kz:"由 Golobek 女士核准；核准申請",
    ex:"Die Überstunden werden von Frau Golobek genehmigt.",
    ez:"加班時數由 Golobek 女士核准。" },

  // ── S.18 — Vorschriften und Regelungen ──────────────────────────
  { mt:"PT", teil:"L2",
    a:"der", w:"Ausschluss", p:"",
    en:"exclusion", zh:"排除、停止資格",
    k:"den Ausschluss von der Arbeit zur Folge haben; jemanden ausschließen",
    kz:"導致被禁止工作；將某人排除",
    ex:"Hat den Ausschluss von der Arbeit und somit einen unentschuldigten Arbeitstag zur Folge.",
    ez:"將導致被禁止工作，因此產生一天的無故缺勤。" },

  { mt:"PT", teil:"L2",
    a:"", w:"somit", p:"",
    en:"thus / therefore", zh:"因此、由此",
    k:"somit einen unentschuldigten Arbeitstag; somit ist klar, dass...",
    kz:"因此產生一天無故缺勤；由此可知……",
    ex:"Den Ausschluss von der Arbeit und somit einen unentschuldigten Arbeitstag zur Folge.",
    ez:"導致被禁止工作，因此產生一天的無故缺勤。" },

  { mt:"PT", teil:"L2",
    a:"", w:"unentschuldigt", p:"",
    en:"unexcused", zh:"無故的、未經請假的",
    k:"ein unentschuldigter Arbeitstag; unentschuldigt fehlen",
    kz:"無故缺勤的一天；無故缺席",
    ex:"Einen unentschuldigten Arbeitstag zur Folge.",
    ez:"導致一天的無故缺勤。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Folge", p:"-n",
    en:"consequence", zh:"後果、結果",
    k:"etwas zur Folge haben; die Folgen tragen",
    kz:"導致某結果；承擔後果",
    ex:"Hat den Ausschluss von der Arbeit zur Folge.",
    ez:"會導致被禁止工作。" },

  { mt:"PT", teil:"L2",
    a:"", w:"sicherheitsgefährdend", p:"",
    en:"safety-endangering", zh:"危及安全的",
    k:"sicherheitsgefährdende Gegenstände; etwas ist sicherheitsgefährdend",
    kz:"危及安全的物品；某物危及安全",
    ex:"Sicherheitsgefährdende Gegenstände wie Ringe, Armbänder, Halsketten dürfen nicht getragen werden.",
    ez:"像戒指、手鐲、項鍊這類危及安全的物品不得佩戴。" },

  { mt:"PT", teil:"L2",
    a:"", w:"diesbezüglich", p:"",
    en:"in this regard", zh:"在這方面、就此而言",
    k:"diesbezüglich unterweisen; diesbezügliche Informationen",
    kz:"就此進行指導；相關資訊",
    ex:"Der Werkstattleiter wird Sie diesbezüglich heute Nachmittag unterweisen.",
    ez:"車間主任今天下午會就此事對您進行指導。" },

  { mt:"PT", teil:"L2",
    a:"", w:"unterweisen", p:"",
    en:"to instruct", zh:"指導、訓練",
    k:"jemanden unterweisen; in etwas unterweisen",
    kz:"指導某人；在某方面進行指導訓練",
    ex:"Der Werkstattleiter wird Sie diesbezüglich heute Nachmittag unterweisen.",
    ez:"車間主任今天下午會就此事對您進行指導。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Bewilligung", p:"",
    en:"approval / authorization", zh:"批准、核准",
    k:"nach Bewilligung durch die Schichtleitung; eine Bewilligung erteilen",
    kz:"經班次主管核准後；給予核准",
    ex:"Das Arbeiten an den Maschinen darf nur nach Bewilligung durch die jeweilige Schichtleitung erfolgen.",
    ez:"操作機器只能在經過該班次主管核准後進行。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"Einsatzplan", p:"-pläne",
    en:"deployment plan / duty roster", zh:"派工計畫、值班計畫",
    k:"Einsatzpläne erfragen; einen Einsatzplan erstellen",
    kz:"詢問值班計畫；製作派工計畫",
    ex:"Entsprechende Einsatzpläne können bei der Werkstattleitung erfragt werden.",
    ez:"可以向車間主管詢問相應的派工計畫。" },

  { mt:"PT", teil:"L2",
    a:"", w:"erfragen", p:"",
    en:"to inquire about", zh:"詢問、查詢",
    k:"bei der Leitung erfragen; Informationen erfragen",
    kz:"向主管詢問；查詢資訊",
    ex:"Einsatzpläne können bei der Werkstattleitung erfragt werden.",
    ez:"可以向車間主管詢問派工計畫。" },

  { mt:"PT", teil:"L2",
    a:"das", w:"Bedienpanel", p:"-e",
    en:"control panel", zh:"操作面板",
    k:"das Bedienpanel prüfen; am Bedienpanel arbeiten",
    kz:"檢查操作面板；在操作面板上作業",
    ex:"Prüfen Sie zum Schichtbeginn am Bedienpanel, ob ausreichend Material vorhanden ist.",
    ez:"輪班開始時請在操作面板上檢查物料是否充足。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"Vorratsbehälter", p:"-",
    en:"storage container / supply tank", zh:"儲料容器",
    k:"den Vorratsbehälter auffüllen; in den Vorratsbehältern",
    kz:"補充儲料容器；在儲料容器中",
    ex:"Ob ausreichend Material in den Vorratsbehältern ist.",
    ez:"儲料容器中是否有足夠的物料。" },

  { mt:"PT", teil:"L2",
    a:"", w:"vorhanden", p:"",
    en:"existing / present", zh:"現有的、存在的",
    k:"vorhandene Schutzvorrichtungen; etwas ist vorhanden",
    kz:"現有的防護裝置；某物存在",
    ex:"Vorhandene Schutzvorrichtungen an den Maschinen dürfen nicht entfernt werden.",
    ez:"機器上現有的防護裝置不得拆除。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Schutzvorrichtung", p:"-en",
    en:"protective device / safety guard", zh:"防護裝置",
    k:"Schutzvorrichtungen entfernen; eine Schutzvorrichtung beschädigen",
    kz:"拆除防護裝置；損壞防護裝置",
    ex:"Vorhandene Schutzvorrichtungen an den Maschinen dürfen weder entfernt noch beschädigt werden.",
    ez:"機器上現有的防護裝置不得被拆除或損壞。" },

  { mt:"PT", teil:"L2",
    a:"", w:"beschädigt", p:"",
    en:"damaged", zh:"損壞的",
    k:"beschädigt werden; ein beschädigtes Gerät",
    kz:"被損壞；損壞的設備",
    ex:"Dürfen weder entfernt noch beschädigt werden.",
    ez:"不得被拆除或損壞。" },

  { mt:"PT", teil:"L2",
    a:"das", w:"Schichtende", p:"",
    en:"end of shift", zh:"班次結束",
    k:"zum Schichtende auszuschalten; am Schichtende",
    kz:"班次結束時要關閉；在班次結束時",
    ex:"Die Maschine ist zum Schichtende auszuschalten und gründlich zu reinigen.",
    ez:"機器在班次結束時要關閉並徹底清潔。" },

  { mt:"PT", teil:"L2",
    a:"", w:"gründlich", p:"",
    en:"thoroughly", zh:"徹底地",
    k:"gründlich reinigen; etwas gründlich prüfen",
    kz:"徹底清潔；徹底檢查某物",
    ex:"Die Maschine ist zum Schichtende auszuschalten und gründlich zu reinigen.",
    ez:"機器在班次結束時要關閉並徹底清潔。" },

  { mt:"PT", teil:"L2",
    a:"", w:"einleiten (Maßnahmen)", p:"",
    en:"to initiate (measures)", zh:"啟動、採取（措施）",
    k:"Maßnahmen zur Behebung einleiten; ein Verfahren einleiten",
    kz:"採取補救措施；啟動一項程序",
    ex:"Die Schichtleitung hat den Störungsfall zu prüfen und Maßnahmen zur Behebung einzuleiten.",
    ez:"班次主管須檢查故障情況並啟動補救措施。" },

  // ── S.19 — Vorschriften und Regelungen ──────────────────────────
  { mt:"PT", teil:"L2",
    a:"", w:"abgeben (Schmuck)", p:"",
    en:"to hand over / surrender (jewelry)", zh:"交出、繳交（飾品）",
    k:"Schmuck beim Werkstattleiter abgeben; etwas abgeben müssen",
    kz:"把飾品交給車間主任；必須交出某物",
    ex:"Schmuck beim Werkstattleiter abgeben.",
    ez:"把飾品交給車間主任保管。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Wirkung", p:"-en",
    en:"effect", zh:"效果、作用",
    k:"die Schutzvorrichtungen auf ihre Wirkung prüfen; eine Wirkung erzielen",
    kz:"檢查防護裝置的效果；達到某種效果",
    ex:"Die Schutzvorrichtungen auf ihre Wirkung prüfen.",
    ez:"檢查防護裝置的效果是否正常。" },

  // ── S.20 — Rechte und Pflichten am Arbeitsplatz (Lesen Teil 2) ──
  { mt:"PT", teil:"L2",
    a:"der", w:"Anspruch (auf)", p:"-sprüche",
    en:"entitlement / claim (to)", zh:"權利、請求權（對於）",
    k:"Anspruch auf drei Tage Homeoffice haben; Anspruch erheben",
    kz:"享有三天居家辦公的權利；提出請求",
    ex:"Sie haben Anspruch auf drei Tage Homeoffice pro Woche.",
    ez:"您每週享有三天居家辦公的權利。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"flexible Arbeitsplatz", p:"-plätze",
    en:"flexible workstation", zh:"彈性座位、共用辦公座位",
    k:"flexible Arbeitsplätze im Rahmen des Desk-Sharings; einen flexiblen Arbeitsplatz wählen",
    kz:"桌位共享制下的彈性座位；選擇彈性座位",
    ex:"Bieten wir Ihnen im Rahmen des „Desk-Sharings“ flexible Arbeitsplätze.",
    ez:"我們在「桌位共享制」下為您提供彈性座位。" },

  { mt:"PT", teil:"L2",
    a:"das", w:"Großraumbüro", p:"-s",
    en:"open-plan office", zh:"開放式辦公室",
    k:"im Großraumbüro arbeiten; acht Schreibtische im Großraumbüro",
    kz:"在開放式辦公室工作；開放式辦公室裡的八個辦公桌",
    ex:"In unserem Großraumbüro stehen acht Schreibtische mit gleicher Ausstattung.",
    ez:"我們的開放式辦公室裡有八張配備相同的辦公桌。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Ausstattung", p:"",
    en:"equipment / fittings", zh:"配備、設備",
    k:"gleiche Ausstattung; mit moderner Ausstattung",
    kz:"相同的配備；配有現代化設備",
    ex:"Acht Schreibtische mit gleicher Ausstattung inklusive Steckdosen.",
    ez:"八張配備相同（包含插座）的辦公桌。" },

  { mt:"PT", teil:"L2",
    a:"", w:"wer zuerst kommt, mahlt zuerst", p:"",
    en:"first come, first served", zh:"先到先得",
    k:"nach dem Prinzip „wer zuerst kommt, mahlt zuerst“",
    kz:"依照「先到先得」的原則",
    ex:"Die Schreibtische sind frei wählbar – nach dem Prinzip „wer zuerst kommt, mahlt zuerst“.",
    ez:"辦公桌可以自由選擇——依照「先到先得」的原則。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Richtlinie", p:"-n",
    en:"guideline", zh:"規範、準則",
    k:"einige Richtlinien beachten; gegen die Richtlinien verstoßen",
    kz:"遵守一些規範；違反規範",
    ex:"Bitten wir Sie, einige Richtlinien zu beachten.",
    ez:"我們請您遵守一些使用規範。" },

  { mt:"PT", teil:"L2",
    a:"", w:"belegen (einen Schreibtisch)", p:"",
    en:"to occupy / reserve (a desk)", zh:"占用、佔據（辦公桌）",
    k:"einen Schreibtisch belegen; einen Platz belegen",
    kz:"佔用一張辦公桌；佔用一個座位",
    ex:"Belegen Sie einen Schreibtisch bitte nur, wenn Sie wirklich daran arbeiten.",
    ez:"請只在真正使用時才佔用辦公桌。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Unterlage", p:"-n",
    en:"document(s) / paperwork", zh:"資料、文件",
    k:"für Ihre Unterlagen; Unterlagen einreichen",
    kz:"用於存放您的資料；提交文件",
    ex:"Für Ihre Unterlagen und Ihre persönlichen Gegenstände erhalten Sie einen Rollcontainer.",
    ez:"您將獲得一個活動式收納櫃，用於存放您的資料和個人物品。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"Gegenstand", p:"-stände",
    en:"object / item", zh:"物品",
    k:"persönliche Gegenstände; Gegenstände aufbewahren",
    kz:"個人物品；保存物品",
    ex:"Für Ihre persönlichen Gegenstände erhalten Sie einen Rollcontainer.",
    ez:"您將獲得一個活動式收納櫃存放個人物品。" },

  { mt:"PT", teil:"L2",
    a:"", w:"abhalten (ein Meeting)", p:"",
    en:"to hold (a meeting)", zh:"舉行（會議）",
    k:"ein Meeting abhalten; informelle Meetings abhalten",
    kz:"舉行會議；舉行非正式會議",
    ex:"Auch der Pausenraum kann für informelle Meetings genutzt werden, die man dort abhalten kann.",
    ez:"休息室也可以用來舉行非正式的會議。" },

  // ── S.21 — Rechte und Pflichten am Arbeitsplatz ──────────────────
  { mt:"PT", teil:"L2",
    a:"", w:"sicherstellen", p:"",
    en:"to ensure", zh:"確保",
    k:"sicherstellen, dass...; etwas sicherstellen",
    kz:"確保……；確保某事",
    ex:"Um sicherzustellen, dass der Arbeitsalltag auch während Ihrer Abwesenheit funktioniert.",
    ez:"為了確保您不在時日常工作仍能正常運作。" },

  { mt:"PT", teil:"L2",
    a:"", w:"störungsfrei", p:"",
    en:"trouble-free / without disruption", zh:"無故障地、順暢地",
    k:"störungsfrei funktionieren; ein störungsfreier Ablauf",
    kz:"順暢無故障地運作；無故障的流程",
    ex:"Damit der Arbeitsalltag störungsfrei funktioniert.",
    ez:"以便日常工作能順暢無阻地運行。" },

  { mt:"PT", teil:"L2",
    a:"die", w:"Übergabe", p:"-n",
    en:"handover", zh:"交接",
    k:"eine Übergabe findet statt; bei der Übergabe",
    kz:"進行交接；在交接時",
    ex:"Einige Tage vor Ihrem Urlaubsbeginn findet eine Übergabe statt.",
    ez:"在您休假開始前幾天會進行一次交接。" },

  { mt:"PT", teil:"L2",
    a:"", w:"Zugangsdaten mitteilen", p:"",
    en:"to share access data / login credentials", zh:"告知登入資訊",
    k:"alle relevanten Zugangsdaten mitteilen; Zugangsdaten weitergeben",
    kz:"告知所有相關的登入資訊；轉發登入資料",
    ex:"Denken Sie bitte daran, Ihrer Vertretung alle relevanten Zugangsdaten mitzuteilen.",
    ez:"請記得告知您的代理人所有相關的登入資訊。" },

  { mt:"PT", teil:"L2",
    a:"", w:"zugreifen (auf)", p:"",
    en:"to access", zh:"存取、取用",
    k:"auf Informationen zugreifen; auf ein System zugreifen",
    kz:"存取資訊；存取系統",
    ex:"Damit sie auf wichtige Informationen und Dokumente zugreifen kann.",
    ez:"以便他能存取重要的資訊和文件。" },

  { mt:"PT", teil:"L2",
    a:"das", w:"Übergabeprotokoll", p:"-e",
    en:"handover report", zh:"交接紀錄",
    k:"ein Übergabeprotokoll erstellen; im Übergabeprotokoll festhalten",
    kz:"製作交接紀錄；在交接紀錄中記載",
    ex:"Empfehlen wir, zusätzlich ein Übergabeprotokoll zu erstellen.",
    ez:"我們建議額外製作一份交接紀錄。" },

  { mt:"PT", teil:"L2",
    a:"", w:"schriftlich festhalten", p:"",
    en:"to record in writing", zh:"以書面方式記錄",
    k:"alle wichtigen Informationen schriftlich festhalten; etwas schriftlich festhalten",
    kz:"以書面方式記錄所有重要資訊；書面記錄某事",
    ex:"In dem Sie alle wichtigen Informationen schriftlich festhalten.",
    ez:"在其中以書面方式記錄所有重要資訊。" },

  { mt:"PT", teil:"L2",
    a:"", w:"vorgesehen (Stunden)", p:"",
    en:"scheduled / allotted (hours)", zh:"預定的、規定的（時間）",
    k:"innerhalb der vorgesehenen 48 Stunden; ein vorgesehener Zeitrahmen",
    kz:"在規定的48小時內；預定的時間範圍",
    ex:"Damit Kundenanfragen innerhalb der vorgesehenen 48 Stunden beantwortet werden können.",
    ez:"以便客戶詢問能在規定的48小時內得到回覆。" },

  { mt:"PT", teil:"L2",
    a:"", w:"grundsätzlich", p:"",
    en:"basically / fundamentally", zh:"原則上、基本上",
    k:"grundsätzlich weitergeleitet werden; grundsätzlich gilt, dass...",
    kz:"原則上會被轉發；基本上的原則是……",
    ex:"Werden E-Mails bei Abwesenheit grundsätzlich weitergeleitet.",
    ez:"在不在的期間，電子郵件原則上會被轉發。" },

  { mt:"PT", teil:"L2",
    a:"", w:"ausschließlich (Standardtext)", p:"",
    en:"exclusively", zh:"僅僅、唯獨",
    k:"ausschließlich unseren Standardtext verwenden; ausschließlich für diesen Zweck",
    kz:"僅使用我們的標準文字；僅用於此目的",
    ex:"Verwenden Sie dafür bitte ausschließlich unseren Standardtext.",
    ez:"請僅使用我們的標準文字格式。" },

  { mt:"PT", teil:"L2",
    a:"der", w:"Wiedereinstieg (gelingen)", p:"",
    en:"return / re-entry (to succeed)", zh:"順利回歸（工作）",
    k:"der Wiedereinstieg gelingt gut; den Wiedereinstieg erleichtern",
    kz:"順利回歸工作；讓重新適應更容易",
    ex:"Damit der Wiedereinstieg nach dem Urlaub gut gelingt.",
    ez:"以便休假後能順利回歸工作。" },

  { mt:"PT", teil:"L2",
    a:"", w:"auf den aktuellen Stand bringen", p:"",
    en:"to bring up to date", zh:"使了解最新進度",
    k:"jemanden auf den aktuellen Stand bringen; den Stand der Dinge mitteilen",
    kz:"讓某人了解最新進度；告知目前狀況",
    ex:"Bringt Sie auf den aktuellen Stand und ermöglicht Ihnen so, schnell wieder in die eigenen Aufgaben hineinzufinden.",
    ez:"讓您了解最新進度，使您能快速重新進入自己的工作狀態。" },

  { mt:"PT", teil:"L2",
    a:"", w:"hineinfinden (in eigene Aufgaben)", p:"",
    en:"to settle back into (one's tasks)", zh:"重新進入（工作狀態）",
    k:"schnell wieder hineinfinden; sich in eine neue Aufgabe hineinfinden",
    kz:"快速重新進入狀態；融入一項新任務",
    ex:"Schnell wieder in die eigenen Aufgaben hineinzufinden.",
    ez:"快速重新進入自己的工作狀態。" },

  { mt:"PT", teil:"L2",
    a:"der/die", w:"Angestellte", p:"-n",
    en:"employee", zh:"員工",
    k:"die Angestellten entscheiden selbst; als Angestellter arbeiten",
    kz:"員工自行決定；以員工身份工作",
    ex:"Die Angestellten entscheiden selbst, wie sie die Abwesenheitsnotiz formulieren.",
    ez:"員工自行決定如何撰寫不在辦公室的自動回覆。" },

  { mt:"PT", teil:"L2",
    a:"", w:"weiterleiten", p:"",
    en:"to forward", zh:"轉發",
    k:"E-Mails weiterleiten; eine Anfrage weiterleiten",
    kz:"轉發電子郵件；轉發詢問",
    ex:"Ob sie ihre E-Mails an die Vertretung weiterleiten.",
    ez:"是否將郵件轉發給代理人。" },

  // ── S.24 — Lesen Teil 3 練習 (Rechte und Pflichten) ─────────────
  { mt:"PT", teil:"L3",
    a:"", w:"gesundheitsbedingt", p:"",
    en:"for health reasons", zh:"因健康原因",
    k:"gesundheitsbedingt nicht arbeiten können; gesundheitsbedingte Ausfälle",
    kz:"因健康原因無法工作；因健康原因造成的缺勤",
    ex:"Ich konnte letzten Monat gesundheitsbedingt drei Wochen nicht arbeiten.",
    ez:"上個月我因健康原因有三週無法工作。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Abmahnung", p:"-en",
    en:"formal warning", zh:"書面警告",
    k:"mit einer Abmahnung drohen; eine Abmahnung erhalten",
    kz:"以書面警告威脅；收到書面警告",
    ex:"Mein Arbeitgeber droht jetzt mit einer Abmahnung.",
    ez:"我的雇主現在威脅要對我發出書面警告。" },

  { mt:"PT", teil:"L3",
    a:"", w:"antreten (eine Reise)", p:"",
    en:"to set out on / begin (a trip)", zh:"啟程、開始（旅行）",
    k:"eine Reise antreten; den Urlaub antreten",
    kz:"啟程旅行；開始休假",
    ex:"Ich wollte heute eigentlich meine Reise nach Italien antreten.",
    ez:"我原本今天要啟程前往義大利旅行。" },

  { mt:"PT", teil:"L3",
    a:"", w:"stornieren", p:"",
    en:"to cancel", zh:"取消",
    k:"das Hotel stornieren; eine Buchung stornieren",
    kz:"取消飯店訂房；取消預訂",
    ex:"Ich habe gerade das Hotel storniert.",
    ez:"我剛才取消了飯店訂房。" },

  { mt:"PT", teil:"L3",
    a:"", w:"verfallen", p:"",
    en:"to lapse / expire", zh:"失效、作廢",
    k:"der Urlaub verfällt; ein Anspruch verfällt",
    kz:"假期失效；權利失效",
    ex:"Verfällt jetzt auch noch mein Urlaub?",
    ez:"我的休假現在會因此而作廢嗎？" },

  { mt:"PT", teil:"L3",
    a:"", w:"in der Lage sein", p:"",
    en:"to be able to / in a position to", zh:"能夠、有能力",
    k:"sich nicht in der Lage fühlen; in der Lage sein, etwas zu tun",
    kz:"覺得自己沒有能力；有能力做某事",
    ex:"Ich fühle mich nicht in der Lage, das Haus zu verlassen.",
    ez:"我覺得自己沒有能力離開家門。" },

  // ── S.25 — Rechte und Pflichten am Arbeitsplatz ─────────────────
  { mt:"PT", teil:"L3",
    a:"", w:"hinfallen", p:"",
    en:"to fall down", zh:"跌倒",
    k:"hingefallen sein; beim Laufen hinfallen",
    kz:"跌倒了；走路時跌倒",
    ex:"Ist hingefallen.",
    ez:"跌倒了。" },

  { mt:"PT", teil:"L3",
    a:"", w:"feststellen (Arbeitsunfähigkeit)", p:"",
    en:"to determine / certify (inability to work)", zh:"確認、診斷出（無法工作）",
    k:"die Arbeitsunfähigkeit feststellen lassen; etwas feststellen",
    kz:"請人確認無法工作的狀態；確定某事",
    ex:"Du solltest unbedingt zum Arzt gehen und deine Arbeitsunfähigkeit feststellen lassen.",
    ez:"你一定要去看醫生，讓他確認你的無法工作狀態。" },

  { mt:"PT", teil:"L3",
    a:"", w:"pauschal", p:"",
    en:"as a blanket statement / generally", zh:"一概而論地、籠統地",
    k:"das kann man nicht pauschal beantworten; eine pauschale Aussage",
    kz:"這不能一概而論地回答；籠統的說法",
    ex:"Das kann man gar nicht so pauschal beantworten.",
    ez:"這個問題根本無法一概而論地回答。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Genesung", p:"",
    en:"recovery (from illness)", zh:"康復",
    k:"der Genesung helfen; auf dem Weg der Genesung sein",
    kz:"有助於康復；正在康復中",
    ex:"Wenn die körperliche Aktivität deiner Genesung hilft, dann ist sie erlaubt.",
    ez:"如果身體活動有助於你的康復，那麼是被允許的。" },

  // ── S.26 — Rechte und Pflichten am Arbeitsplatz ─────────────────
  { mt:"PT", teil:"L3",
    a:"die", w:"Karriereleiter (voranzukommen)", p:"",
    en:"career ladder (to advance)", zh:"職涯階梯（晉升）",
    k:"auf der Karriereleiter voranzukommen; die Karriereleiter erklimmen",
    kz:"在職涯階梯上晉升；攀登職涯階梯",
    ex:"Ich möchte die Zeit nutzen, um auf der Karriereleiter voranzukommen.",
    ez:"我想利用這段時間在職涯上有所晉升。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Fördermöglichkeit", p:"-en",
    en:"funding opportunity", zh:"補助機會",
    k:"Infos zu Fördermöglichkeiten finden; eine Fördermöglichkeit nutzen",
    kz:"找到補助機會的資訊；利用補助機會",
    ex:"Kann mir jemand sagen, wo ich Infos zu Fördermöglichkeiten finde?",
    ez:"有人能告訴我在哪裡可以找到補助機會的資訊嗎？" },

  { mt:"PT", teil:"L3",
    a:"", w:"voll durchstarten", p:"",
    en:"to take off fully / make a strong start", zh:"全力衝刺、全力展開新階段",
    k:"beruflich voll durchstarten; nach der Ausbildung durchstarten",
    kz:"在職業上全力衝刺；培訓結束後全力展開新階段",
    ex:"Mit der ich beruflich nach meiner Ausbildung voll durchstarten kann.",
    ez:"讓我在完成培訓後能在職業上全力衝刺。" },

  { mt:"PT", teil:"L3",
    a:"der", w:"Bildungsurlaub", p:"",
    en:"educational leave", zh:"教育假",
    k:"einen Bildungsurlaub beantragen; Bildungsurlaub wahrnehmen",
    kz:"申請教育假；使用教育假",
    ex:"Dazu möchte ich gern einen Bildungsurlaub beantragen.",
    ez:"我想為此申請教育假。" },

  { mt:"PT", teil:"L3",
    a:"", w:"wahrnehmen (eine Möglichkeit)", p:"",
    en:"to make use of / take advantage of", zh:"利用、把握（機會）",
    k:"einen Bildungsurlaub wahrnehmen; eine Chance wahrnehmen",
    kz:"使用教育假；把握一個機會",
    ex:"Möchte endlich einen Bildungsurlaub wahrnehmen.",
    ez:"終於想好好利用一次教育假。" },

  { mt:"PT", teil:"L3",
    a:"", w:"die Kosten übernehmen", p:"",
    en:"to cover the costs", zh:"負擔費用",
    k:"die Kosten dafür übernehmen; wer übernimmt die Kosten?",
    kz:"負擔這項費用；誰來負擔費用？",
    ex:"Wisst ihr, wer die Kosten dafür übernimmt?",
    ez:"你們知道是誰來負擔這項費用嗎？" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Recherche", p:"-n",
    en:"research", zh:"查詢、調查研究",
    k:"Hilfe bei der Recherche brauchen; eine Recherche durchführen",
    kz:"需要查詢方面的協助；進行調查研究",
    ex:"Braucht Hilfe bei der Recherche nach Online-Fortbildungen.",
    ez:"需要協助查詢線上進修課程的資訊。" },

  // ── S.27 — Rechte und Pflichten am Arbeitsplatz ─────────────────
  { mt:"PT", teil:"L3",
    a:"", w:"etliches", p:"",
    en:"quite a lot / a good deal", zh:"相當多的、不少的",
    k:"etliches geändert haben; etliche Probleme",
    kz:"已經改變了不少事情；不少問題",
    ex:"Hier in der Zwischenzeit etliches geändert hat.",
    ez:"在這段期間，這裡已經有相當多的改變。" },

  { mt:"PT", teil:"L3",
    a:"", w:"verkehrt", p:"",
    en:"wrong / mistaken", zh:"不對的、錯誤的",
    k:"es kann nicht verkehrt sein; etwas verkehrt machen",
    kz:"這不會是錯的；把某事做錯",
    ex:"Dann kann es nicht verkehrt sein, eine Erhaltungsfortbildung zu absolvieren.",
    ez:"那麼參加一個維持性進修課程就不會是錯誤的選擇。" },

  { mt:"PT", teil:"L3",
    a:"", w:"absolvieren", p:"",
    en:"to complete / undergo (a course)", zh:"完成、修完（課程）",
    k:"eine Fortbildung absolvieren; ein Studium absolvieren",
    kz:"完成一項進修課程；完成學業",
    ex:"Eine sogenannte Erhaltungsfortbildung zu absolvieren.",
    ez:"完成一個所謂的維持性進修課程。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Fertigkeit", p:"-en",
    en:"skill", zh:"技能",
    k:"berufliche Fertigkeiten auffrischen; Fertigkeiten erlernen",
    kz:"更新職業技能；學習技能",
    ex:"Damit kann man seine beruflichen Fertigkeiten wieder auffrischen.",
    ez:"這樣就能重新更新自己的職業技能。" },

  { mt:"PT", teil:"L3",
    a:"", w:"auffrischen", p:"",
    en:"to refresh / brush up (skills)", zh:"重新熟悉、更新（技能）",
    k:"Fertigkeiten auffrischen; sein Wissen auffrischen",
    kz:"更新技能；更新知識",
    ex:"Kann man seine beruflichen Fertigkeiten wieder auffrischen.",
    ez:"就能重新更新自己的職業技能。" },

  { mt:"PT", teil:"L3",
    a:"", w:"eindeutig", p:"",
    en:"clearly / unambiguously", zh:"明確地",
    k:"eindeutig geregelt sein; eine eindeutige Antwort",
    kz:"明確規定；明確的答案",
    ex:"Das ist eindeutig geregelt.",
    ez:"這一點有明確的規定。" },

  { mt:"PT", teil:"L3",
    a:"", w:"absetzen (steuerlich)", p:"",
    en:"to deduct (for tax purposes)", zh:"抵稅、扣除（稅務上）",
    k:"die Kosten steuerlich absetzen; etwas von der Steuer absetzen",
    kz:"在稅務上扣除費用；從稅金中扣除某項費用",
    ex:"Du kannst die Kosten steuerlich absetzen.",
    ez:"你可以把這筆費用用來抵稅。" },

  { mt:"PT", teil:"L3",
    a:"", w:"fördern", p:"",
    en:"to fund / sponsor", zh:"資助、補助",
    k:"von der Arbeitsagentur gefördert werden; eine Weiterbildung fördern",
    kz:"獲得職業介紹所的補助；資助進修課程",
    ex:"Bestimmte Weiterbildungen werden von der Arbeitsagentur gefördert.",
    ez:"特定的進修課程會獲得職業介紹所的補助。" },

  { mt:"PT", teil:"L3",
    a:"", w:"allerdings", p:"",
    en:"however / though", zh:"不過、然而",
    k:"allerdings nur für...; allerdings gibt es eine Ausnahme",
    kz:"不過僅限於……；不過有個例外",
    ex:"Allerdings nur für politische Schulungen und Fortbildungen.",
    ez:"不過僅限於政治類的訓練和進修課程。" },

  // ── S.28 — Lesen Teil 3 練習 ──────────────────────────────────────
  { mt:"PT", teil:"L3",
    a:"", w:"sorgfältig", p:"",
    en:"carefully", zh:"仔細地、謹慎地",
    k:"sehr sorgfältig arbeiten; eine sorgfältige Prüfung",
    kz:"非常仔細地工作；仔細的檢查",
    ex:"Ich arbeite normalerweise sehr sorgfältig.",
    ez:"我通常工作都很仔細。" },

  { mt:"PT", teil:"L3",
    a:"", w:"zusätzliche Kosten entstehen", p:"",
    en:"additional costs to arise", zh:"產生額外費用",
    k:"zusätzliche Kosten sind entstanden; Kosten entstehen lassen",
    kz:"產生了額外的費用；導致產生費用",
    ex:"Durch den meinem Arbeitgeber zusätzliche Kosten entstanden sind.",
    ez:"因此而讓我的雇主產生了額外的費用。" },

  { mt:"PT", teil:"L3",
    a:"", w:"plötzlich", p:"",
    en:"suddenly", zh:"突然地",
    k:"sich plötzlich nicht mehr erinnern; plötzlich passieren",
    kz:"突然不記得了；突然發生",
    ex:"Er kann sich plötzlich nicht mehr daran erinnern.",
    ez:"他突然就不記得這件事了。" },

  { mt:"PT", teil:"L3",
    a:"", w:"alleinerziehend", p:"",
    en:"single-parenting", zh:"單親的、獨自育兒的",
    k:"alleinerziehend sein; ein alleinerziehender Vater",
    kz:"是單親；單親爸爸",
    ex:"Ich bin alleinerziehend und hatte in dieser Zeit niemanden, der sich um mein Kind kümmern konnte.",
    ez:"我是單親，這段時間沒有人能幫忙照顧我的孩子。" },

  // ── S.29 — Rechte und Pflichten am Arbeitsplatz ─────────────────
  { mt:"PT", teil:"L3",
    a:"", w:"ungerecht", p:"",
    en:"unfair", zh:"不公平的",
    k:"das finde ich ungerecht; eine ungerechte Behandlung",
    kz:"我覺得這不公平；不公平的對待",
    ex:"Ich finde es auch ungerecht, dass Frauen immer noch weniger verdienen.",
    ez:"我也覺得女性仍然賺得比較少這件事不公平。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Verhandlungssache", p:"",
    en:"a matter for negotiation", zh:"協商事項",
    k:"in der Regel Verhandlungssache sein; etwas ist Verhandlungssache",
    kz:"通常是協商事項；某事是協商事項",
    ex:"Die Höhe des Gehalts ist in der Regel Verhandlungssache.",
    ez:"薪資的高低通常是協商事項。" },

  { mt:"PT", teil:"L3",
    a:"", w:"verhandeln", p:"",
    en:"to negotiate", zh:"談判、協商",
    k:"geschickt verhandeln; mit dem Arbeitgeber verhandeln",
    kz:"巧妙地談判；與雇主協商",
    ex:"Wer geschickt verhandelt, verdient mehr.",
    ez:"善於談判的人賺得更多。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Betriebszugehörigkeit", p:"",
    en:"length of service / seniority", zh:"在職年資",
    k:"die Dauer der Betriebszugehörigkeit; nach Betriebszugehörigkeit gestaffelt",
    kz:"在職年資的長度；依在職年資分級",
    ex:"Oft gibt es sachliche Erklärungen für Gehaltsunterschiede (Dauer der Betriebszugehörigkeit, etc.).",
    ez:"薪資差異通常有客觀的解釋（如在職年資長度等）。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Lohnkürzung", p:"-en",
    en:"wage cut", zh:"減薪",
    k:"Lohnkürzungen sind ein Schock; eine Lohnkürzung hinnehmen",
    kz:"減薪是一大衝擊；接受減薪",
    ex:"Lohnkürzungen sind immer ein Schock für die Angestellten.",
    ez:"減薪對員工來說總是一大衝擊。" },

  { mt:"PT", teil:"L3",
    a:"", w:"zulässig", p:"",
    en:"permissible / allowed", zh:"被允許的、合法的",
    k:"zulässig sein, vorausgesetzt...; eine zulässige Maßnahme",
    kz:"在……前提下是被允許的；合法的措施",
    ex:"Sie sind tatsächlich zulässig – vorausgesetzt, das Unternehmen befindet sich in einer wirtschaftlichen Notsituation.",
    ez:"它們確實是被允許的——前提是公司正處於經濟困境中。" },

  { mt:"PT", teil:"L3",
    a:"", w:"betreffen", p:"",
    en:"to affect / concern", zh:"涉及、影響到",
    k:"alle Mitarbeiter betreffen; eine Regelung betrifft jemanden",
    kz:"影響所有員工；某規定涉及某人",
    ex:"Wenn der Arbeitgeber die Löhne kürzt, betrifft das alle Mitarbeiter*innen, nicht nur einzelne.",
    ez:"如果雇主要減薪，必須影響所有員工，而不只是個別人員。" },

  { mt:"PT", teil:"L3",
    a:"die", w:"Auszeit", p:"-en",
    en:"time off / break", zh:"休假、暫停工作期",
    k:"eine Auszeit von der Arbeit nehmen; eine Auszeit nehmen",
    kz:"請一段工作假期；休一段假",
    ex:"Eltern haben das Recht, sich nach der Geburt ihres Kindes eine Auszeit von der Arbeit zu nehmen.",
    ez:"父母在孩子出生後有權休一段育嬰假期。" },

  { mt:"PT", teil:"L3",
    a:"", w:"absichtlich", p:"",
    en:"intentionally / deliberately", zh:"故意地",
    k:"absichtlich Schaden zufügen; etwas absichtlich tun",
    kz:"故意造成損害；故意做某事",
    ex:"Wenn ein Mitarbeiter absichtlich seinem Arbeitgeber Schaden zufügt.",
    ez:"當員工故意對雇主造成損害時。" },

  { mt:"PT", teil:"L3",
    a:"", w:"Schaden zufügen", p:"",
    en:"to cause damage / harm", zh:"造成損害",
    k:"jemandem Schaden zufügen; absichtlich Schaden zufügen",
    kz:"對某人造成損害；故意造成損害",
    ex:"Wenn ein Mitarbeiter absichtlich seinem Arbeitgeber Schaden zufügt.",
    ez:"當員工故意對雇主造成損害時。" },

  // ── S.31 — Besprechungen und Protokolle (Lesen Teil 4練習) ──────
  { mt:"PT", teil:"L4",
    a:"", w:"die Meinung teilen", p:"",
    en:"to share the opinion", zh:"同意觀點、認同看法",
    k:"die Meinung der anderen Person teilen; eine Meinung teilen",
    kz:"認同對方的看法；同意某觀點",
    ex:"Sagen, dass man die Meinung der anderen Person nicht teilt.",
    ez:"表示自己不同意對方的看法。" },

  { mt:"PT", teil:"L4",
    a:"", w:"nachvollziehen", p:"",
    en:"to understand / follow (someone's reasoning)", zh:"理解、體會（他人想法）",
    k:"sich vorstellen können, was die andere Person meint; etwas nachvollziehen können",
    kz:"能夠想像對方的意思；能夠理解某事",
    ex:"Sich vorstellen können, was die andere Person meint.",
    ez:"能夠想像並理解對方所說的意思。" },

  { mt:"PT", teil:"L4",
    a:"", w:"vorziehen", p:"",
    en:"to bring forward / prefer", zh:"提前、優先（時間或選擇）",
    k:"einen Termin vorziehen; etwas vorziehen",
    kz:"提前某個約定的時間；提前進行某事",
    ex:"Etwas (z. B. einen Termin) früher als geplant stattfinden lassen.",
    ez:"讓某事（例如一個約定的時間）比原計畫提早進行。" },

  { mt:"PT", teil:"L4",
    a:"das", w:"Ereignis", p:"-se",
    en:"event", zh:"事件",
    k:"eine Aussage über zukünftige Ereignisse; ein wichtiges Ereignis",
    kz:"對未來事件的陳述；重要的事件",
    ex:"Eine Aussage über zukünftige Entwicklungen oder Ereignisse.",
    ez:"對未來發展或事件的陳述。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Bericht", p:"-e",
    en:"report", zh:"報告",
    k:"ein Bericht über etwas; einen Bericht schreiben",
    kz:"關於某事的報告；撰寫報告",
    ex:"Ein Bericht oder eine Betrachtung von etwas Vergangenem.",
    ez:"關於過去某事的報告或回顧。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Betrachtung", p:"-en",
    en:"reflection / review", zh:"回顧、檢視",
    k:"eine Betrachtung von etwas Vergangenem; eine kritische Betrachtung",
    kz:"對過去事物的回顧；批判性的檢視",
    ex:"Ein Bericht oder eine Betrachtung von etwas Vergangenem.",
    ez:"關於過去某事的報告或回顧。" },

  { mt:"PT", teil:"L4",
    a:"", w:"ansteigen", p:"",
    en:"to rise / increase", zh:"上升、增加",
    k:"die Zahlen steigen an; ein ansteigender Trend",
    kz:"數字上升；上升的趨勢",
    ex:"Wachsen – zunehmen – sich erhöhen – ansteigen.",
    ez:"增長、增加、提高、上升（同義詞）。" },

  { mt:"PT", teil:"L4",
    a:"", w:"stagnieren", p:"",
    en:"to stagnate", zh:"停滯不前",
    k:"die Zahlen stagnieren; eine stagnierende Wirtschaft",
    kz:"數字停滯不前；停滯的經濟",
    ex:"Gleich bleiben – stillstehen – stagnieren.",
    ez:"保持不變、停滯、停滯不前（同義詞）。" },

  { mt:"PT", teil:"L4",
    a:"", w:"zunehmen", p:"",
    en:"to increase", zh:"增加、增長",
    k:"die Nachfrage nimmt zu; an Bedeutung zunehmen",
    kz:"需求增加；重要性日益增加",
    ex:"Wachsen – zunehmen – sich erhöhen – ansteigen.",
    ez:"增長、增加、提高、上升（同義詞）。" },

  // ── S.34 — Besprechungen und Protokolle ─────────────────────────
  { mt:"PT", teil:"L4",
    a:"die", w:"Wirtschaftslage", p:"",
    en:"economic situation", zh:"經濟狀況",
    k:"die unsichere Wirtschaftslage; aufgrund der Wirtschaftslage",
    kz:"不穩定的經濟狀況；由於經濟狀況",
    ex:"Aufgrund der unsicheren Wirtschaftslage soll geprüft werden, wo Kosten gesenkt werden können.",
    ez:"由於經濟狀況不穩定，應檢視哪裡可以削減成本。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Materialverbrauch", p:"",
    en:"material consumption", zh:"材料消耗",
    k:"Maßnahmen zur Reduktion des Materialverbrauchs; den Materialverbrauch senken",
    kz:"減少材料消耗的措施；降低材料消耗",
    ex:"Maßnahmen zur Reduktion des Materialverbrauchs in der Produktion wurden bereits beschlossen.",
    ez:"已決議了減少生產中材料消耗的措施。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Kostensenkung", p:"-en",
    en:"cost reduction", zh:"成本削減",
    k:"Maßnahmen zur Kostensenkung; eine Kostensenkung erzielen",
    kz:"成本削減的措施；達成成本削減",
    ex:"Weitere Maßnahmen zur Kostensenkung werden zurzeit diskutiert.",
    ez:"目前正在討論進一步的成本削減措施。" },

  { mt:"PT", teil:"L4",
    a:"", w:"aufrufen (zu)", p:"",
    en:"to call upon / urge", zh:"呼籲、號召",
    k:"die Mitarbeiter aufrufen; zu etwas aufrufen",
    kz:"呼籲員工；號召做某事",
    ex:"Die Mitarbeiterinnen und Mitarbeiter sollen aufgerufen werden, Einsparpotenzial zu identifizieren.",
    ez:"應呼籲員工們找出節省潛力。" },

  { mt:"PT", teil:"L4",
    a:"das", w:"Einsparpotenzial", p:"",
    en:"savings potential", zh:"節省潛力",
    k:"Einsparpotenzial identifizieren; Ideen zur Kostensenkung beitragen",
    kz:"找出節省潛力；提出成本削減的想法",
    ex:"Einsparpotenzial in ihren Arbeitsbereichen zu identifizieren.",
    ez:"在自己的工作領域裡找出節省潛力。" },

  { mt:"PT", teil:"L4",
    a:"", w:"vorgesehen (Prämie)", p:"",
    en:"planned / intended (bonus)", zh:"預定的、規劃中的（獎金）",
    k:"eine Prämie ist vorgesehen; etwas vorsehen",
    kz:"預計有獎金；規劃某事",
    ex:"Als Anerkennung ist eine Prämie vorgesehen, die sich nach der Höhe der Kosteneinsparung richtet.",
    ez:"作為獎勵，預計會有一筆依節省金額多寡而定的獎金。" },

  { mt:"PT", teil:"L4",
    a:"", w:"jeweilig (Teamleitung)", p:"",
    en:"respective (team lead)", zh:"各自的（團隊負責人）",
    k:"bei der jeweiligen Teamleitung einreichen; der jeweilige Bereich",
    kz:"提交給各自的團隊負責人；各自相應的部門",
    ex:"Vorschläge sind schriftlich bei der jeweiligen Teamleitung einzureichen.",
    ez:"建議須以書面形式提交給各自的團隊負責人。" },

  { mt:"PT", teil:"L4",
    a:"", w:"in den Ruhestand verabschiedet werden", p:"",
    en:"to be sent off into retirement", zh:"光榮退休、送別退休",
    k:"mit einer kleinen Feier in den Ruhestand verabschiedet werden",
    kz:"以一場小型聚會送別退休",
    ex:"Wird am 30. März mit einer kleinen Feier in den Ruhestand verabschiedet.",
    ez:"將於3月30日以一場小型聚會光榮退休。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Nachfolge", p:"",
    en:"succession", zh:"接班、繼任",
    k:"seine Nachfolge übernimmt; die Nachfolge antreten",
    kz:"由他接任；接任職位",
    ex:"Seine Nachfolge übernimmt sein bisheriger Stellvertreter.",
    ez:"由他先前的副手接任。" },

  { mt:"PT", teil:"L4",
    a:"", w:"des Weiteren verlassen", p:"",
    en:"furthermore, to leave", zh:"此外，將離開",
    k:"des Weiteren verlässt Frau X das Unternehmen",
    kz:"此外，某女士將離開公司",
    ex:"Des Weiteren verlässt Frau Celeste Mamani das Unternehmen nach sechsjähriger Betriebszugehörigkeit.",
    ez:"此外，Celeste Mamani 女士在服務六年後將離開公司。" },

  { mt:"PT", teil:"L4",
    a:"", w:"eintreten (ins Unternehmen)", p:"",
    en:"to join (a company)", zh:"加入、進入（公司）",
    k:"neu in das Unternehmen eingetreten sein; ins Unternehmen eintreten",
    kz:"新加入公司；進入公司任職",
    ex:"Neu eingetreten in das Unternehmen sind Frau Dr. Yumi Sasaki und Herr Johannes Gersmann.",
    ez:"Sasaki 博士和 Gersmann 先生是新加入公司的員工。" },

  { mt:"PT", teil:"L4",
    a:"", w:"einbeziehen", p:"",
    en:"to involve / include", zh:"納入、讓……參與",
    k:"die Angestellten einbeziehen; jemanden in eine Entscheidung einbeziehen",
    kz:"讓員工參與；讓某人參與決策",
    ex:"Möchte die Angestellten einbeziehen, um Sparmöglichkeiten zu finden.",
    ez:"想讓員工參與，以找出節省方法。" },

  // ── S.35 — Besprechungen und Protokolle ─────────────────────────
  { mt:"PT", teil:"L4",
    a:"", w:"erarbeiten", p:"",
    en:"to work out / develop", zh:"研擬、開發出",
    k:"eine Softwarelösung erarbeiten; ein Konzept erarbeiten",
    kz:"研擬軟體解決方案；研擬一個方案",
    ex:"AL berichtet, dass das Team eine Softwarelösung für den Kunden erarbeitet hat.",
    ez:"AL 報告說團隊已為客戶研擬出一套軟體解決方案。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Umsetzung", p:"",
    en:"implementation", zh:"實施、落實",
    k:"der Umsetzung zustimmen; die Umsetzung eines Konzepts",
    kz:"同意實施；方案的落實",
    ex:"Der Kunde ist mit dem Konzept zufrieden und hat der Umsetzung zugestimmt.",
    ez:"客戶對方案感到滿意，並同意了實施。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Fertigstellung", p:"",
    en:"completion", zh:"完成、竣工",
    k:"der Termin für die Fertigstellung; die Fertigstellung vorziehen",
    kz:"完成的期限；提前完成日期",
    ex:"Der Termin für die Fertigstellung soll allerdings um eine Woche vorgezogen werden.",
    ez:"完成的期限不過要提前一週。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Auftragslage", p:"",
    en:"order situation / workload from orders", zh:"訂單狀況",
    k:"aufgrund der momentanen Auftragslage; die Auftragslage ist gut",
    kz:"由於目前的訂單狀況；訂單狀況良好",
    ex:"Aufgrund der momentanen Auftragslage befürchtet RT, dass dies zu zeitlichen Engpässen führen könnte.",
    ez:"由於目前的訂單狀況，RT 擔心這可能導致時間上的緊張。" },

  { mt:"PT", teil:"L4",
    a:"", w:"befürchten", p:"",
    en:"to fear / be apprehensive of", zh:"擔心、憂慮",
    k:"befürchten, dass...; etwas befürchten",
    kz:"擔心……；憂慮某事",
    ex:"RT befürchtet, dass dies zu zeitlichen Engpässen führen könnte.",
    ez:"RT 擔心這可能導致時間上的緊張。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Engpass", p:"-pässe",
    en:"bottleneck / shortage", zh:"瓶頸、緊張、短缺",
    k:"zu zeitlichen Engpässen führen; einen Engpass beheben",
    kz:"導致時間上的緊張；解決瓶頸問題",
    ex:"Dies zu zeitlichen Engpässen führen könnte.",
    ez:"這可能導致時間上的緊張瓶頸。" },

  { mt:"PT", teil:"L4",
    a:"das", w:"Flipchart", p:"-s",
    en:"flip chart", zh:"翻頁掛圖、活動掛圖",
    k:"Flipcharts fehlen; ein Flipchart aufstellen",
    kz:"翻頁掛圖不足；放置翻頁掛圖",
    ex:"Dass in letzter Zeit häufiger Flipcharts, Beamer und/oder Leinwände in den Räumen fehlen.",
    ez:"最近會議室裡常常缺少翻頁掛圖、投影機或投影幕。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Leinwand", p:"-wände",
    en:"projector screen", zh:"投影幕",
    k:"eine Leinwand aufstellen; die Leinwand fehlt",
    kz:"架設投影幕；投影幕不見了",
    ex:"Beamer und/oder Leinwände in den Räumen fehlen.",
    ez:"會議室裡缺少投影機或投影幕。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Verzögerung", p:"-en",
    en:"delay", zh:"延誤、延遲",
    k:"zu Verzögerungen führen; eine Verzögerung verursachen",
    kz:"導致延誤；造成延遲",
    ex:"Dass es dadurch zu Verzögerungen bei Projektbesprechungen kommt.",
    ez:"因此導致專案會議出現延誤。" },

  { mt:"PT", teil:"L4",
    a:"", w:"bestätigen", p:"",
    en:"to confirm", zh:"確認",
    k:"die Teammitglieder bestätigen dies; etwas schriftlich bestätigen",
    kz:"團隊成員確認此事；以書面確認某事",
    ex:"Die anderen Teammitglieder bestätigen dies.",
    ez:"其他團隊成員確認了這一點。" },

  { mt:"PT", teil:"L4",
    a:"", w:"stehen (Geräte stehen irgendwo)", p:"",
    en:"to be located / placed (somewhere)", zh:"被放置在（某處）",
    k:"die Flipcharts ständen teilweise in den Fluren; etwas steht irgendwo",
    kz:"翻頁掛圖部分放置在走廊上；某物放在某處",
    ex:"Die Flipcharts ständen teilweise in den Fluren und sogar in den Toilettenräumen herum.",
    ez:"翻頁掛圖有部分被放置在走廊甚至洗手間裡。" },

  { mt:"PT", teil:"L4",
    a:"", w:"beschließen", p:"",
    en:"to decide / resolve", zh:"決議、決定",
    k:"es wird beschlossen, dass...; einen Beschluss fassen",
    kz:"決議……；做出決議",
    ex:"Wird beschlossen, dass RT bis zum Ende der Woche eine Rundmail schickt.",
    ez:"決議由 RT 在週末前發送一封群組郵件。" },

  { mt:"PT", teil:"L4",
    a:"", w:"anhalten (Mitarbeiter zu etwas)", p:"",
    en:"to urge / instruct (someone to do something)", zh:"要求、督促（某人做某事）",
    k:"die Mitarbeiter dazu anhalten; jemanden zu etwas anhalten",
    kz:"督促員工做某事；要求某人做某事",
    ex:"Mit der Bitte, das Problem zu besprechen und die Mitarbeiter*innen dazu anzuhalten.",
    ez:"請他們討論這個問題並督促員工們配合。" },

  { mt:"PT", teil:"L4",
    a:"", w:"belassen", p:"",
    en:"to leave (as is) / keep in place", zh:"保留、維持原狀",
    k:"die Hilfsmittel in den Räumen zu belassen; etwas so belassen, wie es ist",
    kz:"把輔助器材留在會議室裡；讓某事保持原樣",
    ex:"Die technische Ausstattung sowie alle Hilfsmittel in den Räumen zu belassen.",
    ez:"把技術設備和所有輔助器材都留在會議室裡。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Aushang", p:"-hänge",
    en:"notice / posted announcement", zh:"公告、佈告",
    k:"einen Aushang erstellen; ein Aushang mit Hinweisen",
    kz:"製作一份公告；附帶說明的公告",
    ex:"Erstellt ES einen Aushang mit einem entsprechenden Hinweis.",
    ez:"ES 製作了一份附帶相關說明的公告。" },

  { mt:"PT", teil:"L4",
    a:"", w:"befestigen", p:"",
    en:"to fasten / attach", zh:"固定、張貼",
    k:"an der Glastür befestigt werden; etwas an etwas befestigen",
    kz:"固定在玻璃門上；把某物固定在某處",
    ex:"Der an der Glastür im zweiten Stock befestigt werden soll.",
    ez:"應將其固定在二樓的玻璃門上。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Tagungsraum", p:"-räume",
    en:"conference room", zh:"會議室",
    k:"das Problem mit den Tagungsräumen lösen; einen Tagungsraum buchen",
    kz:"解決會議室的問題；預訂會議室",
    ex:"Um das Problem mit den Tagungsräumen zu lösen.",
    ez:"為了解決會議室方面的問題。" },

  { mt:"PT", teil:"L4",
    a:"", w:"ergreifen (Maßnahmen)", p:"",
    en:"to take (measures)", zh:"採取（措施）",
    k:"Maßnahmen ergreifen; mehrere Maßnahmen ergriffen werden",
    kz:"採取措施；採取多項措施",
    ex:"Sollen mehrere Maßnahmen ergriffen werden.",
    ez:"應採取多項措施。" },

  // ── S.36 — Besprechungen und Protokolle ─────────────────────────
  { mt:"PT", teil:"L4",
    a:"", w:"stetig", p:"",
    en:"steadily", zh:"持續地、穩定地",
    k:"stetig gestiegen; eine stetige Entwicklung",
    kz:"持續上漲；持續的發展",
    ex:"Die Preise für Holz sind stetig gestiegen.",
    ez:"木材的價格持續上漲。" },

  { mt:"PT", teil:"L4",
    a:"", w:"voraussichtlich", p:"",
    en:"expected / probably", zh:"預期地、預計地",
    k:"voraussichtlich auch im zweiten Halbjahr; voraussichtlich fertig sein",
    kz:"預計下半年也會如此；預計會完成",
    ex:"Das wird voraussichtlich auch im zweiten Halbjahr so bleiben.",
    ez:"預計下半年也將維持這個情況。" },

  { mt:"PT", teil:"L4",
    a:"", w:"erhöhen (Preise)", p:"",
    en:"to raise / increase (prices)", zh:"提高、上調（價格）",
    k:"die Verkaufspreise erhöhen; einen Preis erhöhen",
    kz:"上調售價；提高價格",
    ex:"Die meisten anderen Möbelhersteller ihre Verkaufspreise bereits erhöht haben.",
    ez:"大多數其他家具製造商已經上調了售價。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Preisanpassung", p:"-en",
    en:"price adjustment", zh:"價格調整",
    k:"keine Preisanpassungen vorsehen; eine Preisanpassung vornehmen",
    kz:"不打算進行價格調整；進行價格調整",
    ex:"Sind bis zum Jahresende jedoch keine Preisanpassungen vorgesehen.",
    ez:"然而到年底前都不打算進行價格調整。" },

  { mt:"PT", teil:"L4",
    a:"", w:"zeitaufwändig", p:"",
    en:"time-consuming", zh:"耗時的",
    k:"zeitaufwändig sein; eine zeitaufwändige Aufgabe",
    kz:"是耗時的；耗時的任務",
    ex:"Die individuelle Betreuung der Kunden, die allerdings sehr zeitaufwändig ist.",
    ez:"個別化的客戶服務，不過這非常耗時。" },

  { mt:"PT", teil:"L4",
    a:"", w:"unterhaltsam", p:"",
    en:"entertaining", zh:"有趣的、娛樂性的",
    k:"unterhaltsam und leicht verständlich; ein unterhaltsamer Film",
    kz:"有趣且容易理解；一部有趣的電影",
    ex:"Die Produkte und Leistungen des Unternehmens unterhaltsam und leicht verständlich darstellen.",
    ez:"以有趣且容易理解的方式呈現公司的產品和服務。" },

  { mt:"PT", teil:"L4",
    a:"", w:"verbunden (damit verbundene Kosten)", p:"",
    en:"associated (costs)", zh:"相關的、伴隨而來的（費用）",
    k:"die damit verbundenen Kosten; mit etwas verbunden sein",
    kz:"與此相關的費用；與某事相關聯",
    ex:"Die praktische Umsetzbarkeit dieses Vorschlags und die damit verbundenen Kosten sollen geprüft werden.",
    ez:"應檢視這項提案的可行性以及相關的費用。" },

  { mt:"PT", teil:"L4",
    a:"", w:"skizzieren", p:"",
    en:"to outline / sketch out", zh:"概述、草擬",
    k:"mögliche Inhalte skizzieren; ein Konzept skizzieren",
    kz:"概述可能的內容；草擬一個方案",
    ex:"CG und MB skizzieren mögliche Inhalte der Erklärfilme.",
    ez:"CG 和 MB 概述了說明影片的可能內容。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Anfertigung", p:"",
    en:"making / production", zh:"製作、訂製",
    k:"die Anfertigung der Einrichtung; etwas zur Anfertigung geben",
    kz:"裝潢的製作；委託製作某物",
    ex:"Die Anfertigung der Einrichtung soll größtenteils parallel zu der Gebäudesanierung laufen.",
    ez:"裝潢的製作大部分應與建築物的整修同時進行。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Gebäudesanierung", p:"",
    en:"building renovation", zh:"建築物整修",
    k:"parallel zu der Gebäudesanierung; eine Gebäudesanierung durchführen",
    kz:"與建築物整修同時進行；進行建築物整修",
    ex:"Soll größtenteils parallel zu der Gebäudesanierung laufen.",
    ez:"大部分應與建築物的整修同時進行。" },

  // ── S.37 — Besprechungen und Protokolle ─────────────────────────
  { mt:"PT", teil:"L4",
    a:"", w:"vorübergehend Leiharbeiter einstellen", p:"",
    en:"to temporarily hire temp workers", zh:"暫時雇用派遣人員",
    k:"vorübergehend einstellen; Leiharbeiter einstellen",
    kz:"暫時雇用；雇用派遣人員",
    ex:"Schlägt er vor, vorübergehend Leiharbeiter einzustellen.",
    ez:"他建議暫時雇用派遣人員。" },

  { mt:"PT", teil:"L4",
    a:"das", w:"Vorfeld (im Vorfeld)", p:"",
    en:"in advance / beforehand", zh:"事前、提前",
    k:"im Vorfeld Angebote einholen; im Vorfeld informieren",
    kz:"提前取得報價；提前告知",
    ex:"CG hat im Vorfeld Angebote von verschiedenen Agenturen eingeholt.",
    ez:"CG 事先向多家代理商取得了報價。" },

  { mt:"PT", teil:"L4",
    a:"", w:"einholen (Angebote)", p:"",
    en:"to obtain (quotes/offers)", zh:"取得、徵詢（報價）",
    k:"Angebote einholen; Informationen einholen",
    kz:"取得報價；徵詢資訊",
    ex:"CG hat im Vorfeld Angebote von verschiedenen Agenturen eingeholt.",
    ez:"CG 事先向多家代理商取得了報價。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Zuschlag", p:"-schläge",
    en:"contract award / winning bid", zh:"得標、中選",
    k:"den Zuschlag erhalten; einer Agentur den Zuschlag geben",
    kz:"獲得得標；把標案給某代理商",
    ex:"Die Agentur Kellerman den Zuschlag erhält.",
    ez:"Kellerman 代理商獲得了這個標案。" },

  { mt:"PT", teil:"L4",
    a:"", w:"preislich zwar über", p:"",
    en:"price-wise indeed higher than", zh:"價格上雖然高於",
    k:"preislich zwar über dem der anderen liegen",
    kz:"價格上雖然高於其他人",
    ex:"Das Angebot liegt preislich zwar über dem der anderen.",
    ez:"這份報價在價格上確實高於其他報價。" },

  { mt:"PT", teil:"L4",
    a:"", w:"erteilen (einen Auftrag)", p:"",
    en:"to award / place (an order)", zh:"下、給予（訂單）",
    k:"einen Auftrag erteilen; eine Genehmigung erteilen",
    kz:"下訂單；給予核准",
    ex:"CG kontaktiert die Agentur heute im Laufe des Tages, um den Auftrag zu erteilen.",
    ez:"CG 今天會聯絡該代理商，以便下訂單。" },

  { mt:"PT", teil:"L4",
    a:"", w:"zuständig", p:"",
    en:"responsible / in charge", zh:"負責的",
    k:"die zuständige Ansprechpartnerin; für etwas zuständig sein",
    kz:"負責的聯絡人；對某事負責",
    ex:"Die zuständige Ansprechpartnerin ist CG.",
    ez:"負責的聯絡人是 CG。" },

  { mt:"PT", teil:"L4",
    a:"", w:"sich zurückziehen", p:"",
    en:"to withdraw / retire", zh:"退出、退休",
    k:"sich aus dem Unternehmen zurückziehen; sich aus Altersgründen zurückziehen",
    kz:"退出公司；因年齡原因退休",
    ex:"Wird sich ab September aus Altersgründen komplett aus dem Unternehmen zurückziehen.",
    ez:"將從九月起因年事已高完全退出公司。" },

  { mt:"PT", teil:"L4",
    a:"der", w:"Anlass", p:"Anlässe",
    en:"occasion", zh:"場合、機會",
    k:"aus diesem Anlass; ein feierlicher Anlass",
    kz:"藉此機會；隆重的場合",
    ex:"Aus diesem Anlass wird sein Nachfolger eine Feier im Parkhotel organisieren.",
    ez:"藉此機會，他的接任者將在Parkhotel安排一場慶祝活動。" },

  { mt:"PT", teil:"L4",
    a:"", w:"durchführen", p:"",
    en:"to carry out / execute", zh:"執行、進行",
    k:"einen Auftrag durchführen; eine Maßnahme durchführen",
    kz:"執行一項訂單；執行一項措施",
    ex:"Möbel Koslik benötigt mehr Personal, um den Auftrag durchzuführen.",
    ez:"Möbel Koslik 需要更多人力才能執行這項訂單。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Sanierung", p:"-en",
    en:"renovation / refurbishment", zh:"整修、翻新",
    k:"nach Abschluss der Sanierung; eine Sanierung durchführen",
    kz:"整修完成後；進行整修",
    ex:"Soll nach Abschluss der Sanierung mit der Arbeit beginnen.",
    ez:"應在整修完成後才開始這項工作。" },

  { mt:"PT", teil:"L4",
    a:"die", w:"Abschiedsfeier", p:"-n",
    en:"farewell party", zh:"歡送會、告別派對",
    k:"einen festen Termin für die Abschiedsfeier; eine Abschiedsfeier organisieren",
    kz:"歡送會的確定日期；籌辦歡送會",
    ex:"Es gibt zurzeit noch keinen festen Termin für die Abschiedsfeier im Parkhotel.",
    ez:"目前在 Parkhotel 舉辦的歡送會還沒有確定的日期。" },

];

// 此檔案使用獨立分類標籤 mt:"PT" (telc Preparation Training)
// 若 HTML 主頁採用固定 MT1-11 篩選器，需另外新增 "PT" 分類選項才能顯示
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...PREPARATIONTRAINING_LESEN_DATA);
}
