// data_ModellTest8.js
// Modelltest 8 — Cornelsen Prüfungstraining DTB B2, "Modelltest 3" im Buch (S. 151–168)
// Quelle: Prüfungstraining DTB B2 (2022), Cornelsen Verlag
// Format: { mt, teil, a, w, p, en, zh, k, kz, ex, ez }

const MODELLTEST8_DATA = [

  // ── LESEN TEIL 1 ──────────────────────────────────────────────
  { mt:"MT8", teil:"L1",
    a:"", w:"einrichten", p:"",
    en:"to set up / to establish", zh:"設置、建立",
    k:"eine Arbeitnehmervertretung einrichten",
    kz:"建立勞工代表機構",
    ex:"Was kann ich machen, um in meinem Betrieb eine Arbeitnehmervertretung einzurichten?",
    ez:"我能做什麼來在公司裡建立員工代表機構？" },

  { mt:"MT8", teil:"L1",
    a:"", w:"bereuen", p:"",
    en:"to regret", zh:"後悔",
    k:"seine Entscheidung nicht bereuen",
    kz:"不後悔自己的決定",
    ex:"Er hat eine Arbeit als Tierpfleger gefunden und bereut seine Entscheidung nicht.",
    ez:"他找到一份動物管理員的工作，並不後悔自己的決定。" },

  { mt:"MT8", teil:"L1",
    a:"die", w:"zunehmende Überlastung", p:"",
    en:"increasing overload", zh:"日益加重的負荷",
    k:"die zunehmende Überlastung kompensieren",
    kz:"補償日益加重的負荷",
    ex:"Um die zunehmende Überlastung bei der Arbeit zu kompensieren, verstärkt man oft sportliche Aktivitäten in der Freizeit.",
    ez:"為了補償工作上日益加重的負荷，人們常常在閒暇時加強運動。" },

  { mt:"MT8", teil:"L1",
    a:"der", w:"Entschluss", p:"-schlüsse",
    en:"decision", zh:"決定",
    k:"der Entschluss steht fest",
    kz:"決定已經確定",
    ex:"Nach langjähriger Arbeit im Büro steht sein Entschluss fest, sich in Zukunft auch beruflich der Arbeit mit Tieren zu widmen.",
    ez:"在辦公室工作多年後，他已下定決心未來也要投身於與動物相關的工作。" },

  { mt:"MT8", teil:"L1",
    a:"", w:"Geist und Seele", p:"",
    en:"mind and soul", zh:"精神與心靈",
    k:"wichtig für Geist und Seele",
    kz:"對精神與心靈很重要",
    ex:"Lebenslanges Lernen ist wichtig für Geist und Seele und sorgt dafür, fit zu bleiben.",
    ez:"終身學習對精神與心靈都很重要，並有助於保持活力。" },

  { mt:"MT8", teil:"L1",
    a:"der", w:"Beitrag", p:"Beiträge",
    en:"contribution / article", zh:"貢獻；（雜誌、報刊的）文章",
    k:"in ihrem Beitrag",
    kz:"在她的文章中",
    ex:"Anja Kaufner vom Institut für Psychologie der Universität Hildesheim spricht genau über dieses Thema in ihrem Beitrag.",
    ez:"來自希爾德斯海姆大學心理學研究所的 Anja Kaufner 在她的文章中正談論這個主題。" },

  { mt:"MT8", teil:"L1",
    a:"", w:"jeweilig", p:"",
    en:"respective", zh:"各自的、相應的",
    k:"die Situation in den jeweiligen Ländern",
    kz:"各個國家的情況",
    ex:"Diese Gehälter lassen sich aber nur mit der Situation in Deutschland vergleichen, wenn man die Lebenshaltungskosten in den jeweiligen Ländern berücksichtigt.",
    ez:"這些薪資只有在考量各個國家的生活成本後，才能與德國的情況進行比較。" },

  { mt:"MT8", teil:"L1",
    a:"die", w:"Durchschnittszahl", p:"-en",
    en:"average figure", zh:"平均數值",
    k:"unser Überblick über die Durchschnittszahlen",
    kz:"我們對平均數值的概覽",
    ex:"Hierbei hilft unser Überblick über die Durchschnittszahlen zu ausgewählten Ländern.",
    ez:"我們所提供的精選國家平均數值概覽會對此有所幫助。" },

  { mt:"MT8", teil:"L1",
    a:"", w:"gegliedert", p:"",
    en:"structured / categorized", zh:"分類整理的",
    k:"gegliedert nach Berufsgruppen",
    kz:"按職業類別分類",
    ex:"Der Überblick über die Durchschnittszahlen ist gegliedert nach Berufsgruppen.",
    ez:"平均數值概覽按職業類別分類整理。" },

  { mt:"MT8", teil:"L1",
    a:"", w:"angeben", p:"",
    en:"to indicate / to state", zh:"註明、提出",
    k:"konkrete Wünsche angeben",
    kz:"提出具體需求",
    ex:"Sie finden dort eine Liste der lokalen Beratungsstellen, an die Sie sich wenden können, und können Ihre konkreten Wünsche angeben.",
    ez:"您可以在那裡找到當地諮詢機構的名單，並可以提出您具體的需求。" },

  { mt:"MT8", teil:"L1",
    a:"der", w:"Begriff", p:"-e",
    en:"term / concept", zh:"術語、概念",
    k:"Begriffe, die oft gleich verwendet werden",
    kz:"常被視為相同使用的術語",
    ex:"Viele Begriffe, die oft gleich verwendet werden, haben aber entscheidende Unterschiede.",
    ez:"許多常被視為相同使用的術語，實際上有著關鍵的差異。" },

  { mt:"MT8", teil:"L1",
    a:"die", w:"Begriffsklärung", p:"-en",
    en:"clarification of terms", zh:"術語釐清",
    k:"eine Begriffsklärung und zahlreiche Beispiele",
    kz:"術語釐清和大量範例",
    ex:"Eine Begriffsklärung und zahlreiche Beispiele für die einzelnen Maßnahmen finden Sie hier.",
    ez:"您可以在這裡找到術語釐清以及各項措施的大量範例。" },

  // ── LESEN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT8", teil:"L2",
    a:"", w:"umfassend", p:"",
    en:"comprehensive", zh:"全面的、廣泛的",
    k:"ein umfassendes Fortbildungsprogramm",
    kz:"一套全面的進修課程",
    ex:"Wir haben ein umfassendes Fortbildungsprogramm entwickelt, Kurse, die Sie befähigen, sich für Ihre Arbeit weiterzuqualifizieren.",
    ez:"我們開發了一套全面的進修課程，幫助您為工作進一步提升資格。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"befähigen", p:"",
    en:"to enable / to qualify", zh:"使能夠、賦予能力",
    k:"Kurse, die Sie befähigen",
    kz:"使您具備能力的課程",
    ex:"Kurse, die Sie befähigen, sich für Ihre Arbeit weiterzuqualifizieren, z.B. Schulungen in neuen Softwareanwendungen.",
    ez:"使您具備能力進一步提升工作資格的課程，例如新軟體應用的培訓。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"erforderlich", p:"",
    en:"required / necessary", zh:"必要的",
    k:"die Teilnahme ist erforderlich",
    kz:"參加是必要的",
    ex:"Ihre Teilnahme an diesen Fortbildungen ist erforderlich.",
    ez:"您必須參加這些進修課程。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"reichhaltig", p:"",
    en:"rich / extensive", zh:"豐富的",
    k:"ein reichhaltiges Angebot an Seminaren",
    kz:"豐富的研討會課程",
    ex:"Außerdem gibt es im Rahmen der betrieblichen Gesundheitsförderung ein reichhaltiges Angebot an Seminaren.",
    ez:"此外，在公司健康促進計畫下，還有豐富的研討會課程可供選擇。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"den eigenen Bedürfnissen entsprechen", p:"",
    en:"to correspond to one's own needs", zh:"符合個人需求",
    k:"einen Kurs auswählen, der den eigenen Bedürfnissen entspricht",
    kz:"選擇符合個人需求的課程",
    ex:"Wir empfehlen unbedingt den Besuch dieser Gesundheits- und Fitnesskurse: Wählen Sie den Kurs aus, der Ihren eigenen Bedürfnissen entspricht.",
    ez:"我們強烈建議參加這些健康與健身課程：請選擇符合您個人需求的課程。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"bezuschusst", p:"",
    en:"subsidized", zh:"受補助的",
    k:"diese Veranstaltungen werden von uns bezuschusst",
    kz:"這些活動由我們提供補助",
    ex:"Diese Veranstaltungen werden von uns bezuschusst und finden zum Teil auch nicht in unserem Betrieb und außerhalb der Arbeitszeit statt.",
    ez:"這些活動由我們提供補助，部分活動也會在公司外、工作時間之外舉行。" },

  { mt:"MT8", teil:"L2",
    a:"der", w:"Außendienst", p:"",
    en:"field service / external service", zh:"外勤服務",
    k:"für notwendige Fahrten des Außendienstes",
    kz:"供外勤人員必要出差使用",
    ex:"Für notwendige Fahrten stehen den Mitarbeitenden des Außendienstes zehn Firmenwagen zur Verfügung.",
    ez:"外勤員工有十輛公司用車可供必要出差使用。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"dienstlich", p:"",
    en:"for official/business purposes", zh:"公務上的",
    k:"die Fahrzeuge dürfen nur dienstlich genutzt werden",
    kz:"這些車輛只能用於公務",
    ex:"Die Fahrzeuge dürfen nur dienstlich genutzt werden.",
    ez:"這些車輛只能用於公務目的。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"bzw. (beziehungsweise)", p:"",
    en:"or rather / respectively", zh:"或者說、亦即",
    k:"melden Sie sich beim Empfang bzw. tragen Sie sich ein",
    kz:"請至接待處登記，亦即填寫表格",
    ex:"Wenn Sie einen Firmenwagen benötigen, melden Sie sich beim Empfang bzw. tragen Sie sich dort frühzeitig in eine Liste ein.",
    ez:"如需使用公司用車，請至接待處報備，或提前在名單上登記。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"überdacht", p:"",
    en:"covered / roofed", zh:"有遮蓋的",
    k:"überdachte Fahrradstellplätze",
    kz:"有遮蓋的自行車停車位",
    ex:"An beiden Seiten des Firmenparkplatzes gibt es überdachte Fahrradstellplätze.",
    ez:"公司停車場兩側都有有遮蓋的自行車停車位。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"umgestiegen sein", p:"",
    en:"to have switched over (to)", zh:"已轉換、已改用",
    k:"auf das Fahrrad umgestiegen sein",
    kz:"已改用自行車",
    ex:"Die Nutzung des Firmenparkplatzes ist zurzeit noch kostenlos, da immer mehr Mitarbeitende auf das Fahrrad umgestiegen sind.",
    ez:"由於越來越多員工已改用自行車，目前公司停車場的使用仍是免費的。" },

  // ── LESEN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT8", teil:"L3",
    a:"der", w:"Druck", p:"",
    en:"pressure", zh:"壓力",
    k:"das ist ein ziemlicher Druck",
    kz:"這是相當大的壓力",
    ex:"Meine Kollegen erwarten, dass auch ich länger arbeite. Das ist ein ziemlicher Druck.",
    ez:"我的同事們期望我也要工作更久，這是相當大的壓力。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"ansprechen", p:"",
    en:"to address / to bring up (a topic)", zh:"提出、談及（話題）",
    k:"ein Problem ansprechen",
    kz:"提出一個問題",
    ex:"Mein Problem ist, dass ich noch in der Probezeit bin. Kann ich das Problem da überhaupt ansprechen?",
    ez:"我的問題是我還在試用期，我到底能不能提出這個問題呢？" },

  { mt:"MT8", teil:"L3",
    a:"die", w:"Initiative", p:"-n",
    en:"initiative", zh:"主動性、倡議",
    k:"auf deine Initiative",
    kz:"基於你的主動行動",
    ex:"Wenn du zeigen kannst, dass auf deine Initiative vielleicht ein Problem im Team gelöst wurde, ist das bestimmt ein gutes Zeichen.",
    ez:"如果你能展現出你的主動行動解決了團隊中的一個問題，這肯定是個好的信號。" },

  { mt:"MT8", teil:"L3",
    a:"das", w:"Zeichen", p:"-",
    en:"sign / signal", zh:"信號、跡象",
    k:"das ist ein gutes Zeichen",
    kz:"這是一個好的信號",
    ex:"Das ist bestimmt ein gutes Zeichen.",
    ez:"這肯定是個好的信號。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"nebenberuflich", p:"",
    en:"on a part-time / side-job basis", zh:"兼職地、副業性質地",
    k:"nebenberuflich etwas Eigenes aufbauen",
    kz:"以兼職方式建立自己的事業",
    ex:"Ich habe meinen Arbeitsplatz behalten und nebenberuflich etwas Eigenes aufgebaut.",
    ez:"我保留了原本的工作，並以兼職方式建立了自己的事業。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"darunter leiden", p:"",
    en:"to suffer because of it", zh:"因此而受苦、受影響",
    k:"deine Arbeit darf darunter nicht leiden",
    kz:"你的工作不能因此受到影響",
    ex:"Du darfst aber dadurch auf keinen Fall deinem Arbeitgeber Konkurrenz machen. Und deine Arbeit darf darunter nicht leiden.",
    ez:"但你絕對不能因此與你的雇主形成競爭，而且你的工作也不能因此受到影響。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"angeordnet", p:"",
    en:"ordered / instructed", zh:"被下令的、被指示的",
    k:"wenn die Überstunden angeordnet wurden",
    kz:"如果加班是被下令要求的",
    ex:"Nicht, wenn die Überstunden angeordnet wurden. Aber denk daran, dein Jahreseinkommen wird sich dann erhöhen.",
    ez:"如果加班是被下令要求的，那就不是這樣。但要記得，你的年收入會因此增加。" },

  { mt:"MT8", teil:"L3",
    a:"die", w:"Anweisung", p:"-en",
    en:"instruction / directive", zh:"指示、指令",
    k:"die Anweisung bekommen, Überstunden zu machen",
    kz:"接到加班的指示",
    ex:"Wenn man ein wichtiges Projekt fertigstellen muss, bekommt man oft die Anweisung, Überstunden zu machen.",
    ez:"當必須完成一個重要專案時，常常會接到要求加班的指示。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"versäumen", p:"",
    en:"to miss / to fail to do", zh:"錯過、未及時做",
    k:"wenn du diese versäumst",
    kz:"如果你錯過這些（期限）",
    ex:"Oft gibt es im Arbeitsvertrag Fristen, in denen du die Zahlung deiner Überstunden beantragen musst. Wenn du diese versäumst, können sie wirklich verfallen.",
    ez:"工作合約中常會有申請加班費的期限，如果你錯過這些期限，加班費真的可能會失效。" },

  { mt:"MT8", teil:"L3",
    a:"", w:"verfallen", p:"",
    en:"to expire / to lapse", zh:"失效、過期",
    k:"die Überstunden können verfallen",
    kz:"加班時數可能會失效",
    ex:"Wenn du die Fristen versäumst, können die Überstunden wirklich verfallen.",
    ez:"如果你錯過期限，加班時數真的可能會失效。" },

  { mt:"MT8", teil:"L3",
    a:"der", w:"Einzelhandel", p:"",
    en:"retail trade", zh:"零售業",
    k:"Angebote auch für Beschäftigte aus dem Einzelhandel",
    kz:"也提供給零售業員工的方案",
    ex:"Es gibt viele Angebote auch für Beschäftigte aus dem Einzelhandel.",
    ez:"也有許多方案提供給零售業的員工。" },

  // ── LESEN TEIL 4 ──────────────────────────────────────────────
  { mt:"MT8", teil:"L4",
    a:"", w:"die Rede war", p:"",
    en:"was the topic of discussion / was mentioned", zh:"曾被提及、是討論的話題",
    k:"im letzten Protokoll von zwei SB-Kassen die Rede war",
    kz:"上次的會議記錄中提到兩台自助結帳機",
    ex:"IW führt als Korrektur an, dass im letzten Protokoll von zwei SB-Kassen die Rede war, tatsächlich wurden aber vier Kassen aufgestellt.",
    ez:"IW 提出更正，指出上次會議記錄中提到的是兩台自助結帳機，但實際上安裝了四台。" },

  { mt:"MT8", teil:"L4",
    a:"die", w:"Kundenbefragung", p:"-en",
    en:"customer survey", zh:"顧客問卷調查",
    k:"als Ergebnis einer Kundenbefragung",
    kz:"作為顧客問卷調查的結果",
    ex:"AK und LM berichten als Ergebnis einer Kundenbefragung, dass die Kassen gut angenommen werden.",
    ez:"AK 和 LM 報告顧客問卷調查的結果，顯示這些結帳機受到良好接受。" },

  { mt:"MT8", teil:"L4",
    a:"der", w:"Vorgang", p:"Vorgänge",
    en:"process / procedure", zh:"流程、程序",
    k:"die Kassen stoppen den Vorgang",
    kz:"結帳機暫停該流程",
    ex:"Bei Lebensmitteln, für die es eine Altersbeschränkung gebe, stoppen die Kassen den Vorgang und müssen nach einer Alterskontrolle durch das Personal wieder freigegeben werden.",
    ez:"對於有年齡限制的商品，結帳機會暫停該流程，必須由員工進行年齡核對後才能繼續。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"abzurechnen", p:"",
    en:"to settle the bill / to calculate the cost", zh:"結算、計費",
    k:"das Produkt wiegen und abzurechnen",
    kz:"稱重商品並結算",
    ex:"Das Verkaufspersonal muss dann oft bei der Einarbeitung in das Menu auf dem Display helfen, um das Produkt zu wiegen und abzurechnen.",
    ez:"銷售人員在初期常需協助顧客操作螢幕選單，以稱重商品並結算金額。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"wiegen", p:"",
    en:"to weigh", zh:"稱重",
    k:"das Produkt wiegen",
    kz:"稱量商品重量",
    ex:"Die Kundinnen und Kunden müssten zuerst auf dem Display an den Kassen das jeweilige Produkt finden, um es zu wiegen und abzurechnen.",
    ez:"顧客必須先在結帳機螢幕上找到對應商品，才能稱重並結算。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"kleben", p:"",
    en:"to stick / to affix", zh:"貼上",
    k:"den Scan-Aufkleber auf das Produkt kleben",
    kz:"把掃描貼紙貼在商品上",
    ex:"Die Waagen am Obst- und Gemüsestand könnten dann nach dem Wiegen einen Scan-Aufkleber ausdrucken, den Kundinnen und Kunden auf das Produkt kleben.",
    ez:"蔬果區的磅秤在稱重後可以列印出掃描貼紙，讓顧客貼在商品上。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"anhand (+ Genitiv)", p:"",
    en:"based on / using", zh:"依據、根據",
    k:"anhand der Daten aus der Vergangenheit",
    kz:"依據過去的數據",
    ex:"JM bittet CL, anhand der Daten aus der Vergangenheit bis zur nächsten Sitzung zu analysieren, ob dieses Fehlverhalten der Kunden tatsächlich nachzuweisen ist.",
    ez:"JM 請 CL 依據過去的數據，分析在下次會議之前是否能確實證明顧客的這種不當行為。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"bewahrheitet (sich)", p:"",
    en:"to prove true / to be confirmed", zh:"被證實、屬實",
    k:"Bedenken, die sich nicht bewahrheitet hätten",
    kz:"未被證實的擔憂",
    ex:"HS führt an, dass seine Bedenken, durch die SB-Kassen werde Personal abgebaut, sich nicht bewahrheitet hätten.",
    ez:"HS 指出，他原先擔心自助結帳機會導致裁員，但這一擔憂並未被證實。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"verschwinden", p:"",
    en:"to disappear / to vanish", zh:"消失",
    k:"das Verkaufspersonal müsse nicht verschwinden",
    kz:"銷售人員不必消失（不需被裁撤）",
    ex:"Das Verkaufspersonal, das nicht mehr an den Kassen arbeite, müsse nicht verschwinden.",
    ez:"不再於櫃台工作的銷售人員，並不需要被裁撤。" },

  { mt:"MT8", teil:"L4",
    a:"die", w:"Kundenbindung", p:"",
    en:"customer loyalty / retention", zh:"顧客忠誠度、客戶維繫",
    k:"TOP 4 Kundenbindung",
    kz:"議程4：顧客忠誠度",
    ex:"LM berichtet, dass aus der Kundenbefragung auch hervorgehe, dass wir einen großen festen Kundenstamm haben.",
    ez:"LM 報告指出，顧客問卷調查也顯示我們擁有龐大且穩定的客戶群。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"sich beteiligen", p:"",
    en:"to participate / to take part", zh:"參與",
    k:"sich auf dem Stadtteilfest mit einem größeren Stand beteiligen",
    kz:"在社區慶典中以較大的攤位參與",
    ex:"Die Teilnehmenden beschließen, sich auf dem Stadtteilfest weiter auszubauen mit einem größeren Stand zu beteiligen.",
    ez:"與會者決定在社區慶典中以更大的攤位進一步參與和擴大宣傳。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"in Anspruch genommen werden", p:"",
    en:"to be made use of / utilized", zh:"被使用、被利用",
    k:"unser Online-Lieferdienst wird gern in Anspruch genommen",
    kz:"我們的線上配送服務受到歡迎使用",
    ex:"JM führt an, dass unser Online-Lieferdienst für Getränke gern in Anspruch genommen wird.",
    ez:"JM 指出，我們的飲料線上配送服務頗受歡迎使用。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"augenblicklich", p:"",
    en:"currently / at the moment", zh:"目前、此刻",
    k:"augenblicklich keine Option",
    kz:"目前不是一個選項",
    ex:"Ohne eigenes Liefer- und Vertriebsnetz sei für uns als lokalen Supermarkt augenblicklich keine Option.",
    ez:"作為一家本地超市，目前若無自己的配送與物流網絡，這並非一個可行的選項。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"verfolgen", p:"",
    en:"to follow / to track", zh:"追蹤、關注",
    k:"die Entwicklung des Online-Marktes weiter genau verfolgen",
    kz:"持續密切關注網路市場的發展",
    ex:"Sie bittet LM und CL allerdings, die Entwicklung des Online-Marktes für Lebensmittel weiter genau zu verfolgen.",
    ez:"不過她請 LM 和 CL 持續密切關注食品網路市場的發展。" },

  { mt:"MT8", teil:"L4",
    a:"", w:"aus Zeitgründen", p:"",
    en:"due to time constraints", zh:"由於時間原因",
    k:"das Protokoll wurde aus Zeitgründen noch nicht erstellt",
    kz:"由於時間原因尚未完成會議記錄",
    ex:"Das Protokoll der letzten Sitzung wurde aus Zeitgründen noch nicht erstellt.",
    ez:"上次會議的記錄由於時間原因尚未完成。" },

  // ── LESEN UND SCHREIBEN ───────────────────────────────────────
  { mt:"MT8", teil:"L2",
    a:"das", w:"Lastenfahrrad", p:"-räder",
    en:"cargo bike", zh:"載貨自行車",
    k:"fünf Lastenfahrräder bestellt",
    kz:"訂購了五台載貨自行車",
    ex:"Am 10. Februar haben wir bei Ihnen fünf Lastenfahrräder Cora XC5 bestellt.",
    ez:"我們於2月10日向您訂購了五台 Cora XC5 載貨自行車。" },

  { mt:"MT8", teil:"L2",
    a:"der", w:"Zulieferer", p:"-",
    en:"supplier", zh:"供應商",
    k:"einen Zulieferer im Inland haben",
    kz:"有國內的供應商",
    ex:"Sie hätten aber auch einen Zulieferer im Inland und könnten verbindlich bis zum 10. Mai liefern.",
    ez:"但他們在國內也有供應商，並可以保證在5月10日前交貨。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"überschreiten", p:"",
    en:"to exceed", zh:"超過",
    k:"den Termin um 14 Tage überschreiten",
    kz:"超出期限14天",
    ex:"Inzwischen ist auch dieser Termin um 14 Tage überschritten, ohne dass Sie sich deswegen mit uns in Verbindung gesetzt haben.",
    ez:"目前這個期限也已超過14天，但您卻沒有因此與我們聯繫。" },

  { mt:"MT8", teil:"L2",
    a:"", w:"bestehen auf", p:"",
    en:"to insist on", zh:"堅持要求",
    k:"wir bestehen auf umgehender Lieferung",
    kz:"我們堅持要求立即交貨",
    ex:"Wir bestehen auf umgehender Lieferung und bitten um sofortige Antwort.",
    ez:"我們堅持要求立即交貨，並請求即刻回覆。" },

  // ── HÖREN TEIL 1 ──────────────────────────────────────────────
  { mt:"MT8", teil:"H1",
    a:"die", w:"Hobelbank", p:"-bänke",
    en:"workbench", zh:"木工作業台",
    k:"alte Hobelbänke umtauschen",
    kz:"更換舊的木工作業台",
    ex:"Die Tischlerei Schneider möchte alte Hobelbänke umtauschen.",
    ez:"Schneider 木工坊想更換舊的木工作業台。" },

  { mt:"MT8", teil:"H1",
    a:"die", w:"Anschaffung", p:"-en",
    en:"acquisition / purchase", zh:"購置、採購",
    k:"neue Anschaffungen für die Werkstatt",
    kz:"為工作坊新購置的物品",
    ex:"Die Tischlerei denkt über neue Anschaffungen für die Werkstatt nach.",
    ez:"木工坊正在考慮為工作坊新購置物品。" },

  { mt:"MT8", teil:"H1",
    a:"das", w:"Ereignis", p:"-se",
    en:"event / incident", zh:"事件",
    k:"besondere Ereignisse während ihrer Schicht dokumentieren",
    kz:"記錄輪班期間的特殊事件",
    ex:"Die Mitarbeiterin soll sich darum kümmern, dass alle besonderen Ereignisse während ihrer Schicht dokumentiert werden.",
    ez:"這位員工需負責記錄她輪班期間所有的特殊事件。" },

  { mt:"MT8", teil:"H1",
    a:"", w:"sich einigen", p:"",
    en:"to come to an agreement", zh:"達成一致、商定",
    k:"sich auf einen Urlaubstermin einigen",
    kz:"就休假時間達成一致",
    ex:"Die Mitarbeiterin kann sich mit der Kita-Leiterin nicht auf einen Urlaubstermin einigen.",
    ez:"這位員工無法與幼兒園園長就休假時間達成一致。" },

  // ── HÖREN TEIL 2 ──────────────────────────────────────────────
  { mt:"MT8", teil:"H2",
    a:"die", w:"Verringerung", p:"-en",
    en:"reduction", zh:"減少",
    k:"die Verringerung der Arbeitstage",
    kz:"工作天數的減少",
    ex:"Die Verringerung der Arbeitstage pro Woche führt nicht zu weniger Leistung.",
    ez:"每週工作天數的減少並不會導致績效下降。" },

  // ── HÖREN TEIL 3 ──────────────────────────────────────────────
  { mt:"MT8", teil:"H3",
    a:"", w:"eingerichtet werden", p:"",
    en:"to be established / set up", zh:"被建立、被設立",
    k:"die Treffen werden vom Betriebsrat eingerichtet",
    kz:"這些會議由員工委員會設立",
    ex:"Die Treffen des Gesundheitszirkels werden vom Betriebsrat eingerichtet.",
    ez:"健康小組的會議是由員工委員會所設立的。" },

  { mt:"MT8", teil:"H3",
    a:"", w:"gegenseitig", p:"",
    en:"mutual / reciprocal", zh:"互相的",
    k:"zum gegenseitigen Austausch dienen",
    kz:"用於互相交流",
    ex:"Die Treffen dienen zum gegenseitigen Austausch.",
    ez:"這些會議用於互相交流意見。" },

  // ── SPRACHBAUSTEINE TEIL 1 ────────────────────────────────────
  { mt:"MT8", teil:"SB1",
    a:"", w:"fristgerecht", p:"",
    en:"within the deadline / on time", zh:"按期限的、如期的",
    k:"fristgerecht gekündigt",
    kz:"按期限解除合約",
    ex:"Zum 31.10 habe ich meinen Arbeitsvertrag mit Ihrem Unternehmen fristgerecht gekündigt.",
    ez:"我已按期限於10月31日終止與貴公司的勞動合約。" },

  { mt:"MT8", teil:"SB1",
    a:"", w:"bitten (um)", p:"",
    en:"to request / to ask for", zh:"請求、要求",
    k:"Sie gebeten, mir ein Arbeitszeugnis auszustellen",
    kz:"請求您為我開立一份工作證明",
    ex:"Ich habe Sie gebeten, mir ein qualifiziertes Arbeitszeugnis auszustellen.",
    ez:"我已請求您為我開立一份合格的工作證明。" },

  { mt:"MT8", teil:"SB1",
    a:"", w:"ausstellen", p:"",
    en:"to issue (a document)", zh:"開立（文件）",
    k:"ein Arbeitszeugnis ausstellen",
    kz:"開立工作證明",
    ex:"Ich habe Sie gebeten, mir ein qualifiziertes Arbeitszeugnis auszustellen.",
    ez:"我請求您為我開立一份合格的工作證明。" },

  { mt:"MT8", teil:"SB1",
    a:"", w:"ausscheiden", p:"",
    en:"to leave (a company) / to retire", zh:"離職、退出",
    k:"aus dem Unternehmen ausscheiden",
    kz:"離開公司",
    ex:"Ich möchte noch einmal betonen, dass ich es sehr bedauere, aus Ihrem Unternehmen auszuscheiden.",
    ez:"我想再次強調，我非常遺憾要離開貴公司。" },

  { mt:"MT8", teil:"SB1",
    a:"", w:"erfolgreich", p:"",
    en:"successful", zh:"成功的",
    k:"erfolgreiche Teilnahme an den IT-Seminaren",
    kz:"成功參加IT研討會",
    ex:"Vielleicht könnten Sie hier auch meine erfolgreiche Teilnahme an den IT-Seminaren Ihrem Haus erwähnen.",
    ez:"或許您也可以在此提到我成功參加了貴公司的IT研討會。" },

  { mt:"MT8", teil:"SB1",
    a:"", w:"erwähnen", p:"",
    en:"to mention", zh:"提及",
    k:"meine erfolgreiche Teilnahme erwähnen",
    kz:"提及我成功的參與",
    ex:"Vielleicht könnten Sie hier auch meine erfolgreiche Teilnahme an den IT-Seminaren erwähnen.",
    ez:"或許您也可以在此提到我成功參加IT研討會的事情。" },

  // ── SPRACHBAUSTEINE TEIL 2 ────────────────────────────────────
  { mt:"MT8", teil:"SB2",
    a:"die", w:"Beanstandung", p:"-en",
    en:"complaint / objection", zh:"異議、投訴",
    k:"Ihre Beanstandung unserer Rechnung",
    kz:"您對我們帳單的異議",
    ex:"Ihre Beanstandung unserer Rechnung vom 1.6. ist heute bei uns eingegangen.",
    ez:"您對我們6月1日帳單提出的異議今天已收到。" },

  { mt:"MT8", teil:"SB2",
    a:"", w:"eingegangen", p:"",
    en:"received / arrived", zh:"已收到的",
    k:"die Beanstandung ist heute bei uns eingegangen",
    kz:"該異議今天已被我們收到",
    ex:"Ihre Beanstandung unserer Rechnung vom 1.6. ist heute bei uns eingegangen.",
    ez:"您對我們6月1日帳單的異議今天已被收到。" },

  { mt:"MT8", teil:"SB2",
    a:"", w:"zu zahlend(e)", p:"",
    en:"payable / to be paid", zh:"應支付的",
    k:"die von Ihnen zu zahlenden 720 €",
    kz:"您應支付的720歐元",
    ex:"Sie haben uns darauf hingewiesen, dass die von Ihnen zu zahlenden 720 € bereits am 20.5. überwiesen wurden.",
    ez:"您向我們指出，您應支付的720歐元已於5月20日匯出。" },

  { mt:"MT8", teil:"SB2",
    a:"die", w:"Angelegenheit", p:"-en",
    en:"matter / affair", zh:"事務、事情",
    k:"die Angelegenheit sofort überprüfen",
    kz:"立即核實該事項",
    ex:"Wir haben die Angelegenheit sofort überprüft und konnten den Fehler korrigieren.",
    ez:"我們已立即核實該事項，並能夠更正錯誤。" },

];

// GitHub Pages 自動載入機制：將資料注入全域陣列
if (typeof window !== 'undefined') {
  window.MODELLTEST_ALL = window.MODELLTEST_ALL || [];
  window.MODELLTEST_ALL.push(...MODELLTEST8_DATA);
}
